### PR TITLE
[indexer]: Introduce Handler trait for objects snapshot creation

### LINKED ISSUE #5753: [indexer]: Wrong object versions order in `retain_latest_indexed_objects`
## Bug description

The indexer crashes when running sdk e2e tests: `pnpm --filter @iota/iota-sdk test:e2e`

```
thread 'tokio-runtime-worker' panicked at crates/iota-indexer/src/store/pg_indexer_store.rs:2228:29:
Mutation version (SequenceNumber(2)) should be greater than existing mutation version (SequenceNumber(14)) for object 0x0000000000000000000000000000000000000000000000000000000000000006
2025-03-03T15:28:59.817500Z ERROR telemetry_subscribers: panicked at crates/iota-indexer/src/store/pg_indexer_store.rs:2228:29:
Mutation version (SequenceNumber(2)) should be greater than existing mutation version (SequenceNumber(14)) for object 0x0000000000000000000000000000000000000000000000000000000000000006 panic.file="crates/iota-indexer/src/store/pg_indexer_store.rs" panic.line=2228 panic.column=29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by tomxey**
# Description of change

Introduce Handler trait for objects snapshot creation.
The new logic in the Handler will make sure that the checkpoints are processed in order by `backfill_objects_snapshot` 

## Links to any relevant issues

Fixes #5753

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

`cargo ci-clippy`
`cargo run --features indexer --release --bin iota start --with-indexer --force-regenesis --with-faucet --with-graphql` and `pnpm --filter @iota/iota-sdk test:e2e`
`cargo nextest run -p iota-indexer --features pg_integration --test-threads 1` 
`cargo test -j2 --package=iota-indexer --profile=simulator --features=shared_test_runtime`

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota-indexer/src/handlers/mod.rs [hunk 1]
```diff
@@ -45,3 +53,116 @@ pub struct EpochToCommit {
...
+
+    async fn start_transform_and_load(
+        &self,
+        cp_receiver: iota_metrics::metered_channel::Receiver<(u64, T)>,
+        cancel: CancellationToken,
+    ) -> IndexerResult<()> {
+        let checkpoint_commit_batch_size = std::env::var("CHECKPOINT_COMMIT_BATCH_SIZE")
+            .unwrap_or(CHECKPOINT_COMMIT_BATCH_SIZE.to_string())
+            .parse::<usize>()
+            .unwrap();
```
Comment (sergiupopescu199) [inline crates/iota-indexer/src/handlers/mod.rs]: Is the explicit `unwrap()` intended? 

if this fails, then in this task will fail silently without any errors in the `start_objects_snapshot_handler` function.

```rust
spawn_monitored_task!(common_handler.start_transform_and_load(receiver, cancel));
```

```suggestion
            .ok()
            .and_then(|val| val.parse().ok())
            .unwrap_or(CHECKPOINT_COMMIT_BATCH_SIZE);
```

File: crates/iota-indexer/src/handlers/mod.rs [hunk 2]
```diff
@@ -45,3 +53,116 @@ pub struct EpochToCommit {
...
+            }
+
+            if !tuple_batch.is_empty() {
+                let last_checkpoint_seq = tuple_batch.last().unwrap().0;
+                let batch = tuple_batch.into_iter().map(|t| t.1).collect();
+                self.handler.load(batch).await.map_err(|e| {
+                    IndexerError::PostgresWrite(format!(
+                        "Failed to load transformed data into DB for handler {}: {}",
+                        self.handler.name(),
+                        e
```
Comment (sergiupopescu199) [inline crates/iota-indexer/src/handlers/mod.rs]:
```suggestion
                        "Failed to load transformed data into DB for handler {}: {e}",
                        self.handler.name()
```

File: crates/iota-indexer/src/handlers/mod.rs [hunk 3]
```diff
@@ -45,3 +53,116 @@ pub struct EpochToCommit {
...
+        loop {
+            if cancel.is_cancelled() {
+                return Ok(());
+            }
+
+            // Try to fetch new data tuple from the stream
+            if unprocessed.len() >= UNPROCESSED_CHECKPOINT_SIZE_LIMIT {
+                tracing::info!(
+                    "Unprocessed checkpoint size reached limit {}, skip reading from stream...",
+                    UNPROCESSED_CHECKPOINT_SIZE_LIMIT
```
Comment (sergiupopescu199) [inline crates/iota-indexer/src/handlers/mod.rs]:
```suggestion
                    "Unprocessed checkpoint size reached limit {UNPROCESSED_CHECKPOINT_SIZE_LIMIT}, skip reading from stream..."
```

File: crates/iota-indexer/src/handlers/mod.rs [hunk 4]
```diff
@@ -45,3 +53,116 @@ pub struct EpochToCommit {
...
+            } else {
+                // Try to fetch new data tuple from the stream
+                match stream.next().now_or_never() {
+                    Some(Some(tuple_chunk)) => {
+                        if cancel.is_cancelled() {
+                            return Ok(());
+                        }
+                        for tuple in tuple_chunk {
+                            unprocessed.insert(tuple.0, tuple);
+                        }
```
Comment (kodemartin) [inline crates/iota-indexer/src/handlers/mod.rs]: Dealing with `tuple_chunk` and tuple indices like `tuple.0` or `tuple.0`, `tuple.1` is really hiding any semantics we could give to the variables. And this affects readability and maintenance.

I see that the whole tuple, which breaks down to `(checkpoint_seq_num, data)` is inserted only to infer the `last_checkpoint_seq` number in L126. But this can be set explicitly in the `while` loop in L116-.

I would suggest we get rid of all tuple element accesses (e.g. `tuple.0` etc), use pattern matching whenever applicable to get the values (e.g. `for (checkpoint_seq_num, data) in chunk`) and just insert `unprocessed.insert(checkpoint_seq_num, data)` to make the whole thing somewhat easier to follow and understand.

**Review by kodemartin — APPROVED** [review]
lgtm with a minor suggestion

File: crates/iota-indexer/src/handlers/mod.rs [hunk 5]
```diff
@@ -45,3 +53,116 @@ pub struct EpochToCommit {
...
+            .ready_chunks(checkpoint_commit_batch_size);
+
+        let mut unprocessed = BTreeMap::new();
+        let mut tuple_batch = vec![];
+        let mut next_cp_to_process = self
+            .handler
+            .get_watermark_hi()
+            .await?
+            .map(|n| n.saturating_add(1))
+            .unwrap_or_default();
```
Comment (sergiupopescu199) [inline crates/iota-indexer/src/handlers/mod.rs:85]: if this fails, then in this task will fail silently without any errors in the `start_objects_snapshot_handler` function. Is this expected?

```rust
spawn_monitored_task!(common_handler.start_transform_and_load(receiver, cancel));
```

File: crates/iota-indexer/src/handlers/mod.rs [hunk 6]
```diff
@@ -45,3 +53,116 @@ pub struct EpochToCommit {
...
+                            unprocessed.insert(tuple.0, tuple);
+                        }
+                    }
+                    Some(None) => break, // Stream has ended
+                    None => {}           // No new data tuple available right now
+                }
+            }
+
+            // Process unprocessed checkpoints, even no new checkpoints from stream
+            let checkpoint_lag_limiter = self.handler.get_max_committable_checkpoint().await?;
```
Comment (sergiupopescu199) [inline crates/iota-indexer/src/handlers/mod.rs:114]: if this fails, then in this task will fail silently without any errors in the `start_objects_snapshot_handler` function. Is this expected?

```rust
spawn_monitored_task!(common_handler.start_transform_and_load(receiver, cancel));
```

**Review by sergiupopescu199 — APPROVED** [review]
lgtm with some small comments.

I'm a bit worried about this task as it does not handle errors, if any error will occur the task will exit but the indexer will potentially still run, having some unexpected effects.
```rust
spawn_monitored_task!(common_handler.start_transform_and_load(receiver, cancel));
```

File: crates/iota-indexer/src/handlers/mod.rs (hunk 5 above)
Comment (tomxey) [reply crates/iota-indexer/src/handlers/mod.rs:85]: Created issue to investigate this https://github.com/iotaledger/iota/issues/5780

File: crates/iota-indexer/src/handlers/mod.rs (hunk 6 above)
Comment (tomxey) [reply crates/iota-indexer/src/handlers/mod.rs:114]: Created issue to investigate this https://github.com/iotaledger/iota/issues/5780

**Review by Dkwcs — APPROVED** [review]
lgtm

**Review by valeriyr — APPROVED** [review]
