### PR TITLE
chore: Update tracing-subscriber to fix `RUSTSEC-2025-0055`

### LINKED ISSUE #8448: Fix `RUSTSEC-2025-0055`
## Bug description

We should be able to update to fix this security audit after https://github.com/async-graphql/async-graphql/pull/1728 is merged.

See https://rustsec.org/advisories/RUSTSEC-2025-0055

### PR DESCRIPTION
**Pull request by DaughterOfMars**
## Description

Updates `tracing-subscriber` to avoid https://rustsec.org/advisories/RUSTSEC-2025-0055

Closes #8448

### CODE REVIEW

**Review by Thoralf-M — APPROVED** [review]

**Review by muXxer — APPROVED** [review]

**Comment by thibault-martinez** [comment]
Ci failing 😬

**Comment by thibault-martinez** [comment]
> Ci failing 😬

Should be fixed after https://github.com/iotaledger/iota/pull/9717

**Review by muXxer — APPROVED** [review]

**Comment by DaughterOfMars** [comment]
Due to [this PR](https://github.com/async-graphql/async-graphql/pull/1746) which was included in `async-graphql 7.1.0`, it is now necessary to sort the results returned in the `data` field of the `Response` struct, because they are now randomly ordered, and the tests depend on them being in a deterministic order.

**Review by miker83z — APPROVED** [review]

File: crates/iota-graphql-rpc-client/src/response.rs [hunk 1]
```diff
@@ -62,6 +62,28 @@ impl GraphqlResponse {
         serde_json::to_string_pretty(&self.full_response).unwrap()
     }
 
+    /// Sort the response data by first the enum variant then by the types' Ord
+    /// implementations
```
Comment (kodemartin) [inline crates/iota-graphql-rpc-client/src/response.rs]: This description is not very clear to me. From the impl itself it seems that we simply sort by keys in all levels of the response body. Could you elaborate or reiterate on the doc here?

Comment (DaughterOfMars) [reply crates/iota-graphql-rpc-client/src/response.rs]: Mmm, you're right. I had a different impl which better matched the comment but I will simplify it now

**Review by kodemartin — APPROVED** [review]
lgtm

**Review by thibault-martinez — COMMENTED** [review]
```
error[unmaintained]: Bincode is unmaintained
    ┌─ /Users/thibault/iota/iota/Cargo.lock:141:1
    │
141 │ bincode 1.3.3 registry+https://github.com/rust-lang/crates.io-index
    │ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unmaintained advisory detected
    │
    ├ ID: RUSTSEC-2025-0141
    ├ Advisory: https://rustsec.org/advisories/RUSTSEC-2025-0141
    ├ Due to a doxxing and harassment incident, the bincode team has taken the decision to cease development permanently.
```
Do you want to do something about it in this PR?

**Comment by thibault-martinez** [comment]
> ```
> error[unmaintained]: Bincode is unmaintained
>     ┌─ /Users/thibault/iota/iota/Cargo.lock:141:1
>     │
> 141 │ bincode 1.3.3 registry+https://github.com/rust-lang/crates.io-index
>     │ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unmaintained advisory detected
>     │
>     ├ ID: RUSTSEC-2025-0141
>     ├ Advisory: https://rustsec.org/advisories/RUSTSEC-2025-0141
>     ├ Due to a doxxing and harassment incident, the bincode team has taken the decision to cease development permanently.
> ```
> 
> Do you want to do something about it in this PR?

Oh you have another PR for that my bad

**Review by thibault-martinez — APPROVED** [review]
