### PR TITLE
fix(explorer): cleanup fiat integration

### LINKED ISSUE #4965: Cleanup fiat integration in explorer
`apps/explorer/src/components/IotaTokenCard.tsx` makes use of `useIotaCoinData` which seems to be a duplicate of `useTokenPrice`, we should then remove the usage of `useIotaCoinData` in favor of `useTokenPrice`. 

Additionally, in https://github.com/iotaledger/iota/blob/049a33e9627dbe32bf466e90148a572c6418223f/apps/explorer/src/pages/home/Home.tsx#L26 we should rename and change that logic so that it shows the fiat price only if the feature is enabled in apps backend using the fiat conversion feature.

### PR DESCRIPTION
**Pull request by cpl121**
# Description of change

Cleanup fiat integration in explorer

To test

1. Enable FiatConversion flag in `apps/apps-backend/src/features/features.controller.ts` -> `Feature.FiatConversion`
2. Open the explorer and look if the iota token price is correct

## Links to any relevant issues

Closes #4965 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: apps/core/src/constants/coinGeckoUrl.constants.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+// Copyright (c) 2024 IOTA Stiftung
```
Comment (evavirseda) [inline apps/core/src/constants/coinGeckoUrl.constants.ts:1]: duplicated

**Review by evavirseda — CHANGES_REQUESTED** [review]
minor detail :pray:

File: apps/core/src/constants/coinGeckoUrl.constants.ts (hunk 1 above)
Comment (marc2332) [inline apps/core/src/constants/coinGeckoUrl.constants.ts:1]: 🤨

File: apps/explorer/src/components/IotaTokenCard.tsx [hunk 2]
```diff
@@ -8,16 +8,19 @@ import {
...
 } from '@iota/core';
 import { ButtonOrLink } from '~/components/ui';
 import { IOTA_TYPE_ARG } from '@iota/iota-sdk/utils';
+import { useIotaClientContext } from '@iota/dapp-kit';
+import { type Network } from '@iota/iota-sdk/client';
 
-export function IotaTokenCard(): JSX.Element {
-    const { data } = useIotaCoinData();
-    const { currentPrice } = data || {};
+const ONE_IOTA = 1_000_000_000;
```
Comment (marc2332) [inline apps/explorer/src/components/IotaTokenCard.tsx]: Better to use `NANOS_PER_IOTA` instead, right?

**Review by marc2332 — CHANGES_REQUESTED** [review]

File: apps/core/src/constants/coinGeckoUrl.constants.ts (hunk 1 above)
Comment (cpl121) [reply apps/core/src/constants/coinGeckoUrl.constants.ts:1]: :trollface:

**Review by evavirseda — APPROVED** [review]

**Review by evavirseda — CHANGES_REQUESTED** [review]
conflicts :pray:

**Review by evavirseda — APPROVED** [review]

**Review by marc2332 — APPROVED** [review]
