### PR TITLE
fix(explorer): correctly display last epoch rewards

### LINKED ISSUE #6296: Fix 'Last Epoch Rewards' field in Validators table
## Bug description

1. When a validator was part of the committee two epochs prior to the current one (for example, epoch 139 compared to the current epoch 141) and earned rewards in the interim epoch (e.g., 140), but is no longer in the committee for the current epoch, the validator’s last-epoch rewards are incorrectly displayed from epoch 139 in the current epoch 141 in the Validators page table.
2. Sorting base on last epoch rewards is not working as intended.
3. Remove active validators and leave just committee members in the Participating Validators table
4. Add last epoch rewards to Participation table in Epoch details page

### PR DESCRIPTION
**Pull request by brancoder**
# Description of change

resolves #6296

### CODE REVIEW

File: apps/explorer/src/lib/utils/getValidatorMoveEvent.ts [hunk 1]
```diff
@@ -7,11 +7,19 @@ import { type IotaEvent } from '@iota/iota-sdk/client';
...
+    const event = validatorsEvent.find(({ parsedJson }) => {
+        const parsed = parsedJson as { validator_address?: string; epoch?: string };
+
+        if (parsed.validator_address !== validatorAddress) {
+            return false;
+        }
+        if (currentEpoch && parsed.epoch !== currentEpoch) {
+            return false;
+        }
+        return true;
```
Comment (msarcev) [inline apps/explorer/src/lib/utils/getValidatorMoveEvent.ts]: nit: 
```suggestion
        return (
            currentEpoch &&
            parsed.epoch === currentEpoch &&
            parsed.validator_address === validatorAddress
        );
```

Comment (msarcev) [reply apps/explorer/src/lib/utils/getValidatorMoveEvent.ts]: Otherwise LGTM

File: apps/explorer/src/hooks/useEndOfEpochTransactionFromCheckpoint.ts [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+    const client = useIotaClient();
+    return useQuery({
+        queryKey: ['end-of-epoch-transaction', checkpoinId],
+        queryFn: async () => {
+            let cursor: string | undefined | null = null;
+            const filter = checkpoinId ? { Checkpoint: checkpoinId } : undefined;
+            // keep fetching until cursor is null or undefined
+            do {
+                const { data: transactions, nextCursor } = await client.queryTransactionBlocks({
+                    filter,
```
Comment (marc2332) [inline apps/explorer/src/hooks/useEndOfEpochTransactionFromCheckpoint.ts:23]: Couldn't you pass a filter searching for a tx with the tx kind of `EndOfEpochTransaction`? Querying all the txs just to get one doesnt seem every efficient right?

**Review by marc2332 — CHANGES_REQUESTED** [review]

File: apps/explorer/src/hooks/useEndOfEpochTransactionFromCheckpoint.ts (hunk 2 above)
Comment (marc2332) [reply apps/explorer/src/hooks/useEndOfEpochTransactionFromCheckpoint.ts:23]: Alongside the checkpoint one I mean

File: apps/explorer/src/hooks/useEndOfEpochTransactionFromCheckpoint.ts [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+// SPDX-License-Identifier: Apache-2.0
+
+import { useIotaClient } from '@iota/dapp-kit';
+import { type IotaTransactionBlockResponse } from '@iota/iota-sdk/client';
+import { useQuery } from '@tanstack/react-query';
+
+const MAX_TRANSACTIONS_PER_REQ = 50;
+
+export function useEndOfEpochTransactionFromCheckpoint(
+    checkpoinId?: string,
```
Comment (msarcev) [inline apps/explorer/src/hooks/useEndOfEpochTransactionFromCheckpoint.ts]: Typo

**Review by msarcev — DISMISSED** [review]

File: apps/explorer/src/hooks/useEndOfEpochTransactionFromCheckpoint.ts (hunk 2 above)
Comment (brancoder) [reply apps/explorer/src/hooks/useEndOfEpochTransactionFromCheckpoint.ts:23]: I've looked at that but there isn't an `And` filter for the queryTransactionBlock. 
And fetching just `EndOfEpochTransaction` could end up  returning a lot of transactions.

**Review by begonaalvarezd — APPROVED** [review]

**Review by begonaalvarezd — COMMENTED** [review]
conflicts 🙏🏼

**Review by msarcev — APPROVED** [review]

File: apps/explorer/src/pages/epochs/EpochDetail.tsx [hunk 4]
```diff
@@ -71,15 +88,13 @@ export function EpochDetail() {
...
-                        epochData.validators[Number(committeeMemberIndex)].iotaAddress,
-                ) ?? [],
+            committeeMembers: committeeMembers.map((member) => member.iotaAddress),
+            validatorEvents: validatorEvents ?? [],
             showValidatorIcon: true,
             includeColumns,
+            currentEpoch: epochData.epoch,
         });
-    }, [epochData]);
+    }, [epochData, validatorEvents]);
```
Comment (marc2332) [inline apps/explorer/src/pages/epochs/EpochDetail.tsx]:
```suggestion
    }, [epochData, validatorEvents, committeeMembers]);
```

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by marc2332 — APPROVED** [review]
