### PR TITLE
fix(wallet, wallet-dashboard): update the improvement of the date format

### LINKED ISSUE #4627: Improve date/time format
If we display day/month/year it should always be displayed in that order, not the american order
(like the supply increase vesting schedule) 
Image

Also, we should unify the dates of the tx history and details, the wallet and the wallet dashboard use different formats, I would stick to what the wallet uses because its more friendly

dashboard: Image
wallet Image

### PR DESCRIPTION
**Pull request by cpl121**
# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

Closes #4627 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: apps/wallet/src/ui/app/helpers/formatDate.ts
Comment (evavirseda) [inline apps/wallet/src/ui/app/helpers/formatDate.ts:1]: we can remove this file and function since we already have the same functionality in `apps/core/src/hooks/useTimeAgo.ts`, it might be better to move it to the `utils` folder inside `core` rather than keeping it as part of the hook

**Review by evavirseda — CHANGES_REQUESTED** [review]

File: apps/core/src/hooks/useTimeAgo.ts [hunk 1]
```diff
@@ -128,7 +128,7 @@ export const timeAgo = (
 type Format = 'year' | 'month' | 'day' | 'hour' | 'minute' | 'second' | 'weekday';
 
 export function formatDate(date: Date | number, format?: Format[]): string {
```
Comment (marc2332) [inline apps/core/src/hooks/useTimeAgo.ts]: we might as well clean it up
```suggestion
export function formatDate(date: Date | number, format: Format[] = ['day', 'month', 'hour', 'minute'] ): string {
```

File: apps/core/src/hooks/useTimeAgo.ts [hunk 2]
```diff
@@ -128,7 +128,7 @@ export const timeAgo = (
...
-    const formatOption = format ?? (['month', 'day', 'hour', 'minute'] as Format[]);
+    const formatOption = format ?? (['day', 'month', 'hour', 'minute'] as Format[]);
```
Comment (marc2332) [inline apps/core/src/hooks/useTimeAgo.ts]:
```suggestion
```

File: apps/wallet/src/ui/app/helpers/formatDate.ts
Comment (marc2332) [inline apps/wallet/src/ui/app/helpers/formatDate.ts:1]: just an observation: I wonder why do we even have 2 format dates functions

**Review by marc2332 — CHANGES_REQUESTED** [review]

File: apps/core/src/hooks/useTimeAgo.ts [hunk 3]
```diff
@@ -127,8 +127,7 @@ export const timeAgo = (
 // TODO - Merge with related functions
 type Format = 'year' | 'month' | 'day' | 'hour' | 'minute' | 'second' | 'weekday';
 
-export function formatDate(date: Date | number, format?: Format[]): string {
-    const formatOption = format ?? (['month', 'day', 'hour', 'minute'] as Format[]);
+export function formatDate(date: Date | number, format: Format[] = ['day', 'month', 'hour', 'minute']): string {
```
Comment (evavirseda) [inline apps/core/src/hooks/useTimeAgo.ts]: can you move the formatDate function to utils? :pray:

**Review by evavirseda — CHANGES_REQUESTED** [review]
and conflicts :pray:

**Review by marc2332 — APPROVED** [review]

**Review by evavirseda — APPROVED** [review]
