### PR TITLE
fix(iota, iota-swarm, iota-swarm-config): Apply iota-names config upon restart of the swarm persisted by `iota start`

### LINKED ISSUE #7234: `TestCluster` ignores iota-names config on resume
## Bug description

It appears that if the TestCluster is stopped, and the iota-names config parameters are added to the persisted cluster configuration before it is resumed, the resumed cluster ignores the provided iota-names configuration.

It seems that the config loader defaults the iota-names config to `None` instead of reading the correct config.

## Relevant links

https://github.com/iotaledger/iota/issues/6806#issuecomment-2911529015

### PR DESCRIPTION
**Pull request by samuel-rufi**
# Description of change

This PR ensures that adding iota-names options to the persistent swarm configuration (created by the `iota start` command) is applied upon restart. Now, if the swarm is resumed, it gets the iota-names options provided in `fullnode.yaml` (that is reflecting the RPC fullnode of the Swarm). Optionally, validators can also be configured with the iota-names options if applied in the dedicated validator configs part of `network.yaml`.

The options can be added at the bottom of the fullnode.yaml config file for example like:
```
...
iota-names-config:
  package-address: "0xb9d617f24c84826bf660a2f4031951678cc80c264aebc4413459fb2a95ada9ba"
  object-id: "0x07c59b37bd7d036bf78fa30561a2ab9f7a970837487656ec29466e817f879342"
  payments-package-address: "0x98b9b33b7c2347a8f4e8b8716fb4c7e6e1af846ec2ea063a47bba81ffe03b440"
  registry-id: "0xe00b2f2400c33b4dbd3081c4dcf2e289d0544caba23a3d130b264bd756403c07"
  reverse-registry-id: "0x1c1da17843cc453ad4079b05ce55e103b7a8cdd4db6ab42dc367b47ed6d8994d"
```

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/7234

## How the change has been tested

- [X] Basic tests (linting, compilation, formatting, unit/integration tests)
- [X] Patch-specific tests (correctness, functionality coverage)

The patch was tested manually by performing stop-and-resume of the cluster, and checking if the iota-names config was populated.

### Infrastructure QA (only required for crates that are maintained by @iotaledger/infrastructure)

Other tests classes are not relevant, as we don't adjust ingestion or migration objects.

- [ ] Synchronization of the indexer from genesis for a network including migration objects.
- [ ] Restart of indexer synchronization locally without resetting the database.
- [ ] Restart of indexer synchronization on a production-like database.
- [ ] Deployment of services using Docker.
- [X] Verification of API backward compatibility.

### Release Notes

- [ ] Protocol:
- [ ] Nodes (Validators and Full nodes):
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [ ] CLI:
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: crates/iota/src/iota_commands.rs [hunk 1]
```diff
@@ -697,6 +698,25 @@ async fn start(
         swarm_builder = swarm_builder
             .dir(config_path.clone())
             .with_network_config(network_config);
+
+        let fullnode_config_path = config_path.join(IOTA_FULLNODE_CONFIG);
+        if fullnode_config_path.exists() {
+            info!("Loading fullnode config file from {fullnode_config_path:?}");
```
Comment (muXxer) [inline crates/iota/src/iota_commands.rs]: Shouldn't we mention in the log that we only load the config file for the iota_names config?

**Review by muXxer — CHANGES_REQUESTED** [review]

File: crates/iota/src/iota_commands.rs (hunk 1 above)
Comment (samuel-rufi) [reply crates/iota/src/iota_commands.rs]: Good point, clarified the log here  https://github.com/iotaledger/iota/pull/7819/commits/bb3e5ab1e36ae3ad6188d38bafe9da95ab4f9e14

**Review by muXxer — APPROVED** [review]

File: crates/iota/src/iota_commands.rs [hunk 2]
```diff
@@ -697,6 +698,27 @@ async fn start(
         swarm_builder = swarm_builder
             .dir(config_path.clone())
             .with_network_config(network_config);
+
+        let fullnode_config_path = config_path.join(IOTA_FULLNODE_CONFIG);
+        if fullnode_config_path.exists() {
+            info!(
+                "Loading iota-names options from fullnode config file at {fullnode_config_path:?}"
```
Comment (DaughterOfMars) [inline crates/iota/src/iota_commands.rs]:
```suggestion
                "Loading IOTA-Names options from fullnode config file at {fullnode_config_path:?}"
```

**Review by Thoralf-M — APPROVED** [review]
Tried it out and worked 💯
`cargo run --features=iota-names,indexer start --network.config persisted-localnet --with-faucet --committee-size 2 --with-indexer --with-graphql`
publishing and registering name.iota with a target address set
updated `persisted-localnet/fullnode.yaml` with
```
iota-names-config:
  package-address: "0xd0ec870f91910f18e651d77203a59e75a4afb4198ee80c7e497ad659f911736b"
  object-id: "0x509fc7eb34ec360a77770b6a449f4f75d610c71236f7b47be7e1b015131371cb"
  payments-package-address: "0xc063017d7392ef2bf8f21e13f84ec87ff6523660f9fcb320f86bf4b82260650a"
  registry-id: "0x1a10fa069397df775e8d9a0696854bf08ca103336657d1df04e05285e68bef64"
  reverse-registry-id: "0x054d5e7166b5a346120f87c5bb3cce1c50fd1c484ff9270d8534ad2377787c6d"
```
at the end of the file
restarted by running `cargo run --features=iota-names,indexer start --network.config persisted-localnet --with-faucet --committee-size 2 --with-indexer --with-graphql` again
Did a name lookup
```Rust
use iota_sdk::IotaClientBuilder;

#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    let client = IotaClientBuilder::default().build_localnet().await?;

    let res = client
        .read_api()
        .iota_names_lookup("name.iota".into())
        .await?;
    println!("{res:?}");
    Ok(())
}
```
```
Some(IotaNameRecord { nft_id: 0xb292a6319158b632ba6148bd8c96672928f94f7e30fb61542fc0b0a39f3eff5d, expiration_timestamp_ms: 1784197030018, target_address: Some(0x111111111504e9350e635d65cd38ccd2c029434c6a3a480d8947a9ba6a15b215), data: {} })
```
