### PR TITLE
fix(indexer): unskip flaky pruning tests and increase timeouts

### LINKED ISSUE #10291: bug(indexer): flaky tests
The tests sometimes randomly fails on ci with timeout: https://github.com/iotaledger/iota/actions/runs/21997019118/job/63560051882

```
[4](https://github.com/iotaledger/iota/actions/runs/21997019118/job/63560051882#step:8:9505)
test write_api::test_optimistic_tables_pruning ... FAILED

failures:

---- write_api::test_optimistic_tables_pruning stdout ----

thread 'write_api::test_optimistic_tables_pruning' (1162246) panicked at crates/iota-indexer/tests/rpc-tests/../common/mod.rs:281:6:
timeout waiting for indexer to prune optimistic transactions: Elapsed(())
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/std/src/panicking.rs:698:5
   1: core::panicking::panic_fmt
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/core/src/panicking.rs:80:14
   2: core::result::unwrap_failed
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/core/src/result.rs:1862:5
   3: core::result::Result<T,E>::expect
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/core/src/result.rs:1185:23
   4: rpc_tests::common::indexer_wait_for_optimistic_transactions_count::{{closure}}
             at ./tests/rpc-tests/../common/mod.rs:281:6
   5: rpc_tests::write_api::test_optimistic_tables_pruning::{{closure}}
             at ./tests/rpc-tests/write_api.rs:939:86
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/core/src/future/future.rs:133:9
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/core/src/future/future.rs:133:9
   8: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.49.0/src/runtime/scheduler/current_thread/mod.rs:753:70
   9: tokio::task::coop::with_budget
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.49.0/src/task/coop/mod.rs:167:5
  10: tokio::task::coop::budget
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.49.0/src/task/coop/mod.rs:133:5
  11: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.49.0/src/runtime/scheduler/current_thread/mod.rs:753:25
  12: tokio::runtime::scheduler::current_thread::Context::enter
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.49.0/src/runtime/scheduler/current_thread/mod.rs:442:19
  13: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.49.0/src/runtime/scheduler/current_thread/mod.rs:752:44
  14: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.49.0/src/runtime/scheduler/current_thread/mod.rs:840:68
  15: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.49.0/src/runtime/context/scoped.rs:40:9
  16: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.49.0/src/runtime/context.rs:176:38
  17: std::thread::local::LocalKey<T>::try_with
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/std/src/thread/local.rs:508:12
  18: std::thread::local::LocalKey<T>::with
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/std/src/thread/local.rs:472:20
  19: tokio::runtime::context::set_scheduler
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.49.0/src/runtime/context.rs:176:17
  20: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.49.0/src/runtime/scheduler/current_thread/mod.rs:840:27
  21: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.49.0/src/runtime/scheduler/current_thread/mod.rs:740:24
  22: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.49.0/src/runtime/scheduler/current_thread/mod.rs:200:33
  23: tokio::runtime::context::runtime::enter_runtime
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.49.0/src/runtime/context/runtime.rs:65:16
  24: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.49.0/src/runtime/scheduler/current_thread/mod.rs:188:9
  25: tokio::runtime::runtime::Runtime::block_on_inner
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.49.0/src/runtime/runtime.rs:368:52
  26: tokio::runtime::runtime::Runtime::block_on
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.49.0/src/runtime/runtime.rs:342:18
  27: rpc_tests::write_api::test_optimistic_tables_pruning
             at ./tests/rpc-tests/write_api.rs:953:7
  28: rpc_tests::write_api::test_optimistic_tables_pruning::{{closure}}
             at ./tests/rpc-tests/write_api.rs:884:46
  29: core::ops::function::FnOnce::call_once
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/core/src/ops/function.rs:250:5
  30: core::ops::function::FnOnce::call_once
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    write_api::test_optimistic_tables_pruning
```

### PR DESCRIPTION
**Pull request by tomxey**
# Description of change

Unskip `test_optimistic_tables_pruning` and `get_chain_identifier_with_pruning_enabled` that were ignored due to #10291. Increase pruning-related wait timeouts from 30s to 60s to account for slow CI environments.

The pruning implementation changed from the time those tests were observed to be flaky, so it's likely that the flakiness reason was also replaced with the new impl.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/10291

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [ ] Patch-specific tests (correctness, functionality coverage)

### Infrastructure QA (only required for crates that are maintained by @iotaledger/infrastructure)

- [ ] Synchronization of the indexer from genesis for a network including migration objects.
- [ ] Restart of indexer synchronization locally without resetting the database.
- [ ] Restart of indexer synchronization on a production-like database.
- [ ] Deployment of services using Docker.
- [ ] Verification of API backward compatibility.

### CODE REVIEW

File: crates/iota-indexer/tests/common/mod.rs [hunk 1]
```diff
@@ -314,7 +314,7 @@ pub async fn indexer_wait_for_optimistic_transactions_count(
     pg_store: &PgIndexerStore,
     expected_transactions_count: u64,
 ) {
-    tokio::time::timeout(Duration::from_secs(30), async {
+    tokio::time::timeout(Duration::from_secs(60), async {
```
Comment (sergiupopescu199) [inline crates/iota-indexer/tests/common/mod.rs]: nit: could we use a constant in this case?

**Review by sergiupopescu199 — APPROVED** [review]
lgtm 🎸

**Review by kodemartin — APPROVED** [review]

File: crates/iota-indexer/tests/common/mod.rs (hunk 1 above)
Comment (tomxey) [reply crates/iota-indexer/tests/common/mod.rs]: introduced a constant
