### PR TITLE
fix(tooling-dashboard): improve stake wizard

### LINKED ISSUE #4308: Improve stake wizard
if you already have staking on some validator and click on that stake to stake more, the wizard takes you to the select validator list, when that screen is not needed since the validator should already be selected, like in the wallet. See video to reproduce here 

https://github.com/user-attachments/assets/ea014455-befe-4540-8d91-4d6d774d16ea

### PR DESCRIPTION
**Pull request by brancoder**
# Description of change

resolves #4308

### CODE REVIEW

File: apps/wallet-dashboard/components/Dialogs/Staking/StakeDialog.tsx [hunk 1]
```diff
@@ -107,7 +107,12 @@ export function StakeDialog({
     }
 
     function detailsHandleStake() {
-        setView?.(StakeDialogView.SelectValidator);
+        setSelectedValidator?.(stakedDetails?.validatorAddress ?? '');
+        setView?.(
+            isTimelockedStaking
+                ? StakeDialogView.EnterTimelockedAmount
+                : StakeDialogView.EnterAmount,
+        );
```
Comment (cpl121) [inline apps/wallet-dashboard/components/Dialogs/Staking/StakeDialog.tsx]: The same code is used in both functions. Also, since `?? ''` has been added to `setSelectedValidator` before, I think it's a good idea to check if a validator exists before switching to the view
```suggestion
        selectValidatorHandleNext()
```

**Review by cpl121 — CHANGES_REQUESTED** [review]
Another thing that I don't know if it's relevant to this PR, is that all `setView` have `?.`, but the prop is not optional
we could update it here, wdyt?

**Review by evavirseda — APPROVED** [review]

**Review by cpl121 — APPROVED** [review]
