### PR TITLE
fix(docs): add notes about indexer in rpc specs

### LINKED ISSUE #4565: Document indexer-only RPC calls
[Some](https://github.com/iotaledger/iota/blob/develop/crates/iota-json-rpc-api/src/extended.rs) RPCs methods are indexer only. We should document that [here](https://docs.iota.org/iota-api-ref).

### PR DESCRIPTION
**Pull request by Dr-Electron**
# Description of change

Some RPC endpoints are only available on indexer. So I added a note and changed the text where needed.

## Links to any relevant issues

Fixes #4565.

## Type of change

- Documentation Fix

## How the change has been tested

Run locally

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by kodemartin — APPROVED** [review]

File: crates/iota-json-rpc-api/src/extended.rs [hunk 1]
```diff
@@ -14,7 +14,7 @@ use jsonrpsee::{core::RpcResult, proc_macros::rpc};
 #[open_rpc(namespace = "iotax", tag = "Extended API")]
 #[rpc(server, client, namespace = "iotax")]
 pub trait ExtendedApi {
-    /// Return a list of epoch info
+    /// Return a list of epoch info. Exclusively served by the indexer
```
Comment (DaughterOfMars) [inline crates/iota-json-rpc-api/src/extended.rs]:
```suggestion
    /// Return a list of epoch info. Exclusively served by the indexer.
```

Comment (DaughterOfMars) [reply crates/iota-json-rpc-api/src/extended.rs]: And below as well please 🙏

**Review by lucas-tortora — APPROVED** [review]
Besides @DaughterOfMars 's comments, LGTM :)

**Review by vivekjain23 — APPROVED** [review]

File: crates/iota-json-rpc-api/src/extended.rs (hunk 1 above)
Comment (Dr-Electron) [reply crates/iota-json-rpc-api/src/extended.rs]: Done in 5671e46

**Review by Thoralf-M — APPROVED** [review]

**Review by Thoralf-M — CHANGES_REQUESTED** [review]
fmt failing, did you run `cargo +nightly fmt`?

**Review by Thoralf-M — APPROVED** [review]

**Comment by thibault-martinez** [comment]
Let's fix the conflicts and merge this
