### PR TITLE
fix(iota-data-ingestion): remove timeout for kv worker

### LINKED ISSUE #6400: [`iota-data-ingestion`]: kv worker times out on migrated objects genesis checkpoint
## Description

The 'kv-worker' in the `multi_set` method has a max timeout of 60 sec to insert all data. Since Genesis Checkpoint has millions of objects and hundreds of transactions it always goes in timeout.

### PR DESCRIPTION
**Pull request by sergiupopescu199**
# Description of change

Removed timeout for kv worker.

## Links to any relevant issues

fixes #6400 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Started the kv worker using testnet data and made sure it synced. The process took several hours, around 2h 30min

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

File: crates/iota-data-ingestion/src/workers/kv_store.rs [hunk 1]
```diff
@@ -118,9 +115,6 @@ impl KVStoreWorker {
         let mut backoff = ExponentialBackoff::default();
         let mut queue: VecDeque<Vec<_>> = items.chunks(25).map(|ck| ck.to_vec()).collect();
         while let Some(chunk) = queue.pop_front() {
-            if instant.elapsed() > TIMEOUT {
-                return Err(anyhow!("key value worker timed out"));
-            }
```
Comment (kodemartin) [inline crates/iota-data-ingestion/src/workers/kv_store.rs:123]: It could be an option to keep the timeout, but reset it before the next iteration in this `while` loop. This way we still force a timeout for each chunk.

Comment (kodemartin) [reply crates/iota-data-ingestion/src/workers/kv_store.rs:123]: scratch that. The request itself will either succeed or it will fail, and we do have the backoff for any unprocessed items.

**Review by kodemartin — APPROVED** [review]
lgtm

**Review by samuel-rufi — APPROVED** [review]

File: crates/iota-data-ingestion/src/workers/kv_store.rs [hunk 2]
```diff
@@ -129,7 +123,13 @@ impl KVStoreWorker {
                     chunk.to_vec(),
                 )])))
                 .send()
-                .await?;
+                .await
+                .inspect_err(|sdk_err| {
+                    tracing::error!(
```
Comment (samuel-rufi) [inline crates/iota-data-ingestion/src/workers/kv_store.rs]: Nit: you could import tracing

Comment (sergiupopescu199) [reply crates/iota-data-ingestion/src/workers/kv_store.rs]: fixed: https://github.com/iotaledger/iota/pull/6401/commits/0ba217427d37ed390deaaf10f6c50c8081ef7ce5
