### PR TITLE
fix(iota-names): fix domain label validation

### LINKED ISSUE #7194: iota name CLI doesn't allow to register register 30-chars-name----30-chars-name.iota
## Bug description

iota name CLI doesn't allow to register register 30-chars-name----30-chars-name.iota even though it's a valid name

`iota name register 30-chars-name----30-chars-name.iota` results in
`error: invalid value '30-chars-name----30-chars-name.iota' for '<DOMAIN>': Only lowercase letters, numbers, and hyphens are allowed as label characters`

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Fix domain label validation to allow hyphens in labels, when not at the beginning or end of the label.
So for example "this-works.iota"
Also changed the error, to print the char and position if something is wrong

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/7194

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

`cargo run --features=iota-names name register 3%e.iota` prints the expected error message
`error: invalid value '3%e.iota' for '<DOMAIN>': Only lowercase letters, numbers, and hyphens are allowed as label characters. Got '%' at position 1`
`cargo run --features=iota-names name register 30-chars-name----30-chars-name.iot` doesn't fail anymore for the domain validation

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [x] Patch-specific tests (correctness, functionality coverage)

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### Release Notes

- [ ] Protocol:
- [ ] Nodes (Validators and Full nodes):
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [x] CLI: Fixed domain validation for "-" in labels
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

**Review by DaughterOfMars — APPROVED** [review]
Don't we have regex for this?

File: crates/iota-names/src/error.rs [hunk 1]
```diff
@@ -12,8 +12,10 @@ pub enum IotaNamesError {
     InvalidLabelLength(usize, usize, usize),
     #[error("Hyphens are not allowed as first or last character of a label")]
     HyphensAsFirstOrLastLabelChar,
-    #[error("Only lowercase letters, numbers, and hyphens are allowed as label characters")]
-    InvalidLabelChar,
+    #[error(
+        "Only lowercase letters, numbers, and hyphens are allowed as label characters. Got \"{0}\" at position {1}"
```
Comment (thibault-martinez) [inline crates/iota-names/src/error.rs]:
```suggestion
        "Only lowercase letters, numbers, and hyphens are allowed as label characters. Got \'{0}\' at position {1}"
```

**Comment by Thoralf-M** [comment]
> Don't we have regex for this?

We created on in the iota-names repo in TS, but not sure if that would be better to use

File: crates/iota-names/src/domain.rs [hunk 2]
```diff
@@ -226,10 +226,12 @@ pub fn validate_label(label: &str) -> Result<&str, IotaNamesError> {
     for (i, character) in bytes.iter().enumerate() {
         match character {
             b'a'..=b'z' | b'0'..=b'9' => continue,
-            b'-' if i == 0 || i == len - 1 => {
```
Comment (thibault-martinez) [inline crates/iota-names/src/domain.rs:229]: Not fully sure to see why it was failing tbh

**Review by thibault-martinez — APPROVED** [review]

File: crates/iota-names/src/domain.rs (hunk 2 above)
Comment (marc2332) [reply crates/iota-names/src/domain.rs:229]: Because it was falling into

```rs
_ => return Err(IotaNamesError::InvalidLabelChar),
```

**Review by Alex6323 — APPROVED** [review]

File: crates/iota-names/src/domain.rs (hunk 2 above)
Comment (marc2332) [reply crates/iota-names/src/domain.rs:229]: Another way to put it now:
```rs
match character {
      b'a'..=b'z' | b'0'..=b'9' => continue,
      b'-' if i > 0 && i < len - 1 => continue,
      b'-' => return Err(IotaNamesError::HyphensAsFirstOrLastLabelChar),
      _ => return Err(IotaNamesError::InvalidLabelChar((*character) as char, i)),
  };
```

Comment (thibault-martinez) [reply crates/iota-names/src/domain.rs:229]: Ah yeah, obviously, thanks @marc2332. Time for my morning coffee ☕
