### PR TITLE
fix(dashboard): prevent closing popup when closing toast

### LINKED ISSUE #6711: Prevent closing open popup when closing a toast
Closing the "make sure you copied corretly" notification closes the send sidebar popup in the dashboard, probably because of the click outside

### PR DESCRIPTION
**Pull request by KeitoTadashi**
## Links to any relevant issues

fixes #6711

### CODE REVIEW

File: apps/wallet-dashboard/components/dialogs/send-token/SendTokenDialog.tsx [hunk 1]
```diff
@@ -172,7 +172,15 @@ function SendTokenDialogBody({
 
 export function SendTokenDialog(props: SendCoinDialogProps) {
     return (
-        <Dialog open={props.open} onOpenChange={props.setOpen}>
+        <Dialog
```
Comment (evavirseda) [inline apps/wallet-dashboard/components/dialogs/send-token/SendTokenDialog.tsx]: I wouldn't add this here, I'd add it to the Dialog component :bulb: that way it works for all the dialogs, not just the `SendTokenDialog`

File: apps/core/src/components/toaster/Toaster.tsx [hunk 2]
```diff
@@ -30,7 +30,7 @@ export function Toaster(props: ToasterProps) {
     return (
         <ToasterLib
             position="bottom-right"
-            containerClassName={cl('!z-[9999999]', props.containerClassName)}
+            containerClassName={cl('!z-[9999999] toaster-class', props.containerClassName)}
```
Comment (evavirseda) [inline apps/core/src/components/toaster/Toaster.tsx]: i'd rename the class to something more intuitive like `toast-layer` or `toast-focus-zone` :pray:

**Review by evavirseda — CHANGES_REQUESTED** [review]
you could try something like this in the `Dialog` component:
```
        useEffect(() => {
            const handlePointerDown = (event: PointerEvent) => {
                const toastElement = document.querySelector('.toaster-class');
                const clickedInsideToast = toastElement?.contains(event.target as Node);

                if (clickedInsideToast) {
                    event.stopPropagation();
                }
            };

            document.addEventListener('pointerdown', handlePointerDown, true);

            return () => {
                document.removeEventListener('pointerdown', handlePointerDown, true);
            };
        }, []);
```

File: apps/wallet-dashboard/components/dialogs/send-token/SendTokenDialog.tsx (hunk 1 above)
Comment (KeitoTadashi) [reply apps/wallet-dashboard/components/dialogs/send-token/SendTokenDialog.tsx]: :saluting_face:

File: apps/core/src/components/toaster/Toaster.tsx (hunk 2 above)
Comment (KeitoTadashi) [reply apps/core/src/components/toaster/Toaster.tsx]: u right!!

File: .changeset/beige-fans-sit.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@iota/apps-ui-kit': major
```
Comment (evavirseda) [inline .changeset/beige-fans-sit.md]: patch not major  :pray:

File: .changeset/witty-plants-unite.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+'@iota/apps-ui-kit': major
```
Comment (evavirseda) [inline .changeset/witty-plants-unite.md]: an this one too :pray:

**Review by evavirseda — CHANGES_REQUESTED** [review]
:pray:

File: .changeset/perfect-seahorses-tan.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+'@iota/apps-ui-kit': minor
```
Comment (evavirseda) [inline .changeset/perfect-seahorses-tan.md]:
```suggestion
'@iota/apps-ui-kit': patch
```

**Review by evavirseda — CHANGES_REQUESTED** [review]
:pray:

**Review by evavirseda — APPROVED** [review]

**Review by brancoder — APPROVED** [review]
LGTM

**Review by VmMad — APPROVED** [review]
lgtm
