### PR TITLE
refactor(graphql-rpc): Fix complex return type in paginate_consistent_indices

### LINKED ISSUE #4755: Reconsider `paginate_consistent_indices`'s `clippy::type_complexity` allow
A very complex return type was temporarily allowed as changing it would have implications on the schema, and then tooling. Up to infra to decide if they want to change it or not.

> I could create a new type for 
> ```
> Option<(
>             bool,
>             bool,
>             u64,
>             impl Iterator<Item = JsonCursor<ConsistentIndexCursor>>,
>         )>,
> ```
> if infra preferred

_Originally posted by @thibault-martinez in https://github.com/iotaledger/iota/pull/4750#discussion_r1910473011_

### PR DESCRIPTION
**Pull request by tomxey**
# Description of change

Fix complex return type in paginate_consistent_indices

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/4755

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [ ] Patch-specific tests (correctness, functionality coverage)

### Infrastructure QA (only required for crates that are maintained by @iotaledger/infrastructure)

- [ ] Synchronization of the indexer from genesis for a network including migration objects.
- [ ] Restart of indexer synchronization locally without resetting the database.
- [ ] Restart of indexer synchronization on a production-like database.
- [ ] Deployment of services using Docker.
- [ ] Verification of API backward compatibility.

### CODE REVIEW

File: crates/iota-graphql-rpc/src/types/cursor.rs [hunk 1]
```diff
@@ -244,26 +244,28 @@ where
...
 
+pub(crate) struct ConsistentPage {
+    /// Whether there is a previous page available
+    pub has_previous_page: bool,
+    /// Whether there is a next page available
+    pub has_next_page: bool,
+    /// The checkpoint viewed at for consistency
+    pub checkpoint_viewed_at: u64,
+    /// Iterator of cursors within the page
+    pub cursors: Box<dyn Iterator<Item = JsonCursor<ConsistentIndexCursor>> + Send>,
```
Comment (kodemartin) [inline crates/iota-graphql-rpc/src/types/cursor.rs]: No need for dynamic dispatch here. You can add generics to `ConsistentPage<I: Iterator<Item = ConsistentPageCursor>> `  and use `cursors: I`.

where `type ConsistentPageCursor = JoinCursor<ConsistentIndexCursor>`

Then you can return `ConsistentPage<impl Iterator<Item = ConsistentPageCurors>>` in `paginate_consistent_indices`

Comment (tomxey) [reply crates/iota-graphql-rpc/src/types/cursor.rs]: Done in 2052acd7f0aaee7e71e4314a2ea6123670d3207f

**Review by kodemartin — APPROVED** [review]

**Review by sergiupopescu199 — APPROVED** [review]
lgtm ✨
