### PR TITLE
fix(wallet, dapp-kit): overflow issues with small screens

### LINKED ISSUE #5706: improve responsive design for small screens
Multiple testers have reported issues with the responsive design of the wallet and dappKit:

Image
Image
Image
Image

### PR DESCRIPTION
**Pull request by VmMad**
# Description of change

Fixes #5706
## Links to any relevant issues

Be sure to reference any related issues by adding `fixes #(issue)`.

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: apps/ui-kit/src/lib/components/organisms/dialog/Dialog.tsx [hunk 1]
```diff
@@ -68,8 +68,8 @@ const DialogContent = React.forwardRef<
         }, [containerId]);
         const positionClass =
             position === DialogPosition.Right
-                ? 'right-0 h-screen top-0 w-full'
-                : 'max-h-[60vh] left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 rounded-xl';
+                ? 'overflow-hidden right-0 h-screen top-0 w-full'
```
Comment (evavirseda) [inline apps/ui-kit/src/lib/components/organisms/dialog/Dialog.tsx:71]: this is a bit tricky :see_no_evil:  the overflow is good now, but the title disappears
Screenshot from 2025-03-14 08-29-38
image

**Review by evavirseda — CHANGES_REQUESTED** [review]
nice job, just one detail :pray:

**Review by evavirseda — APPROVED** [review]
:star:

**Review by brancoder — APPROVED** [review]
LGTM
