### PR TITLE
fix(node): Fix logic for end-of-epoch checkpoint when dkg has failed

### LINKED ISSUE #4672: [cherrypick] Fix logic for end-of-epoch checkpoint when dkg has faile… · MystenLabs/sui@29ff3e3
[[cherrypick] Fix logic for end-of-epoch checkpoint when dkg has faile… · MystenLabs/sui@29ff3e3](https://github.com/MystenLabs/sui/commit/29ff3e3f53fc7aa590da97d1033265645be1ea1a)   

bug fix.

### PR DESCRIPTION
**Pull request by bingyanglin**
# Description of change

If DKG has failed, we might accidentally construct two end of epoch checkpoints, refer to [[cherrypick] Fix logic for end-of-epoch checkpoint when dkg has failed (#19976)](https://github.com/MystenLabs/sui/pull/19976)

## Links to any relevant issues

fixes #4672

## Type of change

- Bug fix

## How the change has been tested

Ran the local network with `RUST_LOG=info cargo run --release --bin iota start --force-regenesis --with-faucet`

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by jkrvivian — APPROVED** [review]

File: crates/iota-core/src/authority/authority_per_epoch_store.rs [hunk 1]
```diff
@@ -2660,29 +2659,33 @@ impl AuthorityPerEpochStore {
...
             }
             checkpoint_roots.extend(roots.into_iter());
+
+            if let Some(randomness_round) = randomness_round {
+                randomness_roots.insert(TransactionKey::RandomnessRound(
+                    self.epoch(),
+                    randomness_round,
+                ));
+            }
+            // Determine whether to write pending checkpoint for user tx with randomness.
```
Comment (muXxer) [inline crates/iota-core/src/authority/authority_per_epoch_store.rs:2670]: upstream had a newline between the bracket and the comment. Why did you remove it?

**Review by muXxer — APPROVED** [review]

**Review by piotrm50 — APPROVED** [review]

File: crates/iota-core/src/authority/authority_per_epoch_store.rs (hunk 1 above)
Comment (bingyanglin) [reply crates/iota-core/src/authority/authority_per_epoch_store.rs:2670]: Added the newline back in [a8a6d2a](https://github.com/iotaledger/iota/pull/4899/commits/a8a6d2a8e0acbbd52da53e377d7559971bb1c5a1), thanks for pointing that out!
