### PR TITLE
fix(wallet-dashboard): Show validator image in staked timelock objects

### LINKED ISSUE #6739: Display metadata of validator in vested staking
In vested staking the validator is not being displayed with its metadata

Image

### PR DESCRIPTION
**Pull request by marc2332**
Closes https://github.com/iotaledger/iota/issues/6739

### CODE REVIEW

**Review by evavirseda — APPROVED** [review]
works
image

File: apps/wallet-dashboard/components/staked-timelock-object/StakedTimelockObject.tsx [hunk 1]
```diff
@@ -52,14 +50,18 @@ export function StakedTimelockObject({
...
     });
-
     return (
         <Card onClick={() => handleUnstake(timelockedStakedObject)}>
             <CardImage>
-                <ImageIcon src={null} label={name} fallback={name} size={ImageIconSize.Large} />
+                <ImageIcon
+                    src={validatorMeta?.imageUrl || null}
+                    label={validatorMeta?.name || ''}
+                    fallback={validatorMeta?.name || ''}
```
Comment (brancoder) [inline apps/wallet-dashboard/components/staked-timelock-object/StakedTimelockObject.tsx]: label and fallback use to fallback to `validatorAddress` if there is validatorMeta?.name, should we add this back in?

**Review by brancoder — APPROVED** [review]
LG just a nit about fallback name

**Review by brancoder — CHANGES_REQUESTED** [review]
add falback to image

**Review by brancoder — APPROVED** [review]
LGTM 👍

**Review by brancoder — APPROVED** [review]
LGTM 👍
