### PR TITLE
fix(docs): remove exchange integration duplicate

### LINKED ISSUE #6291: [doc] Duplicate exchange integration guide doc.
## Bug description
Duplicate exchange integration guide pages: 

1. https://docs.iota.org/developer/exchange-integration/ 
This one is reachable from side bar on https://docs.iota.org/developer/

2. https://docs.iota.org/exchange-integration-guide
This looks like a free document, I do not see how to reach this doc. from any route

They both have recent commits, and they are similar but not the same. 

More details also here: https://github.com/iotaledger/iota/issues/6020#issuecomment-2775120189. 

We have made our changes to these docs. in this PR https://github.com/iotaledger/iota/pull/6031/files which we want to merge very soon.

### PR DESCRIPTION
**Pull request by Dr-Electron**
# Description of change

Fixed the duplicate issue by removing one of them. Seems like the deleted one was based on a really old version before Dave refactored it here: https://github.com/iotaledger/iota/pull/921/files

## Links to any relevant issues

Fixes #6291.

## Type of change

- Documentation Fix

## How the change has been tested

Not tested yet. We should import the code snippets tho to make sure everything works

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by lucas-tortora — APPROVED** [review]

**Review by Ginowine — APPROVED** [review]

File: docs/examples/rust/exchange/get-balance.rs [hunk 1]
```diff
@@ -0,0 +1,14 @@
+use std::str::FromStr;
+use iota_sdk::types::base_types::IotaAddress;
+use iota_sdk::IotaClientBuilder;
+
+#[tokio::main]
+async fn main() -> Result<(), anyhow::Error> {
+   let iota = IotaClientBuilder::default().build(
+      "https://api.devnet.iota.cafe:443",
+   ).await.unwrap();
```
Comment (Thoralf-M) [inline docs/examples/rust/exchange/get-balance.rs]: Btw why don't use testnet? Also fmt fails
```suggestion
   let iota = IotaClientBuilder::default().build_testnet().await?;
```

File: docs/examples/rust/exchange/get-balance.rs [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+   let address = IotaAddress::from_str("0x849d63687330447431a2e76fecca4f3c10f6884ebaa9909674123c6c662612a3")?;
+   let objects = iota.coin_read_api().get_balance(address, None).await?;
+   println!("{:?}", objects);
```
Comment (Thoralf-M) [inline docs/examples/rust/exchange/get-balance.rs]:
```suggestion
   println!("{objects:?}");
```

File: docs/examples/rust/exchange/derive-address.rs [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+    // Example of deriving a Secp256k1 address from a public key
+    let flag = 0x01; // 0x01 = Secp256k1, 0x02 = Secp256r1, 0x03 = multiSig
+    // Hash the [flag, public key] bytearray using Blake2b
+    let mut hasher = iota_types::crypto::DefaultHash::default();
+    let example_public_key: &str = "0xc5b4eb7d3c7efdeb7f3546fee9971536a24298d0f6cac7a48619c343b3999e11";
+    hasher.update([flag]);
+    hasher.update(example_public_key);
+    let arr = hasher.finalize();
+    let iota_address_string = hex::encode(arr);
+    println!("Address: 0x{}", iota_address_string);
```
Comment (Thoralf-M) [inline docs/examples/rust/exchange/derive-address.rs]:
```suggestion
    println!("Address: 0x{iota_address_string}");
```

File: docs/examples/rust/exchange/get-balance.rs (hunk 1 above)
Comment (Dr-Electron) [reply docs/examples/rust/exchange/get-balance.rs]: No clue dbf 🤔 
Guess back then we only had devnet 😅
