### PR TITLE
fix(iota): fix type resolution for primitive type instantiations

### LINKED ISSUE #4921: fix(iota): type resolution for primitive type instantiations in PTB CLI
https://github.com/MystenLabs/sui/pull/20078

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Fixes an issue where type layouts were not always returned for all primitive types, and simplifies the APIs around this a bit.
Porting over https://github.com/MystenLabs/sui/pull/20078

## Links to any relevant issues

Fixes #4921 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Running the added test

### CODE REVIEW

**Review by DaughterOfMars — APPROVED** [review]

File: crates/iota-json/src/lib.rs [hunk 1]
```diff
@@ -581,104 +579,97 @@ pub fn primitive_type(
...
+        TypeTag::Vector(tag) => MTL::Vector(Box::new(layout_of_primitive_typetag(tag)?)),
+        TypeTag::Struct(stag) => {
+            let StructTag {
+                address,
+                module,
+                name,
+                type_params: type_args,
+            } = &**stag;
+            let resolved_struct = (address, module.as_ident_str(), name.as_ident_str());
+            // is id or..
```
Comment (Alex6323) [inline crates/iota-json/src/lib.rs:654]: is that comment really necessary?

**Review by Alex6323 — APPROVED** [review]

**Review by samuel-rufi — APPROVED** [review]

**Review by jkrvivian — APPROVED** [review]
