### PR TITLE
fix(wallet-dashboard): number of different native tokens in migration summary

### LINKED ISSUE #4578: Fix number of native tokens in migration summary
## Bug description

Image

The sum of the native tokens is not correct, we need to count the different types of native tokens, not the number of bags of native tokens. In the example above, there are 2 types of native tokens, `BOX_COIN` and `TOOL_COIN`, but the number of native tokens is 6

https://github.com/iotaledger/iota/blob/78f337fda8dcf46d3fef0771764b175266c6fc3f/apps/wallet-dashboard/lib/utils/migration/groupStardustObjectsByMigrationStatus.ts#L79

### PR DESCRIPTION
**Pull request by evavirseda**
# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/4578

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: apps/wallet-dashboard/lib/utils/migration/groupStardustObjectsByMigrationStatus.ts [hunk 1]
```diff
@@ -58,25 +61,35 @@ interface SummarizeMigrationObjectParams {
     basicOutputs: IotaObjectData[] | undefined;
     nftOutputs: IotaObjectData[] | undefined;
     address: string;
+    resolvedObjects?: ResolvedObjectTypes[];
 }
 
 export function summarizeMigratableObjectValues({
```
Comment (begonaalvarezd) [inline apps/wallet-dashboard/lib/utils/migration/groupStardustObjectsByMigrationStatus.ts]: I bet this issue also happens in the unmigratable objects too, so we should replicate the same logic there too 🙏🏼

File: apps/wallet-dashboard/lib/utils/migration/groupStardustObjectsByMigrationStatus.ts [hunk 2]
```diff
@@ -149,3 +162,18 @@ export function extractNotOwnedStorageDepositReturnAmount(
...
     return null;
 }
+
+export function calculateTotalNativeTokensByName(objects: ResolvedObjectTypes[]): number {
+    const uniqueTokens: string[] = [];
+
+    return objects.reduce((total, obj) => {
+        if (
+            obj.commonObjectType === CommonMigrationObjectType.NativeToken &&
+            !uniqueTokens.includes(obj.name)
```
Comment (begonaalvarezd) [inline apps/wallet-dashboard/lib/utils/migration/groupStardustObjectsByMigrationStatus.ts]: I think there are be potentially 2 coins with the same name but the type must be different, so we should check against the type, not the name

Comment (begonaalvarezd) [reply apps/wallet-dashboard/lib/utils/migration/groupStardustObjectsByMigrationStatus.ts]: eg 
```ts
export function getUniqueNativeTokensByCoinType(objects: ResolvedObjectTypes[]): number {
    return new Set(
        objects
            .filter((obj) => obj.commonObjectType === CommonMigrationObjectType.NativeToken)
            .map((obj) => obj.coinType),
    ).size;
}
```

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by VmMad — DISMISSED** [review]

**Review by begonaalvarezd — APPROVED** [review]

**Review by VmMad — APPROVED** [review]
Looks good to me

File: apps/wallet-dashboard/app/(protected)/migrations/page.tsx [hunk 3]
```diff
@@ -47,24 +47,49 @@ function MigrationDashboardPage(): JSX.Element {
...
     } = stardustMigrationObjects || {};
 
+    const { data: resolvedMigrationObjects = [] } = useGroupedStardustObjects(
+        [...(migratableBasicOutputs || []), ...(migratableNftOutputs || [])],
+        false,
+    );
+    const { data: resolvedTimelockedObjects = [] } = useGroupedStardustObjects(
+        [...(timelockedBasicOutputs || []), ...(timelockedNftOutputs || [])],
+        true,
+    );
```
Comment (cpl121) [inline apps/wallet-dashboard/app/(protected)/migrations/page.tsx:57]: we could do this inside the `getStardustObjectsTotals` function, by this way we would avoid repeating code

**Review by cpl121 — CHANGES_REQUESTED** [review]

File: apps/wallet-dashboard/app/(protected)/migrations/page.tsx (hunk 3 above)
Comment (cpl121) [reply apps/wallet-dashboard/app/(protected)/migrations/page.tsx:57]: I haven't said anything, we can't add a hook in the function 🤐

**Review by cpl121 — APPROVED** [review]
