### PR TITLE
fix(iota-replay): verify_latest_tx_replay_testnet_mainnet but only for the  testnet once mainnet is ready

### LINKED ISSUE #4400: [iota-replay]: fix verify_latest_tx_replay_testnet_mainnet for the testnet

### PR DESCRIPTION
**Pull request by Dkwcs**
# Description of change

The test is currently passing only on the testnet. Mainnet maintenance will be added once it’s ready.
Related issue for future fix - https://github.com/iotaledger/iota/issues/4405.

## Links to any relevant issues

Fix #4400 .

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

`cargo test verify_latest_tx_replay_testnet_mainnet`

### CODE REVIEW

File: crates/iota-replay/src/tests.rs [hunk 1]
```diff
@@ -30,7 +29,8 @@ async fn verify_latest_tx_replay_impl() {
     let urls: Vec<_> = default_cfg
         .base_network_configs
         .iter()
-        .filter(|q| q.name != "devnet") // Devnet is not always stable
+        // TODO: enable this when mainnet is launched
```
Comment (miker83z) [inline crates/iota-replay/src/tests.rs:32]: Could you create an issue for this TODO?

**Review by miker83z — APPROVED** [review]

File: crates/iota-replay/src/tests.rs (hunk 1 above)
Comment (Dkwcs) [reply crates/iota-replay/src/tests.rs:32]: Sure

Comment (Dkwcs) [reply crates/iota-replay/src/tests.rs:32]: https://github.com/iotaledger/iota/issues/4405

File: crates/iota-replay/src/tests.rs [hunk 2]
```diff
@@ -16,11 +16,10 @@ use crate::{
 
 /// Keep searching for non-system TXs in the checkppints for this long
 /// Very unlikely to take this long, but we want to be sure we find one
-const NUM_CHECKPOINTS_TO_ATTEMPT: usize = 1_000;
+const NUM_CHECKPOINTS_TO_ATTEMPT: usize = 10_000;
```
Comment (Thoralf-M) [inline crates/iota-replay/src/tests.rs:19]: Is this increase required for it to pass?

Comment (miker83z) [reply crates/iota-replay/src/tests.rs:19]: We currently have not enough user transactions in the testnet 😅

File: crates/iota-replay/src/tests.rs (hunk 1 above)
Comment (miker83z) [reply crates/iota-replay/src/tests.rs:32]: Thanks 🙏🏻

**Comment by Thoralf-M** [comment]
Test fails in CI

File: crates/iota-replay/src/tests.rs [hunk 3]
```diff
@@ -30,7 +29,8 @@ async fn verify_latest_tx_replay_impl() {
     let urls: Vec<_> = default_cfg
         .base_network_configs
         .iter()
-        .filter(|q| q.name != "devnet") // Devnet is not always stable
+        // TODO: enable this when mainnet is launched
+        .filter(|q| q.name != "devnet" && q.name != "mainnet") // Devnet is not always stable, mainnet is not ready
         .map(|c| c.public_full_node.clone())
         .collect();
```
Comment (Thoralf-M) [inline crates/iota-replay/src/tests.rs:36]: Btw not related to this change, but further below is a function called `extract_one_system_tx`, shouldn't this be called `extract_one_no_system_tx` instead? Fine to open an issue and addressing it separated, just want to have confirmation that this is wrong

Comment (Dkwcs) [reply crates/iota-replay/src/tests.rs:36]: yeah, I think name of methods is quite wrong, because inside we don’t look at system txs
` txs.retain(|q| *q != TransactionDigest::genesis_marker());`
I can rename this function in scope of this task

**Review by Thoralf-M — APPROVED** [review]

**Review by Thoralf-M — APPROVED** [review]

**Review by valeriyr — APPROVED** [review]
