### PR TITLE
fix(network-metrics-processor): Avoid expensive transaction table scans for `tx_count_metrics` table

### LINKED ISSUE #5334: [analytical-indexer] `tx_count_metrics` table lags behind
## Bug description

When comparing the `tx_count_metrics` table with the `checkpoints` or `epoch` table, it appears to be lagging and not properly synchronized. While the `checkpoints` and `epoch` table show the recent epoch/checkpoint numbers, this is not the case with the `tx_count_metrics` table.

As a result, the “30d peak TPS” value in Explorer is not up to date.

### PR DESCRIPTION
**Pull request by samuel-rufi**
# Description of change

Refactors the existing query for inserting transaction count metrics into the `tx_count_metrics` table by:

- It efficiently filters transactions from the `transactions` table using `tx_sequence_number`, leveraging the indexed primary key, reducing unnecessary full table scans.
- The needed transaction sequence range is fetched from checkpoints via a `checkpoint_range` CTE.

These changes _**significantly**_ optimize the query performance and are critical in order to be able to maintain the `tx_count_metrics` table.

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/5334

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Verified that the updated query correctly filters transaction data.

## Change checklist

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota-indexer/src/processors/network_metrics_processor.rs [hunk 1]
```diff
@@ -10,7 +10,7 @@ use crate::{
     types::IndexerResult,
 };
 
-const NETWORK_METRICS_PROCESSOR_BATCH_SIZE: usize = 10;
+const NETWORK_METRICS_PROCESSOR_BATCH_SIZE: usize = 1000;
```
Comment (Thoralf-M) [inline crates/iota-indexer/src/processors/network_metrics_processor.rs]: This would be every 3,3 minutes? Why not smaller? For current TPS 3 minutes sounds a lot or are they computed separated?

Comment (samuel-rufi) [reply crates/iota-indexer/src/processors/network_metrics_processor.rs]: Yes exactly, it would be around every 3-4 minutes to write into the `tx_count_metrics` table. The idea was to minimize query calls. We have a separate calculation for the `real_time_tps`, however after looking more into it, it appears to also derive its base data from `tx_count_metrics`. That's really a problem.

So what we could do is:
1. populate the `tx_count_metrics` more frequently as you mentioned (Sui had a checkpoint range of 10 which however didn't really work with the expensive query)
2. or calculate the real time tps completely separately

Generally, the query gets more expensive the larger the checkpoint range is and the more transactions are within that range. Anyways, in the end `tx_count_metrics` will always contain metrics for each checkpoint. So we have to produce them sooner or later. So I guess to have more up-to-date metrics in that table we should rather decide for a lower value as you suggested also considering smaller ranges are quite fast to handle.

I would suggest something like 1-2 seconds, what do you think? So I guess we can leave the batch size of 10 as it is.

Comment (Thoralf-M) [reply crates/iota-indexer/src/processors/network_metrics_processor.rs]: Is [Optimize query in order to handle larger checkpoint ranges](https://github.com/iotaledger/iota/pull/5386/commits/57c3a00a089eee695abcbda3ff0087e91f0fa9b9) then still an improvement?

Comment (samuel-rufi) [reply crates/iota-indexer/src/processors/network_metrics_processor.rs]: Yes, also for smaller checkpoint ranges (diff 10) the query before appeared to be quite slow because of the `BETWEEN`, even though we were joining on `tx_sequence_number`. I was first testing only with super small ranges (as not even these did work before with the Sui query) and noticed the issue later for a bit larger and larger checkpoint ranges. So yes, it's really needed.

File: crates/iota-indexer/src/store/pg_indexer_analytical_store.rs [hunk 2]
```diff
@@ -480,29 +480,40 @@ impl IndexerAnalyticalStore for PgIndexerAnalyticalStore {
...
             SUM(CASE WHEN success_command_count > 0 THEN 1 ELSE 0 END) AS total_successful_transaction_blocks,
             SUM(success_command_count) AS total_successful_transactions
-          FROM filtered_txns
-          GROUP BY checkpoint_sequence_number, epoch ORDER BY checkpoint_sequence_number
-          ON CONFLICT (checkpoint_sequence_number) DO NOTHING;
-        ", start_checkpoint, end_checkpoint
+        FROM filtered_txns
+        GROUP BY checkpoint_sequence_number, epoch
+        ORDER BY checkpoint_sequence_number
+        ON CONFLICT (checkpoint_sequence_number) DO NOTHING;"
```
Comment (kodemartin) [inline crates/iota-indexer/src/store/pg_indexer_analytical_store.rs]: Wouldn't it be simpler and likely more efficient to simplify to
```sql
)

INSERT INTO tx_count_metrics
SELECT
    ecr.checkpoint_sequence_number,
    ecr.epoch,
    MAX(t.timestamp_ms) AS timestamp_ms,
    COUNT(*) AS total_transaction_blocks,
    SUM(CASE WHEN t.success_command_count > 0 THEN 1 ELSE 0 END) AS total_successful_transaction_blocks,
    SUM(t.success_command_count) AS total_successful_transactions
FROM expanded_checkpoint_range ecr
JOIN transactions t
    ON t.tx_sequence_number = ecr.tx_sequence_number
GROUP BY ecr.checkpoint_sequence_number, ecr.epoch
ORDER BY ecr.checkpoint_sequence_number
ON CONFLICT (checkpoint_sequence_number) DO NOTHING;

```
That is remove the `filtered_txns` and `JOIN` directly on `transactions`?

Comment (samuel-rufi) [reply crates/iota-indexer/src/store/pg_indexer_analytical_store.rs]: You're absolutely right @kodemartin !

Comment (samuel-rufi) [reply crates/iota-indexer/src/store/pg_indexer_analytical_store.rs]: Fixed with https://github.com/iotaledger/iota/pull/5386/commits/a215e77d6945679177a79d94981d20e4930a6717

**Review by kodemartin — APPROVED** [review]
lgtm :bar_chart:

**Review by sergiupopescu199 — APPROVED** [review]
LGTM 🧚‍♀️
