### PR TITLE
feat(indexer): Do not reindex objects in checkpoint indexing, fix race conditions for display table

### LINKED ISSUE #7289: feat(indexer): disable reindexing of optimistic transactions
## Description

Following #6320

> As discussed, there are three conditions to eliminate the race conditions altogether:
> 
> 1. Disable reindexing of the checkpoint transactions that have been indexed optimistically. Suffice it to check it there is an entry in `tx_global_order`. 
> 2. Ensure that if an optimistic transactions gets an `tx_global_order` entry, it will be (or will have been) indexed.
> 3. Ensure that all transaction dependencies of an optimistic transaction are indexed before proceeding with optimistic indexing. 

This task is for handling (1). That is we want to disable reindexing of checkpoint transactions that already have a row in `tx_global_order` from the optimistic execution path.

### PR DESCRIPTION
**Pull request by tomxey**
# Description of change

Do not reindex objects in checkpoint indexing, fix race conditions for display table

In general this PR makes sure that it's safe to index old transactions, in a sense that newer data will not be overwritten by older data. (with an exception of concurrent indexing, and indexing transactions for which dependencies are not yet indexed)

This PR is a first step to fix race conditions on `objects` table. To fix them completely https://github.com/iotaledger/iota/issues/7290 and https://github.com/iotaledger/iota/issues/6321 would need to be completed.
This PR fixes race conditions on `display` table completely.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/7289

## How the change has been tested

`cargo test --profile simulator --package iota-indexer --test rpc-tests --all-features`

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [x] Patch-specific tests (correctness, functionality coverage) - partially tested, race conditions on `display` table are fixed so they are tested, tests for `objects` table can be added later when remaining issues are closed

### Infrastructure QA (only required for crates that are maintained by @iotaledger/infrastructure)

- [ ] Synchronization of the indexer from genesis for a network including migration objects.
- [ ] Restart of indexer synchronization locally without resetting the database.
- [ ] Restart of indexer synchronization on a production-like database.
- [ ] Deployment of services using Docker.
- [ ] Verification of API backward compatibility.

### Release Notes

- [ ] Protocol:
- [ ] Nodes (Validators and Full nodes):
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [ ] CLI:
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: crates/iota-indexer/src/handlers/committer.rs [hunk 1]
```diff
@@ -243,3 +263,46 @@ async fn commit_checkpoints<S>(
...
+    let already_processed_obj_versions: HashSet<(ObjectID, SequenceNumber)> =
+        transactions_to_commit
+            .iter()
+            .filter(|tx| already_indexed_txs.contains(tx.tx_digest.inner().as_slice()))
+            .flat_map(|tx| {
+                let modified_objs = tx.effects.all_changed_objects();
+                let deleted_objs = tx.effects.all_tombstones();
+                modified_objs
+                    .into_iter()
+                    .map(|o| (o.0.0, o.0.1))
```
Comment (sergiupopescu199) [inline crates/iota-indexer/src/handlers/committer.rs]: nit: if possible, we could add a tuple containing the two values to understand that is `o.0.0` & `o.0.1`

**Review by sergiupopescu199 — APPROVED** [review]
lgtm ✨

**Review by kodemartin — CHANGES_REQUESTED** [review]
Pending #7518

File: crates/iota-indexer/src/handlers/committer.rs (hunk 1 above)
Comment (kodemartin) [reply crates/iota-indexer/src/handlers/committer.rs]: Reverted this logic following #7518

**Review by kodemartin — APPROVED** [review]
