### PR TITLE
fix(genesis-geremony): fix examine-genesis-checkpoint

### LINKED ISSUE #4528: [genesis] Fix broken examine-genesis-checkpoint command of the genesis ceremony
The `examine-genesis-checkpoint` subcommand of the `iota genesis-ceremony` command is not compatible with a genesis ceremony involving a migrated state. This command should be fixed, as it aborts.

Full command: `iota genesis-ceremony examine-genesis-checkpoint`
> "This command opens the Genesis Inspector, a responsive command-line tool which allows viewing various attributes of the current built checkpoint."

### PR DESCRIPTION
**Pull request by nonast**
# Description of change

This (draft) PR fixes the `examine-genesis-checkpoint` command of the genesis ceremony. Due to the migrated objects, the genesis inspector did not function correctly anymore, as not all objects exist in the first genesis state. These migrated objects are created in the following transactions. The genesis inspector was not built to take these extra migrated objects into account. In this PR, the migrated objects are also included in the list of objects that is used to count the total supply. The object inspector of this function now also functions as expected.

**Will rebase on develop**

## Links to any relevant issues

fixes #4528 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Ran a genesis ceremony up to the point where `examine-genesis-checkpoint` is called:
```
$ mkdir genesis && cd genesis
$ cargo run --release --bin iota genesis-ceremony init
$ cargo run --release --bin iota-genesis-builder -- --disable-global-snapshot-verification iota  --snapshot-path ../../latest-full_snapshot.bin --target-network alphanet-test
$ ../target/release/iota validator make-validator-info validator1 validator1 https://www.iota.org/favicon.png https://www.iota.org /ip4/127.0.0.1 1000
$ ../target/release/iota genesis-ceremony add-validator \
    --name validator1 \
    --authority-key-file authority.key \
    --protocol-key-file protocol.key \
    --account-key-file account.key \
    --network-key-file network.key \
    --network-address /ip4/127.0.0.1/tcp/38189/http \
    --p2p-address /ip4/127.0.0.1/udp/34523 \
    --primary-address /ip4/127.0.0.1/udp/38603 \
    --description validator1 \
    --image-url https://www.iota.org/favicon.png \
    --project-url https://www.iota.org
$ ADDRESS=$(sed -n 4p committee/validator1 |  cut -d ":" -f2- | tr -d ' "')
$ echo "delegator,validator,amount-nanos-to-stake,amount-nanos-to-pay-gas" >> delegations.csv
$ echo "0x4f72f788cdf4bb478cf9809e878e6163d5b351c82c11f1ea28750430752e7892,${ADDRESS},1500000000000000,1500000000000000" >> delegations.csv
$ ../target/release/iota genesis-ceremony init-delegations --delegations-path delegations.csv
$ ../target/release/iota genesis-ceremony build-unsigned-checkpoint --local-migration-snapshots stardust_object_snapshot.bin
$ ../target/release/iota genesis-ceremony examine-genesis-checkpoint 
```

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota/src/genesis_inspector.rs [hunk 1]
```diff
@@ -65,10 +73,23 @@ pub(crate) fn examine_genesis_checkpoint(genesis: UnsignedGenesis) {
...
+    let mut timelocked_staked_iota_map = BTreeMap::new();
+    let mut alias_output_iota_map = BTreeMap::new();
+    let mut basic_output_iota_map = BTreeMap::new();
+    let mut nft_output_iota_map = BTreeMap::new();
     let mut coin_metadata_map = BTreeMap::new();
     let mut other_object_map = BTreeMap::new();
 
-    for object in genesis.objects() {
+    // Combine migration objects with genesis objects.
+    let genesis_objects = genesis.objects().to_vec();
```
Comment (thibault-martinez) [inline crates/iota/src/genesis_inspector.rs]: You should be able to chain with the slice directly, avoiding a Vec allocation

File: crates/iota-types/src/stardust/output/nft.rs [hunk 2]
```diff
@@ -469,4 +469,14 @@ impl NftOutput {
 
         Ok(move_nft_output_object)
     }
+
+    /// Create a `NftOutput` from BCS bytes.
+    pub fn from_bcs_bytes(content: &[u8]) -> std::result::Result<Self, bcs::Error> {
```
Comment (thibault-martinez) [inline crates/iota-types/src/stardust/output/nft.rs]: `Result` is in scope already, you don't need the fully qualified path

File: crates/iota-types/src/stardust/output/alias.rs [hunk 3]
```diff
@@ -201,4 +201,14 @@ impl AliasOutput {
 
         Ok(move_alias_output_object)
     }
+
+    /// Create a `AliasOutput` from BCS bytes.
```
Comment (thibault-martinez) [inline crates/iota-types/src/stardust/output/alias.rs]:
```suggestion
    /// Create an `AliasOutput` from BCS bytes.
```

File: crates/iota-types/src/stardust/output/alias.rs [hunk 4]
```diff
@@ -201,4 +201,14 @@ impl AliasOutput {
...
+    pub fn from_bcs_bytes(content: &[u8]) -> Result<Self, bcs::Error> {
+        bcs::from_bytes(content)
+    }
+
+    /// Serialize a `AliasOutput` as a `Vec<u8>` of BCS.
```
Comment (thibault-martinez) [inline crates/iota-types/src/stardust/output/alias.rs]:
```suggestion
    /// Serialize an `AliasOutput` as a `Vec<u8>` of BCS.
```

File: crates/iota-genesis-builder/src/lib.rs [hunk 5]
```diff
@@ -149,6 +149,10 @@ impl Builder {
         }
     }
 
+    pub fn tx_migration_objects(self) -> Vec<Object> {
+        self.migration_tx_data.unwrap().get_objects().collect()
```
Comment (thibault-martinez) [inline crates/iota-genesis-builder/src/lib.rs]: A public API like this shouldn't be able to panic IMO. I would make this function to return an Option and map `get_objects().collect()`

File: crates/iota/src/genesis_inspector.rs [hunk 6]
```diff
@@ -94,6 +115,54 @@ pub(crate) fn examine_genesis_checkpoint(genesis: UnsignedGenesis) {
                     assert_eq!(validator.staking_pool.id, staked_iota.pool_id());
 
                     staked_iota_map.insert(object.id(), staked_iota);
+                } else if let Some(time_locked) = object.as_timelock_balance_maybe() {
```
Comment (thibault-martinez) [inline crates/iota/src/genesis_inspector.rs]: Nitpicking but `time_locked` and `timelock` in the same line is triggering me, space or not space? (I vote no space)

**Comment by miker83z** [comment]
@nonast please add in the description the steps on how to reproduce the environment to execute the command:
```console
$ mkdir genesis && cd genesis
$ cargo run --release --bin iota genesis-ceremony init
$ cargo run --release --bin iota-genesis-builder -- --disable-global-snapshot-verification iota  --snapshot-path ../../latest-full_snapshot.bin --target-network alphanet-test
$ ../target/release/iota validator make-validator-info validator1 validator1 https://www.iota.org/favicon.png https://www.iota.org /ip4/127.0.0.1 1000
$ ../target/release/iota genesis-ceremony add-validator \
    --name validator1 \
    --authority-key-file authority.key \
    --protocol-key-file protocol.key \
    --account-key-file account.key \
    --network-key-file network.key \
    --network-address /ip4/127.0.0.1/tcp/38189/http \
    --p2p-address /ip4/127.0.0.1/udp/34523 \
    --primary-address /ip4/127.0.0.1/udp/38603 \
    --description validator1 \
    --image-url https://www.iota.org/favicon.png \
    --project-url https://www.iota.org
$ ADDRESS=$(sed -n 4p committee/validator1 |  cut -d ":" -f2- | tr -d ' "')
$ echo "delegator,validator,amount-nanos-to-stake,amount-nanos-to-pay-gas" >> delegations.csv
$ echo "0x4f72f788cdf4bb478cf9809e878e6163d5b351c82c11f1ea28750430752e7892,${ADDRESS},1500000000000000,1500000000000000" >> delegations.csv
$ ../target/release/iota genesis-ceremony init-delegations --delegations-path delegations.csv
$ ../target/release/iota genesis-ceremony build-unsigned-checkpoint --local-migration-snapshots stardust_object_snapshot.bin
$ ../target/release/iota genesis-ceremony examine-genesis-checkpoint 
```

File: crates/iota-genesis-builder/src/lib.rs (hunk 5 above)
Comment (kodemartin) [reply crates/iota-genesis-builder/src/lib.rs]: I would go even further and `unwrap_or_default()` after mapping. `Option<Vec<_>>` is a bit redundant since the `Vec` can be empty.

File: crates/iota-types/src/stardust/output/alias.rs [hunk 7]
```diff
@@ -201,4 +201,14 @@ impl AliasOutput {
...
+    pub fn to_bcs_bytes(&self) -> Vec<u8> {
+        bcs::to_bytes(&self).unwrap()
```
Comment (kodemartin) [inline crates/iota-types/src/stardust/output/alias.rs]: Nit: `unwrap` in these functions seems odd as well. You can either `expect` or just propagate the `Result`.

**Review by kodemartin — APPROVED** [review]
lgtm with the minor suggestions already made in the patch.

File: crates/iota-types/src/object.rs [hunk 8]
```diff
@@ -819,6 +820,30 @@ impl ObjectInner {
         }
     }
 
+    pub fn as_alias_output_maybe(&self) -> Option<AliasOutput> {
```
Comment (miker83z) [inline crates/iota-types/src/object.rs]: It would be nice to have similar interfaces used when working in the same spots, i.e., `GasCoin`, `CoinMetadata` and `StakedIota` use the try_from an Object. So I would avoid this `maybe` functions and implement something like this for each Stardust type:
```rust
impl TryFrom<&Object> for AliasOutput {
    type Error = IotaError;
    fn try_from(object: &Object) -> Result<Self, Self::Error> {
        match &object.data {
            Data::Move(o) => {
                if o.type_().is_coin_metadata() {
                    return AliasOutput::from_bcs_bytes(o.contents());
                }
            }
            Data::Package(_) => {}
        }

        Err(IotaError::Type {
            error: format!("Object type is not a AliasOutput: {:?}", object),
        })
    }
}
```

File: crates/iota-types/src/stardust/output/alias.rs [hunk 9]
```diff
@@ -201,4 +201,14 @@ impl AliasOutput {
 
         Ok(move_alias_output_object)
     }
+
+    /// Create a `AliasOutput` from BCS bytes.
+    pub fn from_bcs_bytes(content: &[u8]) -> Result<Self, bcs::Error> {
+        bcs::from_bytes(content)
+    }
```
Comment (miker83z) [inline crates/iota-types/src/stardust/output/alias.rs]:
```suggestion
    pub fn from_bcs_bytes(content: &[u8]) -> Result<Self, IotaError> {
        bcs::from_bytes(content).map_err(|err| IotaError::ObjectDeserialization {
            error: format!("Unable to deserialize AliasOutput object: {}", err),
        })
    }
```

File: crates/iota-types/src/object.rs (hunk 8 above)
Comment (miker83z) [reply crates/iota-types/src/object.rs]: Check the comment in `from_bcs_bytes`

File: crates/iota/src/genesis_inspector.rs (hunk 6 above)
Comment (miker83z) [reply crates/iota/src/genesis_inspector.rs]: Should be `timelock_balance`

File: crates/iota/src/genesis_inspector.rs [hunk 10]
```diff
@@ -213,6 +297,36 @@ fn examine_object(
                 }
                 print_divider(STR_STAKED_IOTA);
             }
+            Ok(name) if name == STR_TIMELOCKED_IOTA => {
+                for time_locked in timelocked_iota_map.values() {
```
Comment (miker83z) [inline crates/iota/src/genesis_inspector.rs]: Here too `timelocked`

File: crates/iota/src/genesis_inspector.rs [hunk 11]
```diff
@@ -7,27 +7,35 @@ use std::collections::BTreeMap;
...
+const STR_NFT_OUTPUT_IOTA: &str = "NftOutputIota";
 const STR_PACKAGE: &str = "Package";
 const STR_COIN_METADATA: &str = "CoinMetadata";
 const STR_OTHER: &str = "Other";
 const STR_IOTA_DISTRIBUTION: &str = "IOTA Distribution";
 const STR_OBJECTS: &str = "Objects";
 const STR_VALIDATORS: &str = "Validators";
 
-pub(crate) fn examine_genesis_checkpoint(genesis: UnsignedGenesis) {
+pub(crate) fn examine_genesis_checkpoint(genesis: UnsignedGenesis, migration_objects: Vec<Object>) {
```
Comment (miker83z) [inline crates/iota/src/genesis_inspector.rs:38]: `migration_objects` should be an Option, as we want to execute the command also for a genesis without migration.

**Review by miker83z — CHANGES_REQUESTED** [review]

File: crates/iota-types/src/stardust/output/nft.rs (hunk 2 above)
Comment (miker83z) [reply crates/iota-types/src/stardust/output/nft.rs]: Also check https://github.com/iotaledger/iota/pull/4829#discussion_r1922658602

File: crates/iota-genesis-builder/src/lib.rs (hunk 5 above)
Comment (miker83z) [reply crates/iota-genesis-builder/src/lib.rs]: Yes, we want to execute the command even in the case of genesis without migration. So this `unwrap()` wouldn't work for that case.

File: crates/iota-genesis-builder/src/lib.rs [hunk 12]
```diff
@@ -150,7 +150,9 @@ impl Builder {
     }
 
     pub fn tx_migration_objects(self) -> Vec<Object> {
```
Comment (DaughterOfMars) [inline crates/iota-genesis-builder/src/lib.rs]: Any reason not to return an iter?
```rust
    pub fn tx_migration_objects(self) -> impl Iterator<Item = Object> {
        self.migration_tx_data
            .map(|tx_data| tx_data.get_objects())
            .flatten()
    }
```

File: crates/iota-types/src/object.rs [hunk 13]
```diff
@@ -820,30 +819,6 @@ impl ObjectInner {
         }
     }
 
-    pub fn as_alias_output_maybe(&self) -> Option<AliasOutput> {
```
Comment (DaughterOfMars) [inline crates/iota-types/src/object.rs]: I'd kind of prefer keeping these methods but renaming them like `try_as_alias_output`, personally

Comment (miker83z) [reply crates/iota-types/src/object.rs]: It is a way to make it adhere to the way the other types are parsed from bcs in the same scope, [check here pls](https://github.com/iotaledger/iota/pull/4829#discussion_r1922658448)

**Comment by miker83z** [comment]
After executing [this](https://github.com/iotaledger/iota/pull/4829#issuecomment-2602840587), that's the outcome of the command:
```bash
Adding migration objects from Local("stardust_object_snapshot.bin")
Total number of migration objects: 4561403
Total Number of Validators: 1
Total Number of Objects/Packages: 4561422
thread '2025-01-23T18:37:39.256249Z ERROR telemetry_subscribers: panicked at crates/iota/src/genesis_inspector.rs:385:5:
assertion `left == right` failed
  left: 4601500000000000000
 right: 4600000000000000000 panic.file="crates/iota/src/genesis_inspector.rs" panic.line=385 panic.column=5
main' panicked at crates/iota/src/genesis_inspector.rs:385:5:
assertion `left == right` failed
  left: 4601500000000000000
 right: 4600000000000000000
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    60880 abort      ../iota/target/release/iota genesis-ceremony examine-genesis-checkpoint
```

File: crates/iota-types/src/object.rs (hunk 13 above)
Comment (DaughterOfMars) [reply crates/iota-types/src/object.rs]: Still, I see that there are other, similar methods still remaining here.

**Comment by miker83z** [comment]
> After executing [this](https://github.com/iotaledger/iota/pull/4829#issuecomment-2602840587), that's the outcome of the command:
> 
> ```shell
> Adding migration objects from Local("stardust_object_snapshot.bin")
> Total number of migration objects: 4561403
> Total Number of Validators: 1
> Total Number of Objects/Packages: 4561422
> thread '2025-01-23T18:37:39.256249Z ERROR telemetry_subscribers: panicked at crates/iota/src/genesis_inspector.rs:385:5:
> assertion `left == right` failed
>   left: 4601500000000000000
>  right: 4600000000000000000 panic.file="crates/iota/src/genesis_inspector.rs" panic.line=385 panic.column=5
> main' panicked at crates/iota/src/genesis_inspector.rs:385:5:
> assertion `left == right` failed
>   left: 4601500000000000000
>  right: 4600000000000000000
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> [1]    60880 abort      ../iota/target/release/iota genesis-ceremony examine-genesis-checkpoint
> ```

Found the bug, not related to this PR. I will fix it soon! -> #5024

File: crates/iota/src/genesis_inspector.rs [hunk 14]
```diff
@@ -92,8 +112,60 @@ pub(crate) fn examine_genesis_checkpoint(genesis: UnsignedGenesis) {
                     // Assert pool id is associated with a known validator.
                     let validator = validator_pool_id_map.get(&staked_iota.pool_id()).unwrap();
                     assert_eq!(validator.staking_pool.id, staked_iota.pool_id());
-
                     staked_iota_map.insert(object.id(), staked_iota);
+                } else if let Ok(timelock_balance) = TimeLock::<Balance>::try_from(object) {
```
Comment (valeriyr) [inline crates/iota/src/genesis_inspector.rs]: Although we can have only time-locked IOTAs during the Genesis, I think, it would be nice to add the locked balance type check here. It can be an assert, just in case.

**Review by valeriyr — APPROVED** [review]
LGTM!

File: crates/iota-types/src/object.rs (hunk 13 above)
Comment (miker83z) [reply crates/iota-types/src/object.rs]: Methods like `as_coin_maybe`  or `as_timelock_balance_maybe` will be possibly reused in the future because the equivalent Move types are in the iota-framework. On the other hand, the alias, nft, basic output types are only tied to stardust and probably will never be never used anymore in the codebase after the migration.

File: crates/iota-genesis-builder/src/lib.rs (hunk 12 above)
Comment (miker83z) [reply crates/iota-genesis-builder/src/lib.rs]: Done here [69d2a9e](https://github.com/iotaledger/iota/pull/4829/commits/69d2a9efe4139ef2a7ef51e8c0286131627176da)

**Review by miker83z — APPROVED** [review]

File: crates/iota/src/genesis_inspector.rs (hunk 14 above)
Comment (miker83z) [reply crates/iota/src/genesis_inspector.rs]: Done [13df074](https://github.com/iotaledger/iota/pull/4829/commits/13df0746f117c52f10215f8a791ec5fb036926ed)

File: crates/iota-genesis-builder/src/lib.rs [hunk 15]
```diff
@@ -259,8 +273,9 @@ impl Builder {
         self.built_genesis.clone()
     }
 
-    fn load_migration_sources(&mut self) -> anyhow::Result<()> {
+    pub fn load_migration_sources(&mut self) -> anyhow::Result<()> {
         for source in &self.migration_sources {
+            println!("Adding migration objects from {:?}", source);
```
Comment (thibault-martinez) [inline crates/iota-genesis-builder/src/lib.rs]: Just making sure this isn't a debug leftover

File: crates/iota-types/src/stardust/output/nft.rs [hunk 16]
```diff
@@ -469,4 +470,35 @@ impl NftOutput {
 
         Ok(move_nft_output_object)
     }
+
+    /// Create a `NftOutput` from BCS bytes.
```
Comment (Alex6323) [inline crates/iota-types/src/stardust/output/nft.rs]:
```suggestion
    /// Create an `NftOutput` from BCS bytes.
```

File: crates/iota-types/src/stardust/output/alias.rs [hunk 17]
```diff
@@ -201,4 +202,35 @@ impl AliasOutput {
...
+
+    /// Create an `AliasOutput` from BCS bytes.
+    pub fn from_bcs_bytes(content: &[u8]) -> Result<Self, IotaError> {
+        bcs::from_bytes(content).map_err(|err| IotaError::ObjectDeserialization {
+            error: format!("Unable to deserialize AliasOutput object: {:?}", err),
+        })
+    }
+
+    pub fn is_alias_output(s: &StructTag) -> bool {
+        s.address == STARDUST_PACKAGE_ID.into()
```
Comment (thibault-martinez) [inline crates/iota-types/src/stardust/output/alias.rs]: Couldn't we compare with `STARDUST_ADDRESS` instead to avoid the copy?

**Review by thibault-martinez — APPROVED** [review]

File: crates/iota/src/genesis_inspector.rs [hunk 18]
```diff
@@ -65,48 +79,114 @@ pub(crate) fn examine_genesis_checkpoint(genesis: UnsignedGenesis) {
...
+    let mut nft_output_iota_map = BTreeMap::new();
     let mut coin_metadata_map = BTreeMap::new();
     let mut other_object_map = BTreeMap::new();
 
-    for object in genesis.objects() {
+    let additional_objects = genesis.objects();
+    let tot_additional_objects = additional_objects.len();
+    let mut tot_objects = 0;
+    for object in additional_objects.iter().cloned().chain(migration_objects) {
+        tot_objects += 1;
```
Comment (Alex6323) [inline crates/iota/src/genesis_inspector.rs]: sorry for this super nit comment but this is the first screening of the PR, but I've rarely seen `tot_` as a prefix (in Germans it means 'dead', so maybe that's why it jumped into my eye in the first place. haha) . I am more used to `num_` as a prefix or flat out `total_` as it's still short enough.

File: crates/iota/src/genesis_inspector.rs [hunk 19]
```diff
@@ -213,6 +308,40 @@ fn examine_object(
                 }
                 print_divider(STR_STAKED_IOTA);
             }
+            Ok(name) if name == STR_TIMELOCKED_IOTA => {
+                for timelocked in timelocked_iota_map.values() {
+                    println!("{:#?}", timelocked);
+                }
+                print_divider(STR_TIMELOCKED_IOTA);
+            }
```
Comment (Alex6323) [inline crates/iota/src/genesis_inspector.rs:316]: I don't know whether this is something you would want to address in this PR or create an issue for it, but since you're adding a lot of match cases you might want to consider to refactor this a bit. IMHO we redundantly und unnecessarily often match on `Ok(name)` here.  Instead we could just break out of the loop immediately after line 296 by checking for an error. Afterwards we could just match on the strings { STR_EXIT, STR_IOTA, STR_TIMELOCKED_DATA, ... } directly, thereby reducing some noise of this  function.

File: crates/iota-genesis-builder/src/lib.rs [hunk 20]
```diff
@@ -149,11 +149,25 @@ impl Builder {
...
+    pub fn tx_migration_objects(&self) -> impl Iterator<Item = Object> + '_ {
+        self.migration_tx_data
+            .as_ref()
+            .map(|tx_data| tx_data.get_objects())
+            .into_iter()
+            .flatten()
+    }
+
+    /// Set the genesis delegation to be a `OneToAll` kind and indicates the
+    /// delegator address.
```
Comment (Alex6323) [inline crates/iota-genesis-builder/src/lib.rs]:
```suggestion
    /// Set the genesis delegation to be a `OneToAll` kind and indicate the
    /// delegator address.
```

Comment (Alex6323) [reply crates/iota-genesis-builder/src/lib.rs]: you chose the term "indicate", because we're not really setting a delegator address?

File: crates/iota-types/src/base_types.rs [hunk 21]
```diff
@@ -380,6 +380,33 @@ impl MoveObjectType {
...
+
+    pub fn is_nft_output(&self) -> bool {
+        match &self.0 {
+            MoveObjectType_::GasCoin | MoveObjectType_::StakedIota | MoveObjectType_::Coin(_) => {
+                false
+            }
+            MoveObjectType_::Other(s) => NftOutput::is_nft_output(s),
+        }
+    }
+
```
Comment (Alex6323) [inline crates/iota-types/src/base_types.rs:409]: Also more of a style nit: Since all method bodies are essentially the same you could factor this logic out expecting a closure and then just pass { `AliasOutput::is_alias_output`,  `NftOutput::is_nft_output`, ... } in each of the different cases. Should make the code a bit less noisy and potentially less error prone.

File: crates/iota-types/src/stardust/output/basic.rs [hunk 22]
```diff
@@ -181,6 +182,19 @@ impl BasicOutput {
...
     }
+
+    /// Create a `BasicOutput` from BCS bytes.
+    pub fn from_bcs_bytes(content: &[u8]) -> Result<Self, IotaError> {
+        bcs::from_bytes(content).map_err(|err| IotaError::ObjectDeserialization {
+            error: format!("Unable to deserialize BasicOutput object: {:?}", err),
+        })
+    }
+
+    pub fn is_basic_output(s: &StructTag) -> bool {
```
Comment (Alex6323) [inline crates/iota-types/src/stardust/output/basic.rs]:
```suggestion

    /// Whether the given `StructTag` represents a `BasicOutput`.
    pub fn is_basic_output(s: &StructTag) -> bool {
```

File: crates/iota/src/genesis_inspector.rs (hunk 18 above)
Comment (miker83z) [reply crates/iota/src/genesis_inspector.rs]: Yes, you are right!

File: crates/iota/src/genesis_inspector.rs (hunk 19 above)
Comment (miker83z) [reply crates/iota/src/genesis_inspector.rs:316]: I would create another issue for the refactoring. Merging this and then #5028 has higher priority!

File: crates/iota-types/src/stardust/output/basic.rs (hunk 22 above)
Comment (Alex6323) [reply crates/iota-types/src/stardust/output/basic.rs]: I probably would have preferred an extension trait implemented on `StructTag` to check for the different output types.

File: crates/iota-types/src/base_types.rs (hunk 21 above)
Comment (miker83z) [reply crates/iota-types/src/base_types.rs:409]: Another issue, like in https://github.com/iotaledger/iota/pull/4829#discussion_r1931988455 I would say 😄

**Review by Alex6323 — APPROVED** [review]

File: crates/iota/src/genesis_inspector.rs (hunk 19 above)
Comment (miker83z) [reply crates/iota/src/genesis_inspector.rs:316]: @Alex6323 here https://github.com/iotaledger/iota/issues/5050

File: crates/iota-types/src/base_types.rs (hunk 21 above)
Comment (miker83z) [reply crates/iota-types/src/base_types.rs:409]: @Alex6323 #5051
