### PR TITLE
fix(types,execution): Additional checks to multisig signature and package linkage

### LINKED ISSUE #8034: [types,execution] Additional checks to multisig signature and packages linkage
Hotfix from https://github.com/MystenLabs/sui/commit/79918a3f13579814e17ab3843250b2856b794d30

### PR DESCRIPTION
**Pull request by TheMrAI**
# Description of change

Add additional signature and linkage checks.

## Links to any relevant issues

fixes #8034 

- Also partially pulled in changes from https://github.com/MystenLabs/sui/pull/22362 for the used `InvalidLinkage` error, but no changes regarding `iota-rest-api` as it all will get refactored/renamed in https://github.com/MystenLabs/sui/pull/20435.
- Omitted changed touching **static-ptb** as those only get introduced in: https://github.com/MystenLabs/sui/pull/22256

## How the change has been tested

- [ ] Basic tests (linting, compilation, formatting, unit/integration tests)
- [ ] Patch-specific tests (correctness, functionality coverage)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### Release Notes

- [x] Protocol: Adds a new protocol config options to enable additional signature and linkage checks.
- [ ] Nodes (Validators and Full nodes):
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [ ] CLI:
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: crates/iota-types/src/unit_tests/zk_login_authenticator_test.rs [hunk 1]
```diff
@@ -111,7 +111,7 @@ fn test_zklogin_sign_personal_message() {
 
     // Construct the required info to verify a zk login authenticator, jwks,
     // supported providers list and env (prod/test).
-    let aux_verify_data = VerifyParams::new(parsed, ZkLoginEnv::Test, true, true, Some(30));
+    let aux_verify_data = VerifyParams::new(parsed, ZkLoginEnv::Test, true, true, Some(30), true);
```
Comment (miker83z) [inline crates/iota-types/src/unit_tests/zk_login_authenticator_test.rs:114]: Even though the code is commented, could you add the `true` value to the equivalent function call in `crates/iota/src/keytool.rs`?

File: crates/iota-types/src/move_package.rs [hunk 2]
```diff
@@ -631,19 +632,37 @@ fn build_linkage_table<'p>(
...
+            let existing = linkage_table.insert(
+                original_id,
+                UpgradeInfo {
+                    upgraded_id: transitive_dep.id,
+                    upgraded_version: transitive_dep.version,
+                },
+            );
+
+            if existing.is_some() {
+                // TODO: need to pull: https://github.com/MystenLabs/sui/pull/22362/files
```
Comment (miker83z) [inline crates/iota-types/src/move_package.rs]: Could you create a GH issue and replace this link with the link of that issue?

**Review by miker83z — APPROVED** [review]

File: crates/iota-types/src/iota_sdk_types_conversions.rs [hunk 3]
```diff
@@ -1243,6 +1243,7 @@ impl From<crate::execution_status::ExecutionFailureStatus> for ExecutionError {
                 congested_objects: congested_objects.0.into_iter().map(Into::into).collect(),
                 suggested_gas_price,
             },
+            ExecutionFailureStatus::InvalidLinkage => todo!(),
```
Comment (TheMrAI) [inline crates/iota-types/src/iota_sdk_types_conversions.rs]: Here

File: crates/iota-types/src/unit_tests/zk_login_authenticator_test.rs (hunk 1 above)
Comment (TheMrAI) [reply crates/iota-types/src/unit_tests/zk_login_authenticator_test.rs:114]: Skipped it as that code already doesn't contain some changes that are in place elsewhere.
`VerifyParams::new(parsed, vec![], env, true, true, Some(2), true)`
For example that second vec![] is no longer in place and I don't know what else.
Added it none the less.

File: crates/iota-types/src/move_package.rs (hunk 2 above)
Comment (TheMrAI) [reply crates/iota-types/src/move_package.rs]: Added it instead in the `crates/iota-types/src/iota_sdk_types_conversions.rs`, that is closer to the point I couldn't resolve.

File: crates/iota-types/src/execution_status.rs [hunk 4]
```diff
@@ -220,6 +220,10 @@ pub enum ExecutionFailureStatus {
         congested_objects: CongestedObjects,
         suggested_gas_price: u64,
     },
+
+    // TODO: pull https://github.com/MystenLabs/sui/pull/22362/files
```
Comment (TheMrAI) [inline crates/iota-types/src/execution_status.rs]: Will remove this too after CI passed.

**Review by valeriyr — APPROVED** [review]

File: crates/iota-types/src/iota_sdk_types_conversions.rs [hunk 5]
```diff
@@ -1243,6 +1243,7 @@ impl From<crate::execution_status::ExecutionFailureStatus> for ExecutionError {
                 congested_objects: congested_objects.0.into_iter().map(Into::into).collect(),
                 suggested_gas_price,
             },
+            ExecutionFailureStatus::InvalidLinkage => todo!(), /* TODO: https://github.com/iotaledger/iota-rust-sdk/issues/65, */
```
Comment (alexsporn) [inline crates/iota-types/src/iota_sdk_types_conversions.rs]: lgtm but not sure about having a `todo!()` in here

Comment (TheMrAI) [reply crates/iota-types/src/iota_sdk_types_conversions.rs]: Yes, I don't like it either, but had no better idea for now.
It depends on changes for `iota-sdk`, have a ticket for pulling those: https://github.com/iotaledger/iota-rust-sdk/issues/65 .
I think the impact is limited to when the users would get this error while using the `iota-sdk`, but am not sure.

Comment (TheMrAI) [reply crates/iota-types/src/iota_sdk_types_conversions.rs]: Fixed in: dc11ae6366ca77b40c3302ba947da4e14edd16c9

**Review by alexsporn — APPROVED** [review]

**Review by Thoralf-M — APPROVED** [review]

**Review by roman1e2f5p8s — APPROVED** [review]

**Review by piotrm50 — APPROVED** [review]

**Review by kodemartin — APPROVED** [review]
