### PR TITLE
feat(explorer): update validator data based on on/off fixed gas price feature flag

### LINKED ISSUE #5623: Update apps after fixed gas price protocol changes
A new protocol upgrade introduced a change so that the gas price is fixed and not proposed by validators before the next epoch. This change comes with multiple things we should update in our apps and sdks

- Add temporary feature flag to be able to enable/disable `FixedGasPrice` feature in each network for the below changes to apply or not
- Remove proposed next epoch gas price from list of validators in epoch page and validators list page Image
- Remove `Estimated Next Epoch Reference Gas Price` from epoch page Image
- Remove `proposed next epoch gas price` from validator page Image

Depends on https://github.com/iotaledger/iota/issues/3536

### PR DESCRIPTION
**Pull request by msarcev**
Closes https://github.com/iotaledger/iota/issues/5623

### CODE REVIEW

**Review by panteleymonchuk — APPROVED** [review]
LGTM 🚀

File: apps/apps-backend/src/features/features.controller.ts [hunk 1]
```diff
@@ -80,6 +80,9 @@ export class FeaturesController {
                         [Network.Custom]: false,
                     },
                 },
+                [Feature.FixedGasPrice]: {
```
Comment (begonaalvarezd) [inline apps/apps-backend/src/features/features.controller.ts:83]: we have to make this feature just like `FiatConversion` to be able to enable it on certain networks only, devnet only will come first probably. Also, the feature must be disabled for all networks for now until devnet is upgraded to protocol v5

File: apps/apps-backend/src/features/features.controller.ts [hunk 2]
```diff
@@ -158,6 +161,9 @@ export class FeaturesController {
...
```
Comment (begonaalvarezd) [inline apps/apps-backend/src/features/features.controller.ts:170]: same comment as above

File: apps/explorer/src/pages/validators/Validators.tsx [hunk 3]
```diff
@@ -128,21 +131,26 @@ function ValidatorPageResult(): JSX.Element {
...
+            'Last Epoch Rewards',
+            'Voting Power',
+            'Status',
+        ];
+
+        if (!isFixedGasPrice) {
+            includeColumns.push('Proposed next Epoch gas price');
+        }
+
         return generateValidatorsTableColumns({
```
Comment (begonaalvarezd) [inline apps/explorer/src/pages/validators/Validators.tsx:151]: wdyt about the code inside this function in https://github.com/iotaledger/iota/blob/1be7d547a139911f281df828a70fcea595906147/apps/explorer/src/lib/ui/utils/generateValidatorsTableColumns.tsx#L148-L149 ? Should we try to clean it up also so when we remove the feature we leave no debris behind?

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
Almost there, just a minor issue, the available balance changes in the dashboard when entering an amount

[IOTA-Wallet-Dashboard.webm](https://github.com/user-attachments/assets/df16fa8d-df83-45ce-a3aa-a018874bbd52)

File: apps/apps-backend/src/features/features.controller.ts (hunk 1 above)
Comment (msarcev) [reply apps/apps-backend/src/features/features.controller.ts:83]: Done in [4658bb3](https://github.com/iotaledger/iota/pull/5847/commits/4658bb3d175361675ee6842f4b1705c360a506ea)

File: apps/apps-backend/src/features/features.controller.ts (hunk 2 above)
Comment (msarcev) [reply apps/apps-backend/src/features/features.controller.ts:170]: Done in [4658bb3](https://github.com/iotaledger/iota/pull/5847/commits/4658bb3d175361675ee6842f4b1705c360a506ea)

File: apps/explorer/src/pages/validators/Validators.tsx (hunk 3 above)
Comment (msarcev) [reply apps/explorer/src/pages/validators/Validators.tsx:151]: Removal task was updated with a reminder https://github.com/iotaledger/iota/issues/5882

**Review by begonaalvarezd — APPROVED** [review]
