### PR TITLE
fix(gas-price-feedback): adapt gas price feedback mechanism to overshoot, use separate for randomness

### LINKED ISSUE #9575: [Task (core-protocol-research)]: Integrate congestion limit overshoot and object debts into `SuggestedGasPriceCalculator`
## Description

We would like to take into account congestion limit overshoot and object debts in the `SuggestedGasPriceCalculator` component.

## Motivation

The shared object congestion tracker was recently updated with the congestion limit overshoot feature (a.k.a. Sui's "overage"), see https://github.com/iotaledger/iota/pull/8883. Enabling the overshoot allows scheduling more than `max_accumulated_txn_cost_per_object_in_mysticeti_commit` transactions for execution per commit. The suggested gas price calculator, however, has not yet been updated to take into account congestion limit overshoot and object debts, which leads to inflated suggested gas prices in the gas price feedback mechanism.

## Requirements

1. A new protocol config feature flag, since this feature will change feedback suggested gas prices (which are included in the execution status of cancelled transactions).
2. Access to object debts to initialize `SuggestedGasPriceCalculator`.
3. Better alignment with `SharedObjectCongestionTracker`: new data types for `SharedObjectCongestionTracker` outputs to use directly as inputs for `SuggestedGasPriceCalculator`.

## Are you planning to do it yourself in a pull request?

Yes.

### PR DESCRIPTION
**Pull request by roman1e2f5p8s**
# Description of change

This PR fixes the gas price feedback mechanism to account for congestion limit overshoot after it was enabled in the shared-object congestion tracker. Additionally, the PR adds a separate gas price feedback mechanism for transactions using randomness.

Summary of changes:

- Added new feature flags `congestion_limit_overshoot_in_gas_price_feedback_mechanism` and `separate_gas_price_feedback_mechanism_for_randomness` and enabled them on `devnet`.
- Added a struct called `CongestionControlParameters` to keep in one place all parameters related to congestion control and the gas price feedback mechanism. It is intended to be created only in `authority_per_epoch_store.rs` to initialize `SharedObjectCongestionTracker` and `SuggestedGasPriceCalculator` with the same set of parameters, both of which were refactored to utilize the new `CongestionControlParameters`.
- Added `BumpObjectExecutionSlotsResult` to store a result of `SharedObjectCongestionTracker::bump_object_execution_slots` for a single scheduled transaction. The result is then intended to be used in `SuggestedGasPriceCalculator` to update the state of `SuggestedGasPriceCalculator`.
- Improved and added new gas price feedback tests:
  - The very long test `calculate_suggested_gas_price` is split into `calculate_suggested_gas_price_in_tx_count_mode_without_overshoot` and `calculate_suggested_gas_price_in_gas_budget_mode_without_overshoot`.
  - Added new tests `calculate_suggested_gas_price_in_tx_count_mode_with_overshoot` and `calculate_suggested_gas_price_in_gas_budget_mode_with_overshoot` to actually test the new feature.
  - Added new tests `calculate_suggested_gas_price_for_unschedulable_transaction_without_overshoot` and `calculate_suggested_gas_price_for_unschedulable_transaction_with_overshoot` to test that the reference gas price should be suggested if a transaction cannot be scheduled in an "empty" tracker because the transaction's estimated execution duration exceeds the congestion limit.

Other minor changes:

- Moved the `get_estimated_execution_duration` method from `SharedObjectCongestionTracker` to `CongestionControlParameters`.
- Improved docstrings for various types and functions in `SharedObjectCongestionTracker` and `SuggestedGasPriceCalculator`.
- Removed unnecessary `pub` visibility for various types and functions in `SharedObjectCongestionTracker` and `SuggestedGasPriceCalculator`.

## Links to any relevant issues

Closes #9575.

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [x] Patch-specific tests (correctness, functionality coverage)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### Release Notes

- [x] Protocol: Adapt gas price feedback to the congestion limit [overshoot feature](https://github.com/iotaledger/iota/pull/8883) and enable it on `devnet`. Add a separate gas price feedback mechanism for transactions using randomness and enable it on `devnet`.
- [ ] Nodes (Validators and Full nodes):
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [ ] CLI:
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: crates/iota-core/src/authority/suggested_gas_price_calculator.rs [hunk 1]
```diff
@@ -70,133 +70,146 @@ type PerCommitCongestionInfo = HashMap<ObjectID, PerObjectCongestionInfo>;
...
+            // price.
 
             self.reference_gas_price
         }
     }
 
+    /// Get congestion limit per commit using `CongestionControlParameters`
+    /// of the calculator. Returns `None` if shared-object congestion control
+    /// is disabled.
+    fn get_congestion_limit_per_commit(&self) -> Option<ExecutionTime> {
```
Comment (bingyanglin) [inline crates/iota-core/src/authority/suggested_gas_price_calculator.rs]: The logic is correct, but the method name could be more explicit about what "limit" means in each context. Might use `get_effective_congestion_limit_for_gas_price_feedback` or something, to clarify it may include overshoot?

File: crates/iota-core/src/authority/suggested_gas_price_calculator.rs [hunk 2]
```diff
@@ -346,52 +350,132 @@ mod tests {
...
 
-    #[derive(Copy, Clone)]
-    struct TxGasData {
-        global_ordering_index: usize,
+    /// Helper data structure to store transaction data used for sequencing.
+    #[derive(Debug)]
+    struct TransactionData {
+        /// Index of transaction in the set ordered by gas price in
+        /// descending order. Used for debugging purposes.
+        #[allow(dead_code)]
```
Comment (bingyanglin) [inline crates/iota-core/src/authority/suggested_gas_price_calculator.rs]: This is still used for debugging? Instead of mark it as `#[allow(dead_code)]`, maybe either removing it entirely or using it in debug output to make the tests more informative?

File: crates/iota-core/src/authority/suggested_gas_price_calculator.rs (hunk 1 above)
Comment (roman1e2f5p8s) [reply crates/iota-core/src/authority/suggested_gas_price_calculator.rs]: Makes sense! Renamed to `get_effective_congestion_limit_per_commit` in https://github.com/iotaledger/iota/pull/9705/changes/4065e317680ce2207f28dfda225338de93d48160.

File: crates/iota-core/src/authority/suggested_gas_price_calculator.rs (hunk 2 above)
Comment (roman1e2f5p8s) [reply crates/iota-core/src/authority/suggested_gas_price_calculator.rs]: Yes, it is only used in panic messages in the tests. I removed `#[allow(dead_code)]` and made use of `order_idx` in https://github.com/iotaledger/iota/pull/9705/changes/90558ca3799066b66d11bf1b58d99888689af3d4.

**Review by bingyanglin — APPROVED** [review]

File: crates/iota-core/src/authority/shared_object_congestion_tracker.rs [hunk 3]
```diff
@@ -297,12 +300,16 @@ impl SharedObjectCongestionTracker {
...
         &self,
         shared_input_objects: &[SharedInputObject],
         tx_duration: ExecutionTime,
     ) -> Option<ExecutionTime> {
-        if self.assign_min_free_execution_slot {
+        let assign_min_free_execution_slot = self
+            .congestion_control_parameters
+            .congestion_control_min_free_execution_slot();
+
+        if assign_min_free_execution_slot {
```
Comment (cyberphysic4l) [inline crates/iota-core/src/authority/shared_object_congestion_tracker.rs]:
```suggestion
        if self.congestion_control_parameters
            .congestion_control_min_free_execution_slot() {
```

File: crates/iota-core/src/authority/shared_object_congestion_tracker.rs [hunk 4]
```diff
@@ -297,12 +300,16 @@ impl SharedObjectCongestionTracker {
...
             // If `assign_min_free_execution_slot` is true, we assign the transaction start
```
Comment (cyberphysic4l) [inline crates/iota-core/src/authority/shared_object_congestion_tracker.rs]:
```suggestion
            // If `congestion_control_min_free_execution_slot` is true, we assign the transaction start
```

Comment (cyberphysic4l) [reply crates/iota-core/src/authority/shared_object_congestion_tracker.rs]: Same for below comment

**Review by thibault-martinez — APPROVED** [review]
Approving `crates/iota-open-rpc/spec/openrpc.json`

File: crates/iota-core/src/authority/shared_object_congestion_tracker.rs [hunk 5]
```diff
@@ -557,22 +545,97 @@ impl SharedObjectCongestionTracker {
...
+    pub(super) fn estimated_execution_duration(&self) -> ExecutionTime {
+        self.estimated_execution_duration
+    }
+
+    /// Get gas price of the scheduled shared-object transaction.
+    pub(super) fn gas_price(&self) -> u64 {
+        self.gas_price
+    }
+
+    /// Crate a new `BumpObjectExecutionSlotsResult` for test.
```
Comment (cyberphysic4l) [inline crates/iota-core/src/authority/shared_object_congestion_tracker.rs]:
```suggestion
    /// Create a new `BumpObjectExecutionSlotsResult` for test.
```

**Review by cyberphysic4l — APPROVED** [review]

**Review by piotrm50 — APPROVED** [review]
