### PR TITLE
fix(iota-move-build): remove duplicate function

### LINKED ISSUE #6232: [iota-move-build] Remove duplicate function · MystenLabs/sui@9fa11ac
minor | fix

https://github.com/MystenLabs/sui/commit/9fa11acb9780ddf2be637041b2615db163287dd8

### PR DESCRIPTION
**Pull request by nonast**
[run-ci]
# Description of change

Removes a duplicate function and replaces its uses by the other identical function.

## Links to any relevant issues

fixes #6232 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota-move-build/src/lib.rs [hunk 1]
```diff
@@ -599,10 +599,6 @@ impl CompiledPackage {
             error: error_message.join("\n"),
         })
     }
-
-    pub fn published_dependency_ids(&self) -> Vec<ObjectID> {
-        self.dependency_ids.published.values().cloned().collect()
```
Comment (DaughterOfMars) [inline crates/iota-move-build/src/lib.rs:604]: While we're here... `ObjectID` is `Copy`, so these values (in the other method) can be `.copied()`. Also, it would be much better to return `impl Iterator<Item = ObjectID>` and allow the caller to decide how to use that.

**Review by muXxer — APPROVED** [review]

**Review by piotrm50 — APPROVED** [review]

**Review by jkrvivian — APPROVED** [review]

File: crates/iota-move-build/src/lib.rs (hunk 1 above)
Comment (nonast) [reply crates/iota-move-build/src/lib.rs:604]: Very nice, I changed cloned to copied. For the second part, I left it as return Vec due to all the usages of this function..
