### PR TITLE
fix(CI): if no tests in changed crates, make tests pass

### LINKED ISSUE #5196: nextest error: no tests to run
https://github.com/iotaledger/iota/actions/runs/13133006891/job/36642558752

### PR DESCRIPTION
**Pull request by nmrshll**
# Description of change

Recently a `cargo nextest` warning became an error: when no tests are found in changed crates in CI tests.
This fixes it

Fixes #5196:
- pass flag --no-tests=warn to cargo nextest
- tests will now pass if changed_crates contain no tests, with a warning still (all crates should likely be tested)

# Checklist
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] Wait for #5035 to be merged (there were conflicts)

### CODE REVIEW

**Comment by thibault-martinez** [comment]
#5035 has been merged :)

File: scripts/ci_tests/rust_tests.sh [hunk 1]
```diff
@@ -143,17 +143,17 @@ function rust_crates() {
...
     eval ${command}
 }
 
 function external_crates() {
     # WARNING: this has  a side effect of updating the Cargo.lock file
     FILTERSET="$(mk_test_filterset) -E '!test(prove) and !test(run_all::simple_build_with_docs/args.txt) and !test(run_test::nested_deps_bad_parent/Move.toml)"
-    command="cargo nextest run --config-file .config/nextest.toml --profile ci --manifest-path external-crates/move/Cargo.toml $FILTERSET"
+    command="cargo nextest run --config-file .config/nextest.toml --profile ci --manifest-path external-crates/move/Cargo.toml $FILTERSET --no-tests=warn"
     echo "Running: $command"
-    cargo nextest run --config-file .config/nextest.toml --profile ci --manifest-path external-crates/move/Cargo.toml $FILTERSET
```
Comment (thibault-martinez) [inline scripts/ci_tests/rust_tests.sh:156]: We were running it twice ?

File: .config/nextest.toml [hunk 2]
```diff
@@ -60,6 +60,7 @@ or test(test_stake_all)
 or test(test_fullnode_traffic_control_spam_delegated)
 or test(ensure_no_tombstone_fragmentation_in_stack_frame_after_flush)
 or test(ip6)
+or test(test_profiler)
```
Comment (thibault-martinez) [inline .config/nextest.toml]: It's not really flaky, it's just broken

File: scripts/ci_tests/rust_tests.sh (hunk 1 above)
Comment (thibault-martinez) [reply scripts/ci_tests/rust_tests.sh:156]: Ah no, once but creating the command for nothing

**Review by thibault-martinez — APPROVED** [review]

File: .config/nextest.toml (hunk 2 above)
Comment (thibault-martinez) [reply .config/nextest.toml]: It's being fixed here https://github.com/iotaledger/iota/pull/5287

Comment (muXxer) [reply .config/nextest.toml]: Yeah please revert 😅

Comment (nmrshll) [reply .config/nextest.toml]: yes saw that, I've reverted it now 👍

**Review by DaughterOfMars — APPROVED** [review]
