### PR TITLE
fix(iota-data-ingestion-core): add timeout to historical reader

### LINKED ISSUE #8072: fix(iota-data-ingestion-core): no timeout on HisotricalReader read operations in CheckpointReader v2
## Description

Fix the `CheckpointReader` using the `HisotricalReader` to have a timeout on read operation for files gathered form S3 since the object store client `HisotricalReader` relies on does not have timeouts.

### PR DESCRIPTION
**Pull request by sergiupopescu199**
# Description of change

This PR fixes a corner case where the GET requests from the `HisotricalReader` to the `S3 ObjectStore` could hang for around 2 hours. This was because the `ObjectStore client` the `HisotricalReader` relies does disable all timeouts (this change was inherited from upstream). 

The fix applies a `tokio::time::timeout`, the duration can be configured as it reads the `ReaderOptions.timeout_secs` field.

## Links to any relevant issues

fixes #8072 

## How the change has been tested

- Ran a custom indexer and manitored it's logs for some hours to assert the fix works. in this amount of time it happened 2 times, once the timeout was reached, it exited the loop and once entered again it was able to successfully fetched the requested file.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [ ] Patch-specific tests (correctness, functionality coverage)

### Infrastructure QA (only required for crates that are maintained by @iotaledger/infrastructure)

> [!NOTE]
> The indexer does not use the `CheckpointReader V2` so this path does not affect the normal operation of the indexer. QA tests were skipped.

### Release Notes

- [ ] Protocol:
- [ ] Nodes (Validators and Full nodes):
- [x] Indexer: the `iota-data-ingestion-core` `CheckpointReader` applies the `ReaderOptions.timeout_secs` also for historical checkpoint reads, previously only live checkpoint reads were respecting the provided timeout value.
- [ ] JSON-RPC:
- [ ] GraphQL:
- [ ] CLI:
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

**Review by samuel-rufi — APPROVED** [review]
Awesome @sergiupopescu199 , looks good to me!

**Review by tomxey — APPROVED** [review]
lgtm

File: crates/iota-data-ingestion-core/src/reader/v2.rs [hunk 1]
```diff
@@ -117,7 +117,6 @@ impl RemoteStore {
                 };
                 let historical = HistoricalReader::new(config)
                     .inspect_err(|e| error!("Unable to instantiate historical reader: {e}"))?;
-                historical.sync_manifest_once().await?;
```
Comment (Thoralf-M) [inline crates/iota-data-ingestion-core/src/reader/v2.rs:120]: This is also not needed with timeout?

Comment (sergiupopescu199) [reply crates/iota-data-ingestion-core/src/reader/v2.rs:120]: I removed it because when spawning the `HisotricalReader` internally it fetches the Manifest in a `tokio` task.

**Review by Thoralf-M — APPROVED** [review]
