### PR TITLE
Fix graceful shutdown for Workers stuck in backoff retry loop 

### LINKED ISSUE #5291: [`iota-data-ingestion-core`]: Fix graceful shutdown
## Description

Currently if the `process_checkpoint` in the `Worker` trait return an error the `WorkerPool` will not be able to to shutdown since it requires all worker to shutdown. 

This is because if the `process_checkpoint` is executed inside an exponential backoff which does not have any limits, so the  the error will always occur and the worker will not be able to exit the loop making it unable to send the `WorkerStatus::Shutdown` message to the WorkerPool upon token cancellation.

To handle graceful shutdown, we can integrate cancellation checks within the backoff loop of the `process_checkpoint` method when it returns an Error. If the CancellationToken is canceled while processing a checkpoint is failing constantly, the [backoff](https://github.com/iotaledger/iota/blob/develop/crates/iota-data-ingestion-core/src/worker_pool.rs#L199-L211) strategy should be interrupted. Upon cancellation, the worker can send a `WorkerStatus::Shutdown` message to the pool and exit the processing loop.

### PR DESCRIPTION
**Pull request by sergiupopescu199**
# Description of change

This PR fixes a corner case in the Worker's checkpoint processing retry mechanism. Previously, when a Worker failed to process a checkpoint, the backoff retry mechanism would continue until either:
1. The checkpoint was successfully processed
2. The backoff's maximum elapsed time was reached (causing a panic)

This made impossible to trigger the graceful shutdown using CRTL+C, as one or more workers were stuck in the backoff retry loop.

## Links to any relevant issues

fixes #5291 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

- Ran the test cases
```shell
cargo test -p iota-data-ingestion-core
```
- Ran the `iota-data-ingestion` binary, modified the worker to always fails to process a checkpoint and tested the checkpoint sync with a local network, inspecting the logs it was never able to sync a single checkpoint, upon pressing the CRTL+C the program was able to exit gracefully.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: crates/iota-data-ingestion-core/src/tests.rs [hunk 1]
```diff
@@ -90,6 +90,24 @@ impl Worker for TestWorker {
     }
 }
 
+/// This worker implementation always returns an error when processing a
+/// checkpoint.
+///
+/// Useful for testing graceful shutdown logic and behaviours
+#[derive(Clone)]
+struct TestWorkerFaulty;
```
Comment (samuel-rufi) [inline crates/iota-data-ingestion-core/src/tests.rs]: Maybe we can just rename this to `FaultyWorker`. It's already under the `test` scope so that would be fine.

Comment (sergiupopescu199) [reply crates/iota-data-ingestion-core/src/tests.rs]: @samuel-rufi [fixed](https://github.com/iotaledger/iota/pull/5496/commits/43731e15728a3f79b505e823ec06f4c19af75194)

File: crates/iota-data-ingestion-core/src/worker_pool.rs [hunk 2]
```diff
@@ -195,23 +212,48 @@ impl<W: Worker + 'static> WorkerPool<W> {
                             info!("received checkpoint for processing {} for workflow {}", sequence_number, task_name);
                             let start_time = Instant::now();
                             let backoff = backoff::ExponentialBackoff::default();
-                            backoff::future::retry(backoff, || async {
-                                worker
-                                    .clone()
+                            let result = backoff::future::retry(backoff, || async {
```
Comment (kodemartin) [inline crates/iota-data-ingestion-core/src/worker_pool.rs]: `status` seems more appropriate as we `expect` at the end.
```suggestion
                            let status = backoff::future::retry(backoff, || async {
```

File: crates/iota-data-ingestion-core/src/worker_pool.rs [hunk 3]
```diff
@@ -195,23 +212,48 @@ impl<W: Worker + 'static> WorkerPool<W> {
...
-                                        info!("transient worker execution error {:?} for checkpoint {}", err, sequence_number);
+                                        info!("transient worker execution error {err:?} for checkpoint {sequence_number}");
                                         backoff::Error::transient(err)
-                                    })
+                                    }).map(BackoffStatus::ProcessedCheckpoint);
+
+                                if processed_checkpoint_result.is_err() & token.is_cancelled() {
+                                    return Ok(BackoffStatus::Shutdown)
+                                }
+                                processed_checkpoint_result
```
Comment (kodemartin) [inline crates/iota-data-ingestion-core/src/worker_pool.rs]: Couldn't we just use `WorkerStatus` instead here?

Comment (sergiupopescu199) [reply crates/iota-data-ingestion-core/src/worker_pool.rs]: That's a good observation, thank you. [Fixed](https://github.com/iotaledger/iota/pull/5496/commits/cf1ee82d3a6a4b38c5ab154824dd67d9df68ce7d)

File: crates/iota-data-ingestion-core/src/worker_pool.rs [hunk 4]
```diff
@@ -195,22 +195,37 @@ impl<W: Worker + 'static> WorkerPool<W> {
...
+                                    .send(WorkerStatus::Shutdown(worker_id))
+                                    .await;
+                                break;
+                            }
+
+                            info!(
+                                "finished checkpoint processing {sequence_number} for workflow {task_name} in {:?}",
+                                start_time.elapsed()
+                            );
+                            if cloned_progress_sender.send(status).await.is_err() {
```
Comment (kodemartin) [inline crates/iota-data-ingestion-core/src/worker_pool.rs]: Nit: You can further simplify to
```suggestion
                            let trigger_shutdown = matches!(status, WorkerStatus::Shutdown(_));
                            if cloned_progress_sender.send(status).await.is_err() || trigger_shutdown {
                                break;
                            }
                            info!(
                                "finished checkpoint processing {sequence_number} for workflow {task_name} in {:?}",
                                start_time.elapsed()
                            );

```

**Review by kodemartin — APPROVED** [review]
lgtm

File: crates/iota-data-ingestion-core/src/worker_pool.rs [hunk 5]
```diff
@@ -195,22 +195,34 @@ impl<W: Worker + 'static> WorkerPool<W> {
...
                                     .process_checkpoint(&checkpoint)
                                     .await
                                     .map_err(|err| {
                                         let err = IngestionError::CheckpointProcessing(err.to_string());
-                                        info!("transient worker execution error {:?} for checkpoint {}", err, sequence_number);
+                                        info!("transient worker execution error {err:?} for checkpoint {sequence_number}");
                                         backoff::Error::transient(err)
-                                    })
+                                    });
+                                if processed_checkpoint_result.is_err() & token.is_cancelled() {
```
Comment (kodemartin) [inline crates/iota-data-ingestion-core/src/worker_pool.rs]: Oops, missed that.
```suggestion
                                if processed_checkpoint_result.is_err() && token.is_cancelled() {
```

**Review by samuel-rufi — APPROVED** [review]
