### PR TITLE
fix(iota-data-ingestion-core): refine clients initialization

### LINKED ISSUE #10962: [iota-data-ingestion-core]: remove gRPC connection backoff
This [commit](https://github.com/iotaledger/iota/pull/10754/changes/8555036d3057860604801ec1b5034552001b347e) was added  by the node team to fix the flaky tests encountered, with the iota indexer.

The `get_health` call during gRPC client initialization in `iota-data-ingestion-core` causes flaky indexer tests, if the gRPC server isn't ready yet, the health check fails and the client falls back to REST (which no longer exists after the REST removal). 

The fix is to remove the `get_health` call entirely. Errors are already caught during checkpoint download, which has built-in backoff and retry. This matches the behavior of the hybrid (V1) & historical (V2) client path in CheckpointReader, which doesn't perform a health check on initialization.

### PR DESCRIPTION
**Pull request by sergiupopescu199**
# Description of change

This PR removes the `get_health` check when instantiating a gRPC fullnode client, previously it was needed to choose between a gRPC or a REST API fullnode connection. With the removal of the fullnode REST API this check is no longer needed.

## Links to any relevant issues

fixes #10962

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [ ] Patch-specific tests (correctness, functionality coverage)

- Ran the indexer using alphanet checkpoints and made sure that the CheckpointReaderV2 was working as expected
- Ran all indexer tests
```shell
cargo test -p iota-indexer --profile simulator --features shared_test_runtime
cargo nextest run -p iota-indexer --features pg_integration --test-threads 1
```

### Infrastructure QA (only required for crates that are maintained by @iotaledger/infrastructure)

- [x] Synchronization of the indexer from genesis for a network including migration objects.
- [x] Restart of indexer synchronization locally without resetting the database.
- [ ] Restart of indexer synchronization on a production-like database.
- [ ] Deployment of services using Docker.
- [ ] Verification of API backward compatibility.

### Release Notes

- [x] Indexer:  From version `v1.21.0`, the `CheckpointReaderV1` in `iota-data-ingestion-core` will be deprecated. ⚠️⚠️⚠️ Operators maintaining custom indexers are advised to migrate to `CheckpointReaderV2` via [`IndexerExecutor::run_with_config`](https://iotaledger.github.io/iota/iota_data_ingestion_core/struct.IndexerExecutor.html#method.run_with_config). With pruning enabled on fullnodes, custom indexers will need `CheckpointReaderV2` to use hybrid historical storage for syncing from genesis, making `CheckpointReaderV1` obsolete. ⚠️⚠️⚠️

### CODE REVIEW

**Review by kodemartin — APPROVED** [review]
lgtm

File: crates/iota-data-ingestion-core/src/reader/v1.rs [hunk 1]
```diff
@@ -174,67 +168,25 @@ impl CheckpointReader {
...
-                            "failed to connect to gRPC fullnode after retries, falling back to object store: {err:?}"
-                        );
-                        let object_store =
-                            create_remote_store_client(url, remote_store_options, timeout_secs)
-                                .expect("failed to create remote store client");
-                        RemoteStore::ObjectStore(object_store)
-                    }
-                }
-            };
+        let (fullnode_url, object_store_url) = url.split_once('|').unwrap_or((&url, &url));
```
Comment (bingyanglin) [inline crates/iota-data-ingestion-core/src/reader/v1.rs:171]: When a single URL is passed (no `|`), `unwrap_or((&url, &url))` uses the same URL for both gRPC and object store. The object store client pointed at a gRPC endpoint will never fetch anything. Maybe skip creating the object store client for single-URL case, since it's always gRPC now? Or do I miss anything?

File: crates/iota-data-ingestion-core/src/reader/v1.rs [hunk 2]
```diff
@@ -174,67 +168,25 @@ impl CheckpointReader {
...
+            timeout_secs,
+        )
+        .expect("failed to create remote store client");
+
+        let grpc_client = GrpcClient::connect(fullnode_url)
+            .await
+            .map(|client| {
+                client.with_max_decoding_message_size(GRPC_MAX_DECODING_MESSAGE_SIZE_BYTES)
+            })
+            .expect("failed to connect to gRPC fullnode");
```
Comment (bingyanglin) [inline crates/iota-data-ingestion-core/src/reader/v1.rs:185]: I am just confused for v2 we use `?` to `propagate` the error but here we panic, any reason? Or we could make it consistent?

File: crates/iota-data-ingestion-core/src/reader/v1.rs [hunk 3]
```diff
@@ -174,67 +168,25 @@ impl CheckpointReader {
...
+        let (fullnode_url, object_store_url) = url.split_once('|').unwrap_or((&url, &url));
 
+        let object_store = create_remote_store_client(
+            object_store_url.to_string(),
+            remote_store_options,
+            timeout_secs,
+        )
+        .expect("failed to create remote store client");
+
+        let grpc_client = GrpcClient::connect(fullnode_url)
```
Comment (bingyanglin) [inline crates/iota-data-ingestion-core/src/reader/v1.rs:180]: The old retry loop with `get_health()` logged `"not ready, retrying..."` so operators knew the fullnode wasn't up yet. Now those failures only show up as checkpoint fetch errors, is it descriptive?

File: crates/iota-data-ingestion-core/src/reader/v1.rs (hunk 1 above)
Comment (sergiupopescu199) [reply crates/iota-data-ingestion-core/src/reader/v1.rs:171]: Good point. The approach is intentional when a single URL is provided, the object store client is created but the gRPC path is attempted first. If the URL is a gRPC endpoint, gRPC succeeds and the object store client is never used. If the URL is an object store endpoint, the gRPC call fails and it falls back to the object store, which then succeeds. So both URL types work correctly without the `|` separator. That said, V1 is being deprecated in `v1.21.0` in favor of V2, so further optimization here isn't warranted.

- https://github.com/iotaledger/iota/issues/10967

File: crates/iota-data-ingestion-core/src/reader/v1.rs (hunk 3 above)
Comment (sergiupopescu199) [reply crates/iota-data-ingestion-core/src/reader/v1.rs:180]: Yes, the errors are descriptive when the gRPC stream fails to fetch a checkpoint, the worker pool logs a `transient worker execution error` with the full gRPC status and error message. The retry is handled automatically by the worker pool's backoff mechanism.

File: crates/iota-data-ingestion-core/src/reader/v1.rs (hunk 2 above)
Comment (sergiupopescu199) [reply crates/iota-data-ingestion-core/src/reader/v1.rs:185]: V1 is legacy code inherited from Sui — the `expect` pattern was already there before this change. V2 uses `?` propagation which is the correct approach. Since V1 is being deprecated in `v1.21.0`, aligning the error handling isn't worth the churn.

**Review by bingyanglin — APPROVED** [review]

**Review by tomxey — APPROVED** [review]
