### PR TITLE
fix(ts-sdk): Update typography light theme line height

### LINKED ISSUE #4590: Sync Typography styling in both dark and light `dapp-kit` themes
The light should probably be the same as the dark one, as the dark was newer

### PR DESCRIPTION
**Pull request by marc2332**
Closes https://github.com/iotaledger/iota/issues/4590

Its now the same one as we have in the dark theme

### CODE REVIEW

**Review by Dr-Electron — APPROVED** [review]
Looks good to me. when fix the real thing tho? :trollface:

**Review by evavirseda — APPROVED** [review]

File: sdk/dapp-kit/src/themes/lightTheme.ts [hunk 1]
```diff
@@ -55,8 +55,8 @@ export const lightTheme: ThemeVars = {
         fontFamily:
             'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
         fontStyle: 'normal',
-        lineHeight: '1.3',
-        letterSpacing: '1',
+        lineHeight: '24px',
```
Comment (begonaalvarezd) [inline sdk/dapp-kit/src/themes/lightTheme.ts:58]: We should add a patch changeset, i'll add it

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — APPROVED** [review]
