### PR TITLE
fix(iota): fix validator commands for committee members

### LINKED ISSUE #6380: iota validator commands fail for CommitteeMember
## Bug description

Many validator commands check the validator status before executing a transaction with `check_status()` which accepts ValidatorStatus variants
Since we added new variants, not everything is covered correctly anymore, `CommitteeMember` is missing for the commands here
https://github.com/iotaledger/iota/blob/b1eca50b821e5854b29d14b6069a107c9a010d90/crates/iota/src/validator_commands.rs#L1250-L1345

Running a command as committee member therefore currently results in in this error
`Validator 0x... is CommitteeMember, this operation is not supported in this tool or prohibited.`

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Fix validator commands for committee members

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/6380

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Modified test

### Release Notes

- [ ] Protocol:
- [ ] Nodes (Validators and Full nodes):
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [x] CLI: Fixed validator commands for committee members
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: crates/iota/src/validator_commands.rs [hunk 1]
```diff
@@ -380,9 +380,10 @@ impl IotaValidatorCommand {
             }
 
             IotaValidatorCommand::LeaveValidators { gas_budget } => {
-                // Only an active validator can leave committee.
+                // Only a committee member can leave the committee.
```
Comment (alexsporn) [inline crates/iota/src/validator_commands.rs]: This is not correct, it is not about leaving the committee, its about leaving the whole list, so both Active and Committee are accepted here

Comment (Thoralf-M) [reply crates/iota/src/validator_commands.rs]: You're right, got it wrong because of the wrong comment, fixed in https://github.com/iotaledger/iota/pull/6381/commits/cc4a90c15c7e45a40ebb248acb9691d2af17f96f

**Review by alexsporn — APPROVED** [review]

**Review by thibault-martinez — APPROVED** [review]
