### PR TITLE
fix(iota, iota-replay): fix test_profiler test by unignoring it and pass valid tx_digest

### LINKED ISSUE #4395: [iota, iota-replay] Fix test_profiler test

### PR DESCRIPTION
**Pull request by Dkwcs**
# Description of change

Protocol version check was removed because of:

> That was used by sui for their logic on tombstones, for us is already fine since protocol version 1

New digest `7qq4W43TqHg9tQPMvdAFW4Tz6J88KnPppBPR1hNKmQAd` it’s digest of generated transaction took from the iota-replay crate.

## Links to any relevant issues

Fix #4395 .

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

`cargo test test_profiler --features gas-profiler --lib
`

### CODE REVIEW

File: crates/iota/src/unit_tests/profiler_tests.rs [hunk 1]
```diff
@@ -62,6 +61,7 @@ async fn test_profiler() {
     let command_result =
         iota_replay::execute_replay_command(Some(testnet_url), false, false, None, None, cmd).await;
 
+    println!("{:?}", command_result);
```
Comment (thibault-martinez) [inline crates/iota/src/unit_tests/profiler_tests.rs]: Do you want to keep it or was it just for debugging purposes?

Comment (Dkwcs) [reply crates/iota/src/unit_tests/profiler_tests.rs]: It was just for debugging purposes
I’ve removed it

**Review by thibault-martinez — APPROVED** [review]

**Review by miker83z — APPROVED** [review]

**Review by valeriyr — APPROVED** [review]
