### PR TITLE
Fix: Cannot find rates for staking pool

### LINKED ISSUE #2929: [Bug (Infrastructure)]: iotax_getStakes fails with "Cannot find rates for staking pool {pool_id}"
## Description

```
curl https://api.iota-rebased-alphanet.iota.cafe \
--header 'content-type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "iotax_getStakes",
    "params": {
        "owner": "0x111111111504e9350e635d65cd38ccd2c029434c6a3a480d8947a9ba6a15b215"
    }
}'
```
Object with the pool id https://explorer.iota.cafe/object/0xe6adbdc0e16674e952d66b97e65a63e108900b7bcdc76f064c2ff79559fb94ac?network=alphanet
The address registered as validator, but isn't one

Basically the same, but didn't get fixed: https://github.com/MystenLabs/sui/issues/18304

### PR DESCRIPTION
**Pull request by sergiupopescu199**
# Description of change

This PR fixes the `"Cannot find rates for staking pool: {pool_id}"` error in the following crates
- `iota-json-rpc`
- `iota-indexer`
- `iota-graphql-rpc` 

The missing piece was to include also the candidate validators into account, now it should include all the the lifecycle phases of a validator: **Candidate**, **Pending**, **Active**, **Inactive**.

## Links to any relevant issues

#2929 

## Type of change
- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

- Start postgres

```sh
docker run --rm --name CONTAINER_NAME -e POSTGRES_PASSWORD=postgrespw -e POSTGRES_USER=postgres -e POSTGRES_DB=iota_indexer -d -p 5432:5432 postgres -N 1000
```

- Start a local network
```sh
RUST_LOG=consensus=off,iota_json_rpc=info cargo run --features indexer --bin iota start --force-regenesis --with-faucet --faucet-amount 2600000000000000 --with-indexer --epoch-duration-ms 10000
```

- run this script, it will step by step execute the RPC call during all the phases of a validator: Candidate, Pending, Active

```sh
function http_request() {
    for PORT in 9000 9124
    do
        RESPONSE=$(curl http://localhost:${PORT} \
        --header 'content-type: application/json' \
        --data '{
            "jsonrpc": "2.0",
            "id": 1,
            "method": "iotax_getStakes",
            "params": {
                "owner": "'${validatorAddress}'"
            }
        }')

        echo $RESPONSE

        if echo $RESPONSE | grep -q "Cannot find rates for staking pool"; then
            echo $RESPONSE
            exit 1
        fi
    done
}

set -x
iota client switch --env localnet
iota client faucet --url http://127.0.0.1:9123/gas
sleep 2
# Create validator
iota validator make-validator-info validator0 description https://iota.org/logo.png https://www.iota.org 127.0.0.1 1000
# Ad validator as candidate, is not in pending list yet
iota validator become-candidate validator.info
sleep 2
# Delegate stakes to validator
coinObjectId=$(iota client gas --json | jq '.[0].gasCoinId')
validatorAddress=$(iota client active-address)
iota client call --package 0x3 --module iota_system --function request_add_stake --args 0x5 $coinObjectId $validatorAddress --gas-budget 10000000
sleep 2
set +x
# Request validator stakes
http_request
# Add the validator into pending list, it will become active on next epoch
set -x
iota validator join-committee
sleep 2
set +x
# Request validator stakes
http_request
# wait till the stakes will be active
set -x
sleep 10
set +x
# Request validator stakes
http_request

```

## Change checklist
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

File: crates/iota-json-rpc/src/governance_api.rs [hunk 1]
```diff
@@ -638,8 +644,34 @@ fn pending_validator_exchange_rate(
...
+        )?;
+
+        tables.push((
+            validator_summary.iota_address,
+            validator_summary.staking_pool_id,
+            validator_summary.exchange_rates_id,
+            validator_summary.exchange_rates_size,
+            false,
+        ));
+    }
```
Comment (kodemartin) [inline crates/iota-json-rpc/src/governance_api.rs]: I would suggest splitting in a dedicated function `candidate_validator_exchange_rate` to minimize the scope.

File: crates/iota-json-rpc/src/governance_api.rs [hunk 2]
```diff
@@ -638,8 +644,34 @@ fn pending_validator_exchange_rate(
...
         .collect::<Vec<(IotaAddress, ObjectID, ObjectID, u64, bool)>>();
 
+    // Try to find for validator candidate and get its exchange rates
+    for (_, df) in state.get_dynamic_fields(
+        system_state_summary.validator_candidates_id,
+        None,
+        system_state_summary.validator_candidates_size as usize,
+    )? {
+        let raw_address =
+            String::deserialize(df.name.value).map_err(|err| IotaError::from(err.to_string()))?;
```
Comment (kodemartin) [inline crates/iota-json-rpc/src/governance_api.rs]: This resolves into an `iota_json_rpc::error::Error`, through the `From<IotaError>` implementation. This is rather opaque and misleading, let alone since `For<&str> for IotaError` resolves into a `GenericAuthority` variant. 

I reckon the most proper variant to use here is `iota_json_rpc::error::Error::StateRead`, since if the value of this dynamic field is not a string then the state must be corrupted. `StateRead` can be converted from `iota_json_rpc::authority_state::StateReadError`, which in turn can be converted from `anyhow::Error`.

File: crates/iota-json-rpc/src/governance_api.rs [hunk 3]
```diff
@@ -638,8 +644,34 @@ fn pending_validator_exchange_rate(
...
+        let validator_address = IotaAddress::from_str(&raw_address)?;
```
Comment (kodemartin) [inline crates/iota-json-rpc/src/governance_api.rs]: This error here turns out to be `iota_json_rpc::error::Error::Internal` due to conversion from the original `anyhow` error in the calling method. `StateReadError` seems proper here as well to give more context.

File: crates/iota-indexer/src/apis/governance_api.rs [hunk 4]
```diff
@@ -337,12 +345,98 @@ impl<T: R2D2Connection + 'static> GovernanceReadApi<T> {
...
+
+        self.validator_exchange_rates(tables).await
+    }
+
+    /// Check if there is any `Pending` and `Candidate` validators and get its
+    /// exchange rates, this two states of a validator lifecycle can manifest
+    /// during an epoch or multiple ones, is essential to not cache this data,
+    /// while exchange rates for `Active` and `Inactive` validators is OK to do
+    /// so because those states are manifested on epoch change.
+    pub async fn pending_and_candidate_validators_exchange_rate(
```
Comment (kodemartin) [inline crates/iota-indexer/src/apis/governance_api.rs]: Again I would suggest splitting the method between `pending` and `candidate` to minimize the scope.

File: crates/iota-indexer/src/apis/governance_api.rs [hunk 5]
```diff
@@ -358,6 +452,42 @@ impl<T: R2D2Connection + 'static> GovernanceReadApi<T> {
...
+                .await?;
+
+            tables.push((
+                validator_candidate.iota_address,
+                validator_candidate.staking_pool_id,
+                validator_candidate.exchange_rates_id,
+                validator_candidate.exchange_rates_size,
+                false,
+            ));
+        }
```
Comment (kodemartin) [inline crates/iota-indexer/src/apis/governance_api.rs]: This seems like a block of code that can be reused for the `inactive` validators, so you might consider making it a method accepting the table id.

File: crates/iota-indexer/src/apis/governance_api.rs [hunk 6]
```diff
@@ -337,12 +345,98 @@ impl<T: R2D2Connection + 'static> GovernanceReadApi<T> {
...
+                })
+                .await?;
+            tables.push((
+                validator.iota_address,
+                validator.staking_pool_id,
+                validator.exchange_rates_id,
+                validator.exchange_rates_size,
+                false,
+            ));
+        }
```
Comment (kodemartin) [inline crates/iota-indexer/src/apis/governance_api.rs]: This can become an independent method as well to delegate the responsibility of the logic in a unit with limited scope.

**Review by kodemartin — COMMENTED** [review]
@sergiupopescu199 lgtm with a few suggestions for polishing the implementation!

File: crates/iota-indexer/src/apis/governance_api.rs [hunk 7]
```diff
@@ -337,12 +345,98 @@ impl<T: R2D2Connection + 'static> GovernanceReadApi<T> {
         Ok(exchange_rates)
     }
 
-    /// Check if there is any pending validator and get its exchange rates
-    pub async fn pending_validators_exchange_rate(
+    /// Cached exchange rates for validators for the given epoch, the cache size
```
Comment (samuel-rufi) [inline crates/iota-indexer/src/apis/governance_api.rs]:
```suggestion
    /// Caches exchange rates for validators for the given epoch, the cache size
```

File: crates/iota-indexer/src/apis/governance_api.rs [hunk 8]
```diff
@@ -337,12 +345,98 @@ impl<T: R2D2Connection + 'static> GovernanceReadApi<T> {
...
+    /// is 1, it will be cleared when the epoch changes. rates are in
```
Comment (samuel-rufi) [inline crates/iota-indexer/src/apis/governance_api.rs]:
```suggestion
    /// is 1, it will be cleared when the epoch changes. Rates are in
```

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 6 above)
Comment (sergiupopescu199) [reply crates/iota-indexer/src/apis/governance_api.rs]: Added an utility [function](https://github.com/iotaledger/iota/pull/4313/commits/353da3b8f1c64730650f552d6b69a8a80833f0d9#diff-324f865071b593cb4ed59dd865b9600fae68065a818e622b14f4f5554812fd98R496-R535)

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 5 above)
Comment (sergiupopescu199) [reply crates/iota-indexer/src/apis/governance_api.rs]: Now fetching [Inactive](https://github.com/iotaledger/iota/pull/4313/commits/353da3b8f1c64730650f552d6b69a8a80833f0d9#diff-324f865071b593cb4ed59dd865b9600fae68065a818e622b14f4f5554812fd98R418-R436) and [Candidate](https://github.com/iotaledger/iota/pull/4313/commits/353da3b8f1c64730650f552d6b69a8a80833f0d9#diff-324f865071b593cb4ed59dd865b9600fae68065a818e622b14f4f5554812fd98R469-R491) validatros uses the utility function which unifies the logic

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 4 above)
Comment (sergiupopescu199) [reply crates/iota-indexer/src/apis/governance_api.rs]: As suggested the [two functions](https://github.com/iotaledger/iota/pull/4313/commits/353da3b8f1c64730650f552d6b69a8a80833f0d9#diff-324f865071b593cb4ed59dd865b9600fae68065a818e622b14f4f5554812fd98R177-R187) now are separate

File: crates/iota-json-rpc/src/governance_api.rs (hunk 1 above)
Comment (sergiupopescu199) [reply crates/iota-json-rpc/src/governance_api.rs]: As suggested the [two functions](https://github.com/iotaledger/iota/pull/4313/commits/9cf72f246047bee46937cce23431ce6d5bf20a52#diff-0a10b5dd25f3cf15826ae9c8e8ab585ac0e76d35d7c0f84a9334f7ed722b5406R206-R209) are separate

File: crates/iota-json-rpc/src/governance_api.rs (hunk 2 above)
Comment (sergiupopescu199) [reply crates/iota-json-rpc/src/governance_api.rs]: After more careful analysis I found that the deserializing as `String` was unecessary, this is the new [solution](https://github.com/iotaledger/iota/pull/4313/commits/9cf72f246047bee46937cce23431ce6d5bf20a52#diff-0a10b5dd25f3cf15826ae9c8e8ab585ac0e76d35d7c0f84a9334f7ed722b5406R680-R685)

File: crates/iota-json-rpc/src/governance_api.rs (hunk 3 above)
Comment (sergiupopescu199) [reply crates/iota-json-rpc/src/governance_api.rs]: resolving in favor of: https://github.com/iotaledger/iota/pull/4313#discussion_r1865396883

File: crates/iota-json-rpc/src/governance_api.rs [hunk 9]
```diff
@@ -642,36 +655,71 @@ fn pending_and_candidate_validators_exchange_rate(
...
+                .into()
+            })
+        },
+    )?;
 
     validator_exchange_rates(state, tables)
 }
 
+/// An utility function to gather `Candidate` or `Inactive` validator status
+/// information from the system state
```
Comment (kodemartin) [inline crates/iota-json-rpc/src/governance_api.rs]: I think this could use some refinement. When I read it I don't understand how  `Candidate` or `Inactive` are relevant to the function's signature.

I would suggest first discussing the closure `key` (what it does, how it is used) which seems like more generic and then mention `Candidate` or `Inactive` being fetched with realization of `key`. An example could be useful as well.

File: crates/iota-json-rpc/src/governance_api.rs [hunk 10]
```diff
@@ -642,36 +655,71 @@ fn pending_and_candidate_validators_exchange_rate(
...
-        ));
-    }
+        system_state_summary.validator_candidates_size,
+        |df| {
+            bcs::from_bytes::<IotaAddress>(&df.bcs_name).map_err(|err| {
+                IotaError::ObjectDeserialization {
+                    error: err.to_string(),
+                }
+                .into()
+            })
```
Comment (kodemartin) [inline crates/iota-json-rpc/src/governance_api.rs]: This should return a `RpInterimResult<T> = Result<T, iota_json_rpc::Error>` for which we have a `From<bcs::Error>` implementation. So I don't see why you have to first make an `IotaError` instead of a simple 

```rust
map_err(crate::error::Error::from)
```

File: crates/iota-json-rpc/src/governance_api.rs [hunk 11]
```diff
@@ -617,20 +585,65 @@ fn validator_exchange_rates(
...
+        state,
+        system_state_summary.inactive_pools_id,
+        system_state_summary.inactive_pools_size,
+        |df| {
+            bcs::from_bytes::<ID>(&df.bcs_name).map_err(|e| {
+                IotaError::ObjectDeserialization {
+                    error: e.to_string(),
+                }
+                .into()
+            })
```
Comment (kodemartin) [inline crates/iota-json-rpc/src/governance_api.rs]: Can be simplified through `crate::error::Error::from`

File: crates/iota-indexer/src/apis/governance_api.rs [hunk 12]
```diff
@@ -450,32 +461,63 @@ impl<T: R2D2Connection + 'static> GovernanceReadApi<T> {
...
                 system_state_summary.validator_candidates_id,
-                None,
-                system_state_summary.validator_candidates_size as usize,
+                system_state_summary.validator_candidates_size,
+                |df| {
+                    bcs::from_bytes::<IotaAddress>(&df.bcs_name).map_err(|err| {
+                        IotaError::ObjectDeserialization {
+                            error: err.to_string(),
+                        }
+                        .into()
```
Comment (kodemartin) [inline crates/iota-indexer/src/apis/governance_api.rs]: Can be simplified with `map_err(IndexerError::from)` (there is a `From<bcs::Error>` implementation)

File: crates/iota-indexer/src/apis/governance_api.rs [hunk 13]
```diff
@@ -375,68 +382,72 @@ impl<T: R2D2Connection + 'static> GovernanceReadApi<T> {
...
-                None,
-                system_state_summary.inactive_pools_size as usize,
+                system_state_summary.inactive_pools_size,
+                |df| {
+                    bcs::from_bytes::<ID>(&df.bcs_name).map_err(|e| {
+                        IotaError::ObjectDeserialization {
+                            error: e.to_string(),
+                        }
+                        .into()
+                    })
```
Comment (kodemartin) [inline crates/iota-indexer/src/apis/governance_api.rs]: Can be simplified through `map_err(IndexerError::from)` (there is a `From<bcs::Error>` implementation).

**Review by kodemartin — COMMENTED** [review]
Looks good @sergiupopescu199  with another small round of suggestions that could be implemented.

File: crates/iota-json-rpc/src/governance_api.rs (hunk 11 above)
Comment (sergiupopescu199) [reply crates/iota-json-rpc/src/governance_api.rs]: [Fixed](https://github.com/iotaledger/iota/pull/4313/commits/2547ea52607206b7ae132cfd626c8b5783fe12da#diff-0a10b5dd25f3cf15826ae9c8e8ab585ac0e76d35d7c0f84a9334f7ed722b5406R621)

File: crates/iota-json-rpc/src/governance_api.rs (hunk 10 above)
Comment (sergiupopescu199) [reply crates/iota-json-rpc/src/governance_api.rs]: [Fixed](https://github.com/iotaledger/iota/pull/4313/commits/2547ea52607206b7ae132cfd626c8b5783fe12da#diff-0a10b5dd25f3cf15826ae9c8e8ab585ac0e76d35d7c0f84a9334f7ed722b5406R672)

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 13 above)
Comment (sergiupopescu199) [reply crates/iota-indexer/src/apis/governance_api.rs]: [Fixed](https://github.com/iotaledger/iota/pull/4313/commits/05a02543dfc4b99f24c0ce410aaffc9139e5bf30#diff-324f865071b593cb4ed59dd865b9600fae68065a818e622b14f4f5554812fd98R426)

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 12 above)
Comment (sergiupopescu199) [reply crates/iota-indexer/src/apis/governance_api.rs]: [Fixed](https://github.com/iotaledger/iota/pull/4313/commits/05a02543dfc4b99f24c0ce410aaffc9139e5bf30#diff-324f865071b593cb4ed59dd865b9600fae68065a818e622b14f4f5554812fd98R474)

File: crates/iota-json-rpc/src/governance_api.rs (hunk 9 above)
Comment (sergiupopescu199) [reply crates/iota-json-rpc/src/governance_api.rs]: [Fixed](https://github.com/iotaledger/iota/pull/4313/commits/2547ea52607206b7ae132cfd626c8b5783fe12da#diff-0a10b5dd25f3cf15826ae9c8e8ab585ac0e76d35d7c0f84a9334f7ed722b5406R678-R723)

File: crates/iota-json-rpc/src/governance_api.rs [hunk 14]
```diff
@@ -636,10 +648,108 @@ fn pending_validator_exchange_rate(
...
+    validator_exchange_rates(state, tables)
+}
+
+/// Fetches validator status information from `StateRead` for validators not
+/// included in `IotaSystemStateSummary`.
+///
+/// `IotaSystemStateSummary` only contains information about `Active`
+/// validators. To retrieve information about `Inactive`, `Candidate`, and
+/// `Pending` validators, we need to access dynamic fields within specific
+/// tables.
```
Comment (kodemartin) [inline crates/iota-json-rpc/src/governance_api.rs]: Nit: 

```suggestion
/// Fetches validator status information from `StateRead`.
///
/// This makes sense for validators not included in `IotaSystemStateSummary`.
/// `IotaSystemStateSummary` only contains information about `Active`
/// validators. To retrieve information about `Inactive`, `Candidate`, and
/// `Pending` validators, we need to access dynamic fields within specific
/// Move tables.
```

File: crates/iota-json-rpc/src/governance_api.rs [hunk 15]
```diff
@@ -636,10 +648,108 @@ fn pending_validator_exchange_rate(
...
+///
+/// To retrieve validator status information, this function utilizes a
+/// `table_id` defined by an `ObjectID` and a `limit` to specify the number of
+/// records to fetch. Both the `table_id` and `limit` are obtained from
+/// `IotaSystemStateSummary`. Additionally, a `key` is extracted from the
+/// `table_id`'s `DynamicFieldInfo` to identify the specific validator within
+/// the table.
```
Comment (kodemartin) [inline crates/iota-json-rpc/src/governance_api.rs]: Nit: 
```suggestion
/// To retrieve validator status information, this function utilizes the
/// corresponding `table_id` (an `ObjectID` value) and a `limit` to specify the
/// number of records to fetch. Both the `table_id` and `limit` can be obtained
/// from `IotaSystemStateSummary` in the caller. Additionally, keys are
/// extracted from the table `DynamicFieldInfo` values according to the `key`
/// closure. This helps in identifying the specific validator within the table.
```

File: crates/iota-json-rpc/src/governance_api.rs [hunk 16]
```diff
@@ -636,10 +648,108 @@ fn pending_validator_exchange_rate(
...
+/// let _ = validator_summary_from_system_state(
+///     state,
+///     // ID of the object that stores preactive validators, mapping their addresses to their Validator structs
+///     system_state_summary.validator_candidates_id,
+///     // Number of preactive validators
+///     system_state_summary.validator_candidates_size,
+///     // Extract the `IotaAddress` of the `Candidate` validator from the `DynamicFieldInfo` in the `system_state_summary.validator_candidates_id` table
+///     |df| bcs::from_bytes::<IotaAddress>(&df.bcs_name).map_err(Into::into),
+/// ).unwrap();
+/// ```
```
Comment (kodemartin) [inline crates/iota-json-rpc/src/governance_api.rs]: Much much better, thank you!

**Review by kodemartin — APPROVED** [review]

File: crates/iota-json-rpc/src/governance_api.rs (hunk 16 above)
Comment (sergiupopescu199) [reply crates/iota-json-rpc/src/governance_api.rs]: Thank to you @kodemartin, really appreciated the suggestions, will keep in mind next time when something similar will occur 🙏

**Review by tomxey — APPROVED** [review]

**Review by samuel-rufi — APPROVED** [review]
