### PR TITLE
fix(iota-indexer): Return transactions that could not be resolved by the package resolver as of failing layouts

### LINKED ISSUE #5789: Indexer iota_getTransactionBlock fails with `Type Parameter 0 out of bounds (0)`
## Bug description

Requesting an invalid transaction with `"showInput": true` fails with `Type Parameter 0 out of bounds (0)`

## Version

- Version: 0.10.0-alpha

## Steps To reproduce the bug

```zsh
curl https://indexer.devnet.iota.cafe \
--header 'content-type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "iota_getTransactionBlock",
    "params": {
        "digest": "AcQ1Zz6ancTJGYuoMZV8DhHyGdbCGi6ajNsAmTUUZEJP",
        "options": { 
            "showInput": true
        }
    }
}' | jq .
```

## Expected behaviour

Should return the transaction data

## Actual behaviour

```JSON
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32603,
    "message": "Type Parameter 0 out of bounds (0)"
  }
}
```

Note: it works with the node, the result is this:
```JSON
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "digest": "AcQ1Zz6ancTJGYuoMZV8DhHyGdbCGi6ajNsAmTUUZEJP",
    "transaction": {
      "data": {
        "messageVersion": "v1",
        "transaction": {
          "kind": "ProgrammableTransaction",
          "inputs": [
            {
              "type": "pure",
              "valueType": null,
              "value": [
                104,
                183,
                41,
                107,
                221,
                103,
                170,
                31,
                100,
                189,
                179,
                159,
                223,
                197,
                136,
                29,
                50,
                5,
                221,
                109,
                190,
                157,
                148,
                103,
                169,
                184,
                76,
                52,
                242,
                111,
                246,
                49
              ]
            },
            {
              "type": "pure",
              "valueType": null,
              "value": [
                3,
                127,
                20,
                209,
                228,
                152,
                22,
                216,
                226,
                130,
                174,
                206,
                178,
                78,
                60,
                232,
                51,
                192,
                147,
                255,
                217,
                112,
                173,
                202,
                245,
                224,
                195,
                148,
                229,
                62,
                226,
                44,
                17,
                184,
                40,
                142,
                224,
                40,
                95,
                65,
                97,
                78,
                101,
                202,
                4,
                232,
                110,
                154,
                75,
                178,
                198,
                183,
                143,
                181,
                82,
                123,
                194,
                45,
                129,
                26,
                49,
                165,
                109,
                251,
                47,
                195,
                65,
                75,
                136,
                19,
                144,
                188,
                136,
                241,
                208,
                82,
                85,
                187,
                205,
                2,
                157,
                210,
                219,
                47,
                2,
                45,
                234,
                58,
                181,
                16,
                236,
                248,
                228,
                135,
                135,
                236,
                24
              ]
            }
          ],
          "transactions": [
            {
              "MoveCall": {
                "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                "module": "pay",
                "function": "join_vec",
                "arguments": [
                  {
                    "Input": 0
                  },
                  {
                    "Input": 1
                  }
                ]
              }
            }
          ]
        },
        "sender": "0xb62979320398473f15a7dbff45f3663ef36d8d5cdbea60c171f80c48d9ba32d1",
        "gasData": {
          "payment": [
            {
              "objectId": "0x68b7296bdd67aa1f64bdb39fdfc5881d3205dd6dbe9d9467a9b84c34f26ff631",
              "version": 4793,
              "digest": "71LpSYN1Aw8zGR7voESKWNM5nF5QprnK6ppzeqbGsDtb"
            }
          ],
          "owner": "0xb62979320398473f15a7dbff45f3663ef36d8d5cdbea60c171f80c48d9ba32d1",
          "price": "1000",
          "budget": "5000000"
        }
      },
      "txSignatures": [
        "ALNaN/cjRnghbN3XUYFK5416pOp4Wn8lb4iaaDnomjShADcYv2nYvE8Rsg8noccjwdwCC2CuK8ST00wL4yHnoAuQuV98vDgDw7Hh5ohTceKh005xLbFL6peQLebLNfxv8A=="
      ]
    },
    "timestampMs": "1741193754966",
    "checkpoint": "43317730"
  }
}
```

### PR DESCRIPTION
**Pull request by samuel-rufi**
# Description of change

Return transactions that could not be resolved by the package resolver as of failing layouts.

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/5789

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [x] Patch-specific tests (correctness, functionality coverage)

**The test has been manually tested as shown in the linked issue.**

### Infrastructure QA (only required for crates that are maintained by @iotaledger/infrastructure)

- [x] Verification of API backward compatibility.

**Testing for following test classes are not necessary for this patch:**

- [ ] Synchronization of the indexer from genesis for a network including migration objects.
- [ ] Restart of indexer synchronization locally without resetting the database.
- [ ] Restart of indexer synchronization on a production-like database.
- [ ] Deployment of services using Docker.

### Release Notes

- [ ] Protocol:
- [ ] Nodes (Validators and Full nodes):
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [ ] CLI:
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: crates/iota-json-rpc-types/src/iota_transaction.rs [hunk 1]
```diff
@@ -1792,7 +1792,16 @@ impl IotaProgrammableTransactionBlock {
...
-        let input_types = package_resolver.pure_input_layouts(&value).await?;
+        // If the pure input layouts cannot be built, we will use `None` for the input
+        // types.
+        let input_types = package_resolver
+            .pure_input_layouts(&value)
+            .await
+            .unwrap_or_else(|e| {
+                tracing::warn!("pure_input_layouts failed: {:?}", e);
+                vec![None; value.inputs.len()]
+            });
```
Comment (kodemartin) [inline crates/iota-json-rpc-types/src/iota_transaction.rs:1803]: Why not `unwrap_or_default`? An empty vector seems more appropriate as we can't return any input layout if `pure_input_layout` fails.

Comment (samuel-rufi) [reply crates/iota-json-rpc-types/src/iota_transaction.rs:1803]: When using `unwrap_or_default()` we would get an empty `Vec` for `input_types` if `pure_input_layout` fails. This would lead to `inputs.zip(input_types)` making zero pairs and the transaction result would not include any inputs, which wouldn't match the response of the node anymore. While we can't provide an input layout for an input in such case, we still want to include the inputs without layout in the response.

**Review by kodemartin — APPROVED** [review]
lgtm

**Review by sergiupopescu199 — APPROVED** [review]
