### PR TITLE
fix(iota-indexer): fix failing test

### LINKED ISSUE #4171: [iota-indexer]: Fix failing test
## Description

Sometimes the `get_total_transaction_blocks` fails in the CI wit this error

```
thread 'read_api::get_total_transaction_blocks' panicked at crates/iota-indexer/tests/rpc-tests/read_api.rs:1167:14:
called `Result::unwrap()` on an `Err` value: Call(ErrorObject { code: InvalidRequest, message: "Verified checkpoint not found for sequence number: 5", data: None })
```

### PR DESCRIPTION
**Pull request by sergiupopescu199**
# Description of change

In indexer's tests don't use the `data_ingestion_path` for checkpoint sync but fallback to the full node's REST API

## Links to any relevant issues

fixes #4171 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Locally this test never fails, the actual test will be to check if on CI is does not fail

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

File: crates/iota-indexer/tests/rpc-tests/read_api.rs [hunk 1]
```diff
@@ -1158,6 +1161,13 @@ fn get_total_transaction_blocks() {
 
     runtime.block_on(async move {
         indexer_wait_for_checkpoint(store, checkpoint).await;
+        // even tough when the indexer caught up with the desired checkpoint from the
+        // fullnode, sometimes when requesting the fullnode
+        // get_checkpoint(CheckpointId::SequenceNumber(checkpoint)) it can say that it
+        // does not exist, here we make sure that also the fullnode is synced
+        // with the desired checkpoint seq number
+        fullnode_wait_for_checkpoint(cluster.rpc_client(), checkpoint).await;
```
Comment (samuel-rufi) [inline crates/iota-indexer/tests/rpc-tests/read_api.rs]: this is a bit weird IMO. if the indexer got a checkpoint from the node, I'm wondering why the node can't provide it via `get_checkpoint(CheckpointId::SequenceNumber(checkpoint))`? Seems like something to investigate..

for now, would  it be possible to maybe call `fullnode_wait_for_checkpoint` directly in `indexer_wait_for_checkpoint` and not expose that function? as I imagine the need of always calling both functions manually might be a bit error prone.

Also I think we should call `fullnode_wait_for_checkpoint` before `indexer_wait_for_checkpoint` as the node should be ready first.

Comment (kodemartin) [reply crates/iota-indexer/tests/rpc-tests/read_api.rs]: The two requests are independent I think. `indexer_wait_for_ehckpoint` is synchronized through the rest API of the node, while `fullnode_wait_for_checkpoint` and the failing request use the JSON-RPC. So I think it makes sense to keep them decoupled and not nest `fullnode_wait` inside the `indexer_wait`.

That said, I would suggest having a look on the node tables that the rest API, and the JSON-RPC use to get the checkpoints to see if there is something off there. Considering also #4154.

Comment (sergiupopescu199) [reply crates/iota-indexer/tests/rpc-tests/read_api.rs]: @kodemartin @samuel-rufi 
I've left a comment with the solution and the investigation on the issue itself to find it easily if needed in the future: https://github.com/iotaledger/iota/issues/4171#issuecomment-2500028348

File: crates/iota-indexer/tests/common/mod.rs [hunk 2]
```diff
@@ -114,7 +114,7 @@ pub async fn start_test_cluster_with_read_write_indexer(
     builder_modifier: Option<Box<dyn FnOnce(TestClusterBuilder) -> TestClusterBuilder>>,
 ) -> (TestCluster, PgIndexerStore<PgConnection>, HttpClient) {
     let temp = tempdir().unwrap().into_path();
-    let mut builder = TestClusterBuilder::new().with_data_ingestion_dir(temp.clone());
+    let mut builder = TestClusterBuilder::new();
```
Comment (kodemartin) [inline crates/iota-indexer/tests/common/mod.rs:117]: This is not necessary to force the indexer syncing from remote, so why remove it?

Comment (sergiupopescu199) [reply crates/iota-indexer/tests/common/mod.rs:117]: I'm afraid in order to force the sync only trough the REST API we need to remove it. I did a quick test with and without the data ingestion path it rarely fetches form REST API since all the checkpoints are available from the validators and the fullnode is always behind.

these are the steps it does:

1.  The [synchronization](https://github.com/iotaledger/iota/blob/develop/crates/iota-data-ingestion-core/src/reader.rs#L369-L371) process is triggered either when an inotify notification is received from monitoring the data ingestion path or according to the specified tick interval (`self.options.tick_interval_ms`).

2. Within the [synchronization](https://github.com/iotaledger/iota/blob/develop/crates/iota-data-ingestion-core/src/reader.rs#L245-L251) routine, the process first checks for any available checkpoints in the data ingestion path. If a [remote](https://github.com/iotaledger/iota/blob/develop/crates/iota-data-ingestion-core/src/reader.rs#L254-L260) source is specified, the system also fetches checkpoints from that source, allowing for the merging of checkpoints obtained from both origins.

3. The issue is the fact that checkpoints in the data ingestion path are generated more rapidly than those retrieved from the full node. Validators can produce checkpoints at a faster rate, while the full node must synchronize with these validators to obtain the latest checkpoints. Consequently, when the system performs remote fetching, it may not yield the most current checkpoints. Thus, checkpoints written into the data ingestion path consistently remain ahead of those accessible via the full node’s REST API.

4. By removing the data ingestion path from the `TestClusterBuilder`, nodes will stop writing checkpoints to that directory. As a result, the only mechanism for synchronization available to the indexer will be the remote fetch. This situation will lead to an empty vector for checkpoints from the data ingestion path

Comment (kodemartin) [reply crates/iota-indexer/tests/common/mod.rs:117]: You're right, I missed the `&&` condition.

File: crates/iota-indexer/src/test_utils.rs [hunk 3]
```diff
@@ -71,6 +73,7 @@ pub async fn start_test_indexer_impl<T: R2D2Connection + 'static>(
     data_ingestion_path: Option<PathBuf>,
     cancel: CancellationToken,
     new_database: Option<&str>,
+    sync_from_rest_api: bool,
```
Comment (kodemartin) [inline crates/iota-indexer/src/test_utils.rs]: Why is this necessary?

Comment (sergiupopescu199) [reply crates/iota-indexer/src/test_utils.rs]: When enabling by default the REST API in the indexer most of e2e tests cases from localnet and graphQL were failing:

- https://github.com/iotaledger/iota/actions/runs/12030001477/job/33537011315
- https://github.com/iotaledger/iota/actions/runs/12030001477/job/33537488968

I tried to add the flag to see if my assumptions were correct

Comment (kodemartin) [reply crates/iota-indexer/src/test_utils.rs]: Couldn't you use `data_ingestion_path = None` to fallback to the rest synchronization and keep the signature intact?

Comment (sergiupopescu199) [reply crates/iota-indexer/src/test_utils.rs]: Of course, that makes perfect sense, I thought that I needed to make it explicit when the rest synchronization was used, I'll add the changes, thank you 🙏

Comment (sergiupopescu199) [reply crates/iota-indexer/src/test_utils.rs]: @kodemartin [fixed](https://github.com/iotaledger/iota/pull/4173/commits/39384b270b251263cce1aaf40a2ad75dad4bc54d#diff-c1acc129a5b81dc72a6ce4d79513b7a2b3903911fc34c75681fc28feefb12b32R89-R92)

**Review by kodemartin — APPROVED** [review]
lgtm :boat:

File: crates/iota-indexer/src/test_utils.rs [hunk 4]
```diff
@@ -86,11 +86,14 @@ pub async fn start_test_indexer_impl<T: R2D2Connection + 'static>(
 
     let mut config = IndexerConfig {
         db_url: Some(db_url.clone().into()),
+        // As fallback sync mechanism enable Rest Api if `data_ingestion_path` was not provided
+        remote_store_url: data_ingestion_path
+            .is_none()
+            .then_some(format!("{}/api/v1", rpc_url)),
```
Comment (Thoralf-M) [inline crates/iota-indexer/src/test_utils.rs]:
```suggestion
            .then_some(format!("{rpc_url}/api/v1")),
```

**Review by Thoralf-M — APPROVED** [review]

File: crates/iota-indexer/src/test_utils.rs (hunk 4 above)
Comment (sergiupopescu199) [reply crates/iota-indexer/src/test_utils.rs]: @Thoralf-M thank you for the suggestion, indeed is better!

**Review by alexsporn — APPROVED** [review]
