### PR TITLE
fix(explorer): Fix last rewards metric in validators page

### LINKED ISSUE #4949: Fix "Last Epoch Rewards" metric in validators page
The last epoch rewards cant rely on the number of validators that are currently in the system, we should query the last ended epoch and see what were the rewards, the same way the epoch page does it using `epochData.endOfEpochInfo?.totalStakeRewardsDistributed`

### PR DESCRIPTION
**Pull request by marc2332**
Closes https://github.com/iotaledger/iota/issues/4949

Uses a more accurate source.

### CODE REVIEW

File: apps/explorer/src/pages/validators/Validators.tsx [hunk 1]
```diff
@@ -58,18 +60,19 @@ function ValidatorPageResult(): JSX.Element {
...
-
-        return totalRewards;
-    }, [validatorEvents]);
+    const enhancedRpc = useEnhancedRpcClient();
+    const { data: epochData } = useQuery({
+        queryKey: ['epoch', data?.epoch],
+        queryFn: async () => {
+            const epoch = Number(data?.epoch || 0);
+            return enhancedRpc.getEpochs({
+                cursor: epoch === 0 || epoch === 1 ? undefined : (epoch - 2).toString(),
```
Comment (begonaalvarezd) [inline apps/explorer/src/pages/validators/Validators.tsx:77]: we might benefit from a comment here explaining why -2, just for the future us, now is clear but maybe in 3 months isnt 🙈 
Also, epoch I presume will never be 0 because the current epoch at minimum is always epoch 1, but thats ok, maybe we could just make `epoch < 2 ? undefined : (epoch - 2).toString()`

**Review by begonaalvarezd — APPROVED** [review]

**Review by cpl121 — CHANGES_REQUESTED** [review]
Only the comment that Bego suggested to include in the code, the rest is fine by me

File: apps/explorer/src/pages/validators/Validators.tsx (hunk 1 above)
Comment (marc2332) [reply apps/explorer/src/pages/validators/Validators.tsx:77]: I think its more clear to use `epoch === 0 || epoch === 1`, just added a comment btw

**Review by cpl121 — APPROVED** [review]
