### PR TITLE
fix(node): refactor ExecutionCacheConfig

### LINKED ISSUE #7847: Split `cache_type` from `ExecutionCacheConfig`
Users can't specify the settings for the writeback cache via config right now in case they have selected the passthrough cache. But they still can set them via env variables. This is an odd behaviour.
We should do something like this instead:

```rust
pub enum ExecutionCacheType {
    PassthroughCache,
    WritebackCache
}

pub struct ExecutionCacheConfig {
        cache_type: ExecutionCacheType,

        /// Maximum number of entries in each cache. (There are several
        /// different caches). If None, the default of 10000 is used.
        max_cache_size: Option<u64>,

        package_cache_size: Option<u64>, // defaults to 1000

        object_cache_size: Option<u64>, // defaults to max_cache_size
        marker_cache_size: Option<u64>, // defaults to object_cache_size
        object_by_id_cache_size: Option<u64>, // defaults to object_cache_size

        transaction_cache_size: Option<u64>, // defaults to max_cache_size
        executed_effect_cache_size: Option<u64>, // defaults to transaction_cache_size
        effect_cache_size: Option<u64>,      // defaults to executed_effect_cache_size

        events_cache_size: Option<u64>, // defaults to transaction_cache_size

        transaction_objects_cache_size: Option<u64>, // defaults to 1000
    },
}
```

### PR DESCRIPTION
**Pull request by semenov-vladyslav**
# Description of change

ProxyCache crates both Passthrough and Writeback caches and thus requires both configs, while previously ExecutionCacheConfig was an enum which could only provide config for one cache. This PR simplifies the definition of ExecutionCacheConfig allowing to keep all config values.

## Links to any relevant issues

Fixes #7847.

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [ ] Patch-specific tests (correctness, functionality coverage)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota-config/src/node.rs [hunk 1]
```diff
@@ -263,178 +262,124 @@ pub struct NodeConfig {
     pub iota_names_config: Option<IotaNamesConfig>,
 }
 
+#[derive(Clone, Copy, Debug, Deserialize, Serialize)]
+pub enum ExecutionCacheConfigType {
```
Comment (muXxer) [inline crates/iota-config/src/node.rs]:
```suggestion
pub enum ExecutionCacheType {
```

**Review by muXxer — CHANGES_REQUESTED** [review]

**Review by piotrm50 — APPROVED** [review]

**Review by muXxer — APPROVED** [review]

File: crates/iota-config/src/node.rs (hunk 1 above)
Comment (semenov-vladyslav) [reply crates/iota-config/src/node.rs]: Done

**Review by muXxer — APPROVED** [review]
