### PR TITLE
fix(wallet,wallet-dashboard): fix inconsistencies in tx history

### LINKED ISSUE #4544: Fix inconsistencies in tx history between wallet & wallet dashboard
- The wallet shows `transaction` and the dashboard `send` Image
Image
- The dashboard shows `NaN` with txs related to visual assetsImage

### PR DESCRIPTION
**Pull request by evavirseda**
# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/4544

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: apps/core/src/utils/transaction/getTransactionAction.ts [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+    const unstakeTypeTransaction = transaction?.events?.find(
+        ({ type }) => type === UNSTAKING_REQUEST_EVENT,
+    );
+    if (stakeTypeTransaction) {
+        return TransactionAction.Staked;
+    } else if (unstakeTypeTransaction) {
+        return TransactionAction.Unstaked;
+    } else {
+        const isSender = transaction.transaction?.data.sender === currentAddress;
+        return isSender ? TransactionAction.Send : TransactionAction.Receive;
```
Comment (begonaalvarezd) [inline apps/core/src/utils/transaction/getTransactionAction.ts]: because we cant know if what we did was sending (for example the user could have migrated) I would call this transaction a generic `Transaction` as it was before.

File: apps/core/src/utils/transaction/getTransactionAction.ts [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+    transaction: IotaTransactionBlockResponse,
+    currentAddress?: string,
+) => {
+    const stakeTypeTransaction = transaction?.events?.find(
+        ({ type }) => type === STAKING_REQUEST_EVENT,
+    );
+    const unstakeTypeTransaction = transaction?.events?.find(
+        ({ type }) => type === UNSTAKING_REQUEST_EVENT,
+    );
+    if (stakeTypeTransaction) {
```
Comment (begonaalvarezd) [inline apps/core/src/utils/transaction/getTransactionAction.ts:20]: We could include here timelocked staking and unstaking, we have events for these too, see events in https://explorer.rebased.iota.org/txblock/8QshWrqFhiLYxsFbcx3rcT9pNJm1oh1RJ4jJh5eL57Vk?network=testnet & https://explorer.rebased.iota.org/txblock/5qJeMgWwvar5ZE58EUWBMmLsenBqmpCJeRsuYTsDvetf?network=testnet

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
Amazing work, just added 2 comments

File: apps/core/src/interfaces/transactions.interfaces.ts [hunk 3]
```diff
@@ -16,6 +16,8 @@ export enum TransactionAction {
     Transaction = 'Transaction',
     Staked = 'Staked',
     Unstaked = 'Unstaked',
+    TimelockedStaked = 'TimelockedStaked',
+    TimelockedUnstaked = 'TimelockedUnstaked',
```
Comment (brancoder) [inline apps/core/src/interfaces/transactions.interfaces.ts]: we should add a space here so the labels are not displayed like this
image

File: apps/wallet/src/ui/app/components/transactions-card/index.tsx [hunk 4]
```diff
@@ -66,7 +66,7 @@ export function TransactionCard({ txn, address }: TransactionCardProps) {
                 <CardImage type={ImageType.BgSolid} shape={ImageShape.SquareRounded}>
                     <TxnIcon
                         txnFailed={executionStatus !== 'success' || !!error}
-                        variant={getLabel(txn, address)}
+                        variant={getTransactionAction(txn, address)}
```
Comment (brancoder) [inline apps/wallet/src/ui/app/components/transactions-card/index.tsx:69]: error is thrown on this line because we should update  TxnIcon component with TimelockedStaked, TimelockedUnstaked variants simmilar to what you added in the dashboard

**Review by brancoder — DISMISSED** [review]
LG just a couple of minor comments

**Review by VmMad — APPROVED** [review]
LGTM

File: apps/core/src/utils/transaction/getTransactionAction.ts [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+    const stakeTypeTransaction = transaction?.events?.find(
+        ({ type }) => type === STAKING_REQUEST_EVENT,
+    );
+    const unstakeTypeTransaction = transaction?.events?.find(
+        ({ type }) => type === UNSTAKING_REQUEST_EVENT,
+    );
+
+    const isTimelockedStaking = stakeTypeTransaction?.transactionModule === 'timelocked_staking';
+    const isTimelockedUnstaking =
+        unstakeTypeTransaction?.transactionModule === 'timelocked_staking';
```
Comment (cpl121) [inline apps/core/src/utils/transaction/getTransactionAction.ts]: better use a constant for `timelocked_staking`

**Review by cpl121 — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
Could we show the amount staked and unstaked when is timelocked staking & unstaking, like we do with the normal stakes? 
image
image

File: apps/wallet-dashboard/components/transactions/TransactionTile.tsx [hunk 6]
```diff
@@ -38,11 +44,42 @@ export function TransactionTile({ transaction }: TransactionTileProps): JSX.Elem
...
-        Math.abs(Number(address ? transactionSummary?.balanceChanges?.[address]?.[0]?.amount : 0)),
-        IOTA_TYPE_ARG,
+
+    const { isTimelockedStaking, isTimelockedUnstaking } = checkIfIsTimelockedStaking(
+        transaction.raw?.events,
     );
 
+    const balanceChanges = transactionSummary?.balanceChanges;
+
+    function getAmount(tx: ExtendedTransaction) {
```
Comment (begonaalvarezd) [inline apps/wallet-dashboard/components/transactions/TransactionTile.tsx:55]: This whole logic now is duplicated with https://github.com/iotaledger/iota/blob/f0614864fdc259135bb7516b2e1d7e7ade9a43d9/apps/core/src/components/transaction/details/StakeTransactionDetails.tsx#L20 & https://github.com/iotaledger/iota/blob/f0614864fdc259135bb7516b2e1d7e7ade9a43d9/apps/core/src/components/transaction/info/UnstakeTransactionInfo.tsx#L22, maybe we could add utils to avoid code duplication?

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
Amzing work, works great, just added a small comment to avoid code duplication 🙏🏼

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
The CI is also failing 🙏🏼 andiim getting an error in the console 
```
TS2307: Cannot find module '@/lib/utils' or its
│  corresponding type declarations.
```

File: apps/core/src/utils/stake/parseEventJson.ts [hunk 7]
```diff
@@ -0,0 +1,9 @@
+// Copyright (c) 2024 IOTA Stiftung
+// SPDX-License-Identifier: Apache-2.0
+
+import type { IotaEvent } from '@iota/iota-sdk/client';
+import { ParsedJson } from '../../interfaces';
+
+export function parseEventJson<T extends ParsedJson>(event: IotaEvent): T {
```
Comment (begonaalvarezd) [inline apps/core/src/utils/stake/parseEventJson.ts]: you are not really parsing but rather getting the parsed json, I would probably rename this function to `getParsedJson` or even probably remove it and make getStakeDetails & getUnstakeDetails be based on the event and not the parsed json, to avoid 1 extra conversion that can happen directly in a single function eg `getStakeDetailsFromEvent(event)`

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by cpl121 — APPROVED** [review]

**Review by begonaalvarezd — APPROVED** [review]
