### PR TITLE
fix(iota-indexer): slow sync

### LINKED ISSUE #6114: [`iota-indexer`]: regression in syncing time with genesis
## Description

Investigate why the syncing time with genesis increased in the latest versions of `iota-indexer`.

### PR DESCRIPTION
**Pull request by sergiupopescu199**
# Description of change

Restore the old logic of adding a lag when start syncing the object snapshot data.

## Links to any relevant issues

fixes #6114 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Started the indexer against the testnet network and measured the time took to sync the genesis checkpoint. 

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

File: crates/iota-indexer/src/handlers/mod.rs [hunk 1]
```diff
@@ -91,7 +91,7 @@ impl<T> CommonHandler<T> {
 
             // Try to fetch new data tuple from the stream
             if unprocessed.len() >= UNPROCESSED_CHECKPOINT_SIZE_LIMIT {
-                tracing::info!(
+                tracing::debug!(
```
Comment (kodemartin) [inline crates/iota-indexer/src/handlers/mod.rs:94]: Yes!

File: crates/iota-indexer/src/handlers/mod.rs [hunk 2]
```diff
@@ -101,9 +101,11 @@ impl<T> CommonHandler<T> {
...
                             return Ok(());
                         }
-                        for (cp_seq, data) in tuple_chunk {
-                            unprocessed.insert(cp_seq, (cp_seq, data));
-                        }
+                        unprocessed.extend(
+                            tuple_chunk
+                                .into_iter()
+                                .map(|(cp_seq, data)| (cp_seq, (cp_seq, data))),
+                        );
```
Comment (kodemartin) [inline crates/iota-indexer/src/handlers/mod.rs]: I think this is rather unnecessary. It is more verbose, and ends up in the same internal logic: https://doc.rust-lang.org/src/alloc/collections/btree/map.rs.html#2312

**Review by kodemartin — APPROVED** [review]
lgtm with a minor suggestion

**Review by samuel-rufi — APPROVED** [review]

File: crates/iota-indexer/src/handlers/mod.rs (hunk 2 above)
Comment (sergiupopescu199) [reply crates/iota-indexer/src/handlers/mod.rs]: fixed: https://github.com/iotaledger/iota/pull/6155/commits/1b4b1523ac55ac2684c05f1b6e39129866414989
