### PR TITLE
fix(explorer): Add tooltips to balance breakdown on address page

### LINKED ISSUE #8168: Explorer Balance Breakdown: make it possible to see the exact balance for an address
## Description

Currently the IOTA amount is rounded, for example https://explorer.iota.org/address/0xb14f13f5343641e5b52d144fd6f106a7058efe2f1ad44598df5cda73acf0101f?network=devnet displays 60 IOTA, but the exact amount is 60.002330000
It should be possible to view this exact amount, maybe by clicking on the amount field

## Motivation

Can be confusing and is misleading

## Requirements

1.Make it possible to view the exact amount

## Are you planning to do it yourself in a pull request?

No.

### PR DESCRIPTION
**Pull request by brancoder**
# Description of change

resolves #8168

### CODE REVIEW

File: apps/explorer/src/pages/address-result/AddressBalanceBreakdown.tsx [hunk 1]
```diff
@@ -211,12 +199,19 @@ function RenderBalanceValue({
...
+    });
     if (isLoading) {
         return <Skeleton className="h-4 w-20" />;
     }
     if (isError) {
         return '--';
     }
 
-    return value;
+    return <Tooltip text={fullAmount}>{roundedAmount}</Tooltip>;
```
Comment (KeitoTadashi) [inline apps/explorer/src/pages/address-result/AddressBalanceBreakdown.tsx]: nit: i would also show symbol in the tooltip like

Image

File: apps/explorer/src/pages/address-result/AddressBalanceBreakdown.tsx [hunk 2]
```diff
@@ -211,12 +199,19 @@ function RenderBalanceValue({
     isLoading,
     isError,
 }: RenderBalanceValueProps): React.JSX.Element | string {
+    const [roundedAmount] = useFormatCoin({
+        balance: value,
+    });
+    const [fullAmount] = useFormatCoin({
```
Comment (Thoralf-M) [inline apps/explorer/src/pages/address-result/AddressBalanceBreakdown.tsx]: Can we show the full nano amount and not remove zeros at the end?
image
I would have expected to see `39.999676400`
Additionally what would be great is to have some visual separation between 3 numbers, a small gap maybe `39.999 676 400` (even smaller and without actual spaces, so it's not annoying when copying)

**Review by Thoralf-M — DISMISSED** [review]
LGTM

**Comment by KeitoTadashi** [comment]
LGTM just 2 small nits:

i think there is a missaligment 
image

also copy button is always on the right but here is on the left

**Review by KeitoTadashi — DISMISSED** [review]

**Review by KeitoTadashi — APPROVED** [review]

**Review by Thoralf-M — APPROVED** [review]

File: apps/explorer/src/pages/address-result/AddressBalanceBreakdown.tsx [hunk 3]
```diff
@@ -34,10 +43,7 @@ export function AddressBalanceBreakdown({ address }: { address: string }): React
         isLoading: isLoadingBalance,
         isError: isBalanceErrored,
     } = useBalance(address);
-
-    const [totalAvailableBalance, symbol] = useFormatCoin({
-        balance: balance?.totalBalance,
-    });
+    const totalAvailableBalance = balance?.totalBalance || '0';
```
Comment (panteleymonchuk) [inline apps/explorer/src/pages/address-result/AddressBalanceBreakdown.tsx]:
```suggestion
    const totalAvailableBalance = balance?.totalBalance ? BigInt(balance.totalBalance) : BigInt(0);
```

File: apps/explorer/src/pages/address-result/AddressBalanceBreakdown.tsx [hunk 4]
```diff
@@ -14,14 +15,22 @@ import {
...
+} from '@iota/apps-ui-kit';
 import { useState } from 'react';
+import { CoinFormat, formatBalance } from '@iota/iota-sdk/utils';
 
 const TOOLTIP_TEXT = 'This balance breakdown does not include unmigrated stardust funds.';
 interface BalanceBreakdownElement {
     keyText: string;
-    value: string;
-    supportingLabel: string;
+    value: string | bigint;
```
Comment (panteleymonchuk) [inline apps/explorer/src/pages/address-result/AddressBalanceBreakdown.tsx]:
```suggestion
    value: bigint;
```

File: apps/explorer/src/pages/address-result/AddressBalanceBreakdown.tsx [hunk 5]
```diff
@@ -201,7 +199,7 @@ export function AddressBalanceBreakdown({ address }: { address: string }): React
 }
 
 interface RenderBalanceValueProps {
-    value: string;
+    value: string | bigint;
```
Comment (panteleymonchuk) [inline apps/explorer/src/pages/address-result/AddressBalanceBreakdown.tsx]:
```suggestion
    value: bigint;
```

File: apps/explorer/src/pages/address-result/AddressBalanceBreakdown.tsx (hunk 3 above)
Comment (panteleymonchuk) [reply apps/explorer/src/pages/address-result/AddressBalanceBreakdown.tsx]: Probably you could keep bigint everywhere

**Review by marc2332 — APPROVED** [review]

File: apps/explorer/src/pages/address-result/AddressBalanceBreakdown.tsx [hunk 6]
```diff
@@ -175,24 +163,34 @@ export function AddressBalanceBreakdown({ address }: { address: string }): React
...
                         }
                         fullwidth
-                        supportingLabel={symbol}
+                        supportingLabel={IOTA_COIN_METADATA.symbol}
+                        copyText={formatBalance(
+                            totalBalanceBreakdown,
+                            IOTA_COIN_METADATA.decimals,
+                            CoinFormat.Full,
+                        )}
                     />
```
Comment (VmMad) [inline apps/explorer/src/pages/address-result/AddressBalanceBreakdown.tsx:197]: Add an onCopySuccess toast:
```tsx
                       import { onCopySuccess } from '~/lib';

                       // ...

                       supportingLabel={IOTA_COIN_METADATA.symbol}
                        copyText={formatBalance(
                            totalBalanceBreakdown,
                            IOTA_COIN_METADATA.decimals,
                            CoinFormat.Full,
                        )}
                        onCopySuccess={onCopySuccess}
```

File: apps/explorer/src/pages/address-result/AddressBalanceBreakdown.tsx [hunk 7]
```diff
@@ -211,12 +209,23 @@ function RenderBalanceValue({
...
     if (isLoading) {
         return <Skeleton className="h-4 w-20" />;
     }
     if (isError) {
         return '--';
     }
 
-    return value;
+    return (
+        <Tooltip openDelay={500} text={`${fullAmount} ${symbol}`}>
```
Comment (VmMad) [inline apps/explorer/src/pages/address-result/AddressBalanceBreakdown.tsx]: the delay makes the app feel slow, a delay of `100` makes it feel smoother

**Review by VmMad — APPROVED** [review]
