### PR TITLE
enhance(test): Add timeout and retry to test to make them more stable

### LINKED ISSUE #5584: Investigate the testing fail: test_checkpoint_executor_crash_recovery
Investigate the failing test: test_checkpoint_executor_crash_recovery
See more details in [the test results](https://github.com/iotaledger/iota/actions/runs/13487310695/job/37680136228).

### LINKED ISSUE #5620: Investigate the testing fail: `iota-network randomness::tests::test_byzantine_peer_handling`
Investigate `iota-network randomness::tests::test_byzantine_peer_handling` fail as it happens more and more often.

### PR DESCRIPTION
**Pull request by jkrvivian**
# Description of change

Rust tests fail during nightly tests, because the tests get slower and thus fail to reach the expected values immediately, this PR adds timeout and retries to fix them.

## Links to any relevant issues

Close #5620 
Close #5584 

## Type of change

- Enhancement 

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota-network/src/randomness/tests.rs [hunk 1]
```diff
@@ -438,12 +438,29 @@ async fn test_byzantine_peer_handling() {
             None,
         );
     }
+
+    // Use tokio timeout to ensure the test has sometime to meet expected results.
```
Comment (muXxer) [inline crates/iota-network/src/randomness/tests.rs]:
```suggestion
    // Use tokio timeout to ensure the test has some time to meet expected results.
```

File: crates/iota-network/src/randomness/tests.rs [hunk 2]
```diff
@@ -473,10 +490,7 @@ async fn test_byzantine_peer_handling() {
     }
     for rx in &mut randomness_rxs[..2] {
         // Validators (0, 1) can communicate normally in new epoch.
-        let (epoch, round, bytes) = rx.recv().await.unwrap();
-        assert_eq!(1, epoch);
-        assert_eq!(0, round.0);
-        assert_ne!(0, bytes.len());
+        receive_with_timeout(rx, 1, 0).await.unwrap();
```
Comment (muXxer) [inline crates/iota-network/src/randomness/tests.rs]: maybe use expect here.

File: crates/iota-network/src/randomness/tests.rs [hunk 3]
```diff
@@ -438,12 +438,29 @@ async fn test_byzantine_peer_handling() {
...
+        Err(())
+    }
+
     for rx in &mut randomness_rxs[2..] {
         // Validators (2, 3) can communicate normally.
-        let (epoch, round, bytes) = rx.recv().await.unwrap();
-        assert_eq!(0, epoch);
-        assert_eq!(0, round.0);
-        assert_ne!(0, bytes.len());
+        receive_with_timeout(rx, 0, 0).await.unwrap();
```
Comment (muXxer) [inline crates/iota-network/src/randomness/tests.rs]: maybe use expect here.

File: crates/iota-core/src/checkpoints/checkpoint_executor/tests.rs [hunk 4]
```diff
@@ -56,37 +56,47 @@ pub async fn test_checkpoint_executor_crash_recovery() {
     let checkpoints = sync_new_checkpoints(
         &checkpoint_store,
         &checkpoint_sender,
-        2 * buffer_size,
+        buffer_size,
```
Comment (muXxer) [inline crates/iota-core/src/checkpoints/checkpoint_executor/tests.rs:59]: what was the reason to change the number of synced checkpoints everywhere?

**Review by muXxer — CHANGES_REQUESTED** [review]

File: crates/iota-core/src/checkpoints/checkpoint_executor/tests.rs (hunk 4 above)
Comment (jkrvivian) [reply crates/iota-core/src/checkpoints/checkpoint_executor/tests.rs:59]: To decrease the number of checkpoints to sync.

File: crates/iota-network/src/randomness/tests.rs (hunk 3 above)
Comment (jkrvivian) [reply crates/iota-network/src/randomness/tests.rs]: Fixed in https://github.com/iotaledger/iota/pull/5732/commits/cc484523a02668f5aad3d643119797be9e10a989.

File: crates/iota-network/src/randomness/tests.rs (hunk 2 above)
Comment (jkrvivian) [reply crates/iota-network/src/randomness/tests.rs]: Fixed in https://github.com/iotaledger/iota/pull/5732/commits/cc484523a02668f5aad3d643119797be9e10a989.

File: crates/iota-network/src/randomness/tests.rs (hunk 1 above)
Comment (jkrvivian) [reply crates/iota-network/src/randomness/tests.rs]: Fixed in https://github.com/iotaledger/iota/pull/5732/commits/cc484523a02668f5aad3d643119797be9e10a989.

**Review by muXxer — APPROVED** [review]

**Comment by jkrvivian** [comment]
We're still investigating `test_byzantine_peer_handling`. It fails frequently on Linux machines, but it always passes on Mac. 

@semenov-vladyslav

**Comment by jkrvivian** [comment]
Regarding the fix on `test_byzantine_peer_handling`, check out: https://github.com/iotaledger/iota/issues/5620#issuecomment-2706190685

**Review by VorobyevIlya — APPROVED** [review]

**Review by bingyanglin — APPROVED** [review]

File: crates/iota-network/src/randomness/mod.rs [hunk 5]
```diff
@@ -982,7 +982,7 @@ impl RandomnessEventLoop {
                     continue; // don't send partial sigs to self
                 }
                 let mut client = RandomnessClient::new(peer.clone());
-                const SEND_PARTIAL_SIGNATURES_TIMEOUT: Duration = Duration::from_secs(10);
+                const SEND_PARTIAL_SIGNATURES_TIMEOUT: Duration = Duration::from_secs(30);
```
Comment (semenov-vladyslav) [inline crates/iota-network/src/randomness/mod.rs]: This is the main culprit behind test_byzantine_peer_handling failures. Increasing the timeout seems to help. But it doesn't look like a proper solution.

File: crates/iota-network/src/randomness/mod.rs [hunk 6]
```diff
@@ -982,6 +982,14 @@ impl RandomnessEventLoop {
                     continue; // don't send partial sigs to self
                 }
                 let mut client = RandomnessClient::new(peer.clone());
+                // `test_byzantine_peer_handling` built in debug mode takes
+                // longer to verify invalid signatures and thus needs larger
+                // timeouts.
+                #[cfg(test)]
+                const SEND_PARTIAL_SIGNATURES_TIMEOUT: Duration = Duration::from_secs(500);
```
Comment (semenov-vladyslav) [inline crates/iota-network/src/randomness/mod.rs]: 500 sec [seems to work on self-hosted-arm64](https://github.com/iotaledger/iota/actions/runs/13791724155/job/38573592500#step:9:2993).
