### PR TITLE
feat(wallet): fix auto-expand wallet when wallet indexes have gaps

### LINKED ISSUE #8629: Fix auto-expand wallet when wallet indexes have gaps
## Description

When wallet indexes have gaps (balance finder)

Image

Clicking + will add a wallet inside the gap **but** expand the last index

More here https://iotafoundation.slack.com/archives/C057SC8EW15/p1748427431852679?thread_ts=1748420476.465469&cid=C057SC8EW15

### PR DESCRIPTION
**Pull request by evavirseda**
# Description of change

[Screencast from 2026-03-31 09-24-31.webm](https://github.com/user-attachments/assets/a1533866-d338-47be-9dd8-b6c8162a66eb)

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/8629

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

### CODE REVIEW

**Review by KeitoTadashi — APPROVED** [review]

File: apps/wallet/src/ui/app/pages/accounts/manage/AccountGroup.tsx [hunk 1]
```diff
@@ -81,9 +82,22 @@ export function AccountGroup({
...
         setSourceFlow(AmpliSourceFlow.ManageAccounts);
-        createAccountsMutation.mutate({
-            type: accountsFormType,
-        });
+        try {
+            const accountCreationResult = await createAccountsMutation.mutateAsync({
+                type: accountsFormType,
+            });
+            const newAccount = accountCreationResult?.[0];
+            if (newAccount && isMnemonicSerializedUiAccount(newAccount)) {
```
Comment (brancoder) [inline apps/wallet/src/ui/app/pages/accounts/manage/AccountGroup.tsx]: we should add the Seed accounts check here and do this for that type also
`if (newAccount && (isMnemonicSerializedUiAccount(newAccount) || isSeedSerializedUiAccount(newAccount)))`

the reason being that the legacy account can come from a ff seed (check `isLegacyAccount`)
seed example: `0xa5cfd040906b2761cb2ebd9e7c7bba9b0c125e6123aa51a4b49d901254b6ac4659ac0e36ff9f4c2062d8f67dec435dd019826962170eb4889ba15eada3128639`

**Review by brancoder — CHANGES_REQUESTED** [review]
LG we just need to enable this for seed derived accounts also

**Review by brancoder — APPROVED** [review]
