### PR TITLE
Use same pattern for force_new_epoch in query_validator_epoch_info_event as in other tests

### LINKED ISSUE #4499: [iota-indexer]: query_validator_epoch_info_event test fails in CI
## Description

Another indexer rpc test fails in CI: https://github.com/iotaledger/iota/actions/runs/12318486243/job/34383616943?pr=4496

Might be related to #4471

### PR DESCRIPTION
**Pull request by tomxey**
# Description of change

In all tests that use `force_new_epoch` function we create a separate test cluster and wait for new checkpoint being present in indexer after epoch change.

Aligned `query_validator_epoch_info_event` test to also be structured that way.
This should improve stability of the test.

## Links to any relevant issues

fixes #4499

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

`cargo test -j2 --profile=simulator --features shared_test_runtime --test rpc-tests`

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota-indexer/tests/rpc-tests/indexer_api.rs [hunk 1]
```diff
@@ -187,17 +188,15 @@ fn query_events_supported_events() {
 
 #[test]
 fn query_validator_epoch_info_event() {
-    let ApiTestSetup {
-        runtime,
-        store,
-        client,
-        cluster,
-    } = ApiTestSetup::get_or_init();
+    let ApiTestSetup { runtime, .. } = ApiTestSetup::get_or_init();
```
Comment (kodemartin) [inline crates/iota-indexer/tests/rpc-tests/indexer_api.rs]: If we only need the runtime, can't we just make it a `#[tokio::test]` test?

Because `ApiTestSetup::get_or_init` starts an indexer instance as well, as far as I can see.

Comment (tomxey) [reply crates/iota-indexer/tests/rpc-tests/indexer_api.rs]: I did it like this for consistency with other tests, but I think we can.
Modified.

Comment (kodemartin) [reply crates/iota-indexer/tests/rpc-tests/indexer_api.rs]: This warrants refactoring all other similar tests as well. We benefit the running time.

Could you create an issue @tomxey ?

**Review by kodemartin — APPROVED** [review]
lgtm :balloon:

File: crates/iota-indexer/tests/rpc-tests/indexer_api.rs (hunk 1 above)
Comment (tomxey) [reply crates/iota-indexer/tests/rpc-tests/indexer_api.rs]: Created https://github.com/iotaledger/iota/issues/4939

Comment (tomxey) [reply crates/iota-indexer/tests/rpc-tests/indexer_api.rs]: The performance benefit may not be that big, since `get_or_init` just returns a shared cluster. But the code would be simpler.

**Review by sergiupopescu199 — APPROVED** [review]
lgtm ✨
