### PR TITLE
fix(docs): Added cookie policy page to the docs

### LINKED ISSUE #7915: Add cookie policy page to the docs site
For the cookie consent component URL [Read our Cookie Policy](https://docs.iota.org/privacy-policy) redirect to `/cookie-policy` add this cookie policy page to the docs site.

### PR DESCRIPTION
**Pull request by vivekjain23**
# Description of change

This PR brings up the changes in cookie consent component and addition of cookie policy page

## Links to any relevant issues

fixes #7915

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [ ] Patch-specific tests (correctness, functionality coverage)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### Release Notes

- [ ] Protocol:
- [ ] Nodes (Validators and Full nodes):
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [ ] CLI:
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: docs/site/src/pages/cookie-policy.tsx [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+          Cookie Policy
+        </h1>
+        
+        <div id="cookie-library-content">
+          <CookieLibrary configuration={configuration} />
+        </div>
+      </main>
+    </Layout>
+  );
+}
```
Comment (Dr-Electron) [inline docs/site/src/pages/cookie-policy.tsx]:
```suggestion
}

```

**Review by Dr-Electron — APPROVED** [review]

**Review by Ginowine — APPROVED** [review]
