### PR TITLE
chore: Update protobuf to fix RUSTSEC-2024-0437

### LINKED ISSUE #5861: RUSTSEC-2024-0437 - `protobuf` uncontrolled recursion
## Bug description

[`RUSTSEC-2024-0437`](https://rustsec.org/advisories/RUSTSEC-2024-0437) will be fixed by https://github.com/stepancheg/rust-protobuf/pull/756 once it is included in a release. We can update it and remove this from `deny.toml`

### PR DESCRIPTION
**Pull request by DaughterOfMars**
## Description 

Updates `protobuf` to version 3 (and prometheus along with it) to fix RUSTSEC-2024-0437.

## Related Issues

Closes #5861

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] gRPC:
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:

### CODE REVIEW

**Review by Dr-Electron — APPROVED** [review]
Example changes look good to me :trollface:  (rest looks good to my noob eyes too 😅 )

**Review by muXxer — APPROVED** [review]

File: consensus/core/src/authority_service.rs [hunk 1]
```diff
@@ -96,7 +96,11 @@ impl<C: CoreThreadDispatcher> NetworkService for AuthorityService<C> {
                 .metrics
                 .node_metrics
                 .invalid_blocks
-                .with_label_values(&[peer_hostname, "handle_send_block", "UnexpectedAuthority"])
+                .with_label_values(&[
+                    peer_hostname.as_str(),
```
Comment (Thoralf-M) [inline consensus/core/src/authority_service.rs:100]: Why this .as_str() change?

**Review by Thoralf-M — APPROVED** [review]

**Review by lucas-tortora — APPROVED** [review]

**Review by valeriyr — APPROVED** [review]

**Review by VorobyevIlya — APPROVED** [review]
