### PR TITLE
fix(wallet/dashboard/explorer): Disable growthbook cache in dev mode

### LINKED ISSUE #5231: Disable growthbook cache in dev mode
https://docs.growthbook.io/lib/js#updating-to-100

### PR DESCRIPTION
**Pull request by marc2332**
Closes https://github.com/iotaledger/iota/issues/5231

### CODE REVIEW

File: apps/wallet-dashboard/lib/utils/growthbook.ts [hunk 1]
```diff
@@ -26,3 +25,5 @@ export const growthbook = new GrowthBook({
     apiHost: getAppsBackend(),
     ...GROWTHBOOK_ENVIRONMENTS[environment],
 });
+
+console.log(environment, growthbook);
```
Comment (begonaalvarezd) [inline apps/wallet-dashboard/lib/utils/growthbook.ts]: ✂️

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — APPROVED** [review]

**Review by cpl121 — APPROVED** [review]
