### PR TITLE
fix(dashboard): update validator address and amount in stake transaction logging

### LINKED ISSUE #8707: Add validator property to staking events in dashboard
Staking events from the wallet dashboard are missing the validator property (though timelock staking has it). Add validator info to standard staking events.

### LINKED ISSUE #8709: Fix validator property in timelockStake event
In the timelockStake event, we are incorrectly sending the sender address instead of the selected validator. Update to send the correct validator.

### PR DESCRIPTION
**Pull request by panteleymonchuk**
Closes #8707
Closes #8709

### CODE REVIEW

File: apps/wallet-dashboard/components/dialogs/staking/views/EnterAmountView.tsx [hunk 1]
```diff
@@ -94,7 +94,8 @@ export function EnterAmountView({
                     onSuccess(tx.digest);
                     toast.success('Stake transaction has been sent');
                     ampli.stakedIota({
-                        stakedAmount: Number(parseAmount(values.amount, IOTA_DECIMALS)),
+                        stakedAmount: Number(values.amount),
```
Comment (msarcev) [inline apps/wallet-dashboard/components/dialogs/staking/views/EnterAmountView.tsx:97]: Is it safe to remove `parseAmount` here ?

Comment (panteleymonchuk) [reply apps/wallet-dashboard/components/dialogs/staking/views/EnterAmountView.tsx:97]: Here we just provide number what user put to input. We have validation of the form, so it should be safe.

**Review by KeitoTadashi — APPROVED** [review]

**Review by VmMad — APPROVED** [review]
