### PR TITLE
fix(wallet): toast overlay connecting dapp buttons

### LINKED ISSUE #3735: Fix toast overlap action buttons when connecting dapp
When unlocking an account when trying to connect to dapp, the toast overlaps the action buttons
https://github.com/user-attachments/assets/2beb4b0d-514e-4ef9-bc41-5130dcaf5c09

### PR DESCRIPTION
**Pull request by VmMad**
# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

Fixes #3735 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by panteleymonchuk — APPROVED** [review]

File: apps/wallet/src/ui/app/shared/toaster/index.tsx [hunk 1]
```diff
@@ -37,8 +37,10 @@ function getBottomSpace(pathname: string, isMenuVisible: boolean, isBottomNavSpa
         '/accounts/manage',
     ].includes(pathname);
 
-    if (overlayWithActionButton || isBottomNavSpace) {
-        return '!bottom-16';
+    const matchDynamicPaths = ['/dapp/connect'].some((path) => pathname.startsWith(path));
```
Comment (cpl121) [inline apps/wallet/src/ui/app/shared/toaster/index.tsx:40]: why is it necessary to match the path?

Comment (cpl121) [reply apps/wallet/src/ui/app/shared/toaster/index.tsx:40]: ahh, I got it 🤐

**Review by cpl121 — APPROVED** [review]
