### PR TITLE
fix(indexer, json-rpc): Support Coin Manager in `get_coin_metadata` RPC API

### LINKED ISSUE #5772: [iotax_getCoinMetadata) Always returns "null" for Coin created with Coin manager
see thread : https://discord.com/channels/912718559954747442/1282243183648178208/1346788047512932353

### LINKED ISSUE #7100: fix(indexer): Leverage index for singleton query (#19247)  `{"side-effects": "minor", "type": "fix"}`
https://www.github.com/MystenLabs/sui/pull/19247

### PR DESCRIPTION
**Pull request by tomxey**
# Description of change

Fix RPC APIs always returning "null" for Coins created with Coin manager.

One case couldn't be supported by the node easily, a separate issue was created for this: https://github.com/iotaledger/iota/issues/7014

This PR only fixes the `get_coin_metadata` endpoint, the `get_total_supply` endpoint will be fixed in scope of https://github.com/iotaledger/iota/issues/7134

The size of the diff comes mostly from the tests.
The meat of the change which changes the logic is in:
 - [crates/iota-json-rpc/src/coin_api.rs](https://github.com/iotaledger/iota/pull/7052/files#diff-387356559ec229db00d1da4c92ca83f65cd112df1da6f0f8bd7d2173274f3905) for Node
 - [crates/iota-indexer/src/indexer_reader.rs](https://github.com/iotaledger/iota/pull/7052/files#diff-59c7fa0841ea58f4030d1040643d35471b08f0d570bd91d8a35607cdeb86ccc3) for Indexer

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/5772
fixes https://github.com/iotaledger/iota/issues/7100

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [x] Patch-specific tests (correctness, functionality coverage) - **created patch-specific tests and ensured that they pass**

`cargo test --profile simulator --package iota-indexer --test rpc-tests --all-features -- coin_api`

### Infrastructure QA (only required for crates that are maintained by @iotaledger/infrastructure)

- [ ] Synchronization of the indexer from genesis for a network including migration objects.
- [ ] Restart of indexer synchronization locally without resetting the database.
- [ ] Restart of indexer synchronization on a production-like database.
- [ ] Deployment of services using Docker.
- [x] Verification of API backward compatibility. - **Endpoint should behave without changes for standard coins**

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### Release Notes

- [ ] Protocol:
- [ ] Nodes (Validators and Full nodes):
- [x] Indexer:
  - fixed CoinManager support in get_coin_metadata
- [x] JSON-RPC:
  - fixed support for native CoinManager coins in get_coin_metadata
- [ ] GraphQL:
- [ ] CLI:
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: crates/iota-types/src/base_types.rs [hunk 1]
```diff
@@ -317,6 +318,15 @@ impl MoveObjectType {
         }
     }
 
+    pub fn is_coin_manager(&self) -> bool {
+        match &self.0 {
+            MoveObjectType_::GasCoin | MoveObjectType_::StakedIota | MoveObjectType_::Coin(_) => {
+                false
+            }
+            MoveObjectType_::Other(s) => CoinManager::is_coin_manager(s),
+        }
```
Comment (sergiupopescu199) [inline crates/iota-types/src/base_types.rs]: Since we only seek for the `MoveObjectType_::Other` variant we could replace the logic using this one line

```suggestion
        matches!(&self.0, MoveObjectType_::Other(s) if CoinManager::is_coin_manager(s))
```

File: crates/iota-types/src/coin_manager.rs [hunk 2]
```diff
@@ -49,6 +51,21 @@ impl CoinManager {
             && object_type.module.as_ident_str() == COIN_MANAGER_MODULE_NAME
             && object_type.name.as_ident_str() == COIN_MANAGER_STRUCT_NAME
     }
+
+    pub fn from_bcs_bytes(content: &[u8]) -> Result<Self, IotaError> {
+        bcs::from_bytes(content).map_err(|err| IotaError::ObjectDeserialization {
+            error: format!("Unable to deserialize CoinManager object: {}", err),
```
Comment (sergiupopescu199) [inline crates/iota-types/src/coin_manager.rs]:
```suggestion
            error: format!("Unable to deserialize CoinManager object: {err}"),
```

File: crates/iota-types/src/coin_manager.rs [hunk 3]
```diff
@@ -82,3 +99,28 @@ impl CoinManagerTreasuryCap {
...
+    type Error = IotaError;
+    fn try_from(object: &Object) -> Result<Self, Self::Error> {
+        match &object.data {
+            Data::Move(o) => {
+                if o.type_().is_coin_manager() {
+                    return CoinManager::from_bcs_bytes(o.contents());
+                }
+            }
+            Data::Package(_) => {}
+        }
```
Comment (sergiupopescu199) [inline crates/iota-types/src/coin_manager.rs]:
```suggestion
        if let Data::Move(o) = &object.data {
            if o.type_().is_coin_manager() {
                return CoinManager::from_bcs_bytes(o.contents());
            }
        }
```

File: crates/iota-types/src/coin_manager.rs [hunk 4]
```diff
@@ -82,3 +99,28 @@ impl CoinManagerTreasuryCap {
...
+
+        Err(IotaError::Type {
+            error: format!("Object type is not a CoinManager: {:?}", object),
```
Comment (sergiupopescu199) [inline crates/iota-types/src/coin_manager.rs]:
```suggestion
            error: format!("Object type is not a CoinManager: {object:?}"),
```

**Review by sergiupopescu199 — APPROVED** [review]
lgtm ✨

Left some optional nits.

File: crates/iota-indexer/tests/data/coin_manager_coins/sources/normal_coin.move [hunk 5]
```diff
@@ -0,0 +1,34 @@
+// Copyright (c) Mysten Labs, Inc.
+// Modifications Copyright (c) 2025 IOTA Stiftung
```
Comment (jkrvivian) [inline crates/iota-indexer/tests/data/coin_manager_coins/sources/normal_coin.move]: The same for other new files 😁 
```suggestion
// Copyright (c) 2025 IOTA Stiftung
```

**Review by jkrvivian — CHANGES_REQUESTED** [review]

File: crates/iota-types/src/base_types.rs (hunk 1 above)
Comment (tomxey) [reply crates/iota-types/src/base_types.rs]: Done

File: crates/iota-types/src/coin_manager.rs (hunk 2 above)
Comment (tomxey) [reply crates/iota-types/src/coin_manager.rs]: Done

File: crates/iota-types/src/coin_manager.rs (hunk 3 above)
Comment (tomxey) [reply crates/iota-types/src/coin_manager.rs]: Done

File: crates/iota-types/src/coin_manager.rs (hunk 4 above)
Comment (tomxey) [reply crates/iota-types/src/coin_manager.rs]: Done

File: crates/iota-indexer/tests/data/coin_manager_coins/sources/normal_coin.move (hunk 5 above)
Comment (tomxey) [reply crates/iota-indexer/tests/data/coin_manager_coins/sources/normal_coin.move]: Done

**Review by jkrvivian — APPROVED** [review]

File: crates/iota-indexer/src/indexer_reader.rs [hunk 6]
```diff
@@ -831,6 +832,27 @@ impl IndexerReader {
         })
     }
 
+    fn get_singleton_object(&self, struct_tag: StructTag) -> Result<Option<Object>, IndexerError> {
```
Comment (samuel-rufi) [inline crates/iota-indexer/src/indexer_reader.rs:835]: If the provided struct tag is not of a singleton I guess it would be more safe to return an error instead of picking just the first object. But since the API is not public it should be fine for internal use as it is.

**Review by samuel-rufi — APPROVED** [review]
Looks good to me!

File: crates/iota-indexer/src/indexer_reader.rs (hunk 6 above)
Comment (tomxey) [reply crates/iota-indexer/src/indexer_reader.rs:835]: It would be a responsibility of the caller to know that this type is a singleton in this case. As you said, it should be fine since it's an internal function.
