### PR TITLE
fix(genesis-builder): Always destroy allocation objects when picked

### LINKED ISSUE #5024: [genesis] Allocation does not destroy the migrated timelock/gas coin when it is a "surplus"
When the genesis is created through migration, the allocation process for timelocked or gas coins in favor of a list of validators includes a special "surplus" coin. This "surplus" coin is set aside during the transition from one validator's allocation to another's. Specifically, only a portion of its balance is used for a validator's allocation, while the remaining surplus may be utilized later for the next validator.

During this process, the last surplus timelocked coin picked during the execution of: https://github.com/iotaledger/iota/blob/3b51dac8934d26076d25cd0030e0a13b0a48bb0b/crates/iota-genesis-builder/src/stake.rs#L349 
will be put in the list of timelocks to split, here:
https://github.com/iotaledger/iota/blob/3b51dac8934d26076d25cd0030e0a13b0a48bb0b/crates/iota-genesis-builder/src/stake.rs#L273
however, the original timelock object is never put in the list of objects to destroy 
https://github.com/iotaledger/iota/blob/3b51dac8934d26076d25cd0030e0a13b0a48bb0b/crates/iota-genesis-builder/src/stake.rs#L204

This basically results in cloning the object.

## Suggested change: 
- Put the newly selected surplus coin in the objects to destroy here: https://github.com/iotaledger/iota/blob/3b51dac8934d26076d25cd0030e0a13b0a48bb0b/crates/iota-genesis-builder/src/stake.rs#L414

### PR DESCRIPTION
**Pull request by miker83z**
# Description of change

Fixes #5024 (it also adds a validation of the migrated objects after the genesis build)

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

- After the setup of #4829 
- `cargo run --release --bin iota genesis-ceremony build-unsigned-checkpoint --local-migration-snapshots stardust_object_snapshot.bin`

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by muXxer — APPROVED** [review]

File: crates/iota-config/src/migration_tx_data.rs [hunk 1]
```diff
@@ -155,6 +159,30 @@ impl MigrationTxData {
...
 
+    /// Validates the total supply of the migration data adding up the amount of
+    /// gas coins found in migrated objects.
+    pub fn validate_total_supply(&self, expected_total_supply: u64) -> anyhow::Result<()> {
+        let total_supply: u64 = self
+            .get_objects()
+            .map(|object| match &object.data {
+                Data::Move(_) => GasCoin::try_from(&object)
+                    .map(|gas| gas.value())
+                    .or_else(|_| TimeLock::<Balance>::try_from(&object).map(|t| t.locked().value()))
```
Comment (valeriyr) [inline crates/iota-config/src/migration_tx_data.rs]: Should we add a check of the locked type here as well?

**Review by valeriyr — APPROVED** [review]

File: crates/iota-config/src/migration_tx_data.rs [hunk 2]
```diff
@@ -155,6 +159,30 @@ impl MigrationTxData {
...
+                    .or_else(|_| AliasOutput::try_from(&object).map(|a| a.balance.value()))
+                    .or_else(|_| BasicOutput::try_from(&object).map(|b| b.balance.value()))
+                    .or_else(|_| NftOutput::try_from(&object).map(|n| n.balance.value()))
+                    .unwrap_or(0),
```
Comment (DaughterOfMars) [inline crates/iota-config/src/migration_tx_data.rs]: Any chance we can avoid this by checking a type byte or something?

File: crates/iota-config/src/migration_tx_data.rs (hunk 1 above)
Comment (miker83z) [reply crates/iota-config/src/migration_tx_data.rs]: Added [bd609eb](https://github.com/iotaledger/iota/pull/5028/commits/bd609ebc0b39c4538c8122b69bfe192dd585d6ce)

File: crates/iota-config/src/migration_tx_data.rs (hunk 2 above)
Comment (miker83z) [reply crates/iota-config/src/migration_tx_data.rs]: That `object` is encoded through a Move Struct, so unfortunately I don't see an easy change to support a type byte.

**Review by lzpap — APPROVED** [review]
Yaay, it worked! 🎉 
```
Total Number of Validators: 4
Total Number of Migration Objects: 4561398
Total Number of Objects/Packages: 4561441
Total Supply of Iota: 4600000000000000000 NANOS or 4600000000 IOTA
Total Amount of StakedIota: 45000000000000000 NANOS or 45000000 IOTA
```
