### PR TITLE
fix(consensus): track failures to choose optimal peers and adjust parameters in the Starfish transaction synchronizer

### LINKED ISSUE #9162: Tune TransactionSynchronizer to not choke easily
Currently Transaction Synchronizer is saturated quite easily, as it runs only 1 live fetching task and 1 pending task. We need to tune parameters and remove some processing timeouts so that it runs more smoothly.

### PR DESCRIPTION
**Pull request by polinikita**
# Description of change

Transaction synchronizer fetches transactions either slowly or with some warning in many scenarios:
-  after commit syncer has synced a big number of certified commits, the transactions from the committed subDAGs are fetched quite slowly.
- when some connections are blocked, the transaction synchronizer produces too many failures with blocked peers.

In this PR, 
- we tune parameters of the transaction synchronizer to increase the number of concurrent high-level task and control the total number of spawned tasks.
- we introduce a simple memory tracking when the transaction fetch has failed for the last time for each given peer. This memory is then used to take proper peers for fetching
- we remove transaction verification from the transaction synchronizer (similarly to how it was done in the commit syncer) since the verification and validity of transactions was already performed by a quorum of the network.

## Links to any relevant issues

Fixes #9162 

## How the change has been tested
We have tested the change using the fuzz testing scenarios.

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [ ] Patch-specific tests (correctness, functionality coverage)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/starfish/core/src/transactions_synchronizer.rs [hunk 1]
```diff
@@ -649,81 +740,77 @@ impl<C: NetworkClient, V: BlockVerifier, D: CoreThreadDispatcher>
                 // Stable order for tests
                 Box::new(blocks_by_authority.into_iter())
             } else {
-                let mut vec: Vec<_> = blocks_by_authority.into_iter().collect();
+                let excluded_authorities = last_failure_by_peer.get_excluded_authorities();
+                // Exclude authorities with latest recorded failures
+                let mut vec: Vec<_> = blocks_by_authority
+                    .into_iter()
+                    .filter(|(authority, _)| !excluded_authorities.contains(authority))
+                    .collect();
```
Comment (VorobyevIlya) [inline crates/starfish/core/src/transactions_synchronizer.rs]: Do I understand correctly that we exclude 2/3 authorities with latest failures, and then filter out all these authorities from blocks_by_authority? 
But in blocks_by_authority we don't have all authorities, is it possible that we will exclude too many? Maybe it is better to exclude 2/3 of authorities from blocks_by_authority?

**Review by piotrm50 — APPROVED** [review]

File: crates/starfish/core/src/transactions_synchronizer.rs (hunk 1 above)
Comment (NaitsabesMue) [reply crates/starfish/core/src/transactions_synchronizer.rs]: Also if we filter out 2/3, and keep only 1/3, this 1/3 might just be those who have not the transactions. If we filter out only 1/3, we have at least 1/3 that have the transactions.

**Review by NaitsabesMue — CHANGES_REQUESTED** [review]

File: crates/starfish/core/src/transactions_synchronizer.rs (hunk 1 above)
Comment (NaitsabesMue) [reply crates/starfish/core/src/transactions_synchronizer.rs]: More general, if you exclude 2/3 you may end with only one honest. Since we do not weight by stake, the risk increases.

**Comment by NaitsabesMue** [comment]
The name of the PR is not optimal as main contribution is about "memory tracking" when the transaction fetch has failed.

File: crates/starfish/core/src/transactions_synchronizer.rs (hunk 1 above)
Comment (polinikita) [reply crates/starfish/core/src/transactions_synchronizer.rs]: I tried some scenarios when 1/3 was no sufficient for good effect. But in general I agree with arguments. For safety reasons, I changed to return less than 1/3 by stake so the intersection is more than 1/3 by stake.

**Review by VorobyevIlya — APPROVED** [review]

**Review by NaitsabesMue — APPROVED** [review]
