### PR TITLE
fix(consensus): TODOs in `block_header` module

### LINKED ISSUE #8222: `block_header` TODOs
Go over the teams TODOS in the `block_header` module.

### PR DESCRIPTION
**Pull request by filipdulic**
# Description of change

This PR removes superfluous TODOs for which issues have been created, or the TODOs themselves have since been resolved.
## Links to any relevant issues

fixes #8222 

## How the change has been tested

- [ ] Basic tests (linting, compilation, formatting, unit/integration tests)
- [ ] Patch-specific tests (correctness, functionality coverage)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### Release Notes

- [ ] Protocol:
- [ ] Nodes (Validators and Full nodes):
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [ ] CLI:
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: crates/starfish/core/src/block_header.rs [hunk 1]
```diff
@@ -90,15 +90,12 @@ pub struct BlockHeaderV1 {
     epoch: Epoch,
     round: Round,
     author: AuthorityIndex,
-    // TODO: during verification ensure that timestamp_ms >= ancestors.timestamp
```
Comment (filipdulic) [inline crates/starfish/core/src/block_header.rs:93]: removed because this is done in the `block_manager` verification step before the `DagState` write

File: crates/starfish/core/src/block_header.rs [hunk 2]
```diff
@@ -90,15 +90,12 @@ pub struct BlockHeaderV1 {
...
     timestamp_ms: BlockTimestampMs,
     // ancestors are BlockRefs such that there are at least 2f+1 BlockRefs (by stake) from the
     // previous round
     ancestors: Vec<BlockRef>,
     // acknowledgments are BlockRefs for blocks for which a validator acknowledges data
     // availability of transactions
-    // TODO: we should compress it together with ancestors to
```
Comment (filipdulic) [inline crates/starfish/core/src/block_header.rs:100]: #8151 issue created to discuss this TODO.

File: crates/starfish/core/src/block_header.rs [hunk 3]
```diff
@@ -272,7 +269,6 @@ impl BlockRef {
     }
 }
 
-// TODO: re-evaluate formats for production debugging.
```
Comment (filipdulic) [inline crates/starfish/core/src/block_header.rs:275]: #8152 issue created to discuss this TODO as well as the following few Display and Debug related TODOs

File: crates/starfish/core/src/block_header.rs [hunk 4]
```diff
@@ -877,14 +865,12 @@ impl TryFrom<SerializedHeaderAndTransactions> for VerifiedBlock {
         let transactions: Vec<Transaction> =
             bcs::from_bytes(&serialized_block.serialized_transactions)
                 .map_err(ConsensusError::MalformedTransactions)?;
-        // TODO: do we need to check the signature here?
```
Comment (filipdulic) [inline crates/starfish/core/src/block_header.rs:880]: #8221 issue was created to disuses weather the signature and transaction commitment need to be checked at all.

File: crates/starfish/core/src/block_header.rs [hunk 5]
```diff
@@ -355,11 +351,6 @@ impl AsRef<[u8]> for BlockHeaderDigest {
     }
 }
 
-// TODO: we might need to join TransactionDigest with BlockDigest since we use
```
Comment (filipdulic) [inline crates/starfish/core/src/block_header.rs:358]: #8220 issue created to track this TODO.

**Review by piotrm50 — APPROVED** [review]
