### PR TITLE
fix(wallet): Make `TransactionCard` use non-iota coin type & amount if available

### LINKED ISSUE #5784: [IOTA wallet] Bad coin's name in "Activity" tab
## Bug description

I succesfully minted and transfered a coin named "POSTI" (value=3), with CoinManager
In the wallet, activity tab displays an incorrect name : "Received 3 IOTA"
However, when i click on the transaction, the detail window displays the correct name "POSTI" 
See captures.

## Version

Iota 0.9.2-rc
Wallet 0.4.0 chrome extension

Image

Image

### PR DESCRIPTION
**Pull request by marc2332**
Closes https://github.com/iotaledger/iota/issues/5784

### CODE REVIEW

**Review by evavirseda — APPROVED** [review]
image

**Review by evavirseda — CHANGES_REQUESTED** [review]
I just saw that the same situation is present on the dashboard, so we need to fix it as well :pray: 

image
Screenshot from 2025-03-13 10-45-11

File: apps/wallet/src/ui/app/components/transactions-card/index.tsx [hunk 1]
```diff
@@ -46,22 +47,29 @@ export function TransactionCard({ txn, address }: TransactionCardProps) {
...
 
-    function getAmount(tx: IotaTransactionBlockResponse) {
-        if ((isTimelockedStaking || isTimelockedUnstaking) && tx.events) {
-            return getTransactionAmountForTimelocked(
-                tx.events,
+    const [balance, coinType] = (() => {
+        // Use any non-iota coin type if found, otherwise simply use IOTA
+        const nonIotaCoinType = balanceChanges?.[address]
+            .map((change) => change.coinType)
+            .find((coinType) => coinType !== IOTA_TYPE_ARG);
```
Comment (panteleymonchuk) [inline apps/wallet/src/ui/app/components/transactions-card/index.tsx]:
```suggestion
        // Use any non-iota coin type if found, otherwise simply use IOTA
        const nonIotaCoinType = balanceChanges?.[address]
            ?.map((change) => change.coinType)
            .find((coinType) => coinType !== IOTA_TYPE_ARG);
```

balanceChanges?.[address] might be undefined as well

File: apps/wallet/src/ui/app/components/transactions-card/index.tsx [hunk 2]
```diff
@@ -46,22 +47,29 @@ export function TransactionCard({ txn, address }: TransactionCardProps) {
...
+                txn.events,
                 isTimelockedStaking,
                 isTimelockedUnstaking,
             );
+            return [balance, IOTA_TYPE_ARG];
         } else {
-            return address && balanceChanges?.[address]?.[0]?.amount
-                ? Math.abs(Number(balanceChanges?.[address]?.[0]?.amount))
-                : 0;
+            const balanceChange = balanceChanges?.[address]?.find((change) => {
```
Comment (panteleymonchuk) [inline apps/wallet/src/ui/app/components/transactions-card/index.tsx:71]:
```suggestion
            const nonIotaCoinType = balanceChanges?.[address]
              ?.map((change) => change.coinType)
              .find((coinType) => coinType !== IOTA_TYPE_ARG);
              const coinType = nonIotaCoinType ?? IOTA_TYPE_ARG;
            const balanceChange = balanceChanges?.[address]?.find((change) => {
```

we use `nonIotaCoinType` `coinType`  values only under `else` condition. I'd move them

**Review by panteleymonchuk — CHANGES_REQUESTED** [review]

**Review by msarcev — APPROVED** [review]

**Comment by msarcev** [comment]
LGTM (after we apply suggested changes) and seams to work :P

**Review by evavirseda — APPROVED** [review]

File: apps/wallet-dashboard/components/transactions/TransactionTile.tsx [hunk 3]
```diff
@@ -51,22 +52,29 @@ export function TransactionTile({ transaction }: TransactionTileProps): JSX.Elem
 
     const balanceChanges = transactionSummary?.balanceChanges;
 
-    function getAmount(tx: ExtendedTransaction) {
-        if ((isTimelockedStaking || isTimelockedUnstaking) && tx.raw.events) {
-            return getTransactionAmountForTimelocked(
-                tx.raw.events,
+    const [balance, coinType] = (() => {
+        if ((isTimelockedStaking || isTimelockedUnstaking) && transaction.raw.events) {
```
Comment (begonaalvarezd) [inline apps/wallet-dashboard/components/transactions/TransactionTile.tsx:57]: If the tx if of type migration we should also always render the iota balance balance

File: apps/wallet/src/ui/app/components/transactions-card/index.tsx [hunk 4]
```diff
@@ -46,22 +47,29 @@ export function TransactionCard({ txn, address }: TransactionCardProps) {
     // Get the balance changes for the transaction and the amount
     const balanceChanges = getBalanceChangeSummary(txn, recognizedPackagesList);
 
-    function getAmount(tx: IotaTransactionBlockResponse) {
-        if ((isTimelockedStaking || isTimelockedUnstaking) && tx.events) {
-            return getTransactionAmountForTimelocked(
-                tx.events,
+    const [balance, coinType] = (() => {
+        if ((isTimelockedStaking || isTimelockedUnstaking) && txn.events) {
```
Comment (begonaalvarezd) [inline apps/wallet/src/ui/app/components/transactions-card/index.tsx:52]: If the tx if of type migration we should also always render the iota balance balance

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — APPROVED** [review]

**Review by panteleymonchuk — APPROVED** [review]
