### PR TITLE
fix nightly simtests

### LINKED ISSUE #4909: Fix nightly tests: "MSIM_SEED" should always be the same
Right now the `basic_read_cmd_snapshot_tests` fails because the `MSIM_TEST_SEED` in the nightly CI is set to the current date, resulting in different snapshots.

### PR DESCRIPTION
**Pull request by nmrshll**
# Description of change

Previously, we were using the current date as a simtest seed in nightly CI, which means nightly tests would often fail.

Fix nightly tests: previously, the current date was used as a seed for simtest pseudo-randomness
- this made one test fail, which was relying on static objects, but actual objects were generated pseudo-randomly each time

Other additions:
- make it possible to override the timeout for simtests locally (previous hardcoded value becomes default in CI)
- make it possible to override the SIMTEST_LOGS_DIR

## Links to any relevant issues

Fixes #4909 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Relevant configurations: when running `./scripts/simtest/simtest-run.sh`, you can now pass env vars to override:
- PER_TEST_TIMEOUT_MS: if tests timeout on your machine, override the per test timeout
Docs are as comments at the top of the script.
- SIMTEST_LOGS_DIR: override the default logs directory

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have checked that existing unit tests pass locally with my changes 

## Follow-up issues to create

- [x] fixing env vars (actually passing them) on the last call to `cargo simtest` made some tests fail more often because of non-determinism.
- [ ] Sould we also use non-determinism in CI tests run on each PR ? This doesn't seem to be the case yet, but double-check

### CODE REVIEW

**Review by piotrm50 — APPROVED** [review]

**Comment by DaughterOfMars** [comment]
Why would this make the tests fail, and if it is, why are we changing the seed and not fixing the tests?

**Comment by muXxer** [comment]
> Why would this make the tests fail, and if it is, why are we changing the seed and not fixing the tests?

I fixed the test and reverted the change. Now seed is always random as before.

**Review by muXxer — APPROVED** [review]

File: crates/iota-e2e-tests/tests/snapshot_tests.rs [hunk 1]
```diff
@@ -63,8 +63,11 @@ async fn basic_read_cmd_snapshot_tests() -> Result<(), anyhow::Error> {
         "iota client objects 0x0000000000000000000000000000000000000000000000000000000000000000", /* empty addr */
         "iota client object 0x5",       // valid object
         "iota client object 0x5 --bcs", // valid object BCS
-        "iota client object 0x4d03f39deb5e27a76a568adb591da553688e6df6fb053bc9ac069f2bd9495ae3", /* valid object */
-        "iota client object 0x4d03f39deb5e27a76a568adb591da553688e6df6fb053bc9ac069f2bd9495ae3 --bcs", /* valid object BCS */
+        // Simtest object IDs are not stable so these object IDs may or may not exist currently --
+        // commenting them out for now.
+        // WARNING: Do not uncomment this, because that will break simtests with random MSIM_TEST_SEED!
+        // "iota client object 0x3b5121a0603ef7ab4cb57827fceca17db3338ef2cd76126cc1523b681df27cee", // valid object
+        // "iota client object 0x3b5121a0603ef7ab4cb57827fceca17db3338ef2cd76126cc1523b681df27cee --bcs", // valid object BCS
```
Comment (DaughterOfMars) [inline crates/iota-e2e-tests/tests/snapshot_tests.rs]: I see that sui also hasn't uncommented this yet. Do we have any ideas about how this might be actually done correctly? If not, maybe we should just delete it altogether.

Comment (muXxer) [reply crates/iota-e2e-tests/tests/snapshot_tests.rs]: I left it there so nobody will accidentally add a test that checks an object.

**Review by DaughterOfMars — APPROVED** [review]

File: crates/iota-e2e-tests/tests/snapshot_tests.rs (hunk 1 above)
Comment (nmrshll) [reply crates/iota-e2e-tests/tests/snapshot_tests.rs]: We just talked about this just now on a call with @muXxer, we left it here intentionally so no one has the idea of trying to test this command with static object IDs when the pseudo-random simtests mean these IDs can't be stable
