### PR TITLE
fix(iota-keys): check alias uniqueness in alias update

### LINKED ISSUE #4880: `CLI/Keytool`: When updating an alias make sure the new alias does not exist yet, and error otherwise
Currently it is possible to create the same alias for different addresses.

### PR DESCRIPTION
**Pull request by thibault-martinez**
Fixes https://github.com/iotaledger/iota/issues/4880

It is not supposed to be possible to create different addresses with the same alias, as shown here when using the `client new-address` CLI.
```
thibault@Mac ~/i/iota (develop)> ./target/debug/iota client new-address --alias tibo
Keys saved as Bech32.
╭───────────────────────────────────────────────────────────────────────────────────────────────╮
│ Created new keypair and saved it to keystore.                                                 │
├────────────────┬──────────────────────────────────────────────────────────────────────────────┤
│ alias          │ tibo                                                                         │
│ address        │ 0x77d2fc4949895e3f6c1b3e1cdcde1f873c9ad4436a5962029fc157ee215dfcc3           │
│ keyScheme      │ ed25519                                                                      │
│ recoveryPhrase │ off toss pass pepper nominee pelican clutch taste child tree tomorrow tenant │
╰────────────────┴──────────────────────────────────────────────────────────────────────────────╯

thibault@Mac ~/i/iota (develop)> ./target/debug/iota client new-address --alias tibo
Alias tibo already exists. Please choose another alias.
```

However, it is possible to update an alias in such a way to create duplicates.

# Before

```
thibault@Mac ~/i/iota (develop) [1]> ./target/debug/iota client new-address
Keys saved as Bech32.
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│ Created new keypair and saved it to keystore.                                               │
├────────────────┬────────────────────────────────────────────────────────────────────────────┤
│ alias          │ strange-jasper                                                             │
│ address        │ 0xd06b0069cf83e586eee980fb800a6f55d56450eaa8f2b4b0663bd7657fc415c5         │
│ keyScheme      │ ed25519                                                                    │
│ recoveryPhrase │ lab just slide over census wheat fantasy scorpion attack surround draw fox │
╰────────────────┴────────────────────────────────────────────────────────────────────────────╯

thibault@Mac ~/i/iota (develop)> ./target/debug/iota keytool update-alias strange-jasper tibo
Old alias strange-jasper was updated to tibo

thibault@Mac ~/i/iota (develop)> ./target/debug/iota keytool list
╭────────────────────────────────────────────────────────────────────────────────────────────╮
│ ╭─────────────────┬──────────────────────────────────────────────────────────────────────╮ │
│ │ alias           │  competent-plasma                                                    │ │
│ │ iotaAddress     │  0x1775ea9f3322548fe31e71aa01a41b496adaa29a5f6d94140cab2e91c8d8378d  │ │
│ │ publicBase64Key │  jbXCqXdAUHdgV7zi44SGwQ4MR2b9eufKZvIs1PJ943k=                        │ │
│ │ keyScheme       │  ed25519                                                             │ │
│ │ flag            │  0                                                                   │ │
│ │ peerId          │  8db5c2a9774050776057bce2e38486c10e0c4766fd7ae7ca66f22cd4f27de379    │ │
│ ╰─────────────────┴──────────────────────────────────────────────────────────────────────╯ │
│ ╭─────────────────┬──────────────────────────────────────────────────────────────────────╮ │
│ │ alias           │  tibo                                                                │ │
│ │ iotaAddress     │  0x77d2fc4949895e3f6c1b3e1cdcde1f873c9ad4436a5962029fc157ee215dfcc3  │ │
│ │ publicBase64Key │  JHkDOLTf2q0seprIYHQ8puv0tfzW3g0NuFkBhLPTUP0=                        │ │
│ │ keyScheme       │  ed25519                                                             │ │
│ │ flag            │  0                                                                   │ │
│ │ peerId          │  24790338b4dfdaad2c7a9ac860743ca6ebf4b5fcd6de0d0db8590184b3d350fd    │ │
│ ╰─────────────────┴──────────────────────────────────────────────────────────────────────╯ │
│ ╭─────────────────┬──────────────────────────────────────────────────────────────────────╮ │
│ │ alias           │  tibo                                                                │ │
│ │ iotaAddress     │  0xd06b0069cf83e586eee980fb800a6f55d56450eaa8f2b4b0663bd7657fc415c5  │ │
│ │ publicBase64Key │  NApvsk0asdz+WWu99dqhGj965tzBBh255E1O2FJF/CI=                        │ │
│ │ keyScheme       │  ed25519                                                             │ │
│ │ flag            │  0                                                                   │ │
│ │ peerId          │  340a6fb24d1ab1dcfe596bbdf5daa11a3f7ae6dcc1061db9e44d4ed85245fc22    │ │
│ ╰─────────────────┴──────────────────────────────────────────────────────────────────────╯ │
╰────────────────────────────────────────────────────────────────────────────────────────────╯
thibault@Mac ~/i/iota (develop)> 
```

# After

```
thibault@Mac ~/i/iota (develop)> ./target/debug/iota client new-address --alias tibo
Keys saved as Bech32.
╭──────────────────────────────────────────────────────────────────────────────────────────╮
│ Created new keypair and saved it to keystore.                                            │
├────────────────┬─────────────────────────────────────────────────────────────────────────┤
│ alias          │ tibo                                                                    │
│ address        │ 0xa609e45c4932c2d017acbe6b89ebb7cb9ff2003dd4f98bad5884072c5ec1a6bc      │
│ keyScheme      │ ed25519                                                                 │
│ recoveryPhrase │ west try scout shoe tornado steel width age favorite uniform near float │
╰────────────────┴─────────────────────────────────────────────────────────────────────────╯

thibault@Mac ~/i/iota (develop)> ./target/debug/iota client new-address
Keys saved as Bech32.
╭──────────────────────────────────────────────────────────────────────────────────────╮
│ Created new keypair and saved it to keystore.                                        │
├────────────────┬─────────────────────────────────────────────────────────────────────┤
│ alias          │ ecstatic-obsidian                                                   │
│ address        │ 0xb46a5ce8a44d9f93e8bf82b4cf06e4aed0ce7f8e696f1f812d8466f43d314ce7  │
│ keyScheme      │ ed25519                                                             │
│ recoveryPhrase │ hammer setup artwork trim top echo photo run render onion rural day │
╰────────────────┴─────────────────────────────────────────────────────────────────────╯

thibault@Mac ~/i/iota (develop)> ./target/debug/iota keytool update-alias ecstatic-obsidian tibo
Alias tibo already exists. Please choose another alias.
```

### CODE REVIEW

**Review by DaughterOfMars — APPROVED** [review]

**Comment by thibault-martinez** [comment]
I will add a test.

File: crates/iota-keys/tests/tests.rs [hunk 1]
```diff
@@ -163,6 +163,21 @@ fn update_alias_test() {
...
+            SignatureScheme::ED25519,
+            Some("my_alias_test".to_string()),
+            None,
+            None,
+        )
+        .unwrap();
+    assert!(
+        keystore
+            .update_alias("my_alias_test", Some(&update))
+            .is_err()
```
Comment (Alex6323) [inline crates/iota-keys/tests/tests.rs:179]: Can't we match on the exact error? Is there a `DuplicateAliasError` or smth? That'll make fixing the test - should it ever fail - easier I think.

Comment (thibault-martinez) [reply crates/iota-keys/tests/tests.rs:179]: No, `bail!` is used so there is no proper typing, and I'd rather not match on the string itself

**Review by Alex6323 — APPROVED** [review]
