### PR TITLE
fix(iota-core): Fix differences between StarfishConsensusHandler and MysticetiConsensusHandler

### LINKED ISSUE #9484: Check that Starfish and Mysticeti adapter/handler have the same functionality
Make sure that iota-core components that are creating and handling consensus instances handle them in the same manner. Both consensus have the same interfaces so they should be handled in the same way.

### PR DESCRIPTION
**Pull request by piotrm50**
# Description of change

Fix differences between Starfish and Mysticeti in handling of previously processed commits at startup by introducing a replay mechanism. Adjust `StarfishConsensusHandler` to manage commit ranges effectively and log replay progress.

## Links to any relevant issues

Fixes #9484 

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [x] Patch-specific tests (correctness, functionality coverage)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota-core/src/unit_tests/mysticeti_manager_tests.rs [hunk 1]
```diff
@@ -137,3 +143,91 @@ async fn test_mysticeti_manager() {
...
+
+    // THEN verify that the highest handled commit is only updated for newer commits
+    // (8-10) Commits 1-7 should have been processed as prior commits and
+    // not update the monitor
+    let highest_handled = commit_consumer_monitor.highest_handled_commit();
+    assert_eq!(
+        highest_handled, 10,
+        "Expected highest handled commit to be 10, got {}",
+        highest_handled
+    );
```
Comment (muXxer) [inline crates/iota-core/src/unit_tests/mysticeti_manager_tests.rs:232]: I'm sorry, but I don't understand that part, neither in mysticeti nor in starfish.
All 10 commits are equally created, so where is the difference at all? Only because we set the `last_processed_commit_at_startup` to 7?
Is this test really checking what we want? At least the last assert comment is also weird, because the assert only checks for highest handled = 10.
Do we even check they are correctly replayed?

Comment (piotrm50) [reply crates/iota-core/src/unit_tests/mysticeti_manager_tests.rs:232]: I implemented those tests with wrong assumptions in my mind. They are in reality not needed, so I removed them.

**Review by muXxer — APPROVED** [review]

**Review by polinikita — APPROVED** [review]
