### PR TITLE
fix(tooling-wallet): Fix staking with ledger

### LINKED ISSUE #4222: Fix broken ledger staking
Recently in develop we broke ledger staking, we have to fix it

### PR DESCRIPTION
**Pull request by msarcev**
# Description of change

Closes https://github.com/iotaledger/iota/issues/4222

### CODE REVIEW

File: apps/wallet/src/ui/app/SpeculosHttpTransport.tsx [hunk 1]
```diff
@@ -7,7 +7,7 @@ import Transport from '@ledgerhq/hw-transport';
 import { log } from '@ledgerhq/logs';
 import { Subject } from 'rxjs';
 
-const SPECULOS_API_DEFAULT_PORT = '5000';
+const SPECULOS_API_DEFAULT_PORT = '5001';
```
Comment (begonaalvarezd) [inline apps/wallet/src/ui/app/SpeculosHttpTransport.tsx]: the default port in speculos is 5000 i wouldnt change this

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

File: apps/wallet/src/ui/app/SpeculosHttpTransport.tsx (hunk 1 above)
Comment (begonaalvarezd) [reply apps/wallet/src/ui/app/SpeculosHttpTransport.tsx]: actually...let me think about this because if 5000 is always occupied by the network we should probably change to 5001

**Review by begonaalvarezd — APPROVED** [review]

**Review by evavirseda — APPROVED** [review]
