### PR TITLE
fix(wallet): empty info box on shorter mnemonic

### LINKED ISSUE #3915: Empty info box on shorter mnemonic
if you enter a shorter mnemonic, an empty error box shows up with 0 info on it
Image

### PR DESCRIPTION
**Pull request by evavirseda**
# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/3915

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by marc2332 — CHANGES_REQUESTED** [review]
It seems like now it won't render an error if you have a wrong mnemonic

image

File: apps/wallet/src/ui/app/components/accounts/ImportRecoveryPhraseForm.tsx [hunk 1]
```diff
@@ -125,14 +125,15 @@ export function ImportRecoveryPhraseForm({
...
             <div className="sticky bottom-0 left-0 flex flex-col gap-2.5 bg-neutral-100 pt-sm dark:bg-neutral-6">
-                {touchedFields.recoveryPhrase && errors.recoveryPhrase && (
-                    <InfoBox
-                        type={InfoBoxType.Default}
-                        supportingText={errors.recoveryPhrase.message}
-                        icon={<Exclamation />}
-                        style={InfoBoxStyle.Elevated}
-                    />
-                )}
+                {errors?.recoveryPhrase?.message &&
```
Comment (panteleymonchuk) [inline apps/wallet/src/ui/app/components/accounts/ImportRecoveryPhraseForm.tsx:128]: Do you see error if `validateMnemonics` returns false?

Because for me `errors?.recoveryPhrase?.message` always undefined

Comment (panteleymonchuk) [reply apps/wallet/src/ui/app/components/accounts/ImportRecoveryPhraseForm.tsx:128]: upd: It doen’t work if insert mnemonic manually


https://github.com/user-attachments/assets/b88920eb-7ce3-4deb-afad-dd5ad2417caa

**Review by panteleymonchuk — APPROVED** [review]

File: apps/wallet/src/ui/app/components/accounts/ImportRecoveryPhraseForm.tsx [hunk 2]
```diff
@@ -125,14 +125,15 @@ export function ImportRecoveryPhraseForm({
...
+                    !touchedFields.recoveryPhrase?.every(Boolean) && (
+                        <InfoBox
+                            type={InfoBoxType.Error}
+                            supportingText={errors?.recoveryPhrase?.message}
```
Comment (begonaalvarezd) [inline apps/wallet/src/ui/app/components/accounts/ImportRecoveryPhraseForm.tsx:132]: Lets update https://github.com/iotaledger/iota/blob/921db2eb6e52b9c26bba5b4f0453a3b9683ec0f3/apps/wallet/src/ui/app/components/accounts/ImportRecoveryPhraseForm.tsx#L31 to `Mnenonic is invalid` so the message is in sync with what how the app calls it

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by marc2332 — APPROVED** [review]

**Review by begonaalvarezd — APPROVED** [review]
