### PR TITLE
fix(indexer): Handle errors for task common_handler.start_transform_and_load

### LINKED ISSUE #5780: Handle errors in spawn_monitored_task!(common_handler.start_transform_and_load(receiver, cancel));
> I'm a bit worried about this task as it does not handle errors, if any error will occur the task will exit but the indexer will potentially still run, having some unexpected effects.
> ```rust
> spawn_monitored_task!(common_handler.start_transform_and_load(receiver, cancel));
> ```

_Originally posted by @sergiupopescu199 in https://github.com/iotaledger/iota/pull/5777#pullrequestreview-2660983225_

To be investigated and fixed if needed, considering comments:
 - https://github.com/iotaledger/iota/pull/5777#discussion_r1981357074
 - https://github.com/iotaledger/iota/pull/5777#discussion_r1981438509

### PR DESCRIPTION
**Pull request by tomxey**
# Description of change

Handle errors for task common_handler.start_transform_and_load

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/5780

## How the change has been tested

I've ran custom checks, to verify that on failure graceful shutdown of the other branch works.

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [ ] Patch-specific tests (correctness, functionality coverage)

### Infrastructure QA (only required for crates that are maintained by @iotaledger/infrastructure)

- [ ] Synchronization of the indexer from genesis for a network including migration objects.
- [ ] Restart of indexer synchronization locally without resetting the database.
- [ ] Restart of indexer synchronization on a production-like database.
- [ ] Deployment of services using Docker.
- [ ] Verification of API backward compatibility.

### CODE REVIEW

**Review by sergiupopescu199 — APPROVED** [review]

File: crates/iota-indexer/src/indexer.rs [hunk 1]
```diff
@@ -140,8 +141,26 @@ impl Indexer {
...
-            )
-            .await?;
+            ),
+        );
+
+        tokio::select! {
+            executor_result = &mut executor_handle => {
+                // Executor completed first - cancel snapshot task and check result
+                cancel.cancel();
+                let snapshot_result = object_snapshot_task_handle.await;
```
Comment (kodemartin) [inline crates/iota-indexer/src/indexer.rs]: Shouldn't we [abort](https://docs.rs/tokio/latest/tokio/task/struct.JoinHandle.html#method.abort) here? 

Is there a guarantee that executor completion guarantees snapshot completion so that to await? Otherwise this might hang.

File: crates/iota-indexer/src/indexer.rs [hunk 2]
```diff
@@ -140,8 +141,26 @@ impl Indexer {
...
+                executor_result.context("failed to join data ingestion executor")?.context("data ingestion executor failed")?;
+                snapshot_result.context("failed to join snapshot task during shutdown")?.context("snapshot task failed during shutdown")?;
+            },
+            snapshot_result = &mut object_snapshot_task_handle => {
+                // Snapshot task completed first - cancel executor and check result
+                cancel.cancel();
+                let executor_result = executor_handle.await;
```
Comment (kodemartin) [inline crates/iota-indexer/src/indexer.rs]: Same here: shouldn't we abort instead?

File: crates/iota-indexer/src/indexer.rs (hunk 1 above)
Comment (tomxey) [reply crates/iota-indexer/src/indexer.rs]: Proceeded with a timeout: a37b2cba6eb75f43b290f379416b77f28e168a3c

File: crates/iota-indexer/src/indexer.rs (hunk 2 above)
Comment (tomxey) [reply crates/iota-indexer/src/indexer.rs]: Proceeded with a timeout: a37b2cba6eb75f43b290f379416b77f28e168a3c

File: crates/iota-indexer/src/indexer.rs [hunk 3]
```diff
@@ -15,6 +15,9 @@ use prometheus::Registry;
 use tokio_util::sync::CancellationToken;
 use tracing::info;
 
+// Timeout for waiting for tasks to shutdown gracefully after cancellation
```
Comment (sergiupopescu199) [inline crates/iota-indexer/src/indexer.rs]:
```suggestion
/// Timeout for waiting for tasks to shutdown gracefully after cancellation
```

Comment (tomxey) [reply crates/iota-indexer/src/indexer.rs]: fixed

**Review by kodemartin — APPROVED** [review]
lgtm
