### PR TITLE
fix(consensus): reading own blocks returns only fully available blocks from DAG state

### LINKED ISSUE #8874: starfish: make read method for owned cached blocks soft without panicking
We observed a panic during epoch change when establishing connections. That happened due to non-atomic write to the dag_state
`iota  | 2025-10-13T19:23:32.134456Z  INFO iota_core::consensus_manager: Starting up consensus for epoch 2482 & protocol version ProtocolVersion(14) is complete - took 0.012248099 seconds
iota  | 2025-10-13T19:23:32.134459Z  INFO iota_node: Spawning checkpoint service
iota  | 2025-10-13T19:23:32.134464Z  INFO iota_core::checkpoints: Waiting for checkpoints to be rebuilt, previously built seq: 6030452, currently built seq: 6030452
iota  | 2025-10-13T19:23:32.134465Z  INFO iota_core::checkpoints: Checkpoint rebuild complete
iota  | 2025-10-13T19:23:32.134468Z  INFO iota_core::checkpoints: Starting CheckpointBuilder
iota  | 2025-10-13T19:23:32.134490Z  INFO iota_core::checkpoints: Starting CheckpointAggregator
iota  | 2025-10-13T19:23:32.134495Z  INFO iota_node: Reconfiguration finished
iota  | 2025-10-13T19:23:32.135343Z  INFO iota_node: Creating checkpoint executor for epoch 2482
iota  | 2025-10-13T19:23:32.135574Z  INFO starfish_core::commit_syncer: Checking to schedule fetches: synced_commit_index=0, highest_handled_index=0, highest_scheduled_index=0, quorum_commit_index=0, unhandled_commits_threshold=3200
iota  | 2025-10-13T19:23:32.140966Z  INFO iota_node: submitting capabilities to consensus transaction=ConsensusTransaction { tracking_id: [91, 10, 121, 196, 182, 40, 102, 98], kind: CapabilityNotificationV1(AuthorityCapabilities { authority: k#a5c2edfe.., generation: 1760383412140, supported_protocol_versions: SupportedProtocolVersionsWithHashes { versions: [(ProtocolVersion(14), 4HzqGWA3zfGdfqciaVChXcfmtMHHK7Ri7C8YJxqBThFw)] }, available_system_packages: [(0x0000000000000000000000000000000000000000000000000000000000000001, SequenceNumber(1), o#8Pz9cv34A3xxus8GxAFEMufmghi3SDXx1mR4df1Vhzyh), (0x0000000000000000000000000000000000000000000000000000000000000002, SequenceNumber(2), o#2rK2JyVQ9sa4HfoBRsGbGWeNJQM5HsMY26QbcBkMmHJm), (0x0000000000000000000000000000000000000000000000000000000000000003, SequenceNumber(2), o#5nTX4pPg6syVcyCVtA2MsDYcdaycTxY2Ptw2FidD9wcd), (0x000000000000000000000000000000000000000000000000000000000000107a, SequenceNumber(2), o#Hu7wJw8YywzeqrvqVdaXgVMFjjmbxMP2hk5mp79o3nYr)] }) }
iota  | 2025-10-13T19:23:32.141008Z  INFO run_epoch{epoch=2482}: iota_core::checkpoints::checkpoint_executor: CheckpointExecutor::run_epoch run_with_range=None
iota  | 2025-10-13T19:23:32.225464Z  INFO starfish_core::core: A quorum of block subscribers exists: true
iota  |
iota  | thread 'iota-node-runtime' panicked at crates/starfish/core/src/dag_state.rs:819:36:
iota  | Missing transactions for B1([2],TWCj)
iota  | 2025-10-13T19:23:32.225794Z ERROR telemetry_subscribers: panicked at crates/starfish/core/src/dag_state.rs:819:36:
iota  | Missing transactions for B1([2],TWCj) panic.file="crates/starfish/core/src/dag_state.rs" panic.line=819 panic.column=36`

### PR DESCRIPTION
**Pull request by polinikita**
# Description of change

Due to the non-atomic nature of storing transactions and headers in the DAG state, we could have an own block header, but no transactions for that header leading to the panic when calling method `get_own_cached_blocks`. In particular, that is used after getting a subscription for streaming own blocks.

We change the method `get_own_cached_blocks` to return only blocks which have both headers and transactions and don't return those with missing parts (e.g. transactions).

## Links to any relevant issues

Fixes #8874

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/starfish/core/src/dag_state.rs [hunk 1]
```diff
@@ -800,24 +803,24 @@ impl DagState {
...
-            let transactions = self
-                .recent_transactions
-                .get(block_ref)
-                .unwrap_or_else(|| panic!("Missing transactions for {block_ref:?}"));
-            blocks.push(VerifiedBlock::new(header.clone(), transactions.clone()));
+            let header_opt = self.recent_block_headers.get(block_ref);
+            let transactions_opt = self.recent_transactions.get(block_ref);
+            if let (Some(header), Some(transactions)) = (header_opt, transactions_opt) {
+                blocks.push(VerifiedBlock::new(header.clone(), transactions.clone()));
+                continue;
```
Comment (piotrm50) [inline crates/starfish/core/src/dag_state.rs]: `continue` not needed if using `else` 
```suggestion
```

**Review by piotrm50 — APPROVED** [review]

**Review by filipdulic — APPROVED** [review]
