### PR TITLE
fix(wallet): keep updating countdown message and disable 'unlock' button

### LINKED ISSUE #6684: Improve locked account UX
if the account is temp locked, we could just disable the input and render the error always

Image
Image
Image

### PR DESCRIPTION
**Pull request by KeitoTadashi**
## Links to any relevant issues

fixes #6684

### CODE REVIEW

File: apps/wallet/src/shared/accounts.ts [hunk 1]
```diff
@@ -32,12 +32,15 @@ export interface AccountFromFinder {
 }
 
 export class AccountTooManyAttemptsError extends Error {
-    constructor(public remainingTime: number) {
+    public remainingTime: number;
+
+    constructor(remainingTime: number) {
```
Comment (marc2332) [inline apps/wallet/src/shared/accounts.ts]: The previous code was also correct btw

Comment (marc2332) [reply apps/wallet/src/shared/accounts.ts]: I see now it was eslint that complained about it :(

Comment (KeitoTadashi) [reply apps/wallet/src/shared/accounts.ts]: :laughing:

**Review by evavirseda — DISMISSED** [review]

**Review by panteleymonchuk — DISMISSED** [review]

File: apps/wallet/src/ui/app/components/accounts/PasswordInputDialog.tsx [hunk 2]
```diff
@@ -56,6 +57,28 @@ export function PasswordModalDialog({
...
+    // Clear the interval and error if the dialog closed but not unmounted
+    useEffect(() => {
+        if (!open && countdownError?.interval) {
+            clearInterval(countdownError.interval);
+            setCountdownError(null);
+        }
+    }, [open]);
+
+    // Clear the interval if the dialog unmounted
+    useEffect(() => {
```
Comment (msarcev) [inline apps/wallet/src/ui/app/components/accounts/PasswordInputDialog.tsx:70]: These two can't be merge into one `useEffect` ?
Like if you add the return to the first `useEffect` won't it just run when the component unmounts ?

File: apps/wallet/src/background/accounts/index.ts [hunk 3]
```diff
@@ -300,14 +300,21 @@ export async function accountsHandleUIMessage(msg: Message, uiConnection: UiConn
         return true;
     }
     if (isMethodPayload(payload, 'getLockedState')) {
-        const { failedAttempts, lastFailedAttemptTime, isLockedOut, lockTimeMs } =
-            await getLockedState();
+        let remainingTime = 0;
+        const WALLET_LOCK_DURATION_IN_MS = 60 * MILLISECONDS_PER_SECOND;
```
Comment (marc2332) [inline apps/wallet/src/background/accounts/index.ts]: we should move this constant (is also in other functions) to another place so we can reuse it instead of duplicating it :D

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by msarcev — APPROVED** [review]

**Review by marc2332 — APPROVED** [review]
