### PR TITLE
feat(evm-bridge): Fix metamask version used in bridge tests to `12.20.0`

### LINKED ISSUE #7749: Add specified MetaMask version for EVM bridge test suite
Add a way to specify the version of MetaMask that will be used in the EVM bridge tests.

### PR DESCRIPTION
**Pull request by brancoder**
# Description of change

* Fixes metamask version used in evm-bridge e2e tests (`12.20.0`)
* Also adds retries and debug logs to `addL1FundsThroughBridgeUI` function

resolves #7749

### CODE REVIEW

File: apps/evm-bridge/tests/utils/utils.ts [hunk 1]
```diff
@@ -187,9 +187,60 @@ export async function addNetworkToMetaMask(l2WalletPage: Page) {
 }
 
 export async function addL1FundsThroughBridgeUI(page: Page, browser: BrowserContext) {
```
Comment (msarcev) [inline apps/evm-bridge/tests/utils/utils.ts:189]: Do we need to change this ? Afaik it was working for a while as-is with the older metamask.

**Review by evavirseda — APPROVED** [review]

**Review by msarcev — APPROVED** [review]
