### PR TITLE
Fix get_all_balances returning zero objects count in fullnode

### LINKED ISSUE #4349: [iota-json-rpc]: get_all_balances returns values with zero object count
## Description

As reported by @begonaalvarezd

> when querying balances we noticed that the fullnode sometimes returns a different response when it comes to 0 iota balance
> ```
> curl 'https://api.testnet.iota.cafe/' \
>   -H 'content-type: application/json' \
>   --data-raw '{"jsonrpc":"2.0","id":4,"method":"iotax_getAllBalances","params":["0x9f7130ab87a0db2a03bc3b547ffd248788f5e7bbeabb7cd190fef26fcfcbc1d6"]}' | json_pp
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   312  100   176  100   136    547    422 --:--:-- --:--:-- --:--:--   971
> {
>    "id" : 4,
>    "jsonrpc" : "2.0",
>    "result" : [
>       {
>          "coinObjectCount" : 1,
>          "coinType" : "0xfef1ff8d81dd4586597f775b2be55ed4d8d3c722aa737cdd84298cbba4e06ca5::img_coin::IMG_COIN",
>          "totalBalance" : "0"
>       }
>    ]
> }
> ```
> vs
> ```
> curl 'https://api.testnet.iota.cafe/' \
>   -H 'content-type: application/json' \
>   --data-raw '{"jsonrpc":"2.0","id":4,"method":"iotax_getAllBalances","params":["0x9f7130ab87a0db2a03bc3b547ffd248788f5e7bbeabb7cd190fef26fcfcbc1d6"]}' | json_pp
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   382  100   246  100   136    756    418 --:--:-- --:--:-- --:--:--  1179
> {
>    "id" : 4,
>    "jsonrpc" : "2.0",
>    "result" : [
>       {
>          "coinObjectCount" : 1,
>          "coinType" : "0xfef1ff8d81dd4586597f775b2be55ed4d8d3c722aa737cdd84298cbba4e06ca5::img_coin::IMG_COIN",
>          "totalBalance" : "0"
>       },
>       {
>          "coinObjectCount" : 0,
>          "coinType" : "0x2::iota::IOTA",
>          "totalBalance" : "0"
>       }
>    ]
> }
> ```
> effectively is the same because the object count is 0, but wanted to mention it just in case. The indexer always returns the first one

The expected behaviour would be to filter out `Balance` values with `coinObjectCount = 0`.

### Requirements

- [ ] Investigate under which conditions this happens.
- [ ] Verify that `iota-indexer` does not return such balances under any circumstances.
- [ ] Filter out those balances on the server side in `iota-json-rpc`. If this can happen also in  `iota-indexer` apply the filter there as well.

### PR DESCRIPTION
**Pull request by tomxey**
# Description of change

Implement filtering of balances returned by `get_all_balances` to omit coins with zero objects count.

The most probable root cause of the issue was described here: https://github.com/iotaledger/iota/issues/4349#issuecomment-2595213598

## Links to any relevant issues

fixes #4349

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

`cargo test --package=iota-indexer --profile=simulator --features shared_test_runtime`
`cargo nextest run --package=iota-json-rpc-tests`

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota-storage/src/indexes.rs [hunk 1]
```diff
@@ -1367,6 +1367,15 @@ impl IndexStore {
                 })
             })
             .await
+            .map(|balances_map| {
```
Comment (muXxer) [inline crates/iota-storage/src/indexes.rs]: I'm not sure I understand this part to 100%, but wouldn't that mean we never cache entries with 0 balance, and therefore with every lookup we have expensive DB lookups now?

Comment (tomxey) [reply crates/iota-storage/src/indexes.rs]: The filtering is done at the very end, so it's not affecting the process of reading from and filling the cache.

We are storing the 0 balance entries in cache just like before.

File: crates/iota-storage/src/indexes.rs [hunk 2]
```diff
@@ -1367,6 +1367,15 @@ impl IndexStore {
...
+                Arc::new(
+                    (*balances_map)
+                        .clone()
+                        .into_iter()
+                        .filter(|(_, TotalBalance { num_coins, .. })| *num_coins > 0)
+                        .collect::<HashMap<_, _>>(),
+                )
```
Comment (kodemartin) [inline crates/iota-storage/src/indexes.rs]: Nit: It would save the reallocation, and reconstruction of the map
```suggestion
            .map(|mut balances_map| {
                Arc::make_mut(&mut balances_map)
                    .retain(|_, TotalBalance { num_coins, .. }| *num_coins > 0);
                balances_map
```

**Review by kodemartin — APPROVED** [review]
lgtm :balloon:

**Review by muXxer — APPROVED** [review]

File: crates/iota-storage/src/indexes.rs (hunk 2 above)
Comment (tomxey) [reply crates/iota-storage/src/indexes.rs]: Didn't know about the `make_mut` function. Applied the change. Thanks.
