### PR TITLE
fix(iota-move): update move command to use module labels, generate-struct-layouts fix

### LINKED ISSUE #5249: [iota-move] Update to use module labels
- type: a refactor and 2 fixes
- side effects minor
- the three changes can be implemented together:
  - [feat: update sui-move new to use module labels (#19485) · MystenLabs/sui@5efd2c4](https://github.com/MystenLabs/sui/commit/5efd2c4b32df36983220a8a3ce25bd148a610f47)
  - [CLI generate-struct-layouts fix (#19954) · MystenLabs/sui@7e01df8](https://github.com/MystenLabs/sui/commit/7e01df826d676519cba3c0be4e1c68652adf7df0)
  - [sui-move: drop duplicate `--path` options (#20005) · MystenLabs/sui@1837a5e](https://github.com/MystenLabs/sui/commit/1837a5e366553e51d1f87ff2d034720476ee1b39)

### PR DESCRIPTION
**Pull request by Dkwcs**
# Description of change

Update sui-move new to use module labels. According to [changes](https://github.com/MystenLabs/sui/commit/5efd2c4b32df36983220a8a3ce25bd148a610f47)
CLI generate-struct-layouts fix. According to [changes](https://github.com/MystenLabs/sui/commit/7e01df826d676519cba3c0be4e1c68652adf7df0)
[Changes](https://github.com/MystenLabs/sui/commit/1837a5e366553e51d1f87ff2d034720476ee1b39) were applied already.

## Links to any relevant issues

#5249 .

## Type of change

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)

### CODE REVIEW

File: crates/iota-move/src/build.rs [hunk 1]
```diff
@@ -97,11 +97,13 @@ impl Build {
         if generate_struct_layouts {
             let layout_str = serde_yaml::to_string(&pkg.generate_struct_layouts()).unwrap();
             // store under <package_path>/build/<package_name>/layouts/struct_layouts.yaml
-            let layout_filename = rerooted_path
+            let dir_name = rerooted_path
                 .join("build")
                 .join(pkg.package.compiled_package_info.package_name.as_str())
                 .join(LAYOUTS_DIR)
-                .join(STRUCT_LAYOUTS_FILENAME);
+                .join(LAYOUTS_DIR);
```
Comment (valeriyr) [inline crates/iota-move/src/build.rs:103]: I think this line should be deleted, right? `LAYOUTS_DIR` is doubled in the path.

**Review by valeriyr — CHANGES_REQUESTED** [review]

File: crates/iota-move/src/build.rs (hunk 1 above)
Comment (Dkwcs) [reply crates/iota-move/src/build.rs:103]: Yep, thanks, you’re right

**Review by valeriyr — APPROVED** [review]
LGTM!

**Review by nonast — APPROVED** [review]
LGTM!
