### PR TITLE
cherry pick: (rest-api): Avoid panic in append_info_headers

### LINKED ISSUE #4087: node crash when requesting RESTful API before initial checkpoint sync completes
## Bug description

Requesting any checkpoint related RESTful API (including health, node info, etc.) before the message `Finished syncing and executing checkpoint 0` appears in the log will cause the node to crash.

In our scenario, we start the indexer and the IOTA node in a single docker compose setup. The indexer repeatedly sends requests to the IOTA node endpoint `/checkpoints/0/full`, which results in the IOTA node crashing. 

Additionally, we use `/api/v1/health` to monitor the IOTA node docker container health status, but this also causes the IOTA node to crash.

## Errors

```
iota  | thread 'iota-node-runtime' panicked at crates/iota-rest-api/src/response.rs:133:74:
iota  | called `Result::unwrap()` on an `Err` value: Error { inner: Inner { kind: Missing, source: Some("unable to get latest checkpoint") } }
iota  | stack backtrace:
iota  | 2024-11-16T03:23:37.910765Z ERROR telemetry_subscribers: panicked at crates/iota-rest-api/src/response.rs:133:74:
iota  | called `Result::unwrap()` on an `Err` value: Error { inner: Inner { kind: Missing, source: Some("unable to get latest checkpoint") } } panic.file="crates/iota-rest-api/src/response.rs" panic.line=133 panic.column=74
iota  |    0: rust_begin_unwind
iota  |    1: core::panicking::panic_fmt
iota  |    2: core::result::unwrap_failed
iota  |    3: <axum::middleware::map_response::MapResponse<F,S,I,(T1,)> as tower_service::Service<http::request::Request<B>>>::call::{{closure}}
iota  |    4: <axum::middleware::map_response::ResponseFuture as core::future::future::Future>::poll
iota  |    5: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
iota  |    6: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
iota  |    7: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
iota  |    8: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
iota  |    9: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
iota  |   10: <axum::routing::route::RouteFuture<E> as core::future::future::Future>::poll
iota  |   11: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
iota  |   12: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
iota  |   13: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
iota  |   14: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
iota  |   15: <axum::routing::route::RouteFuture<E> as core::future::future::Future>::poll
iota  |   16: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
iota  |   17: <axum::middleware::from_fn::FromFn<F,S,I,(T1,)> as tower_service::Service<http::request::Request<axum_core::body::Body>>>::call::{{closure}}
iota  |   18: <axum::middleware::from_fn::ResponseFuture as core::future::future::Future>::poll
iota  |   19: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
iota  |   20: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
iota  |   21: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
iota  |   22: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
iota  |   23: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
iota  |   24: <axum::routing::route::RouteFuture<E> as core::future::future::Future>::poll
iota  |   25: <hyper_util::service::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
iota  |   26: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
iota  |   27: <hyper::server::conn::http1::UpgradeableConnection<I,S> as core::future::future::Future>::poll
iota  |   28: <hyper_util::server::conn::auto::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
iota  |   29: <axum::serve::Serve<M,S> as core::future::into_future::IntoFuture>::into_future::{{closure}}::{{closure}}
iota  |   30: tokio::runtime::task::core::Core<T,S>::poll
iota  |   31: tokio::runtime::task::harness::Harness<T,S>::poll
iota  |   32: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
iota  |   33: tokio::runtime::scheduler::multi_thread::worker::Context::run
iota  |   34: tokio::runtime::context::scoped::Scoped<T>::set
iota  |   35: tokio::runtime::context::runtime::enter_runtime
iota  |   36: tokio::runtime::scheduler::multi_thread::worker::run
iota  |   37: tokio::runtime::task::core::Core<T,S>::poll
iota  |   38: tokio::runtime::task::harness::Harness<T,S>::poll
iota  |   39: tokio::runtime::blocking::pool::Inner::run
iota  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by jkrvivian**
# Description of change

The REST API might cause the node to panic if `append_info_headers` fails to retrieve the data. This PR cherry picked commit  https://github.com/MystenLabs/sui/commit/f9ac5d5b915ec5e1306581df0673ad398c8b5a39 from upstream.
   

## Links to any relevant issues

Close #4087 

## Type of change

- Bug fix 

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota-rest-api/src/response.rs [hunk 1]
```diff
@@ -130,18 +130,26 @@ pub async fn append_info_headers(
...
 ) -> impl IntoResponse {
-    let latest_checkpoint = state.reader.inner().get_latest_checkpoint().unwrap();
+    let (epoch, sequence_number, timestamp_ms) = match state.reader.inner().get_latest_checkpoint()
+    {
+        Ok(checkpoint) => (
+            checkpoint.epoch(),
+            *checkpoint.sequence_number(),
+            checkpoint.timestamp_ms,
+        ),
+        Err(_) => (0, 0, 0),
```
Comment (samuel-rufi) [inline crates/iota-rest-api/src/response.rs]: Instead of ignoring the error, it might be better to return it from this function. Overriding the error with (0,0,0) doesn't seem good to me, also because it might be an important error from the state reader.

File: crates/iota-rest-api/src/response.rs [hunk 2]
```diff
@@ -126,22 +127,57 @@ where
     }
 }
 
+#[derive(Debug)]
+pub enum HeaderError {
+    InternalServerError(String),
+}
```
Comment (bingyanglin) [inline crates/iota-rest-api/src/response.rs]: I am not very sure whether it is necessary to introduce a new `HeaderError`, or maybe you can just use the [`RestError`](https://github.com/iotaledger/iota/blob/develop/crates/iota-rest-api/src/error.rs#L9-L12 )defined in the `iota-rest-api` crate?

**Comment by semenov-vladyslav** [comment]
It seems that this issue was already fixed in the [upstream](https://github.com/MystenLabs/sui/blob/main/crates/sui-rest-api/src/response.rs#L171). They just ignore the header if the corresponding object is not found instead of failing with internal server error.

**Review by samuel-rufi — APPROVED** [review]

**Review by bingyanglin — APPROVED** [review]
Can consider to merge [upstream](https://github.com/MystenLabs/sui/blob/main/crates/sui-rest-api/src/response.rs#L171) as @semenov-vladyslav mentioned.

**Comment by bingyanglin** [comment]
@alexsporn do you suggest that we use cherry pick to merge [their fix](https://github.com/MystenLabs/sui/pull/19267) in the PR?

**Comment by bingyanglin** [comment]
After the sync call discussion @alexsporn suggested to cherry pick the commit @semenov-vladyslav found in this PR, then we merge it.

**Review by bingyanglin — APPROVED** [review]
Looks correctly cherry picked https://github.com/MystenLabs/sui/pull/19267
