### PR TITLE
fix(explorer): resolve inactive validator metadata

### LINKED ISSUE #6332: Resolve inactive validator metadata in explorer
when a validator is inactive and you visit it in the validator page it doesnt resolve, we should try to fetch it eg https://explorer.rebased.iota.org/validator/0x364ce6276f29c45728ca66685ef4ed0bcee55deb936c2ad63761082efb26b162

We might be able to fetch the inactive validators by looking at the staking pool id and from the pool extract the validator.

### PR DESCRIPTION
**Pull request by KeitoTadashi**
# Description of change

Please write a summary of your changes and why you made them.

fixes #6332 

Be sure to reference any related issues by adding `fixes #(issue)`.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by KeitoTadashi** [comment]
Explorer should work as expected. Im working in dashboard now

**Review by begonaalvarezd — COMMENTED** [review]
CI is failing 🙏🏼

File: apps/explorer/src/pages/validator/ValidatorDetails.tsx [hunk 1]
```diff
@@ -67,12 +189,14 @@ function ValidatorDetails(): JSX.Element {
                 content={
                     <div className="mb-10">
                         <InfoBox
-                            title="Failed to load validator data"
-                            supportingText={`No validator data found for ${id}`}
+                            title="Inactive validator"
```
Comment (marc2332) [inline apps/explorer/src/pages/validator/ValidatorDetails.tsx:198]: What if a validator does not exist + is not inactive ? I think it would make sense to still render "Failed to load validator data" and render "Inactive validator" if its really inactive

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by evavirseda — CHANGES_REQUESTED** [review]
the page shows a `Failed to load validator data` infobox before it finishes loading the inactive validator :pray: 
https://github.com/user-attachments/assets/678ab8ee-46fb-4439-8dab-2c4656fbff3e

File: apps/explorer/src/components/validator/ValidatorMeta.tsx [hunk 2]
```diff
@@ -12,6 +11,94 @@ type ValidatorMetaProps = {
     validatorData: IotaValidatorSummary;
 };
 
+export type InactiveValidatorData = {
```
Comment (evavirseda) [inline apps/explorer/src/components/validator/ValidatorMeta.tsx]:
```suggestion
export type InactiveValidatorDataProps = {
```

File: apps/explorer/src/components/validator/ValidatorMeta.tsx [hunk 3]
```diff
@@ -51,7 +138,7 @@ export function ValidatorMeta({ validatorData }: ValidatorMetaProps): JSX.Elemen
                         </div>
                     </div>
                     <div className="flex w-1/2 flex-col gap-y-md">
-                        <span className="text-label-lg text-neutral-40 dark:text-neutral-60">
+                        <span className="text-label-lg text-neutral-40 dark:text-neutral-6">
```
Comment (evavirseda) [inline apps/explorer/src/components/validator/ValidatorMeta.tsx]: revert this please :pray: 
```suggestion
                        <span className="text-label-lg text-neutral-40 dark:text-neutral-60">
```

**Review by evavirseda — CHANGES_REQUESTED** [review]
tiny details, but looks nice :pray:

**Review by evavirseda — APPROVED** [review]

**Review by marc2332 — APPROVED** [review]
