### PR TITLE
fix(iota-light-client): fix light client rpc

### LINKED ISSUE #6067: Fix light client RPC
https://github.com/MystenLabs/sui/pull/19028

### PR DESCRIPTION
**Pull request by Alex6323**
Cherry-picked from upstream https://github.com/MystenLabs/sui/commit/bb93869a4c1b83cb52a64019a2ca70e33597eed7#diff-0baf913a411d91fbe5195f2b54709576d6cc2077d8f425e95d5814e13f56012e

### CODE REVIEW

File: crates/iota-light-client/src/bin/generate_chk_snapshots.rs
Comment (Thoralf-M) [inline crates/iota-light-client/src/bin/generate_chk_snapshots.rs:1]: This isn't modified in the referenced commit, however the referenced commit modifies src/main.rs which you don't edit in this PR
Where is this difference coming from?

Comment (Alex6323) [reply crates/iota-light-client/src/bin/generate_chk_snapshots.rs:1]: it's coming from the fact, that we diverged from them (we renamed main.rs to utils.rs, and added the bin directory).

Comment (Thoralf-M) [reply crates/iota-light-client/src/bin/generate_chk_snapshots.rs:1]: But even then there are many more changes in your PR, did you just move stuff around or what is this?

Comment (Alex6323) [reply crates/iota-light-client/src/bin/generate_chk_snapshots.rs:1]: Do you have an example of such change you mean? (In general my changes were related to making their commit compatible with our diverged state).

Comment (Thoralf-M) [reply crates/iota-light-client/src/bin/generate_chk_snapshots.rs:1]: image
Their diff, just adding a cache field
image
your diff looks like completely new struct, but it was moved from L345
Aren't we missing some more commits in between then?

Comment (Alex6323) [reply crates/iota-light-client/src/bin/generate_chk_snapshots.rs:1]: No, we don't. We are also just adding the `cache` field. During conflict resolution I chose their placement of the struct to make future upstream pulls easier, so it moved. However, I kept our changes as well, which was leaving the 2 CLIs (`iota-light-client`, `generate_chk_snapshots`) in `bin`.

Comment (Alex6323) [reply crates/iota-light-client/src/bin/generate_chk_snapshots.rs:1]: also ... I wouldn't worry about this too much @Thoralf-M . This is all going to be refactored drastically (and nicely) by their next commit (which basically moves everything into their dedicated modules)

Comment (Thoralf-M) [reply crates/iota-light-client/src/bin/generate_chk_snapshots.rs:1]: All the things moved around on our side in https://github.com/iotaledger/iota/pull/3723/files#diff-5f56a42813238f8b97e5b445a6935955fb67a7feb61f09c450ba530a9721920d

File: crates/iota-light-client/tests/check_proof.rs [hunk 1]
```diff
@@ -52,10 +59,10 @@ async fn read_test_data() -> (Committee, CheckpointData) {
 }
 
 async fn read_data(committee_seq: u64, seq: u64) -> (Committee, CheckpointData) {
-    let mut d = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
-    d.push(format!("example_config/{}.chk", committee_seq));
+    let mut checkpoint_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
+    checkpoint_path.push(format!("example_config/{}.chk", committee_seq));
```
Comment (Thoralf-M) [inline crates/iota-light-client/tests/check_proof.rs:63]:
```suggestion
    checkpoint_path.push(format!("example_config/{committee_seq}.chk"));
```

File: crates/iota-light-client/src/utils.rs [hunk 2]
```diff
@@ -26,64 +27,157 @@ use iota_types::{
...
-    genesis_path.push(&config.genesis_filename);
-    let genesis_committee = Genesis::load(&genesis_path)?.committee()?;
+#[async_trait]
+impl PackageStore for RemotePackageStore {
+    /// Read package contents. Fails if `id` is not an object, not a package, or
+    /// is malformed in some way.
+    async fn fetch(&self, id: AccountAddress) -> ResolverResult<Arc<Package>> {
+        // Check if we have it in the cache
+        if let Some(package) = self.cache.lock().unwrap().get(&id) {
+            info!("Fetch Package: {} cache hit", id);
```
Comment (Thoralf-M) [inline crates/iota-light-client/src/utils.rs:57]:
```suggestion
            info!("Fetch Package: {id} cache hit");
```

File: crates/iota-light-client/src/utils.rs [hunk 3]
```diff
@@ -26,64 +27,157 @@ use iota_types::{
...
+            return Ok(package.clone());
+        }
 
-    // Check the signatures of all checkpoints
-    // And download any missing ones
+        info!("Fetch Package: {}", id);
```
Comment (Thoralf-M) [inline crates/iota-light-client/src/utils.rs:61]:
```suggestion
        info!("Fetch Package: {id}");
```

File: crates/iota-light-client/src/utils.rs [hunk 4]
```diff
@@ -26,64 +27,157 @@ use iota_types::{
...
-        }
+        Ok(package)
     }
+}
 
-    Ok(())
+#[derive(Subcommand, Debug)]
+pub enum SCommands {
+    /// Sync all end-of-epoch checkpoints
+    Sync {},
```
Comment (Thoralf-M) [inline crates/iota-light-client/src/utils.rs:76]: Why is this not just `Sync`?

File: crates/iota-light-client/src/utils.rs [hunk 5]
```diff
@@ -26,64 +27,157 @@ use iota_types::{
...
+    config: &Config,
+    checkpoint_number: u64,
+    path: Option<&str>,
+) -> anyhow::Result<Envelope<CheckpointSummary, AuthorityQuorumSignInfo<true>>> {
+    // Read the resulting file and parse the yaml checkpoint list
+    let mut checkpoint_path = config.checkpoint_summary_dir.clone();
+    if let Some(path) = path {
+        checkpoint_path.push(path);
+    }
+    // TODO why yaml? rename to .sum
```
Comment (Thoralf-M) [inline crates/iota-light-client/src/utils.rs:174]: Want to do this in another PR?

File: crates/iota-light-client/src/utils.rs [hunk 6]
```diff
@@ -26,64 +27,157 @@ use iota_types::{
...
+    checkpoint_path.push(format!("{}.yaml", checkpoint_number));
```
Comment (Thoralf-M) [inline crates/iota-light-client/src/utils.rs:175]:
```suggestion
    checkpoint_path.push(format!("{checkpoint_number}.yaml"));
```

File: crates/iota-light-client/src/utils.rs [hunk 7]
```diff
@@ -127,103 +221,207 @@ pub fn write_checkpoint_list(
 
 pub async fn download_checkpoint_summary(
     config: &Config,
-    seq: u64,
+    checkpoint_number: u64,
+) -> anyhow::Result<CertifiedCheckpointSummary> {
+    // TODO switch to object store once available
```
Comment (Thoralf-M) [inline crates/iota-light-client/src/utils.rs:226]: Is there an issue, if not please open one

File: crates/iota-light-client/src/utils.rs [hunk 8]
```diff
@@ -127,103 +221,207 @@ pub fn write_checkpoint_list(
...
+    // Download the checkpoint from the server
+
+    let url = Url::parse(&config.object_store_url)?;
+    let (dyn_store, _store_path) = parse_url(&url).unwrap();
+    let path = Path::from(format!("{}.chk", checkpoint_number));
+    let response = dyn_store.get(&path).await?;
+    let bytes = response.bytes().await?;
+    let (_, blob) = bcs::from_bytes::<(u8, CheckpointData)>(&bytes)?;
+
+    info!("Downloaded checkpoint summary: {}", checkpoint_number);
```
Comment (Thoralf-M) [inline crates/iota-light-client/src/utils.rs:256]: Not going to add the suggestion for all of them, you know what I want :trollface:

File: crates/iota-light-client/src/utils.rs [hunk 9]
```diff
@@ -127,103 +221,207 @@ pub fn write_checkpoint_list(
...
 
     Ok(())
 }
 
-pub async fn get_full_checkpoint(config: &Config, seq: u64) -> anyhow::Result<CheckpointData> {
+pub async fn get_full_checkpoint(
+    config: &Config,
+    checkpoint_number: u64,
+) -> anyhow::Result<CheckpointData> {
+    // TODO add config option
```
Comment (Thoralf-M) [inline crates/iota-light-client/src/utils.rs:388]: This depends on the object store?

File: crates/iota-light-client/src/utils.rs [hunk 10]
```diff
@@ -319,138 +519,47 @@ pub async fn get_verified_effects_and_events(
...
 
+    info!("Extracting effects and events for TID: {}", tid);
     extract_verified_effects_and_events(&full_check_point, &committee, tid)
+        .map_err(|e| anyhow!(format!("Cannot extract effects and events: {e}")))
 }
 
 pub async fn get_verified_object(config: &Config, id: ObjectID) -> anyhow::Result<Object> {
-    let client: Client = Client::new(config.rest_url());
-    let object = client.get_object(id).await?;
+    let iota_client: iota_sdk::IotaClient = IotaClientBuilder::default()
```
Comment (Thoralf-M) [inline crates/iota-light-client/src/utils.rs:533]:
```suggestion
    let iota_client = IotaClientBuilder::default()
```

File: crates/iota-light-client/src/utils.rs [hunk 11]
```diff
@@ -319,138 +519,47 @@ pub async fn get_verified_effects_and_events(
...
+        .build(config.full_node_url.as_str())
+        .await
+        .unwrap();
```
Comment (Thoralf-M) [inline crates/iota-light-client/src/utils.rs:536]: Shouldn't we return an error instead? There are a few more unwraps in this file in functions that return a Result

File: crates/iota-light-client/src/utils.rs (hunk 5 above)
Comment (Alex6323) [reply crates/iota-light-client/src/utils.rs:174]: yes, once all the upstream changes have been merged. I don't understand their reasoning here at all.

File: crates/iota-light-client/src/utils.rs (hunk 7 above)
Comment (Alex6323) [reply crates/iota-light-client/src/utils.rs:226]: no need for an issue, because infra is already working on it.

Comment (Thoralf-M) [reply crates/iota-light-client/src/utils.rs:226]: But they are not working to add this here? Or at least link to the infra issue?

**Review by Thoralf-M — APPROVED** [review]
My comments will be resolved in future PRs

File: crates/iota-light-client/src/utils.rs (hunk 8 above)
Comment (Alex6323) [reply crates/iota-light-client/src/utils.rs:256]: I know. I want it too :rofl:

File: crates/iota-light-client/src/utils.rs (hunk 7 above)
Comment (Alex6323) [reply crates/iota-light-client/src/utils.rs:226]: https://github.com/iotaledger/iota/issues/6089

File: crates/iota-light-client/src/utils.rs (hunk 11 above)
Comment (Alex6323) [reply crates/iota-light-client/src/utils.rs:536]: https://github.com/iotaledger/iota/pull/6066#discussion_r2012133918

File: crates/iota-light-client/src/utils.rs (hunk 10 above)
Comment (Alex6323) [reply crates/iota-light-client/src/utils.rs:533]: https://github.com/iotaledger/iota/pull/6066#discussion_r2012133918

File: crates/iota-light-client/src/utils.rs (hunk 9 above)
Comment (Alex6323) [reply crates/iota-light-client/src/utils.rs:388]: https://github.com/iotaledger/iota/pull/6066#discussion_r2012133918

File: crates/iota-light-client/src/utils.rs (hunk 8 above)
Comment (Alex6323) [reply crates/iota-light-client/src/utils.rs:256]: https://github.com/iotaledger/iota/pull/6066#discussion_r2012133918

File: crates/iota-light-client/src/utils.rs (hunk 6 above)
Comment (Alex6323) [reply crates/iota-light-client/src/utils.rs:175]: https://github.com/iotaledger/iota/pull/6066#discussion_r2012133918

File: crates/iota-light-client/src/utils.rs (hunk 5 above)
Comment (Alex6323) [reply crates/iota-light-client/src/utils.rs:174]: https://github.com/iotaledger/iota/pull/6066#discussion_r2012133918

File: crates/iota-light-client/src/utils.rs (hunk 4 above)
Comment (Alex6323) [reply crates/iota-light-client/src/utils.rs:76]: https://github.com/iotaledger/iota/pull/6066#discussion_r2012133918

File: crates/iota-light-client/src/utils.rs (hunk 3 above)
Comment (Alex6323) [reply crates/iota-light-client/src/utils.rs:61]: https://github.com/iotaledger/iota/pull/6066#discussion_r2012133918

File: crates/iota-light-client/src/utils.rs (hunk 2 above)
Comment (Alex6323) [reply crates/iota-light-client/src/utils.rs:57]: https://github.com/iotaledger/iota/pull/6066#discussion_r2012133918

File: crates/iota-light-client/tests/check_proof.rs (hunk 1 above)
Comment (Alex6323) [reply crates/iota-light-client/tests/check_proof.rs:63]: https://github.com/iotaledger/iota/pull/6066#discussion_r2012133918

**Review by Thoralf-M — APPROVED** [review]

File: crates/iota-light-client/Cargo.toml
Comment (thibault-martinez) [inline crates/iota-light-client/Cargo.toml:1]: Why not also remove `iota-json` like upstream?

Comment (thibault-martinez) [reply crates/iota-light-client/Cargo.toml:1]: While you are at it, `move-binary-format` seems to be removable?

File: crates/iota-light-client/example_config/light_client.yaml [hunk 12]
```diff
@@ -1,3 +1,6 @@
-full_node_url: "http://0.0.0.0:9000"
-checkpoint_summary_dir: "example_config"
+full_node_url: "http://localhost:9000"
+# Provide an existing directory that contains the genesis file of the network
+checkpoint_summary_dir: ""
```
Comment (thibault-martinez) [inline crates/iota-light-client/example_config/light_client.yaml]: Why not `checkpoints_dir` then? Since it's gitignored, I'm expecting it to be the standard name...

File: crates/iota-light-client/example_config/light_client.yaml
Comment (thibault-martinez) [inline crates/iota-light-client/example_config/light_client.yaml:1]: Maybe more interesting to make this example about testnet and not localnet?

File: crates/iota-light-client/example_config/light_client.yaml [hunk 13]
```diff
@@ -1,3 +1,6 @@
...
 genesis_filename: "genesis.blob"
+object_store_url: ~
```
Comment (thibault-martinez) [inline crates/iota-light-client/example_config/light_client.yaml:6]: maybe add an entry in your issue to change that in the future?

File: crates/iota-light-client/src/utils.rs [hunk 14]
```diff
@@ -319,138 +519,47 @@ pub async fn get_verified_effects_and_events(
...
-}
-
-// The list of checkpoints at the end of each epoch
-#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
-pub struct CheckpointsList {
-    // List of end of epoch checkpoints
-    pub checkpoints: Vec<u64>,
-}
-
-pub fn read_checkpoint_list(file_path: PathBuf) -> anyhow::Result<CheckpointsList> {
```
Comment (thibault-martinez) [inline crates/iota-light-client/src/utils.rs:421]: Where do things like `pub fn read_checkpoint_list(config: &Config)` -> `pub fn read_checkpoint_list(file_path: PathBuf)` come from? They are not upstream

File: crates/iota-light-client/Cargo.toml
Comment (Alex6323) [reply crates/iota-light-client/Cargo.toml:1]: yes, good catch. I ran udeps but it seems like it can't detect unused workspace deps :/

File: crates/iota-light-client/example_config/light_client.yaml
Comment (Alex6323) [reply crates/iota-light-client/example_config/light_client.yaml:1]: I guess you're right. Changing it ...

Comment (Alex6323) [reply crates/iota-light-client/example_config/light_client.yaml:1]: Done

File: crates/iota-light-client/Cargo.toml
Comment (Alex6323) [reply crates/iota-light-client/Cargo.toml:1]: done

File: crates/iota-light-client/example_config/light_client.yaml (hunk 12 above)
Comment (Alex6323) [reply crates/iota-light-client/example_config/light_client.yaml]: changed

File: crates/iota-light-client/src/utils.rs (hunk 14 above)
Comment (Alex6323) [reply crates/iota-light-client/src/utils.rs:421]: tracked it down to this PR https://github.com/iotaledger/iota/pull/3831

File: crates/iota-light-client/example_config/light_client.yaml (hunk 13 above)
Comment (thibault-martinez) [reply crates/iota-light-client/example_config/light_client.yaml:6]: Did you add it?

File: crates/iota-light-client/src/utils.rs [hunk 15]
```diff
@@ -127,103 +221,207 @@ pub fn write_checkpoint_list(
...
-    if let Some(latest_in_list) = checkpoints_list.checkpoints.last() {
-        // Download the latest in list checkpoint
-        let summary = download_checkpoint_summary(config, *latest_in_list).await?;
-        last_epoch = summary.epoch();
-        last_checkpoint_seq = summary.sequence_number;
-    }
+    let mut checkpoints_list: CheckpointsList = read_checkpoint_list(config)?;
+    let latest_in_list = if let Some(latest_in_list) = checkpoints_list.checkpoints.last() {
+        *latest_in_list
+    } else {
```
Comment (thibault-martinez) [inline crates/iota-light-client/src/utils.rs:267]: What's the reason for the upstream difference here?

File: crates/iota-light-client/src/utils.rs [hunk 16]
```diff
@@ -127,103 +221,207 @@ pub fn write_checkpoint_list(
...
-            // Note: Do not write summary to file, since we must only persist
-            //       checkpoints that have been verified by the previous committee
+    // Check the signatures of all checkpoints
+    // And download any missing ones
 
-            // Add to the list
-            checkpoints_list.checkpoints.push(summary.sequence_number);
-            write_checkpoint_list(config, &checkpoints_list)?;
+    let mut prev_committee = genesis_committee;
+    for ckp_id in checkpoints_list.checkpoints.iter().skip(1) {
```
Comment (thibault-martinez) [inline crates/iota-light-client/src/utils.rs]: skip(1)?

File: crates/iota-light-client/src/utils.rs (hunk 15 above)
Comment (Alex6323) [reply crates/iota-light-client/src/utils.rs:267]: it's a bug I fixed that they had at that point. When you sync the first time, their code just panics, because at first run the checkpoint list doesn't contain anything. So this code here instead then fetches the first end-of-epoch checkpoint of epoch 0.

File: crates/iota-light-client/src/utils.rs (hunk 16 above)
Comment (Alex6323) [reply crates/iota-light-client/src/utils.rs]: hmm, good catch. I think that's not required anymore. For context: this was also necessary due to an upstream bug, which didn't fetch the very first end-of-epoch checkpoint. I'll verify that we can remove the skip. 

This code will heavily change and fixed by following PRs btw.

File: crates/iota-light-client/example_config/light_client.yaml (hunk 13 above)
Comment (Alex6323) [reply crates/iota-light-client/example_config/light_client.yaml:6]: I am pretty sure I added it, but it didn't publish it for some reason.

File: crates/iota-light-client/src/utils.rs (hunk 16 above)
Comment (Alex6323) [reply crates/iota-light-client/src/utils.rs]: removed in https://github.com/iotaledger/iota/pull/6066/commits/c6837ca15ba066992dfc2e8c2115abd1cbe7ab25

File: crates/iota-light-client/example_config/light_client.yaml (hunk 13 above)
Comment (Alex6323) [reply crates/iota-light-client/example_config/light_client.yaml:6]: https://github.com/iotaledger/iota/issues/5368#issuecomment-2789158657

Comment (thibault-martinez) [reply crates/iota-light-client/example_config/light_client.yaml:6]: I was thinking of https://github.com/iotaledger/iota/issues/6090 but all good

**Review by thibault-martinez — APPROVED** [review]
