### PR TITLE
refactor(consensus): Fixing Starfish for pipeline enabled and one leader per round

### LINKED ISSUE #6425: Cleanup - Update Default Protocol Constants
- [ ] Set wave_length to 3
- [ ] Ensure pipelining is enabled
- [ ] Leave multi-leader optional for now

### PR DESCRIPTION
**Pull request by polinikita**
# Description of change

This PR reduces the number of constants used in the Starfish protocol. The wavelength is hard-coded to be 3. The pipeline in the universal committer is always enabled. While we leave the opportunity for a multileader universal committer, all current tests and the consensus logic assume exactly one leader per round. The PR fixes many tests and replaces with new ones, and, in addition, changes the name of the so-called "decision" round to "certifying" round to align with the Starfish paper and the underlying meaning of this name.

## Links to any relevant issues

Closes #6425 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

CI

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### Release Notes

- [ ] Protocol:
- [ ] Nodes (Validators and Full nodes):
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [ ] CLI:
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: crates/starfish/core/src/tests/universal_committer_tests.rs [hunk 1]
```diff
@@ -400,159 +417,157 @@ async fn indirect_commit() {
     }
 }
 
-/// Commit the first leader, skip the 2nd, and commit the 3rd leader.
+/// Skip indirectly the leader of round 4 and .
```
Comment (VorobyevIlya) [inline crates/starfish/core/src/tests/universal_committer_tests.rs]: unfinished sentence

Comment (polinikita) [reply crates/starfish/core/src/tests/universal_committer_tests.rs]: Fixed with some other typos

**Review by VorobyevIlya — APPROVED** [review]

File: crates/starfish/core/src/base_committer.rs [hunk 2]
```diff
@@ -26,8 +26,7 @@ mod base_committer_tests;
 mod base_committer_declarative_tests;
 
 pub(crate) struct BaseCommitterOptions {
-    /// TODO: Re-evaluate if we want this to be configurable after running
-    /// experiments. The length of a wave (minimum 3)
+    /// The length of a wave is set to a hardcoded constant 3
```
Comment (piotrm50) [inline crates/starfish/core/src/base_committer.rs]: Why do we have it in the options if there is no possibility to change this and the value is sourced from the constant anyway? IMO we should use the constant value instead.

File: crates/starfish/core/src/commit.rs [hunk 3]
```diff
@@ -27,19 +27,12 @@ pub type CommitIndex = u32;
...
-// TODO: merge DEFAULT_WAVE_LENGTH and MINIMUM_WAVE_LENGTH into a single
-// constant, because we are unlikely to change them via config in the
-// foreseeable future.
-pub(crate) const DEFAULT_WAVE_LENGTH: Round = MINIMUM_WAVE_LENGTH;
-
-/// We need at least one leader round, one voting round, and one decision round.
-pub(crate) const MINIMUM_WAVE_LENGTH: Round = 3;
+/// One wave consists of one leader round, one voting round, and one certifying
+/// round.
+pub(crate) const DEFAULT_WAVE_LENGTH: Round = 3;
```
Comment (piotrm50) [inline crates/starfish/core/src/commit.rs]: If it's hardcoded, then there is no need to prefix it with `DEFAULT_`. This will need to be properly replaced in other places as well. 

```suggestion
pub(crate) const WAVE_LENGTH: Round = 3;

```

File: crates/starfish/core/src/universal_committer.rs [hunk 4]
```diff
@@ -181,29 +183,14 @@ pub(crate) mod universal_committer_builder {
                 dag_state,
                 wave_length: DEFAULT_WAVE_LENGTH,
                 number_of_leaders: 1,
-                pipeline: false,
```
Comment (piotrm50) [inline crates/starfish/core/src/universal_committer.rs:184]: We can also remove `wave_length` field as there is no way to change this.

File: crates/starfish/core/src/universal_committer.rs [hunk 5]
```diff
@@ -181,29 +183,14 @@ pub(crate) mod universal_committer_builder {
...
             }
         }
 
-        #[expect(unused)]
-        pub(crate) fn with_wave_length(mut self, wave_length: Round) -> Self {
-            self.wave_length = wave_length;
-            self
-        }
-
-        pub(crate) fn with_number_of_leaders(mut self, number_of_leaders: usize) -> Self {
```
Comment (piotrm50) [inline crates/starfish/core/src/universal_committer.rs:194]: I'd leave this one, as we want to keep the possibility of changing the number of leaders for the future.

**Review by piotrm50 — COMMENTED** [review]
Looks good overall. Left some comments regarding wave length and leaders count parameters.

**Review by piotrm50 — APPROVED** [review]
