### PR TITLE
fix(iota-indexer): Fix `network_metrics` view and handle missing data for epoch 0

### LINKED ISSUE #5626: Fetching `network_metrics` fails if `peak_tps_30d` is not available yet
## Bug description

The call `iotax_getNetworkMetrics` is based on following view:

```
CREATE OR REPLACE VIEW network_metrics AS 
SELECT  (SELECT recent_tps from real_time_tps)                                                          AS current_tps,
        (SELECT COALESCE(peak_tps_30d, 0) FROM epoch_peak_tps ORDER BY epoch DESC LIMIT 1)              AS tps_30_days,
        (SELECT reltuples AS estimate FROM pg_class WHERE relname = 'addresses')::BIGINT                AS total_addresses,
        (SELECT reltuples AS estimate FROM pg_class WHERE relname = 'objects')::BIGINT                  AS total_objects,
        (SELECT reltuples AS estimate FROM pg_class WHERE relname = 'packages')::BIGINT                 AS total_packages,
        (SELECT MAX(epoch) FROM epochs)                                                                 AS current_epoch,
        (SELECT MAX(sequence_number) FROM checkpoints)    
```

and fails if `peak_tps_30d` is not available yet. This value only becomes available if the first epoch (epoch 0) ends. Meaning, until then it's not possible to fetch data with `iotax_getNetworkMetrics`.

Instead of failing the whole command if this value is not available yet, it should return `0` or `-1`.

### PR DESCRIPTION
**Pull request by samuel-rufi**
# Description of change

Makes sure that `iotax_getNetworkMetrics` can fetch data from the `network_metrics` view in epoch 0 if `epoch_peak_tps` and the `addresses` tables are not populated yet.

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/5626

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Manual queries on localhost

## Change checklist

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Thoralf-M — APPROVED** [review]

File: crates/iota-indexer/migrations/pg/2023-10-04-161244_network_metrics/up.sql [hunk 1]
```diff
@@ -35,9 +35,9 @@ WHERE
   time_diff IS NOT NULL
 ORDER BY sequence_number DESC LIMIT 1;
 
-CREATE OR REPLACE VIEW network_metrics AS 
+CREATE OR REPLACE VIEW network_metrics AS
 SELECT  (SELECT recent_tps from real_time_tps)                                                          AS current_tps,
-        (SELECT COALESCE(peak_tps_30d, 0) FROM epoch_peak_tps ORDER BY epoch DESC LIMIT 1)              AS tps_30_days,
+        COALESCE((SELECT peak_tps_30d FROM epoch_peak_tps ORDER BY epoch DESC LIMIT 1), 0)              AS tps_30_days,
```
Comment (kodemartin) [inline crates/iota-indexer/migrations/pg/2023-10-04-161244_network_metrics/up.sql]: How is this functionally different  from the previous query?

**Review by kodemartin — COMMENTED** [review]
Editing the existing migration file will require a database reset to work, which is not ideal. 

I therefore suggest creating a new migration.

File: crates/iota-indexer/migrations/pg/2023-10-04-161244_network_metrics/up.sql (hunk 1 above)
Comment (samuel-rufi) [reply crates/iota-indexer/migrations/pg/2023-10-04-161244_network_metrics/up.sql]: In the previous query, if `epoch_peak_tps` had no rows, the  `SELECT` returns `NULL`. If there however was one row with `peak_tps_30d` being `NULL`, it returned `0` for it instead. Looking at the table definition:

```
CREATE TABLE epoch_peak_tps
(
    epoch           BIGINT  PRIMARY KEY,   
    peak_tps        FLOAT8  NOT NULL,
    peak_tps_30d    FLOAT8  NOT NULL
);
```

it's not possible that `peak_tps_30d` can be `NULL`. So the previous query didn't really solve the issue.

With the new query, if `epoch_peak_tps` has no rows it returns `0` for it.

---

Another approach would be to make it optional in `StoredNetworkMetrics` type, so that Diesel could map the `NULL` value (but then the existing query should be adjusted too as of the unnecessary COALESCE). And when we return the iota-json-rpc `NetworkMetrics` type we could map it to `0` or make it optional.
I think the previous `COALESCE` query was a try to solve this issue. And I think it would be fine to adjust this query as suggested (with a new migration). But I also see the advantage of just adjusting the `StoredNetworkMetrics` type and map the `NULL` value to`0` (still it would require a migration to get rid of the COALESCE). Do you prefer to do that? @kodemartin

Comment (kodemartin) [reply crates/iota-indexer/migrations/pg/2023-10-04-161244_network_metrics/up.sql]: No, that is fine. Thanks for the explanation!

Comment (samuel-rufi) [reply crates/iota-indexer/migrations/pg/2023-10-04-161244_network_metrics/up.sql]: Okay perfect, then I will simply create a new migration as suggested!

File: crates/iota-indexer/src/indexer_reader.rs [hunk 2]
```diff
@@ -1568,6 +1568,17 @@ impl IndexerReader {
             diesel::sql_query("SELECT * FROM network_metrics;")
                 .get_result::<StoredNetworkMetrics>(conn)
         })?;
+        if metrics.tps_30_days == -1.0 {
+            // this implies that the value is not available in the db
+            metrics.tps_30_days = 0.0;
+        }
```
Comment (kodemartin) [inline crates/iota-indexer/src/indexer_reader.rs]: Why did you opt out from `COALESCE(..., 0)`?

**Review by kodemartin — APPROVED** [review]
lgtm :bar_chart:

File: crates/iota-indexer/src/indexer_reader.rs (hunk 2 above)
Comment (samuel-rufi) [reply crates/iota-indexer/src/indexer_reader.rs]: As the `estimates` for the other relations can return `-1` I thought it would be cleaner to handle it also for the `tps_30_days` value in a similar way. Also I guess `-1` better reflects that the value is not available yet.

Comment (kodemartin) [reply crates/iota-indexer/src/indexer_reader.rs]: It is not cleaner though. Returning `-1` for the other values relying on [estimates](https://www.postgresql.org/docs/current/row-estimation-examples.html) is well defined and consistent with postgres docs.

Returning `-1.0` for an actual value is an ad-hoc convention that is not transparent in my opinion.

Comment (samuel-rufi) [reply crates/iota-indexer/src/indexer_reader.rs]: I see and agree it's not the optimal. However, also I think returning `0.0` for 30d TPS is not really clean.
But since it's an actual value as you mentioned, maybe it's better to rely on `0.0`. I will change.

Comment (samuel-rufi) [reply crates/iota-indexer/src/indexer_reader.rs]: Fixed with https://github.com/iotaledger/iota/pull/5632/commits/6f1da5844aec5584a189ed490ba0861b57113873

**Review by Thoralf-M — APPROVED** [review]
