### PR TITLE
scripts: add test for "Move examples reverse dependencies" to CI script

### LINKED ISSUE #5354: [CI]: tests flagged with "simtest" are also exectured during "normal" tests
Somehow the "simtests" are also run during normal test execution, which leads to failures in the "move tests". 

See this test run: https://github.com/iotaledger/iota/actions/runs/13260770688/job/37016856320
The test `test_quorum_driver_handling_overload_and_retry` is actually a simtest, and will fail because the failpoints don't work if it is run as a normal test.

### PR DESCRIPTION
**Pull request by muXxer**
# Description of change

This PR adds changes the workflows of the former "move tests".
Now it will run the tests of all crates that depend on the "Move examples", in case those examples get changed.
The workflow was added to the `rust_tests.sh` script.

It also fixes #5354.
It reverts the changes introduced in #4429, because those were introduced for easier filtering for tests, but are now replaced by different filters in the script.

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Changed tests run locally.

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: scripts/ci_tests/rust_tests.sh [hunk 1]
```diff
@@ -89,6 +89,28 @@ function mk_test_filterset() {
...
+        if [ -z "$FILTERSET" ]; then
+            FILTERSET="$add_filter"
+        else
+            FILTERSET="$FILTERSET | $add_filter"
+        fi
+    done
+
+    echo "${FILTERSET}"
+}
+
```
Comment (nmrshll) [inline scripts/ci_tests/rust_tests.sh:117]: this function looks like it's returning constant text, is that right ?
And if it is, would it make sense to just write the result by hand in a constant for readability/maintainability ?

File: scripts/ci_tests/rust_tests.sh [hunk 2]
```diff
@@ -111,6 +133,29 @@ function mk_exclude_filterset() {
...
+    for item in "${EXCLUDED[@]}"; do
+        add_filter="!(${item})"
+
+        if [ -z "$EXCLUDE_SET" ]; then
+            EXCLUDE_SET="$add_filter"
+        else
+            EXCLUDE_SET="$EXCLUDE_SET & $add_filter"
+        fi
+    done
+
```
Comment (nmrshll) [inline scripts/ci_tests/rust_tests.sh:162]: same here, it seems at first glance that this function is returning constant text
Would it make sense to just write the result by hand in a constant for readability/maintainability ?

File: scripts/ci_tests/rust_tests.sh [hunk 3]
```diff
@@ -221,6 +283,30 @@ function audit_deps_external() {
...
+        FILTERSET="-E '($FILTERSET)'"
+    fi
+
+    command="cargo nextest run --config-file .config/nextest.toml --profile ci $FILTERSET --no-tests=warn"
+    echo "Running: $command"
+    eval ${command}
+}
+
+function move_simtests() {
+    FILTERSET="$(mk_move_test_filterset)"
```
Comment (nmrshll) [inline scripts/ci_tests/rust_tests.sh]: would it make sense to add an EXTRA_FILTERSET passed as env var to any/all steps in the script ? for the user pick a subset of tests ? (what we talked about in the call yesterday)

and then any `cargo nextest` commands in the step would be called with `-E (($default_filterset) && ($extra_filterset))`

doesn't have to be part of this PR (maybe it shouldn't), could also be in a separate one

**Review by nmrshll — APPROVED** [review]

**Comment by gokhan-simsek-iota** [comment]
When we have any change in iota-types (or any code which iota-framework depends on), we had to run this cmd: 
`cargo r -p iota -- move test -p crates/iota-framework/packages/iota-system/` 
which will test iota-framework move tests (in this case `iota-system`) with the latest state of all dependant Rust/Move code.

Do we have these tests already? I think you said we did, but I could not find after a quick search.

File: scripts/ci_tests/rust_tests.sh (hunk 1 above)
Comment (muXxer) [reply scripts/ci_tests/rust_tests.sh:117]: Let's make one single function for the filters, but in another PR.

File: scripts/ci_tests/rust_tests.sh (hunk 3 above)
Comment (muXxer) [reply scripts/ci_tests/rust_tests.sh]: Let's make another PR for this added functionality.

**Review by nmrshll — APPROVED** [review]

**Review by DaughterOfMars — APPROVED** [review]

**Review by alexsporn — APPROVED** [review]

File: scripts/ci_tests/rust_tests.sh [hunk 4]
```diff
@@ -186,39 +266,79 @@ function restart_postgres() {
...
+        print_and_run_command "cargo nextest run --config-file .config/nextest.toml --profile ci --no-fail-fast --test-threads 1 --package iota-graphql-rpc --lib --features pg_integration -- test_query_cost ${ENABLE_NO_CAPTURE:+--nocapture}"
+        print_and_run_command "cargo nextest run --config-file .config/nextest.toml --profile ci --no-fail-fast --test-threads 8 --package iota-graphql-e2e-tests --features pg_integration ${ENABLE_NO_CAPTURE:+--nocapture}"
+        print_and_run_command "cargo nextest run --config-file .config/nextest.toml --profile ci --no-fail-fast --test-threads 1 --package iota-cluster-test --test local_cluster_test --features pg_integration ${ENABLE_NO_CAPTURE:+--nocapture}"
+        print_and_run_command "cargo nextest run --config-file .config/nextest.toml --profile ci --no-fail-fast --test-threads 1 --package iota-indexer --test ingestion_tests --features pg_integration ${ENABLE_NO_CAPTURE:+--nocapture}"
```
Comment (DaughterOfMars) [inline scripts/ci_tests/rust_tests.sh]: If we're adding the config file we may as well create a profile instead of defining all the options in the command

Comment (muXxer) [reply scripts/ci_tests/rust_tests.sh]: I pushed a change. You imagined it like this?

File: .github/workflows/_move_examples_reverse_dependencies_tests.yml
Comment (DaughterOfMars) [inline .github/workflows/_move_examples_reverse_dependencies_tests.yml:1]: Maybe shorten to `move_examples_rdeps_tests`?

File: scripts/ci_tests/rust_tests.sh [hunk 5]
```diff
@@ -186,39 +270,79 @@ function restart_postgres() {
...
+
+        if [ "$RESTART_POSTGRES" == "true" ]; then restart_postgres; fi
+        print_and_run_command "cargo nextest run --config-file .config/nextest.toml --profile threads-1 --package iota-graphql-rpc --test e2e_tests --test examples_validation_tests --features pg_integration ${ENABLE_NO_CAPTURE:+--nocapture}"
+        print_and_run_command "cargo nextest run --config-file .config/nextest.toml --profile threads-1 --package iota-graphql-rpc --lib --features pg_integration -- test_query_cost ${ENABLE_NO_CAPTURE:+--nocapture}"
+        print_and_run_command "cargo nextest run --config-file .config/nextest.toml --profile threads-8 --package iota-graphql-e2e-tests --features pg_integration ${ENABLE_NO_CAPTURE:+--nocapture}"
+        print_and_run_command "cargo nextest run --config-file .config/nextest.toml --profile threads-1 --package iota-cluster-test --test local_cluster_test --features pg_integration ${ENABLE_NO_CAPTURE:+--nocapture}"
+        print_and_run_command "cargo nextest run --config-file .config/nextest.toml --profile threads-1 --package iota-indexer --test ingestion_tests --features pg_integration ${ENABLE_NO_CAPTURE:+--nocapture}"
```
Comment (DaughterOfMars) [inline scripts/ci_tests/rust_tests.sh]: Hmm that didn't help much did it 😆 maybe instead of profiles we could have a common base for the command?

```sh
NEXTEST_RUN="cargo nextest run --config-file .config/nextest.toml --features pg_integration"

print_and_run_command "$NEXTEST_RUN -p iota-graphql-rpc --test-threads 1 --test e2e_tests --test examples_validation_tests ${ENABLE_NO_CAPTURE:+--nocapture}"
...
```

**Review by DaughterOfMars — APPROVED** [review]

**Review by piotrm50 — APPROVED** [review]

File: .github/workflows/_move_examples_rdeps_tests.yml [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+  # from transient network timeouts or other issues.
+  CARGO_NET_RETRY: 10
+  RUSTUP_MAX_RETRIES: 10
+  # RUSTFLAGS: -D warnings
+  RUSTDOCFLAGS: -D warnings
+  TEST_ONLY_CHANGED_CRATES: false
+
+jobs:
+  # If there are changes to the Move examples,
+  # this job runs tests for all reverse dependencies those.
```
Comment (jkrvivian) [inline .github/workflows/_move_examples_rdeps_tests.yml]: `....of those`?

**Review by sergiupopescu199 — APPROVED** [review]

File: .github/workflows/_move_examples_rdeps_tests.yml (hunk 6 above)
Comment (muXxer) [reply .github/workflows/_move_examples_rdeps_tests.yml]: That happens if you ask copilot to refactor your comment 😆

**Review by miker83z — APPROVED** [review]

**Review by nmrshll — APPROVED** [review]
