### PR TITLE
fix(iota-data-ingestion-core): make file updates atomic

### LINKED ISSUE #6889: [`iota-data-ingestion-core`]: FileProgressStore updates are not atomic
## Bug description

Currently, updating the file by calling `set_len(0)` followed by `write_all` is not atomic. If the process crashes between truncating and writing, the file may be left empty, resulting in loss of watermark data.

Using `OpenOptions::truncate(true)` is also insufficient, as a crash after truncation but before writing will similarly leave the file empty.

**Proposed Solution:**  
Adopt the `tempfile + rename` pattern. This approach writes new data to a temporary file first, and only replaces the original file with an atomic rename if the write succeeds. This ensures that the original file remains intact unless the entire update completes successfully, greatly reducing the risk of data loss due to partial writes or crashes.

### PR DESCRIPTION
**Pull request by sergiupopescu199**
# Description of change

This PR refactors the `FileProgressStore` to ensure atomic updates when storing watermark data.  
It leverages a temporary file to write the new data, and then uses an atomic rename operation to replace the original file with the updated version.
  
This approach guarantees that the watermark file is never left in a partially written or corrupted state, even in the event of a crash or unexpected shutdown, ensuring data integrity and reliability.

## Links to any relevant issues

fixes #6889 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

- Added 2 test cases to verify the results.
 ```shell
 cargo test -p iota-data-ingestion-core
```
Make sure to provide instructions for the maintainer as well as any relevant configurations.

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
    - Existing tests passed 
- [x] Patch-specific tests (correctness, functionality coverage)
    - Added 2 tests in the `iota-data-ingestion-core` crate that verifies the actual patch changes
    -  `file_progress_store_save_timeout_simulates_crash` & `file_progress_store`

### Infrastructure QA (only required for crates that are maintained by @iotaledger/infrastructure)

- [x] Verification of API backward compatibility.

> [!NOTE]
> The other checkboxes were removed since this patch does not directly affect the indexer performance, nevertheless running locally the ingestion framework for checkpoint processing risulted in the same performance as before, not visible regression were spotted.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### Release Notes

- [ ] Protocol:
- [ ] Nodes (Validators and Full nodes):
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [ ] CLI:
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: crates/iota-data-ingestion-core/src/progress_store/file.rs [hunk 1]
```diff
@@ -95,11 +98,30 @@ impl FileProgressStore {
...
+            if cfg!(test) {
+                tokio::time::sleep(std::time::Duration::from_nanos(10)).await;
+            }
+        }
+
+        // Atomically replace the original file
+        tokio::fs::rename(&tmp_path, &self.path).await?;
+
+        // Re-open the file handle for further reads
+        self.file = Self::open_or_create_file(&self.path).await?;
```
Comment (kodemartin) [inline crates/iota-data-ingestion-core/src/progress_store/file.rs]: At this point we know that the file exists, so why not open it directly and not use `open_or_create_file`?

It would avoid breaking the signature of `open_or_create_file` above.

**Review by kodemartin — APPROVED** [review]
looks good with a remark

File: crates/iota-data-ingestion-core/src/progress_store/file.rs (hunk 1 above)
Comment (sergiupopescu199) [reply crates/iota-data-ingestion-core/src/progress_store/file.rs]: Mostly because I wanted to reuse the already present logic, but thinking now it can be misleading. Will follow with a patch shortly.

The `open_or_create_file` is a private function so I suppose is not critical if we change its signature, internally it needs a ref of `PathBuf` avoiding cloning it in the `FileProgressStore::new` method.

Comment (sergiupopescu199) [reply crates/iota-data-ingestion-core/src/progress_store/file.rs]: fixed: https://github.com/iotaledger/iota/pull/6918/commits/36aa17e99dcef30c86c6b2869a56a395a3e7d380

File: crates/iota-data-ingestion-core/src/progress_store/file.rs [hunk 2]
```diff
@@ -95,11 +98,30 @@ impl FileProgressStore {
...
+
+        {
+            let mut tmp_file = OpenOptions::new()
+                .write(true)
+                .create(true)
+                .truncate(true)
+                .open(&tmp_path)
+                .await?;
+            tmp_file.write_all(data.as_ref()).await?;
+
```
Comment (samuel-rufi) [inline crates/iota-data-ingestion-core/src/progress_store/file.rs:112]: Should there be a `tmp_file.sync_all().await?;` after the `write_all` to ensure data is on disk?
https://docs.rs/tokio/latest/tokio/fs/struct.File.html#method.sync_all

Without it, isn't there a risk that `rename()`could  point to a file that was never flushed to disk if the system crashes?

**Review by samuel-rufi — COMMENTED** [review]
Wondering about the need of `sync_all`, please see below:

File: crates/iota-data-ingestion-core/src/progress_store/file.rs (hunk 2 above)
Comment (sergiupopescu199) [reply crates/iota-data-ingestion-core/src/progress_store/file.rs:112]: `sync_all()` was quite slow during testing (from nano to millis), but as a tradeoff we could use the [sync_data()](https://docs.rs/tokio/latest/tokio/fs/struct.File.html#method.sync_data) since we only need the file content and not its metadata, is a little bit faster. 

I guess is a good tradeoff for having robust data storage during crashes, what do you think?

Comment (sergiupopescu199) [reply crates/iota-data-ingestion-core/src/progress_store/file.rs:112]: fixed: https://github.com/iotaledger/iota/pull/6918/commits/9fca597f1dc3ac4fa2069be048d4deaf4593eaf3

**Review by samuel-rufi — APPROVED** [review]
