### PR TITLE
fix(wallet, wallet-dashboard): Allow accessing active stakes at all times

### LINKED ISSUE #6784: Allow accessing active stakes at all times
in the wallet, if you have only inactive stakes you cant access the list of stakes to make unstake
we shouldnt block users from accessing their stakes if they have active stakes, even if they have no gas

### PR DESCRIPTION
**Pull request by KeitoTadashi**
## Links to any relevant issues

fixes #6784

### CODE REVIEW

File: apps/wallet-dashboard/components/dialogs/unstake/views/UnstakeView.tsx [hunk 1]
```diff
@@ -156,14 +156,24 @@ export function UnstakeView({
             </DialogLayoutBody>
 
             <DialogLayoutFooter>
+                {(!isUnstakeTxPending || isTransactionPending || !delegationId) && (
```
Comment (begonaalvarezd) [inline apps/wallet-dashboard/components/dialogs/unstake/views/UnstakeView.tsx]: how come this is the condition to show not having enough gas? im not following the logic here

File: apps/wallet-dashboard/components/dialogs/unstake/views/UnstakeView.tsx [hunk 2]
```diff
@@ -156,14 +156,24 @@ export function UnstakeView({
...
+                )}
                 <Button
                     type={ButtonType.Secondary}
                     fullWidth
                     onClick={handleUnstake}
                     disabled={isPreparingUnstake || isTransactionPending || !delegationId}
                     text="Unstake"
                     icon={
-                        isPreparingUnstake ? (
+                        isUnstakeTxPending || isTransactionPending || !delegationId ? (
```
Comment (begonaalvarezd) [inline apps/wallet-dashboard/components/dialogs/unstake/views/UnstakeView.tsx]: you dont need isPreparingUnstake anymore?

File: apps/wallet/src/ui/app/pages/home/tokens/TokenStakingOverview.tsx [hunk 3]
```diff
@@ -55,7 +49,7 @@ export function TokenStakingOverview({
     const isLoading = isPending || queryResultStake.isPending;
 
     return (
-        <Card type={CardType.Filled} onClick={handleOnClick} isDisabled={disabled}>
+        <Card type={CardType.Filled} onClick={handleOnClick} isDisabled={false}>
```
Comment (begonaalvarezd) [inline apps/wallet/src/ui/app/pages/home/tokens/TokenStakingOverview.tsx]: I wouldnt remove the `disabled` prop of this component in case we need it in the future, just dont use it

File: apps/wallet/src/ui/app/staking/stake/UnstakeForm.tsx [hunk 4]
```diff
@@ -209,6 +209,16 @@ export function UnStakeForm({ stakedIotaId, validatorAddress, epoch, onSuccess }
                     />
                 </div>
             )}
+            {!isLoading && isError && (
```
Comment (begonaalvarezd) [inline apps/wallet/src/ui/app/staking/stake/UnstakeForm.tsx]: are you sure isError is always when you dont have enough gas? I dont think this is accurate

Comment (begonaalvarezd) [reply apps/wallet/src/ui/app/staking/stake/UnstakeForm.tsx]: Also, lets better use messages we already use in the app for these cases instead of harcoding them https://github.com/iotaledger/iota/blob/99e937af083bc96d518586480f9d4bc31a6088ba/apps/core/src/constants/errorMessages.constants.ts#L7

Comment (begonaalvarezd) [reply apps/wallet/src/ui/app/staking/stake/UnstakeForm.tsx]: for the error i think  you have to try matching the error message or something to make sure you are showing the right thing, otherwise for any error you display the not enough gas message https://github.com/iotaledger/iota/blob/99e937af083bc96d518586480f9d4bc31a6088ba/apps/wallet-dashboard/app/(protected)/(feature-controlled)/vesting/page.tsx#L180

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

File: apps/wallet/src/ui/app/staking/stake/UnstakeForm.tsx (hunk 4 above)
Comment (begonaalvarezd) [reply apps/wallet/src/ui/app/staking/stake/UnstakeForm.tsx]: the usage of GAS_BUDGET_ERROR_MESSAGES applies to the dashboard too

File: apps/wallet-dashboard/components/dialogs/unstake/views/UnstakeView.tsx (hunk 1 above)
Comment (begonaalvarezd) [reply apps/wallet-dashboard/components/dialogs/unstake/views/UnstakeView.tsx]: shouldnt it be based on an error message that matches the not enough balance error? i think it would be more robust like that, this condition to show not enough gas seems a bit arbitrary

File: apps/wallet/src/ui/app/pages/home/tokens/TokenStakingOverview.tsx (hunk 3 above)
Comment (begonaalvarezd) [reply apps/wallet/src/ui/app/pages/home/tokens/TokenStakingOverview.tsx]: I mean the prop of `TokenStakingOverview`

File: apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx [hunk 5]
```diff
@@ -250,8 +250,8 @@ export function TokenDetails() {
                                 <div className="flex w-full flex-col items-center gap-xs">
                                     {accountHasIota || delegatedStake?.length ? (
                                         <TokenStakingOverview
-                                            disabled={!tokenBalance}
                                             accountAddress={activeAccountAddress}
+                                            disabled={false}
```
Comment (begonaalvarezd) [inline apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx]: nit: i think you can just not pass this
```suggestion
```

File: apps/wallet-dashboard/components/dialogs/unstake/views/UnstakeView.tsx [hunk 6]
```diff
@@ -156,14 +159,30 @@ export function UnstakeView({
             </DialogLayoutBody>
 
             <DialogLayoutFooter>
+                {isNotEnoughGas && (
+                    <div className="pt-sm">
+                        <InfoBox
+                            supportingText={GAS_BUDGET_ERROR_MESSAGES[NOT_ENOUGH_BALANCE_ID]}
```
Comment (begonaalvarezd) [inline apps/wallet-dashboard/components/dialogs/unstake/views/UnstakeView.tsx]: I would better use this
```suggestion
                            supportingText={GAS_BUDGET_ERROR_MESSAGES[GAS_BALANCE_TOO_LOW_ID]}
```

File: apps/wallet-dashboard/components/dialogs/unstake/views/UnstakeView.tsx [hunk 7]
```diff
@@ -74,7 +77,7 @@ export function UnstakeView({
     } = delegatedStakeDataResult;
 
     const delegationId = extendedStake?.stakedIotaId;
-    const isPreparingUnstake = !unstakeData || isUnstakeTxPending;
+    const isNotEnoughGas = error && error.message.includes(NOT_ENOUGH_BALANCE_ID);
```
Comment (begonaalvarezd) [inline apps/wallet-dashboard/components/dialogs/unstake/views/UnstakeView.tsx]: this has only been tested with having no balance at all, but it can also happen that there is balance but is too low 
image
same in the wallet

Comment (begonaalvarezd) [reply apps/wallet-dashboard/components/dialogs/unstake/views/UnstakeView.tsx]: you can reproduce this error by having a tiny bit of dust

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by brancoder — APPROVED** [review]
LGTM

**Review by evavirseda — APPROVED** [review]

**Review by begonaalvarezd — APPROVED** [review]
