### PR TITLE
fix(wallet): unlock accounts after create

### LINKED ISSUE #10517: Double password dialog when importing sourceless account
https://github.com/user-attachments/assets/e444998d-6807-4262-9412-ba0c5b74dd92

### PR DESCRIPTION
**Pull request by KeitoTadashi**
# Description of change

unlock accounts right after creating em. Otherwise they will be refetched asynchronously, causing a one-blinking view

- Fix: 

`apps/wallet/src/background/account-sources/index.ts`
`apps/wallet/src/background/accounts/index.ts`
`apps/wallet/src/background/connections/uiConnection.ts`
`apps/wallet/src/background/index.ts`

------------------------------------------------------------

@brancoder and I detected all unnecceserry unlocks in the code and removed them ⬇️ 

- Refactor unused/unnecessary/dead code:

```
apps/wallet/src/ui/app/hooks/useCreateAccountsMutation.ts
apps/wallet/src/ui/app/pages/accounts/manage/accounts-finder/AccountsFinderView.tsx
apps/wallet/src/ui/app/pages/accounts/manage/AccountGroup.tsx
apps/wallet/src/ui/app/pages/accounts/manage/RemoveDialog.tsx
apps/wallet/src/ui/app/pages/accounts/ExportAccountPage.tsx
apps/wallet/src/ui/app/pages/accounts/ExportSeedPage.tsx
apps/wallet/src/ui/app/pages/accounts/ExportPassphrasePage.tsx
apps/wallet/src/ui/app/pages/accounts/ProtectAccountPage.tsx
```

## Links to any relevant issues

fixes #10517

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

### CODE REVIEW

File: apps/wallet/src/ui/app/pages/accounts/ProtectAccountPage.tsx
Comment (brancoder) [inline apps/wallet/src/ui/app/pages/accounts/ProtectAccountPage.tsx:1]: we should review other place where unlockAllAccountsAndSources is used in this file and in the project

**Review by brancoder — CHANGES_REQUESTED** [review]
we should review the use of unlockAllAccountsAndSources

File: apps/wallet/src/ui/app/pages/accounts/ProtectAccountPage.tsx
Comment (KeitoTadashi) [reply apps/wallet/src/ui/app/pages/accounts/ProtectAccountPage.tsx:1]: ill take a look

File: apps/wallet/src/ui/app/pages/accounts/manage/AccountGroup.tsx [hunk 1]
```diff
@@ -93,13 +84,7 @@ export function AccountGroup({
...
             ? AccountsFormType.MnemonicSource
             : AccountsFormType.SeedSource;
-        setAccountsFormValues({
-            type: accountsFormType,
-            sourceID: accountSource.id,
-        });
-        if (accountSource.isLocked) {
-            setPasswordModalVisible(true);
-        } else {
+        if (!accountSource.isLocked) {
```
Comment (brancoder) [inline apps/wallet/src/ui/app/pages/accounts/manage/AccountGroup.tsx]: 1. we can remove this check here because the source is unlocked

File: apps/wallet/src/ui/app/pages/accounts/manage/AccountGroup.tsx [hunk 2]
```diff
@@ -93,13 +84,7 @@ export function AccountGroup({
         const accountsFormType = isMnemonicDerivedGroup
             ? AccountsFormType.MnemonicSource
             : AccountsFormType.SeedSource;
-        setAccountsFormValues({
-            type: accountsFormType,
-            sourceID: accountSource.id,
-        });
```
Comment (brancoder) [inline apps/wallet/src/ui/app/pages/accounts/manage/AccountGroup.tsx:99]: adding account is not working currently se should revert the: because form validation checks the form context
```
setAccountsFormValues({
            type: accountsFormType,
            sourceID: accountSource.id,
        });
```

File: apps/wallet/src/ui/app/pages/accounts/manage/RemoveDialog.tsx [hunk 3]
```diff
@@ -70,9 +69,6 @@ export function RemoveDialog({ isOpen, setOpen, accountID }: RemoveDialogProps)
             <VerifyPasswordModal
                 open={isOpen}
                 onVerify={async (password) => {
```
Comment (brancoder) [inline apps/wallet/src/ui/app/pages/accounts/manage/RemoveDialog.tsx]: we can remove the `password` because it is unused

File: apps/wallet/src/ui/app/pages/accounts/ProtectAccountPage.tsx
Comment (brancoder) [inline apps/wallet/src/ui/app/pages/accounts/ProtectAccountPage.tsx:1]: there is one leftover instance of unlockAllAccountsAndSources in this file  in verify password modal  that we can remove

**Review by brancoder — CHANGES_REQUESTED** [review]
LG just a few changes

File: apps/wallet/src/ui/app/pages/accounts/manage/accounts-finder/AccountsFinderView.tsx [hunk 4]
```diff
@@ -334,14 +332,8 @@ export function AccountsFinderView(): JSX.Element {
                         if (accountSourceType === AllowedAccountSourceTypes.LedgerDerived) {
                             // for ledger
                             setPassword(password);
-                        } else if (accountSourceId) {
-                            // unlock software account sources
-                            await unlockAllAccountsMutation.mutateAsync({
-                                password,
-                            });
+                            setPasswordModalVisible(true);
```
Comment (brancoder) [inline apps/wallet/src/ui/app/pages/accounts/manage/accounts-finder/AccountsFinderView.tsx]: we should move this outside of the if clause

File: apps/wallet/src/ui/app/pages/accounts/manage/accounts-finder/AccountsFinderView.tsx [hunk 5]
```diff
@@ -334,14 +332,8 @@ export function AccountsFinderView(): JSX.Element {
...
                             setPassword(password);
-                        } else if (accountSourceId) {
-                            // unlock software account sources
-                            await unlockAllAccountsMutation.mutateAsync({
-                                password,
-                            });
                         }
-
-                        setPasswordModalVisible(false);
+                        setPasswordModalVisible(true);
```
Comment (brancoder) [inline apps/wallet/src/ui/app/pages/accounts/manage/accounts-finder/AccountsFinderView.tsx]: we should probably revert this flag change to false

**Review by brancoder — CHANGES_REQUESTED** [review]

**Review by VmMad — CHANGES_REQUESTED** [review]
There's a flash of the verify password modal when creating a new acc

https://github.com/user-attachments/assets/9cf90c1e-b99f-4068-b455-cfa6a4a5b3e3

File: apps/wallet/src/ui/app/pages/accounts/manage/AccountGroup.tsx [hunk 6]
```diff
@@ -97,14 +89,10 @@ export function AccountGroup({
...
-        } else {
-            createAccountsMutation.mutate({
-                type: accountsFormType,
-                sourceFlow: SOURCE_FLOW,
-            });
-        }
+        createAccountsMutation.mutate({
+            type: accountsFormType,
+            sourceFlow: SOURCE_FLOW,
+        });
```
[the remark this answers is not in the document]
Comment (brancoder) [reply apps/wallet/src/ui/app/pages/accounts/manage/AccountGroup.tsx:95]: account is never locked at this point

File: apps/wallet/src/ui/app/pages/accounts/manage/accounts-finder/AccountsFinderView.tsx [hunk 7]
```diff
@@ -334,13 +332,7 @@ export function AccountsFinderView(): JSX.Element {
...
                             // for ledger
                             setPassword(password);
-                        } else if (accountSourceId) {
-                            // unlock software account sources
-                            await unlockAllAccountsMutation.mutateAsync({
-                                password,
-                            });
                         }
-
                         setPasswordModalVisible(false);
```
[the remark this answers is not in the document]
Comment (brancoder) [reply apps/wallet/src/ui/app/pages/accounts/manage/accounts-finder/AccountsFinderView.tsx:336]: accounts are never locked at this point

File: apps/wallet/src/background/index.ts [hunk 8]
```diff
@@ -100,7 +100,11 @@ accountSourcesEvents.on('accountSourcesChanged', () => {
 
 Browser.alarms.onAlarm.addListener((alarm) => {
     if (alarm.name === AUTO_LOCK_ALARM_NAME) {
-        lockAllAccountsAndSources();
+        (async () => {
+            await lockAllAccountsAndSources();
+            accountSourcesEvents.emit('accountSourcesChanged');
+            accountsEvents.emit('accountsChanged');
+        })();
```
[the remark this answers is not in the document]
Comment (KeitoTadashi) [reply apps/wallet/src/background/index.ts:107]: If this fails, the extension's storage layer is fundamentally broken, and a .catch() with console.error cannot recover or help, it only would only hide the error.

if this is even reasonable, then we need to revisit  every other unhandled async listener in this file.
For last, but not least, probably we want to handle it with Sentry, not a `console.log`

**Review by brancoder — APPROVED** [review]
LGTM

**Review by VmMad — APPROVED** [review]
lgtm
