### PR TITLE
fix(node): Remove old committee members

### LINKED ISSUE #4902: Remove old committee members from the known peers
There is still this TODO in the codebase:

```
// TODO: we don't boot out old committee member yets, however we may want to do
// this in the future along with other network management work.
/// Handles a [`TrustedPeerChangeEvent`] by adding the new trusted peers to
/// known peers list.
fn handle_trusted_peer_change_event(
```

Since we are currently in a Testnet phase with changing validators this means when one leaves that the others still keep it whitelisted for peering.

This also is problematic once the committee rotation is in place in case there are shifts in stake.

### PR DESCRIPTION
**Pull request by gokhan-simsek-iota**
# Description of change

`fn handle_trusted_peer_change_event` was handling `TrustedPeerChangeEvent.new_peers` by always inserting the new trusted peers to known peers list, without removing the old ones.
With this PR, we update the known peers by removing the old peers and adding the latest trusted new peers and we do this without deleting the allowlisted peers which might have the latest PeerInfo (which might have come from `TrustedPeerChangeEvent.new_peers` with the same PeerId).

The changes require a new `batch_update` function in anemo, so the version is updated in Cargo.toml.
https://github.com/MystenLabs/anemo/pull/66 

## Links to any relevant issues

https://github.com/iotaledger/iota/issues/4902

## Type of change

- Enhancement (a non-breaking change which adds functionality)
 
## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota-network/src/discovery/mod.rs [hunk 1]
```diff
@@ -212,18 +212,36 @@ impl DiscoveryEventLoop {
...
+            .allowlisted_peers
+            .iter()
+            .filter_map(|(peer_id, _)| self.network.known_peers().get(peer_id))
+            .collect();
+
+        // Update the known peers with the latest trusted new peers and
+        // the allowlisted peers.
+        // Note: self.network.known_peers consists of:
+        // self.allowlisted_peers + TrustedPeerChangeEvent.new_peers
+        let _: Vec<_> = self.network.known_peers().remove_all().collect();
```
Comment (muXxer) [inline crates/iota-network/src/discovery/mod.rs]: Wouldn't that introduce race conditions, in case someone else accesses the known_peers `Arc<RwLock<HashMap<PeerId, PeerInfo>>>` in the meantime?

Wouldn't it be better to add an `update` function to the `anemo::KnownPeers` with peers_to_add, peers_to_remove?

File: crates/iota-network/src/discovery/mod.rs [hunk 2]
```diff
@@ -212,18 +212,36 @@ impl DiscoveryEventLoop {
...
 
-    // TODO: we don't boot out old committee member yets, however we may want to do
-    // this in the future along with other network management work.
-    /// Handles a [`TrustedPeerChangeEvent`] by adding the new trusted peers to
-    /// known peers list.
+    /// Handles a [`TrustedPeerChangeEvent`] by updating the known peers with
+    /// the latest trusted new peers without deleting the allowlisted peers
     fn handle_trusted_peer_change_event(
         &mut self,
         trusted_peer_change_event: TrustedPeerChangeEvent,
```
Comment (muXxer) [inline crates/iota-network/src/discovery/mod.rs:220]: Can't we figure out when the `TrustedPeerChangeEvent` gets created, which peers should be added and which should be removed? Ofc the "peers_to_remove" list should not remove peers that are part of the "allowlisted_peers". This is the initial list of trusted peers from the config, right?

**Review by muXxer — CHANGES_REQUESTED** [review]
I wonder if the meaning of `validators` changes in #4793.
Could it be that we only need to add the `committee` members to the trusted peers instead? @piotrm50 ? If that is the case, we need to change the logic.

Can we somehow utilize the emitted events from `validator_set.move`?

For example `ValidatorJoinEvent`, `ValidatorLeaveEvent`, `CommitteeValidatorJoinEvent`, `CommitteeValidatorLeaveEvent`.

**Comment by gokhan-simsek-iota** [comment]
> I wonder if the meaning of `validators` changes in #4793. Could it be that we only need to add the `committee` members to the trusted peers instead? @piotrm50 ? If that is the case, we need to change the logic.
> 
> Can we somehow utilize the emitted events from `validator_set.move`?
> 
> For example `ValidatorJoinEvent`, `ValidatorLeaveEvent`, `CommitteeValidatorJoinEvent`, `CommitteeValidatorLeaveEvent`.

---

(1) About `committee_members`:

Looking at @piotrm50's PR more closely, in Move side, there will be `committee_members` **in addition** to `active_validators` in `ValidatorSetV2`:
https://github.com/iotaledger/iota/blob/e97851bd38e27cbbd7edf637b65eeb0b725795c8/crates/iota-framework/packages/iota-system/sources/validator_set.move#L70-L75

In current code (develop), `active_validators` are sent in every epoch start from `iota-node::send_trusted_peer_change()` to `iota-network :: DiscoveryEventLoop` by this fn in `EpochStartSystemStateV1`:

https://github.com/iotaledger/iota/blob/a96d831e3b8d0e07471f50a11ad851ae0618294d/crates/iota-types/src/iota_system_state/epoch_start_iota_system_state.rs#L227-L229

But, with @piotrm50's PR, `EpochStartSystemStateV1` will have `committee_members` **instead of** `active_validators`, so, in short, `iota-network :: DiscoveryEventLoop` will be receiving `committee_members` instead of `active_validators`, which seems to me does not effect this PR's logic if I understand your concern correctly assuming `committee_members` is what we need as trusted peers, not `active_validators`.

**Comment by gokhan-simsek-iota** [comment]
> I wonder if the meaning of `validators` changes in #4793. Could it be that we only need to add the `committee` members to the trusted peers instead? @piotrm50 ? If that is the case, we need to change the logic.
> 
> Can we somehow utilize the emitted events from `validator_set.move`?
> 
> For example `ValidatorJoinEvent`, `ValidatorLeaveEvent`, `CommitteeValidatorJoinEvent`, `CommitteeValidatorLeaveEvent`.

(2) About those events:
Seems to me that those Move events are intended to be used by DApps front-ends, this looks very similar to Ethereum events (which I used before from a DApp).
https://docs.sui.io/guides/developer/sui-101/using-events#query-events-in-rust

File: crates/iota-network/src/discovery/mod.rs (hunk 1 above)
Comment (gokhan-simsek-iota) [reply crates/iota-network/src/discovery/mod.rs]: It would be if that was shared between tasks.

Firstly, `DiscoveryEventLoop.network.known_peers` is used in one task (`DiscoveryEventLoop` task) so the data race is not possible in current design/usage.
https://github.com/iotaledger/iota/blob/a96d831e3b8d0e07471f50a11ad851ae0618294d/crates/iota-network/src/discovery/builder.rs#L164

Secondly, the API of `anemo::KnownPeers` (or its parent `anemo::Network`) does not allow to acquire lock which suggests that it is not designed to be used concurrently from multiple execution contexts (in our case tokio tasks).

Even if we wanted to protect it from future concurrent usage (multiple tasks), we will get the this error:
```
    fn handle_trusted_peer_change_event()
    {
        // Acquire write lock once and hold it
        let mut known_peers = self.network.known_peers().0.write().unwrap();
            // error[E0616]: field `0` of struct `KnownPeers` is private
        // ... do things with `known_peers`
    } // Lock is automatically released when `known_peers` local var goes out of scope
```

The lock cannot be acquired, because inner of KnownPeers is private:
```
struct KnownPeers(Arc<RwLock<HashMap<PeerId, PeerInfo>>>);
```

If we really want to make it data race safe for possible future multi-task uses, we need API changes as you suggested, also need to take care of other places where `known_peers` used.

**Comment by semenov-vladyslav** [comment]
Here is a brief summary of the updates:

- Added `old_committee` to `TrustedPeerChangeEvent`; the only long-term instance of this type is managed by `tokio::sync::watch` channel; this way we keep the new_committee from the previous epoch that becomes the old_committee in the new epoch; we use `send_modify` now to emit the event;
- the discovery loop removes the peers from old_committee that are not in new_committee and that are not allowlisted; then we add all new_committee peers (and thus probably update the allowlisted ones);
- switched to the latest anemo commit that introduces `batch_update` function needed for the atomic updates; that requires to update Cargo.lock as well;
- added `TrustedPeerChangeEvent` handling tests.

File: Cargo.lock [hunk 3]
```diff
@@ -107,7 +107,7 @@ dependencies = [
  "getrandom 0.2.15",
  "once_cell",
  "version_check",
- "zerocopy",
+ "zerocopy 0.7.35",
```
Comment (muXxer) [inline Cargo.lock]: Did you run `cargo update` on this branch?
IMO all those changes to this file need to be reverted, except the ones that update anemo.

**Comment by gokhan-simsek-iota** [comment]
@semenov-vladyslav 
If we want to go down that road to make it data race safe, there is another multi step modify here:
https://github.com/iotaledger/iota/blob/df70cff8a2e68163d92d2057c8849dff58486d84/crates/iota-network/src/discovery/mod.rs#L206

So, we might need something like `insert_all()` in anemo, or maybe `batch_update` can be re-used.

**Comment by jkrvivian** [comment]
> @semenov-vladyslav If we want to go down that road to make it data race safe, there is another multi step modify here:
> 
> https://github.com/iotaledger/iota/blob/df70cff8a2e68163d92d2057c8849dff58486d84/crates/iota-network/src/discovery/mod.rs#L206
> 
> So, we might need something like `insert_all()` in anemo, or maybe `batch_update` can be re-used.

This is called at the initialization phase (`configure_preferred_peers`), the discovery loop is not yet up, it should be safe as it is.

File: crates/iota-network/src/discovery/mod.rs [hunk 4]
```diff
@@ -74,7 +74,8 @@ pub struct NodeInfo {
 #[derive(Clone, Debug, Default)]
 /// Contains a new list of available trusted peers.
 pub struct TrustedPeerChangeEvent {
-    pub new_peers: Vec<PeerInfo>,
+    pub new_committee: Vec<PeerInfo>,
+    pub old_committee: Vec<PeerInfo>,
```
Comment (DaughterOfMars) [inline crates/iota-network/src/discovery/mod.rs:78]: Any reason not to use HashSets here?

Comment (semenov-vladyslav) [reply crates/iota-network/src/discovery/mod.rs:78]: We don't need it here, the type returned by `get_validator_as_p2p_peers` is Vec, PeerInfo is neither Eq, nor Hash.

File: crates/iota-network/src/discovery/mod.rs (hunk 2 above)
Comment (semenov-vladyslav) [reply crates/iota-network/src/discovery/mod.rs:220]: We figured it! The config contains allowlisted and seed peers; we implemented the event handling logic so that they can only be updated (if metadata changed) but not removed.

**Comment by gokhan-simsek-iota** [comment]
> > @semenov-vladyslav If we want to go down that road to make it data race safe, there is another multi step modify here:
> > https://github.com/iotaledger/iota/blob/df70cff8a2e68163d92d2057c8849dff58486d84/crates/iota-network/src/discovery/mod.rs#L206
> > 
> > So, we might need something like `insert_all()` in anemo, or maybe `batch_update` can be re-used.
> 
> This is called at the initialization phase (`configure_preferred_peers`), the discovery loop is not yet up, it should be safe as it is.

Yes, it is safe now, but the idea was to make data race proof for the future, `fn handle_trusted_peer_change_event` was safe (known_peers was not shared between tokio tasks) as it was but we wanted to make it data race safe for future possible uses. So what I mean is that  someone else can easily use `fn configure_preferred_peers` out of init phase in the future.

**Comment by muXxer** [comment]
> Yes, it is safe now, but the idea was to make data race proof for the future.

Let's not over-engineer it. My point was that a batch_update function would make sense, because for me it was not super obvious if there could be data races or not on the first quick view of the code.
I didn't mean that every single part of the code needs to be future proof data race safe, even functions that are just used once during configuration phase. Let's be more pragmatic.

**Review by muXxer — APPROVED** [review]

**Review by jkrvivian — APPROVED** [review]

**Review by muXxer — APPROVED** [review]

**Review by alexsporn — APPROVED** [review]

**Comment by muXxer** [comment]
The tests fail because of an incompatibility of the updated crates. We need to update those in a clean way in another PR first.
