### PR TITLE
fix(starfish): new issues to track in Starfish manager and adapter

### LINKED ISSUE #8362: starfish: add tracking issues for todos
To address the comments from #6633 , we need to add tracking issues for todos in the Starfish adapter and manager.

### PR DESCRIPTION
**Pull request by polinikita**
# Description of change

Added tracking issues for todos in Starfish manager and adapter

## Links to any relevant issues

Closes #8362

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [x] I have checked that new and existing unit tests pass locally with my changes

### Release Notes

- [ ] Protocol:
- [ ] Nodes (Validators and Full nodes):
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [ ] CLI:
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

**Review by VorobyevIlya — APPROVED** [review]

**Review by piotrm50 — APPROVED** [review]

File: crates/iota-core/src/consensus_manager/starfish_manager.rs [hunk 1]
```diff
@@ -1,4 +1,5 @@
-// Copyright (c) 2025 IOTA Stiftung
+// Copyright (c) Mysten Labs, Inc.
```
Comment (jkrvivian) [inline crates/iota-core/src/consensus_manager/starfish_manager.rs:1]: Is it inherited from Mysten Labs?

File: crates/iota-core/src/starfish_adapter.rs [hunk 2]
```diff
@@ -1,4 +1,5 @@
-// Copyright (c) 2025 IOTA Stiftung
+// Copyright (c) Mysten Labs, Inc.
+// Modifications Copyright (c) 2025 IOTA Stiftung
```
Comment (jkrvivian) [inline crates/iota-core/src/starfish_adapter.rs:2]: Same here.

**Review by jkrvivian — CHANGES_REQUESTED** [review]

**Review by filipdulic — APPROVED** [review]

File: crates/iota-core/src/consensus_manager/starfish_manager.rs (hunk 1 above)
Comment (polinikita) [reply crates/iota-core/src/consensus_manager/starfish_manager.rs:1]: It is not inherited, but it was mostly copy-pasted. To be on a safe side, we add this copyright.

File: crates/iota-core/src/starfish_adapter.rs (hunk 2 above)
Comment (polinikita) [reply crates/iota-core/src/starfish_adapter.rs:2]: It is not inherited, but it was mostly copy-pasted. To be on a safe side, we add this copyright.

**Review by jkrvivian — APPROVED** [review]
