### PR TITLE
fix(wallet-dashboard): catch migration error when balance is dust

### LINKED ISSUE #7032: Improve error message during migration when not enough balance
Improve error message during migration when not enough balance to cover SDRUCs
Image

### PR DESCRIPTION
**Pull request by KeitoTadashi**
## Links to any relevant issues

fixes #7032

### CODE REVIEW

File: apps/wallet-dashboard/components/dialogs/migration/views/ConfirmMigrationView.tsx [hunk 1]
```diff
@@ -66,7 +66,6 @@ export function ConfirmMigrationView({
     const account = useCurrentAccount();
     const { data: balance, isLoading: isLoadingBalance } = useBalance(account?.address || '');
     const hasBalance = BigInt(balance?.totalBalance || 0) > BigInt(0);
-
```
Comment (begonaalvarezd) [inline apps/wallet-dashboard/components/dialogs/migration/views/ConfirmMigrationView.tsx]: tiny nit but the changes in this file can be reverted as they do nothing in the PR

**Review by begonaalvarezd — APPROVED** [review]

**Review by brancoder — APPROVED** [review]
