### PR TITLE
Fix rare crash when a transaction executes after its shared object assignments have been deleted

### LINKED ISSUE #4690: Fix rare crash when a transaction executes after its shared object as… · MystenLabs/sui@3aac32e
[Fix rare crash when a transaction executes after its shared object as… · MystenLabs/sui@3aac32e](https://github.com/MystenLabs/sui/commit/3aac32e2e5c97293a20644bd1fbc287dd61d8be0)   

fix rare crash when a transaction executes after its shared object assignments have been deleted.

### PR DESCRIPTION
**Pull request by bingyanglin**
# Description of change

Fix rare crash when a transaction executes after its shared object assignments have been deleted.
Note that in the upstream changes there is a new `fatal!` macro, where will be addressed in another PR with issue #4756 

## Links to any relevant issues

fixes #4690

## Type of change

- Bug fix

## How the change has been tested

Ran the local network with `RUST_LOG=info cargo run --release --bin iota start --force-regenesis --with-faucet`

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota-core/src/authority.rs [hunk 1]
```diff
@@ -1158,7 +1159,20 @@ impl AuthorityState {
         debug!("execute_certificate_internal");
 
         let tx_digest = certificate.digest();
-        let input_objects = self.read_objects_for_execution(certificate, epoch_store)?;
+
+        // prevent concurrent executions of the same tx.
```
Comment (DaughterOfMars) [inline crates/iota-core/src/authority.rs]:
```suggestion
        // Acquire a lock to prevent concurrent executions of the same transaction.
```

File: crates/iota-core/src/authority.rs [hunk 2]
```diff
@@ -1158,7 +1159,20 @@ impl AuthorityState {
...
+        let tx_guard = epoch_store.acquire_tx_guard(certificate).await?;
+        // The cert could have been processed by a concurrent attempt of the same cert,
+        // so check if the effects have already been written.
+        if let Some(effects) = self
```
Comment (DaughterOfMars) [inline crates/iota-core/src/authority.rs:1161]:
```suggestion
        
        // The cert could have been processed by a concurrent attempt of the same cert,
        // so check if the effects have already been written.
        if let Some(effects) = self
```

File: crates/iota-core/src/authority.rs [hunk 3]
```diff
@@ -1188,6 +1195,7 @@ impl AuthorityState {
 
     pub fn read_objects_for_execution(
         &self,
+        tx_lock: &CertLockGuard,
```
Comment (DaughterOfMars) [inline crates/iota-core/src/authority.rs:1192]: Some places this is `tx_lock`, others `tx_guard`. I would suggest sticking with one

File: crates/iota-core/src/authority/authority_per_epoch_store.rs [hunk 4]
```diff
@@ -131,12 +131,22 @@ pub(crate) type EncG = bls12381::G2Element;
 // retain a distinction anyway. If we need to support distributed object
 // storage, having this distinction will be useful, as we will most likely have
 // to re-implement a retry / write-ahead-log at that point.
-pub struct CertLockGuard(#[expect(unused)] MutexGuard);
-pub struct CertTxGuard(#[expect(unused)] CertLockGuard);
+pub struct CertLockGuard(#[allow(unused)] MutexGuard);
+pub struct CertTxGuard(#[allow(unused)] CertLockGuard);
```
Comment (DaughterOfMars) [inline crates/iota-core/src/authority/authority_per_epoch_store.rs]: If this is no longer unused, then remove the tags altogether please

File: crates/iota-core/src/authority/authority_per_epoch_store.rs [hunk 5]
```diff
@@ -131,12 +131,22 @@ pub(crate) type EncG = bls12381::G2Element;
...
 impl CertTxGuard {
     pub fn release(self) {}
     pub fn commit_tx(self) {}
+    pub fn as_lock_guard(&self) -> &CertLockGuard {
+        &self.0
+    }
+}
+
+impl CertLockGuard {
+    pub fn dummy_for_tests() -> Self {
```
Comment (DaughterOfMars) [inline crates/iota-core/src/authority/authority_per_epoch_store.rs]: Do we like `dummy`?

File: crates/iota-core/src/transaction_input_loader.rs [hunk 6]
```diff
@@ -134,10 +136,11 @@ impl TransactionInputLoader {
         &self,
         shared_lock_store: &impl GetSharedLocks,
         tx_key: &TransactionKey,
+        _tx_lock: &CertLockGuard, // see below for why this is needed
```
Comment (DaughterOfMars) [inline crates/iota-core/src/transaction_input_loader.rs]: I don't see anything below?

**Comment by Thoralf-M** [comment]
Could you please choose another PR title, which makes it clear what this change is about? `upstream change` isn't very helpful

File: crates/iota-core/src/transaction_manager.rs [hunk 7]
```diff
@@ -438,15 +438,34 @@ impl TransactionManager {
...
+                            // hold tx locks for every cert for the duration
+                            // of this function in order to remove the race.
+                            if self
+                                .transaction_cache_read
+                                .is_tx_already_executed(cert.digest())
+                                .expect("is_tx_already_executed cannot fail")
+                            {
+                                return None;
+                            }
+                            panic!("Failed to get input object keys: {:?}", e);
```
Comment (DaughterOfMars) [inline crates/iota-core/src/transaction_manager.rs]: Why are we using panics instead of propagating errors?

File: crates/iota-core/src/unit_tests/authority_tests.rs [hunk 8]
```diff
@@ -4713,6 +4713,7 @@ async fn test_shared_object_transaction_ok() {
         .epoch_store_for_testing()
         .get_shared_locks(&certificate.key())
         .expect("Reading shared locks should not fail")
+        .expect("Locks should be set")
```
Comment (DaughterOfMars) [inline crates/iota-core/src/unit_tests/authority_tests.rs]: These comments are in the wrong format. They should describe the error, not what should occur. More below and also some are incorrectly capitalized

**Comment by bingyanglin** [comment]
> Could you please choose another PR title, which makes it clear what this change is about? `upstream change` isn't very helpful

Good suggestion. Changed the title, and please feel free to suggest a better naming. Thanks.

File: crates/iota-single-node-benchmark/src/mock_storage.rs [hunk 9]
```diff
@@ -57,7 +57,7 @@ impl InMemoryObjectStore {
         tx_key: &TransactionKey,
         input_object_kinds: &[InputObjectKind],
     ) -> IotaResult<InputObjects> {
-        let shared_locks_cell: OnceCell<HashMap<_, _>> = OnceCell::new();
+        let shared_locks_cell: OnceCell<Option<HashMap<_, _>>> = OnceCell::new();
```
Comment (DaughterOfMars) [inline crates/iota-single-node-benchmark/src/mock_storage.rs:60]: Can you explain this change?

File: crates/iota-core/src/authority/authority_per_epoch_store.rs (hunk 5 above)
Comment (bingyanglin) [reply crates/iota-core/src/authority/authority_per_epoch_store.rs]: better suggesion?

File: crates/iota-core/src/authority.rs (hunk 3 above)
Comment (bingyanglin) [reply crates/iota-core/src/authority.rs:1192]: Good suggestion, looks reasonable to change new added ones to be `tx_guard`.

File: crates/iota-core/src/unit_tests/authority_tests.rs (hunk 8 above)
Comment (bingyanglin) [reply crates/iota-core/src/unit_tests/authority_tests.rs]: Sorry I am not following what format is wrong? Can you give me an example?

File: crates/iota-core/src/transaction_manager.rs (hunk 7 above)
Comment (bingyanglin) [reply crates/iota-core/src/transaction_manager.rs]: I think this should not happen?

File: crates/iota-core/src/transaction_input_loader.rs (hunk 6 above)
Comment (bingyanglin) [reply crates/iota-core/src/transaction_input_loader.rs]: The reason is the following, as included in this PR, and same as the MystenLabs/sui@3aac32e
```rust
                            // Important to hold the _tx_lock here - otherwise it would be possible
                            // for a concurrent execution of the same tx to enter this point after
                            // the first execution has finished and the
                            // shared locks have been deleted.
```

File: crates/iota-single-node-benchmark/src/mock_storage.rs (hunk 9 above)
Comment (bingyanglin) [reply crates/iota-single-node-benchmark/src/mock_storage.rs:60]: Yes. As the `shared_locks` was also changed in the following code.

File: crates/iota-core/src/authority/authority_per_epoch_store.rs (hunk 5 above)
Comment (DaughterOfMars) [reply crates/iota-core/src/authority/authority_per_epoch_store.rs]: `guard_for_tests` is probably fine?

File: crates/iota-core/src/transaction_input_loader.rs (hunk 6 above)
Comment (DaughterOfMars) [reply crates/iota-core/src/transaction_input_loader.rs]: I would move this comment up to the param site.

File: crates/iota-core/src/transaction_manager.rs (hunk 7 above)
Comment (DaughterOfMars) [reply crates/iota-core/src/transaction_manager.rs]: I guess this is just how this code works 🤷‍♀️ as there seems to be no other error propagation

File: crates/iota-single-node-benchmark/src/mock_storage.rs (hunk 9 above)
Comment (DaughterOfMars) [reply crates/iota-single-node-benchmark/src/mock_storage.rs:60]: But why?

File: crates/iota-core/src/unit_tests/authority_tests.rs (hunk 8 above)
Comment (DaughterOfMars) [reply crates/iota-core/src/unit_tests/authority_tests.rs]: 1. These messages should be all lowercase
2. The phrasing should be "locks are not set" instead of "locks should be set", I.E. Descriptive not prescriptive

**Comment by thibault-martinez** [comment]
> Good suggestion. Changed the title, and please feel free to suggest a better naming. Thanks.

IMO I would rather have the name be explicit about what it is fixing than just saying it's porting a commit

**Comment by bingyanglin** [comment]
> > Good suggestion. Changed the title, and please feel free to suggest a better naming. Thanks.
> 
> IMO I would rather have the name be explicit about what it is fixing than just saying it's porting a commit

Agreed. Changed the title to be explicit and the same as the ported commits, so we can easier map them in the future.

File: crates/iota-core/src/authority.rs (hunk 3 above)
Comment (bingyanglin) [reply crates/iota-core/src/authority.rs:1192]: So after double check now we call them `tx_lock` if it is `CertLockGuard`, and `tx_guard` if it is `GaugeGuard<'_>` or `CertTxGuard`, i.e., no `Lock` naming in the struct.
Then I think current naming might be clear already?

File: crates/iota-core/src/unit_tests/authority_tests.rs (hunk 8 above)
Comment (bingyanglin) [reply crates/iota-core/src/unit_tests/authority_tests.rs]: Fixed at [d206cd8](https://github.com/iotaledger/iota/pull/4757/commits/d206cd846c0a10ff1496e207cf2a504492d43e66).

File: crates/iota-core/src/authority/authority_per_epoch_store.rs (hunk 5 above)
Comment (bingyanglin) [reply crates/iota-core/src/authority/authority_per_epoch_store.rs]: Modified at [fa3d2b6](https://github.com/iotaledger/iota/pull/4757/commits/fa3d2b6563477d4c2c2274f9bea66ab40ebd7e0f).

File: crates/iota-core/src/authority/authority_per_epoch_store.rs (hunk 4 above)
Comment (bingyanglin) [reply crates/iota-core/src/authority/authority_per_epoch_store.rs]: Modified at [a1dbc6f](https://github.com/iotaledger/iota/pull/4757/commits/a1dbc6f2329904210cd6520dfc0478f3eb13fd7d). Note that for the `MutexGuard` the tag is still needed.

File: crates/iota-core/src/transaction_input_loader.rs (hunk 6 above)
Comment (bingyanglin) [reply crates/iota-core/src/transaction_input_loader.rs]: Modified at [93f423b](https://github.com/iotaledger/iota/pull/4757/commits/93f423b897183cc74dc64b0552b8c58e860dc7cb).

File: crates/iota-single-node-benchmark/src/mock_storage.rs (hunk 9 above)
Comment (bingyanglin) [reply crates/iota-single-node-benchmark/src/mock_storage.rs:60]: I think it's for better handling when the `shared_locks` returns `None`. When it is `None`, it will be handled by the following error
```rust 
IotaError::GenericAuthority {
    error: "Shared object locks should have been set.".to_string(),
}
```

File: crates/iota-core/src/transaction_input_loader.rs [hunk 10]
```diff
@@ -161,17 +167,20 @@ impl TransactionInputLoader {
...
-                    // 1. either we have a bug that skips shared object version assignment
-                    // 2. or we have some DB corruption
+                                .get_shared_locks(tx_key)
+                                .expect("loading shared locks should not fail")
+                                .map(|locks| locks.into_iter().collect())
+                        })
+                        .as_ref()
+                        .unwrap_or_else(|| {
+                            // _tx_lock is held, so this should not happen
+                            panic!("Failed to get shared locks for transaction {tx_key:?}");
```
Comment (muXxer) [inline crates/iota-core/src/transaction_input_loader.rs]: Should we add a TODO that "fatal" should be used here in the future?

File: crates/iota-core/src/transaction_manager.rs [hunk 11]
```diff
@@ -438,15 +438,34 @@ impl TransactionManager {
         let mut receiving_objects: HashSet<InputKey> = HashSet::new();
         let certs: Vec<_> = certs
             .into_iter()
-            .map(|(cert, fx_digest)| {
+            .filter_map(|(cert, fx_digest)| {
```
Comment (muXxer) [inline crates/iota-core/src/transaction_manager.rs:442]: Maybe add a TODO in line 423 that we need to add fatal there.

File: crates/iota-core/src/transaction_manager.rs [hunk 12]
```diff
@@ -438,15 +438,34 @@ impl TransactionManager {
...
                     .value
                     .input_objects()
                     .expect("input_objects() cannot fail");
                 let mut input_object_keys =
-                    epoch_store.get_input_object_keys(&cert.key(), &input_object_kinds);
+                    match epoch_store.get_input_object_keys(&cert.key(), &input_object_kinds) {
+                        Ok(keys) => keys,
+                        Err(e) => {
+                            // Because we do not hold the transaction lock during enqueue, it is
+                            // possible that the transaction was
```
Comment (muXxer) [inline crates/iota-core/src/transaction_manager.rs]: maybe format the comment a bit nicer. with our changed line length settings this looks weird.

File: crates/iota-core/src/unit_tests/authority_tests.rs [hunk 13]
```diff
@@ -2069,15 +2069,15 @@ async fn test_conflicting_transactions() {
...
+                .expect("object is not locked")
                 .auth_sig()
         );
 
         assert_eq!(
             &ok.clone().status.into_signed_for_testing(),
             gas_info
                 .lock_for_debugging
-                .expect("gas should be locked")
+                .expect("gas is not locked")
```
Comment (muXxer) [inline crates/iota-core/src/unit_tests/authority_tests.rs:2080]: where did that changed? :D

Comment (bingyanglin) [reply crates/iota-core/src/unit_tests/authority_tests.rs:2080]: So basically this is suggested by @DaughterOfMars [here](https://github.com/iotaledger/iota/pull/4757#discussion_r1913411569) where
```bash
1. These messages should be all lowercase
2. The phrasing should be "locks are not set" instead of "locks should be set", I.E. Descriptive not prescriptive
```

File: crates/iota-core/src/transaction_manager.rs (hunk 11 above)
Comment (bingyanglin) [reply crates/iota-core/src/transaction_manager.rs:442]: Thanks for pointing this out! Fixed at [bec3e9b](https://github.com/iotaledger/iota/pull/4757/commits/bec3e9b139251a8fb5a5d6595c681c517ae9030d).

File: crates/iota-core/src/transaction_input_loader.rs (hunk 10 above)
Comment (bingyanglin) [reply crates/iota-core/src/transaction_input_loader.rs]: Thanks! Fixed at [bec3e9b](https://github.com/iotaledger/iota/pull/4757/commits/bec3e9b139251a8fb5a5d6595c681c517ae9030d).

File: crates/iota-core/src/transaction_manager.rs (hunk 12 above)
Comment (bingyanglin) [reply crates/iota-core/src/transaction_manager.rs]: Agreed! Missed this. Fixed at [cdeb224](https://github.com/iotaledger/iota/pull/4757/commits/cdeb22415fc93c9e36e1d1b009bf2c7622cb5959).

File: crates/iota-single-node-benchmark/src/mock_storage.rs (hunk 9 above)
Comment (DaughterOfMars) [reply crates/iota-single-node-benchmark/src/mock_storage.rs:60]: Yes, but it is set by `get_or_init`. This whole change seems very suspicious, as it adds an `Option` only so that it can fail.

Comment (bingyanglin) [reply crates/iota-single-node-benchmark/src/mock_storage.rs:60]: Tbh I don't have other clues, but I would prefer use this change as we can handle the `None` case better.

File: crates/iota-core/src/authority.rs (hunk 3 above)
Comment (DaughterOfMars) [reply crates/iota-core/src/authority.rs:1192]: Alright

File: crates/iota-core/src/authority/authority_per_epoch_store.rs (hunk 4 above)
Comment (DaughterOfMars) [reply crates/iota-core/src/authority/authority_per_epoch_store.rs]: Then it should be `expect`

Comment (bingyanglin) [reply crates/iota-core/src/authority/authority_per_epoch_store.rs]: Enhanced the tag at [a8d3303](https://github.com/iotaledger/iota/pull/4757/commits/a8d33036b54d7a794c485d5feb9d9490490eb371).

**Review by muXxer — APPROVED** [review]

**Review by piotrm50 — APPROVED** [review]

**Review by miker83z — APPROVED** [review]

File: crates/iota-core/src/transaction_input_loader.rs (hunk 10 above)
Comment (alexsporn) [reply crates/iota-core/src/transaction_input_loader.rs]: @bingyanglin `fatal!` shoud be available now, so please update

File: crates/iota-core/src/transaction_manager.rs [hunk 14]
```diff
@@ -420,6 +420,7 @@ impl TransactionManager {
                     .transaction_cache_read
                     .is_tx_already_executed(&digest)
                     .unwrap_or_else(|err| {
+                        // TODO: use fatal! once it is available
```
Comment (alexsporn) [inline crates/iota-core/src/transaction_manager.rs]: Same here

File: crates/iota-core/src/transaction_manager.rs [hunk 15]
```diff
@@ -438,15 +439,34 @@ impl TransactionManager {
...
+                            // remove the race.
+                            if self
+                                .transaction_cache_read
+                                .is_tx_already_executed(cert.digest())
+                                .expect("is_tx_already_executed cannot fail")
+                            {
+                                return None;
+                            }
+                            // TODO: use fatal! once it is available
+                            panic!("Failed to get input object keys: {:?}", e);
```
Comment (alexsporn) [inline crates/iota-core/src/transaction_manager.rs]: Same here

**Review by alexsporn — CHANGES_REQUESTED** [review]
Please update with `develop` and fix the introduced TODOs

File: crates/iota-core/src/transaction_manager.rs (hunk 15 above)
Comment (bylin-mh) [reply crates/iota-core/src/transaction_manager.rs]: Thanks! Modified at [db7870d](https://github.com/iotaledger/iota/pull/4757/commits/db7870d37f7dc3acc6baae9d840e591447509887).

**Review by alexsporn — APPROVED** [review]
