### PR TITLE
fix(iota-node): unregister and re-register consensus adapter metrics during reconfiguration

### LINKED ISSUE #6277: Validator node crashes when it was a validator node before, and becomes a validator/committee member again

### PR DESCRIPTION
**Pull request by semenov-vladyslav**
# Description of change

This PR fixes an issue with an unwrap panic during creation of ConsensusAdapterMetrics with error AlreadyReg. Metrics are created during reconfiguration when a node becomes a validator. It a node becomes a validator for the second time (after eg. "leaving validator set") the metrics will be created for the second time reusing the same "default" registry which would lead to a crash as metrics are never unregistered.

This PR adds ConsensusAdapterMetrics::unregister function to unregister previously created metrics (it can't be done in `drop` as we need the registry). It is called when a node is no longer a validator after reconfiguration. HistogramVec from iota-metrics counters are dropped separately.

## Links to any relevant issues

fix #6277

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota-core/src/consensus_adapter.rs [hunk 1]
```diff
@@ -182,6 +182,87 @@ impl ConsensusAdapterMetrics {
     pub fn new_test() -> Self {
         Self::new(&Registry::default())
     }
+
+    pub fn unregister(&self, registry: &Registry) {
+        registry
+            .unregister(Box::new(self.sequencing_certificate_attempt.clone()))
+            .expect("Failed to unregister sequencing_certificate_attempt");
```
Comment (nmrshll) [inline crates/iota-core/src/consensus_adapter.rs]: We have quite a few new expect() panics, is this okay ?
(I suppose it won't actually stop the program as they're caught and recovered, but do we want to just print an error right here instead ?)

File: crates/iota-core/src/consensus_adapter.rs [hunk 2]
```diff
@@ -182,6 +182,87 @@ impl ConsensusAdapterMetrics {
...
+            .expect("Failed to unregister sequencing_resubmission_interval_ms");
+    }
+}
+
+// HistogramVec from iota-metrics uses asynchronous model to report metrics
+// which makes it difficult to unregister counters in the usual manner. Here we
+// re-create counters so that their `desc()`s match the ones created by
+// HistogramVec and remove them from the registry. Counters can be safely
+// unregistered even if they are still in use.
+fn unregister_histogram_vec(name: &str, desc: &str, labels: &[&str], registry: &Registry) {
```
Comment (muXxer) [inline crates/iota-core/src/consensus_adapter.rs]: I wonder if that should rather be moved to `histogram.rs` in `iota-metrics`, below the logic where it's created/registered.

**Review by nmrshll — APPROVED** [review]
We still keep the `unwrap()` that were panicking in `ConsensusAdapterMetrics::new()`, is this also okay ? Would the new logic of "unregister if no longer a validator" probably catch all these cases ?

And same question, do we want to simply print the error where it happens instead of panicking (e.g. replace the unwrap()s by local error handling / tracing:error!()s ?)

File: crates/iota-core/src/consensus_adapter.rs [hunk 3]
```diff
@@ -1255,4 +1340,44 @@ mod adapter_tests {
             assert!(zero_found);
         }
     }
+
+    #[test]
+    fn test_unregister_consensus_adapter_metrics() {
```
Comment (muXxer) [inline crates/iota-core/src/consensus_adapter.rs]: Please add a test for the bad case as well, and catch the panic.

**Review by muXxer — CHANGES_REQUESTED** [review]

File: crates/iota-core/src/consensus_adapter.rs (hunk 1 above)
Comment (muXxer) [reply crates/iota-core/src/consensus_adapter.rs]: If that code ever panics, there is a logic error somewhere and the developer made a mistake. IMO we should keep the panics, and add test cases that prevent that someone forgets to unregister a metrics.

File: crates/iota-core/src/consensus_adapter.rs (hunk 2 above)
Comment (semenov-vladyslav) [reply crates/iota-core/src/consensus_adapter.rs]: Thought that too. Moved to HistogramVec

**Review by muXxer — APPROVED** [review]

**Review by piotrm50 — APPROVED** [review]
