### PR TITLE
fix(cli): don't attempt connection for `client envs` command

### LINKED ISSUE #4504: CLI: don't attempt connection for `client envs` command
This command should just list the envs without attempting a connection.

```
$ ./iota client envs
client error (Connect)

Caused by:
    0: tcp connect error: Connection refused (os error 111)
    1: Connection refused (os error 111)
```

### PR DESCRIPTION
**Pull request by thibault-martinez**
Fixes https://github.com/iotaledger/iota/issues/4504
Based on upstream https://github.com/MystenLabs/sui/pull/19506

### CODE REVIEW

File: crates/iota/src/client_commands.rs [hunk 1]
```diff
@@ -2424,14 +2383,16 @@ impl IotaClientCommandResult {
...
         match &mut self {
             IotaClientCommandResult::DryRun(DryRunTransactionBlockResponse { effects, .. })
             | IotaClientCommandResult::TransactionBlock(IotaTransactionBlockResponse {
                 effects: Some(effects),
                 ..
-            }) => prerender_clever_errors(effects, read_api).await,
-
+            }) => {
+                let client = context.get_client().await.expect("Cannot connect to RPC");
+                prerender_clever_errors(effects, client.read_api()).await
```
Comment (DaughterOfMars) [inline crates/iota/src/client_commands.rs:2394]: Perhaps we could have two ways to render, one with a connection and one without?

Comment (thibault-martinez) [reply crates/iota/src/client_commands.rs:2394]: Closing this as I prefer to keep this PR in line with upstream. Please open an issue or subsequent PR if you want to pursue the idea.

**Review by Thoralf-M — APPROVED** [review]

**Review by DaughterOfMars — APPROVED** [review]

**Comment by thibault-martinez** [comment]
Please don't merge before https://github.com/iotaledger/iota/pull/4614
