### PR TITLE
fix(consensus): `authority service` TODOs

### LINKED ISSUE #8229: `authority_service` TODOs
Go through the TODOs in `authority_service` module created by @iotaledger/consensus  and remove any superfluous, create issues for those that need to be added to the backlog, and fix those quick to fix.

### PR DESCRIPTION
**Pull request by filipdulic**
# Description of change
Removes TODOs that have been resolved, or are being tracked by created issues.

## Links to any relevant issues

fixes #8229

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [ ] Patch-specific tests (correctness, functionality coverage)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ x I have checked that new and existing unit tests pass locally with my changes

### Release Notes

- [ ] Protocol:
- [ ] Nodes (Validators and Full nodes):
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [ ] CLI:
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: crates/starfish/core/src/authority_service.rs [hunk 1]
```diff
@@ -449,11 +449,6 @@ impl<C: CoreThreadDispatcher> NetworkService for AuthorityService<C> {
             .map_err(|_| ConsensusError::Shutdown)?;
 
         // 9. Add block to dag, add its missing ancestors to the set
-        // TODO:: consider possible optimization:
```
Comment (filipdulic) [inline crates/starfish/core/src/authority_service.rs:452]: BlockManager already implements this optimization.

File: crates/starfish/core/src/authority_service.rs [hunk 2]
```diff
@@ -449,11 +449,6 @@ impl<C: CoreThreadDispatcher> NetworkService for AuthorityService<C> {
...
-        //  first try to accept the block. If it fails, try to find missing ancestors
-        //  among additional headers and from block_round-1 add only them. From the
-        //  rounds < block_round-1 add all headers
-        // TODO: handle missing transactions as well
```
Comment (filipdulic) [inline crates/starfish/core/src/authority_service.rs:456]: missing transactions are handled right after step 9 and before return from method.

File: crates/starfish/core/src/authority_service.rs [hunk 3]
```diff
@@ -475,8 +470,6 @@ impl<C: CoreThreadDispatcher> NetworkService for AuthorityService<C> {
         }
 
         if !missing_committed_txns.is_empty() {
-            // TODO: decide whether to remove the live transaction fetcher
```
Comment (filipdulic) [inline crates/starfish/core/src/authority_service.rs:478]: #8227 issue created to track this TODO.

File: crates/starfish/core/src/authority_service.rs [hunk 4]
```diff
@@ -590,9 +583,6 @@ impl<C: CoreThreadDispatcher> NetworkService for AuthorityService<C> {
         };
 
         if block_refs.len() > max_fetch_size {
-            // TODO: we might need to reevaluate whether we want to reject such a request
```
Comment (filipdulic) [inline crates/starfish/core/src/authority_service.rs:593]: #8228 issue created to track this TODO.

**Review by piotrm50 — APPROVED** [review]
