### PR TITLE
fix(wallet-dashboard): other assets

### LINKED ISSUE #4572: Fix other assets
- Other assets in the dashboard should not contain Coins nor NFTs, it contains at least coins for now
- Other assets should just open a new tab in the explorer

Copy behavior from the wallet

### PR DESCRIPTION
**Pull request by cpl121**
# Description of change

Other assets in the dashboard should not contain Coins nor NFTs, it contains at least coins for now
Other assets should just open a new tab in the explorer

## Links to any relevant issues

Closes #4572 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: apps/wallet-dashboard/app/(protected)/assets/page.tsx [hunk 1]
```diff
@@ -31,21 +31,22 @@ export default function AssetsDashboardPage(): React.JSX.Element {
...
-        undefined,
+        {
+            MatchNone: [{ StructType: '0x2::coin::Coin' }],
+        },
         OBJECTS_PER_REQ,
     );
 
-    const assets: IotaObjectData[] = [];
+    const visualAssets: IotaObjectData[] = [];
+    const otherAssets: IotaObjectData[] = [];
```
Comment (brancoder) [inline apps/wallet-dashboard/app/(protected)/assets/page.tsx]: we simplified this code by removing `visualAssets` and `otherAssets` based on the comment in this PR > https://github.com/iotaledger/iota/pull/4038#discussion_r1856058919
with this PR we would be reverting back the changes

**Review by brancoder — CHANGES_REQUESTED** [review]
just a nit about code optimization and reverting code added in previous PR

File: apps/wallet-dashboard/app/(protected)/assets/page.tsx (hunk 1 above)
Comment (cpl121) [reply apps/wallet-dashboard/app/(protected)/assets/page.tsx]: That code was incorrect because the objects were always pushed to assets array
`if (selectedCategory == AssetCategory.Visual) {
                    if(hasDisplayData(asset)) {
                        assets.push(asset.data);
                    }
                } else if(selectedCategory == AssetCategory.Other) {
                    assets.push(asset.data);
                }`
I have added a Map to simplify the code, but also to be able to separate it into the 2 categories, take a look and tell me what you think

Comment (brancoder) [reply apps/wallet-dashboard/app/(protected)/assets/page.tsx]: i think that it was correct because only one array is shown at a time. that means that everything can be stored in the same array

File: apps/wallet-dashboard/app/(protected)/assets/page.tsx [hunk 2]
```diff
@@ -31,21 +31,23 @@ export default function AssetsDashboardPage(): React.JSX.Element {
     const account = useCurrentAccount();
     const { data, isFetching, fetchNextPage, hasNextPage, refetch } = useGetOwnedObjects(
         account?.address,
-        undefined,
+        {
+            MatchNone: [{ StructType: '0x2::coin::Coin' }],
```
Comment (marc2332) [inline apps/wallet-dashboard/app/(protected)/assets/page.tsx]:
```suggestion
            MatchNone: [{ StructType: COIN_TYPE }],
```

File: apps/wallet-dashboard/app/(protected)/assets/page.tsx [hunk 3]
```diff
@@ -31,21 +31,23 @@ export default function AssetsDashboardPage(): React.JSX.Element {
...
+        },
         OBJECTS_PER_REQ,
     );
 
-    const assets: IotaObjectData[] = [];
+    const assets = new Map<string, IotaObjectData[]>(
```
Comment (marc2332) [inline apps/wallet-dashboard/app/(protected)/assets/page.tsx]:
```suggestion
    const assets = new Map<AssetCategory, IotaObjectData[]>(
```

File: apps/wallet-dashboard/app/(protected)/assets/page.tsx (hunk 1 above)
Comment (cpl121) [reply apps/wallet-dashboard/app/(protected)/assets/page.tsx]: I don't think so, since before the NFTs were shown with the others filter
Captura desde 2024-12-20 09-29-29

File: apps/wallet-dashboard/app/(protected)/assets/page.tsx (hunk 3 above)
Comment (marc2332) [inline apps/wallet-dashboard/app/(protected)/assets/page.tsx]: I wouldn't have used a `Map` as you already know what/how many entries are going to be, I would just have made it a record like `ASSET_CATEGORIES`, just a thought 👍🏻

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by brancoder — APPROVED** [review]
LGTM 🎊

**Review by panteleymonchuk — APPROVED** [review]
All looks good 🚀

Just FYI this PR might be crossing with https://github.com/iotaledger/iota/pull/4512

**Review by marc2332 — APPROVED** [review]

File: apps/explorer/tests/utils/localnet.ts [hunk 4]
```diff
@@ -24,7 +25,7 @@ export async function split_coin(address: string) {
     const tx = new Transaction();
     tx.moveCall({
         target: '0x2::pay::split',
-        typeArguments: ['0x2::iota::IOTA'],
+        typeArguments: [COIN_TYPE],
```
Comment (marc2332) [inline apps/explorer/tests/utils/localnet.ts]: Revert this!!

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by marc2332 — APPROVED** [review]
