### PR TITLE
fix(iota-indexer): resolve all objects needed for calculating balance changes in dry run

### LINKED ISSUE #11085: [indexer]: dry_run panics when executing a request add stake
With the gRPC migration, balance change and object change computation moved from the node (which had full state access) to the indexer (which only has objects from the simulate response). Dynamically loaded objects (e.g. staking pool child objects) are missing from the simulate response, causing a panic during dry_run for transactions like request_add_stake.

### PR DESCRIPTION
**Pull request by sergiupopescu199**
# Description of change

This PR fixes a panic during `dry_run_transaction_block` when the transaction dynamically loads child objects at runtime (e.g. staking pool objects in `request_add_stake`).

Previously, the node's JSON-RPC `dry_run` used `ObjectProviderCache` backed by the full `AuthorityState`, which could resolve any object from the node's database as a fallback. With the gRPC migration, balance and object change computation moved to the indexer, which only had objects from the `simulate_transaction` response — no fallback. Dynamically loaded objects (not in the response's input/output sets) caused a panic.
 
The fix introduces `TxObjectResolver`, which checks the in-memory cache first (simulate response objects), then falls back to the indexer's `objects` table for any missing objects.

## Links to any relevant issues

fixes #11085 

## How the change has been tested

Describe the tests that you ran to verify your changes.

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [x] Patch-specific tests (correctness, functionality coverage)

- Tested the by applying the changes on a branch that mathes the version deployed on the devnet
```shell
git log --oneline -1
git checkout -b fix/dry-run-object-resolution v1.20.0-beta
git cherry-pick <commit-hash>
```
- Started locally a indexer reader by providng as database the devent one and the node gRPC, 
- Ran the query which was previously was panicking 
```shell
curl --location 'localhost:9000' \
--header 'content-type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": 57,
    "method": "iota_dryRunTransactionBlock",
    "params": [
        "AAADAAgA1hF+AwAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUBAAAAAAAAAAEAIERrerzKU8WOumcgMJvujVAXrRD95mbzl7ucBHVsGCWXAgIAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwtpb3RhX3N5c3RlbRFyZXF1ZXN0X2FkZF9zdGFrZQADAQEAAgAAAQIAy7PxV/mY4SLcAGbzpg3Lj3bjD5vA4nLOGtR0S0xKDHYAy7PxV/mY4SLcAGbzpg3Lj3bjD5vA4nLOGtR0S0xKDHboAwAAAAAAAAB0O6QLAAAAAA=="
    ]
}'
```
- Response received.

### Infrastructure QA (only required for crates that are maintained by @iotaledger/infrastructure)

- [ ] Synchronization of the indexer from genesis for a network including migration objects.
- [ ] Restart of indexer synchronization locally without resetting the database.
- [ ] Restart of indexer synchronization on a production-like database.
- [ ] Deployment of services using Docker.
- [ ] Verification of API backward compatibility.

> [!NOTE]
> This patch does not affect the ingestion path, thus no further tests were conducted

### CODE REVIEW

**Review by bingyanglin — APPROVED** [review]

File: crates/iota-indexer/src/apis/write_api.rs [hunk 1]
```diff
@@ -519,3 +523,105 @@ impl IotaRpcModule for OptimisticWriteApi {
...
+    pub(crate) async fn get_changes(
+        &self,
+        tx: &TransactionData,
+        effects: &TransactionEffects,
+        tx_digest: &TransactionDigest,
+    ) -> IndexerResult<(
+        Vec<iota_json_rpc_types::BalanceChange>,
+        Vec<IndexedObjectChange>,
+    )> {
+        let object_change: Vec<_> = get_object_changes(
```
Comment (kodemartin) [inline crates/iota-indexer/src/apis/write_api.rs]: nit: 
```suggestion
        let object_changes: Vec<_> = get_object_changes(
```

File: crates/iota-indexer/src/apis/write_api.rs [hunk 2]
```diff
@@ -519,3 +523,105 @@ impl IotaRpcModule for OptimisticWriteApi {
...
+            tx.sender(),
+            effects.modified_at_versions(),
+            effects.all_changed_objects(),
+            effects.all_removed_objects(),
+        )
+        .await?
+        .into_iter()
+        .map(IndexedObjectChange::from)
+        .collect();
+        let balance_change = get_balance_changes_from_effect(
```
Comment (kodemartin) [inline crates/iota-indexer/src/apis/write_api.rs]: Nit: 
```suggestion
        let balance_changes = get_balance_changes_from_effect(
```

File: crates/iota-indexer/src/apis/write_api.rs [hunk 3]
```diff
@@ -519,3 +523,105 @@ impl IotaRpcModule for OptimisticWriteApi {
...
+            self,
+            effects,
+            tx.input_objects().unwrap_or_else(|e| {
+                panic!("checkpointed tx {tx_digest:?} has invalid input objects: {e}")
+            }),
+            None,
+        )
+        .await?;
+        Ok((balance_change, object_change))
```
Comment (kodemartin) [inline crates/iota-indexer/src/apis/write_api.rs]: Nit: 
```suggestion
        Ok((balance_changes, object_changes))
```

File: crates/iota-indexer/src/apis/write_api.rs [hunk 4]
```diff
@@ -519,3 +523,105 @@ impl IotaRpcModule for OptimisticWriteApi {
...
+#[async_trait]
+impl ObjectProvider for TxObjectResolver {
+    type Error = IndexerError;
+
+    async fn get_object(
+        &self,
+        id: &ObjectID,
+        version: &SequenceNumber,
+    ) -> Result<Object, Self::Error> {
+        // try in-memory cache first (simulate response objects)
```
Comment (kodemartin) [inline crates/iota-indexer/src/apis/write_api.rs]: This is something that can be used beyond the scope of `simulate` endpoints. 

```suggestion
        // try in-memory cache first 
```

File: crates/iota-indexer/src/apis/write_api.rs [hunk 5]
```diff
@@ -519,3 +523,105 @@ impl IotaRpcModule for OptimisticWriteApi {
...
+        if let Some(o) = self.object_cache.get(id, Some(version)) {
+            return Ok(o.clone());
+        }
+
+        // fallback: query the indexer's objects table.
+        // for dry_run, the pre-mutation version should match the latest
+        // version in the objects table since the simulation didn't commit.
```
Comment (kodemartin) [inline crates/iota-indexer/src/apis/write_api.rs]: Here too, adding a simulate-specific comment in a function that can be used in different scopes is a bit misleading. 

I believe that this comment seems more fit for the caller, if you find it important.

**Review by kodemartin — APPROVED** [review]
Looks good with a few minor suggestions.

File: crates/iota-indexer/src/apis/write_api.rs [hunk 6]
```diff
@@ -519,3 +523,105 @@ impl IotaRpcModule for OptimisticWriteApi {
...
+        id: &ObjectID,
+        version: &SequenceNumber,
+    ) -> Result<Object, Self::Error> {
+        // try in-memory cache first (simulate response objects)
+        if let Some(o) = self.object_cache.get(id, Some(version)) {
+            return Ok(o.clone());
+        }
+
+        // fallback: query the indexer's objects table.
+        // for dry_run, the pre-mutation version should match the latest
```
Comment (tomxey) [inline crates/iota-indexer/src/apis/write_api.rs]: this doesn't have to be true, other txs can be executed in the meantime that bump the version of objects

File: crates/iota-indexer/src/apis/write_api.rs [hunk 7]
```diff
@@ -519,3 +523,105 @@ impl IotaRpcModule for OptimisticWriteApi {
...
+
+        // try latest in cache
+        if let Some(o) = self.object_cache.get(id, None) {
+            if o.version() <= *version {
+                return Ok(Some(o.clone()));
+            }
+        }
+
+        // fallback to indexer DB
+        self.reader.get_object_in_blocking_task(*id).await
```
Comment (tomxey) [inline crates/iota-indexer/src/apis/write_api.rs]: what if live objects table has a different version?

maybe it would be better to return an error instead of wrong simulation results?

Comment (sergiupopescu199) [reply crates/iota-indexer/src/apis/write_api.rs]: fixed: https://github.com/iotaledger/iota/pull/11088/commits/2718713ae2b2ad32fbcf1d1672761ce0fa939622

File: crates/iota-indexer/src/apis/write_api.rs (hunk 6 above)
Comment (sergiupopescu199) [reply crates/iota-indexer/src/apis/write_api.rs]: fixed: https://github.com/iotaledger/iota/pull/11088/commits/2718713ae2b2ad32fbcf1d1672761ce0fa939622

File: crates/iota-indexer/src/apis/write_api.rs (hunk 5 above)
Comment (sergiupopescu199) [reply crates/iota-indexer/src/apis/write_api.rs]: fixed: https://github.com/iotaledger/iota/pull/11088/commits/2718713ae2b2ad32fbcf1d1672761ce0fa939622

**Review by tomxey — APPROVED** [review]
