### PR TITLE
fix(iota-open-rpc-macros): proper handling of empty line doc comments 

### LINKED ISSUE #5176: fix(open-rpc): Handle empty doc comment lines
https://github.com/MystenLabs/sui/commit/80198bed01996d973176dbce67bbf0f07197939c

### PR DESCRIPTION
**Pull request by Alex6323**
# Description of change

Fixes the `extract_doc_comments` function in `iota-open-rpc-macros` and makes it more flexible regarding empty lines in doc comments.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/5176

Upstream PR: https://github.com/MystenLabs/sui/commit/80198bed01996d973176dbce67bbf0f07197939c

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

```sh
cargo run -p iota-graphql-rpc -- generate-schema -f schema.sdl
```
does not panic any longer, when there's an empty line doc comment on any of the extracted API traits from `iota-json-rpc-api`. 
Such a comment on any of the trait functions would currently panic:

```rust
/// A
///
/// B
```
The empty doc comment line must not contain any additional whitespace for the panic to occur.

### CODE REVIEW

**Review by Thoralf-M — APPROVED** [review]

**Review by DaughterOfMars — APPROVED** [review]

File: crates/iota-open-rpc-macros/src/lib.rs [hunk 1]
```diff
@@ -336,21 +336,42 @@ fn respan_token_stream(stream: TokenStream2, span: Span) -> TokenStream2 {
...
-                }
-        })
-        .map(|attr| {
-            let s = attr.tokens.to_string();
-            s[4..s.len() - 1].to_string()
-        })
-        .join(" ");
+    let mut s = String::new();
+    let mut sep = "";
+    for attr in attrs {
```
Comment (thibault-martinez) [inline crates/iota-open-rpc-macros/src/lib.rs:349]:
```suggestion
    
    for attr in attrs {
```

**Review by thibault-martinez — APPROVED** [review]
