### PR TITLE
fix: Unify `--version` output for CLIs

### LINKED ISSUE #5210: [binaries] add --version option to all binaries and normalize version
## Description

1) --version option is missing for iota-indexer and iota-faucet

2) For other binaries, version is not homogeneous (commit hash is sometimes mentioned, sometimes not) : 

>iota --version
>iota 0.9.2-beta-4c6a57fe30fb
>
>iota-graphql-rpc --version
>iota-graphql-rpc 0.9.2-beta
>
>iota-bridge --version
>iota-bridge 0.9.2-beta-4c6a57fe30fb
>
>iota-tool --version
>iota-tool 0.9.2-beta-4c6a57fe30fb

Maybe output only corresponding tag's name (including v), without commit hash nor binary's name ?

>iota --version
>v0.9.2-beta

## Motivation

Need to know exact version of each binary

## Requirements

Write a list of what you want this feature to do.

1. add --version option for all binaries
2. normalize version = tag's name
3.

## Open questions (optional)

.

## Are you planning to do it yourself in a pull request?

No.

### PR DESCRIPTION
**Pull request by DaughterOfMars**
## Description 

Unifies the `--version` output for the following CLIs:

- `iota-faucet`
- `iota-graphql-rpc`
- `iota-indexer`

Based on the output from the following:

- `iota`
- `iota-bridge`
- `iota-tool`

Some of these required adding the version argument outside of the derive as the `bin_version!` macro can only be run from a binary and will error if the file is included in a lib, meaning it basically can only go in `main.rs`. Because some of the commands are defined in the lib for sharing, the version cannot be added in the derive.

## Related Issues

Closes #5210

### Release Notes

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] gRPC:
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [x] CLI: Unified `--version` flags across CLI commands.
- [ ] Rust SDK:

### CODE REVIEW

File: crates/iota-graphql-rpc/src/main.rs
Comment (Thoralf-M) [inline crates/iota-graphql-rpc/src/main.rs:1]: So how does the output look now if you run `--version`?

Comment (DaughterOfMars) [reply crates/iota-graphql-rpc/src/main.rs:1]: They all look like this: `iota-graphql-rpc 0.10.0-alpha-6b45695532c7-debug`
`-debug` is added if the binary has debug symbols.

File: crates/iota-graphql-rpc/src/main.rs [hunk 1]
```diff
@@ -13,28 +13,21 @@ use iota_graphql_rpc::{
 use tokio_util::{sync::CancellationToken, task::TaskTracker};
 
 // Define the `GIT_REVISION` const
```
Comment (thibault-martinez) [inline crates/iota-graphql-rpc/src/main.rs]:
```suggestion
// Define the `GIT_REVISION` and `VERSION` consts
```

Comment (DaughterOfMars) [reply crates/iota-graphql-rpc/src/main.rs:15]: This one doesn't do both

File: crates/iota-faucet/src/main.rs [hunk 2]
```diff
@@ -4,22 +4,28 @@
...
 #[tokio::main]
 async fn main() -> Result<(), anyhow::Error> {
     // initialize tracing
     let _guard = telemetry_subscribers::TelemetryConfig::new()
         .with_env()
         .init();
 
-    let config: FaucetConfig = FaucetConfig::parse();
+    let config = FaucetConfig::from_arg_matches_mut(
+        &mut FaucetConfig::command().version(VERSION).get_matches(),
```
Comment (thibault-martinez) [inline crates/iota-faucet/src/main.rs:26]: Can you briefly explain this change please?

Comment (DaughterOfMars) [reply crates/iota-faucet/src/main.rs:26]: I explained it in the description

**Review by Thoralf-M — APPROVED** [review]

File: crates/iota-graphql-rpc/src/main.rs [hunk 3]
```diff
@@ -4,37 +4,30 @@
...
 use tokio_util::{sync::CancellationToken, task::TaskTracker};
 
-// Define the `GIT_REVISION` const
-bin_version::git_revision!();
+// Define the `GIT_REVISION` and `VERSION` consts
+bin_version::bin_version!();
 
 // VERSION mimics what other iota binaries use for the same const
-static VERSION: Version = Version {
+static VERSION_VAL: Version = Version {
```
Comment (Alex6323) [inline crates/iota-graphql-rpc/src/main.rs:19]: should this comment now say `VERSION_VAL` mimics .... ?

Comment (DaughterOfMars) [reply crates/iota-graphql-rpc/src/main.rs:19]: Yeah, probably 😆

File: crates/iota-graphql-rpc/src/main.rs [hunk 4]
```diff
@@ -4,37 +4,30 @@
...
     server::{builder::export_schema, graphiql_server::start_graphiql_server},
 };
 use tokio_util::{sync::CancellationToken, task::TaskTracker};
 
-// Define the `GIT_REVISION` const
-bin_version::git_revision!();
+// Define the `GIT_REVISION` and `VERSION` consts
+bin_version::bin_version!();
 
 // VERSION mimics what other iota binaries use for the same const
```
Comment (DaughterOfMars) [inline crates/iota-graphql-rpc/src/main.rs]:
```suggestion
// VERSION_VAL mimics what other iota binaries use for the VERSION const
```

**Review by sergiupopescu199 — APPROVED** [review]
