### PR TITLE
fix(consensus): handle errors from `SerializedBlockBundle::try_from`

### LINKED ISSUE #8225: Handle errors from `SerializedBlockBundle::try_from` in `handle_subscribe_block_bundles_request`

### PR DESCRIPTION
**Pull request by filipdulic**
# Description of change

Implements error handling via logging to not disturb/break stream processing on a single block header fault.
## Links to any relevant issues

fixes #8225 

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [ ] Patch-specific tests (correctness, functionality coverage)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### Release Notes

- [ ] Protocol:
- [ ] Nodes (Validators and Full nodes):
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [ ] CLI:
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: crates/starfish/core/src/authority_service.rs [hunk 1]
```diff
@@ -503,13 +503,17 @@ impl<C: CoreThreadDispatcher> NetworkService for AuthorityService<C> {
         // If last_received is a valid and more blocks have been proposed since then,
         // this call is guaranteed to return at least some recent blocks, which
         // will help with liveness.
-        // TODO:: do we need to add some headers here?
```
Comment (filipdulic) [inline crates/starfish/core/src/authority_service.rs:506]: #8224 issue created to investigate this TODO.

**Review by piotrm50 — APPROVED** [review]
