### PR TITLE
fix(starfish): eviction acks from tracker

### LINKED ISSUE #8243: starfish: fix bug with eviction from transactions tracker
Currently we evict from the transaction tracker at the moment when the commited leader is going forward. However, some transactions could be unavailable and the tracker is also used to get information who acknowledged availability of that data. This makes impossible for transactions synchronizer to get the required information

### PR DESCRIPTION
**Pull request by polinikita**
# Description of change

Right now eviction from ack tracker in linearizer is done whenever we progress pending commits. However, we should keep this information until the commit gets solid, i.e., all transactions committed to it are locally available. Otherwise, the transaction synchronizer, which relies on the ack tracker, will not get information about authorities that marked the data as available.

## Links to any relevant issues

Fixes #8243 

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [ ] Patch-specific tests (correctness, functionality coverage)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### Release Notes

- [ ] Protocol:
- [ ] Nodes (Validators and Full nodes):
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [ ] CLI:
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: crates/starfish/core/src/commit_observer.rs [hunk 1]
```diff
@@ -143,6 +143,17 @@ impl CommitObserver {
...
+        // Evict the ack tracker using the information from the latest solid subdag
+        if !solid_sub_dags.is_empty() {
+            let max_solid_commit_leader_round = solid_sub_dags
+                .last()
+                .expect("There should be at least one solid subdag")
+                .leader
+                .round;
+            self.commit_interpreter
+                .evict_old_acknowledgments(max_solid_commit_leader_round);
+        }
```
Comment (filipdulic) [inline crates/starfish/core/src/commit_observer.rs:156]: Nit: You could simplify this block using if let Some(...), which avoids is_empty() + expect and makes the intent a bit clearer IMO.
```suggestion
        if let Some(last_solid_sub_dag) = solid_sub_dags.last() {
            self.commit_interpreter
                .evict_old_acknowledgments(last_solid_sub_dag.leader.round);
        }
```

**Review by filipdulic — APPROVED** [review]

**Comment by filipdulic** [comment]
Great catch :+1:

File: crates/starfish/core/src/dag_state.rs [hunk 2]
```diff
@@ -340,21 +340,18 @@ impl DagState {
...
         info!(
-            "Last commit with available transactions has leader at round {}; last commit leader round was {}",
-            last_available_commit_leader_round, max_commit_round
+            "Last solid commit has leader at round {}; last pending commit has leader at round {}",
+            last_solid_commit_leader_round, max_commit_round
         );
-        self.last_available_commit_leader_round = Some(last_available_commit_leader_round);
-        let gap = last_available_commit_leader_round.saturating_sub(*max_commit_round);
+        self.last_solid_commit_leader_round = Some(last_solid_commit_leader_round);
+        let gap = (*max_commit_round).saturating_sub(last_solid_commit_leader_round);
```
Comment (VorobyevIlya) [inline crates/starfish/core/src/dag_state.rs:354]: I'm a little confused. Why did we subtract max_commit_round before, and now we subtract from max_commit_round? Was it a bug before?

**Review by VorobyevIlya — APPROVED** [review]

File: crates/starfish/core/src/dag_state.rs (hunk 2 above)
Comment (polinikita) [reply crates/starfish/core/src/dag_state.rs:354]: Yes! We overlooked that. It was constantly zero
