### PR TITLE
fix(wallet,wallet-dashboard): fix total stake/unstake amount in timelocks transaction summary

### LINKED ISSUE #4779: Fix total stake/unstake amount in timelocks transaction summary
there seems to be an issue displaying the correct amount in the TransactionReceipt for timeocked staking and unstaking.
eg. i have staked 12 iota and tx is correct but the receipt only shows amount from one object 2 IOTA (there are 6 objects of 2 iota in tx to stake the 12)

Image

### PR DESCRIPTION
**Pull request by evavirseda**
# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/4779

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: apps/core/src/components/transaction/TransactionReceipt.tsx [hunk 1]
```diff
@@ -51,6 +57,7 @@ export function TransactionReceipt({
                             gasSummary={summary?.gas}
                             renderValidatorLogo={renderValidatorLogo}
                             renderExplorerLink={renderExplorerLink}
+                            timelockedStakingAmount={timelockedStakingAmount}
```
Comment (begonaalvarezd) [inline apps/core/src/components/transaction/TransactionReceipt.tsx]: wouldnt it be better passing the events instead so the calculation is directly in the StakeTransactionDetails & UnstakeTransactionInfo, just a thought

Comment (begonaalvarezd) [reply apps/core/src/components/transaction/TransactionReceipt.tsx]: That would imply a change in `getStakeDetailsFromEvent` to make it from events in array form, but it might be more flexible

**Review by begonaalvarezd — APPROVED** [review]

File: apps/core/src/utils/stake/getTransactionAmountForTimelocked.ts [hunk 2]
```diff
@@ -15,8 +11,13 @@ export function getTransactionAmountForTimelocked(
     const { isTimelockedStaking, isTimelockedUnstaking } = checkIfIsTimelockedStaking(events);
 
     if (isTimelockedStaking) {
-        const { stakedAmount } = getStakeDetailsFromEvent(events[0]);
-        return stakedAmount;
+        let amount = 0;
+        events?.forEach((event) => {
```
Comment (cpl121) [inline apps/core/src/utils/stake/getTransactionAmountForTimelocked.ts]: we can better use a reduce, wdyt?

**Review by cpl121 — CHANGES_REQUESTED** [review]
The unstake amount is not adding up well
image

File: apps/core/src/utils/stake/getUnstakeDetailsFromEvents.ts [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+        return sum + Number((event.parsedJson as { reward_amount: number }).reward_amount || 0);
+    }, 0);
+
+    const totalUnstakeAmount = BigInt(totalAmountWithoutRewards) + BigInt(totalRewards);
+
+    return {
+        validatorAddress: eventJson.validator_address || '',
+        totalAmountWithoutRewards: BigInt(totalAmountWithoutRewards),
+        totalRewards: BigInt(totalRewards),
+        totalUnstakeAmount,
```
Comment (cpl121) [inline apps/core/src/utils/stake/getUnstakeDetailsFromEvents.ts]: I think we can improve these names. `totalAmountWithoutRewards` is confusing to me as it seems like we are subtracting the rewards from the total value when we are not doing this. We get the amount that was staked, then the rewards obtained, and then we calculate the total by adding them together.

wdyt about -> unstakeAmount  / unstakeRewards / totalUnstakeAmount

File: apps/core/src/utils/stake/getUnstakeDetailsFromEvents.ts [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+import type { IotaEvent } from '@iota/iota-sdk/client';
+
+export function getUnstakeDetailsFromEvents(events: IotaEvent[]): {
+    validatorAddress: string;
+    totalAmountWithoutRewards: bigint;
+    totalUnstakeAmount: bigint;
+    totalRewards: bigint;
+} {
+    const unstakeEvent = events.find(({ type }) => type === UNSTAKING_REQUEST_EVENT);
+    const eventJson = unstakeEvent?.parsedJson as UnstakeEventJson;
```
Comment (cpl121) [inline apps/core/src/utils/stake/getUnstakeDetailsFromEvents.ts]:
```suggestion
    const unstakeEventJson = unstakeEvent?.parsedJson as UnstakeEventJson;
```

File: apps/core/src/utils/stake/getTransactionAmountForTimelocked.ts [hunk 5]
```diff
@@ -15,10 +15,10 @@ export function getTransactionAmountForTimelocked(
     const { isTimelockedStaking, isTimelockedUnstaking } = checkIfIsTimelockedStaking(events);
```
Comment (cpl121) [inline apps/core/src/utils/stake/getTransactionAmountForTimelocked.ts]: We can pass this info by prop and remove that function from here. In the places where `getTransactionAmountForTimelocked` is called, it is checked if the tx is timelocked or not, so `checkIfIsTimelockedStaking` is called twice

**Review by cpl121 — CHANGES_REQUESTED** [review]
Just minimal comments 🙏🏼

**Review by cpl121 — APPROVED** [review]
