### PR TITLE
fix(core): Do not wait on notify_read_effects for transactions that may be reverted after the epoch ends

### LINKED ISSUE #4674: [cherrypick] Must not wait on notify_read_effects after epoch ends, o… · MystenLabs/sui@bf79606
[[cherrypick] Must not wait on notify_read_effects after epoch ends, o… · MystenLabs/sui@bf79606](https://github.com/MystenLabs/sui/commit/bf79606ff4eb7c666629f14157715c1219504fed)   

bug fix to avoid crash. Description from the original PR: Found this crash after adding the delay failpoint seen in this PR. I don't quite understand why that exposed this crash.

### PR DESCRIPTION
**Pull request by jkrvivian**
# Description of change

Merge an upstream fix: https://github.com/MystenLabs/sui/commit/bf79606ff4eb7c666629f14157715c1219504fed

Do not wait on notify_read_effects for transactions that may be reverted after the epoch ends.

## Links to any relevant issues

#4674 

## Type of change

- Bug fix 

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota-core/src/authority.rs [hunk 1]
```diff
@@ -1132,7 +1132,14 @@ impl AuthorityState {
...
 
-        self.notify_read_effects(certificate).await
+        // tx could be reverted when epoch ends, so we must be careful not to return a
+        // result here after the epoch ends.
+        epoch_store
+            .within_alive_epoch(self.notify_read_effects(certificate))
+            .await
+            .map_err(|_| IotaError::EpochEnded(epoch_store.epoch()))
+            .and_then(|r| r)
+        // self.notify_read_effects(certificate).await
```
Comment (muXxer) [inline crates/iota-core/src/authority.rs]:
```suggestion
```

**Review by muXxer — COMMENTED** [review]
There was also a change in `await_transaction_effects` on upstream, which doesn't exist yet in our version. Is this important as well?

**Comment by jkrvivian** [comment]
> There was also a change in `await_transaction_effects` on upstream, which doesn't exist yet in our version. Is this important as well?

The `await_transaction_effects` function has been separated from `handle_certificates`. This change was introduced in a previous PR (https://github.com/MystenLabs/sui/pull/19401, included from v1.35.1), which added `TransactionV2` RPC handler related to Mysticeti fastpath. I believe the consensus team will decide whether to implement the `TransactionV2` changes. However, in this PR, I only apply changes that are compatible with the current codebase. 😃

**Review by piotrm50 — APPROVED** [review]

File: crates/iota-core/src/authority.rs [hunk 2]
```diff
@@ -2906,7 +2912,16 @@ impl AuthorityState {
...
         self.metrics.reset_on_reconfigure();
         self.committee_store.insert_new_committee(&new_committee)?;
+
+        // Wait until no transactions are being executed.
         let mut execution_lock = self.execution_lock_for_reconfiguration().await;
+
+        // Terminate all epoch-specific tasks (those started with within_alive_epoch).
+        cur_epoch_store.epoch_terminated().await;
+
+        // Safe to being reconfiguration now. No transactions are being executed,
```
Comment (gokhan-simsek-iota) [inline crates/iota-core/src/authority.rs]: "Safe to reconfigure now." ?

**Review by muXxer — APPROVED** [review]
