### PR TITLE
fix(wallet,explorer): Reconfigure Amplitude

### LINKED ISSUE #4950: Fix Amplitude codegen of Wallet and Explorer
They are missconfigured and the codegen is wrong and outdated

### PR DESCRIPTION
**Pull request by marc2332**
Closes https://github.com/iotaledger/iota/issues/4950

### CODE REVIEW

File: apps/explorer/src/lib/utils/analytics/amplitude.ts [hunk 1]
```diff
@@ -12,15 +12,20 @@ const IS_PROD_ENV = import.meta.env.PROD;
 
 export const persistableStorage = new PersistableStorage<UserSession>();
 
+const ApiKey = {
+    production: '896b9073219c06800d9bf0aecf1b6f80',
+    development: '253fa1582d8ed913d8c5957f601df3fe',
```
Comment (cpl121) [inline apps/explorer/src/lib/utils/analytics/amplitude.ts:17]: I assume this API key is public, right? 🥲

File: apps/wallet/src/shared/analytics/amplitude.ts [hunk 2]
```diff
@@ -12,12 +12,17 @@ const IS_PROD_ENV = process.env.NODE_ENV === 'production';
 
 export const persistableStorage = new PersistableStorage<UserSession>();
 
+const ApiKey = {
+    production: '2a5d35822a1bab41835813f0223f319e',
+    development: '30a15c4ef8ae0e10ce5d2ed4f0023de3',
```
Comment (cpl121) [inline apps/wallet/src/shared/analytics/amplitude.ts:17]: I assume this API key is public, right? 🥲

File: apps/explorer/src/lib/utils/analytics/amplitude.ts (hunk 1 above)
Comment (marc2332) [reply apps/explorer/src/lib/utils/analytics/amplitude.ts:17]: Yes, I already told you in slack, these apis keys are public, whats private is called API Token.

**Review by cpl121 — APPROVED** [review]

**Review by begonaalvarezd — APPROVED** [review]
