### PR TITLE
fix(indexer): enable partition pruning when fetching StoredTransactions

### LINKED ISSUE #9983: [iota-indexer]: `iota_getTransactionBlock` & `iota_multiGetTransactionBlocks` db queries triggers a scan of all partitions.
On `alphanet` we noticed that when requesting one or more transaction blocks it would take several seconds to return the response. On other networks it would take several milliseconds.

We noticed that the db query was not performing partition pruning, thus it triggered the scan of all partitions.

### PR DESCRIPTION
**Pull request by sergiupopescu199**
# Description of change

This patch refactors the database query in order to use partition pruning when requesting one or multiple `StoredTransaction`.

The postgres query planner was not able to execute partition pruning when using `JOIN` or `IN` clauses.
This [response](https://www.postgresql.org/message-id/CAKJS1f9nWfAYDMF8-ysG%3DTQZ5r9vB%3Dpkk7-y7zQKdZExOraJ3w%40mail.gmail.com) does add some more context.

## Links to any relevant issues

fixes #9983

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [ ] Patch-specific tests (correctness, functionality coverage)

- Connected the indexer reader to `alphanet` database and executed the following JSON RPC query
```shell
curl --location 'localhost:9000' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "iota_multiGetTransactionBlocks",
    "params": [
        [
            "AUKbNtEvQzL8JJBTeLAwGV6z76C8829gtjgqVGDiRJP2",
            "Dgs1TReXNrM8fPpxbG56hM69Mmucvmm6b1xoHoc6NMq8",
            "AiTcsZFcxzBMCcKJWKnaHDoPq8Y5bVnHjGMheXFTiwXM"
        ],
        {
            "showInput": true,
            "showRawInput": false,
            "showEffects": true,
            "showEvents": true,
            "showObjectChanges": false,
            "showBalanceChanges": false,
            "showRawEffects": false
        }
    ]
}'
```
it takes around 120ms compared to 10s-13s.

### Infrastructure QA (only required for crates that are maintained by @iotaledger/infrastructure)

- [ ] Synchronization of the indexer from genesis for a network including migration objects.
- [ ] Restart of indexer synchronization locally without resetting the database.
- [ ] Restart of indexer synchronization on a production-like database.
- [ ] Deployment of services using Docker.
- [x] Verification of API backward compatibility.

> [!NOTE]
> This patch does not impact the ingestion pipeline, only the JSON RPC part which was tested.

### CODE REVIEW

**Review by tomxey — APPROVED** [review]

File: crates/iota-indexer/src/read.rs [hunk 1]
```diff
@@ -2769,15 +2769,22 @@ impl<'a> DBReader<'a> {
         digests: Vec<Vec<u8>>,
     ) -> IndexerResult<Vec<StoredTransaction>> {
         let pool = self.main_reader.get_pool();
+
         run_query_async!(&pool, |conn| {
+            // we use a two step query to enable partition pruning.
+            // using JOIN or IN clauses do not support partition pruning and triggers a scan
```
Comment (kodemartin) [inline crates/iota-indexer/src/read.rs]: This is not entirely true. Both JOIN and IN allow partition pruning when conditions contain literal values. E.g. `IN (1, 2, 3)` or `ON <condition> AND <partition-key> IN (literals)`

The second query below actually uses IN.

It is when using expressions whose values are not known during planing or execution that this does not work. You can also add the link to the Postgres mail thread.

**Review by kodemartin — APPROVED** [review]
lgtm with a small suggestion

File: crates/iota-indexer/src/read.rs (hunk 1 above)
Comment (sergiupopescu199) [reply crates/iota-indexer/src/read.rs]: fixed: https://github.com/iotaledger/iota/pull/9984/commits/63334041de11c4866f85943a12a18b5dd8e4eb6c
