### PR TITLE
fix(iota-indexer): Filter `move_call_metrics` based on latest epoch

### LINKED ISSUE #5364: [indexer rpc]: getMoveCallMetrics may return duplicate metrics
## Description

The `iotax_getMoveCallMetrics` method in `iota-indexer` uses this query to fetch the latest metrics:

https://github.com/iotaledger/iota/blob/0355a82d9a25cfbe9a6ea9f2f5e70c898c9952ab/crates/iota-indexer/src/indexer_reader.rs#L1583-L1587

where the `move_call_metrics` table is defined as follows:

https://github.com/iotaledger/iota/blob/0355a82d9a25cfbe9a6ea9f2f5e70c898c9952ab/crates/iota-indexer/migrations/pg/2023-10-04-161107_move_call_metrics/up.sql#L12-L22

This query tries to fetch the 10 most used functions that may have been calculated in **any** epoch in the last 10 rows inserted for the respective 3-,7-, or 30-day. This obviously may lead to duplicate or overlapping metrics under certain corner cases that may occur during testing (e.g. exclusive calls of certain function during the most recent epochs). 

We should therefore eliminate duplicate results.

Issue originally reported @philou-078 [in discord](https://discord.com/channels/912718559954747442/1282254816525156476/1337087092412645436)

### PR DESCRIPTION
**Pull request by samuel-rufi**
# Description of change

Filters `move_call_metrics` based on latest epoch to avoid duplicate entries.

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/5364

## How the change has been tested

At localhost, deployed packages, executed function calls and fetched `iotax_getMoveCallMetrics` with `curl`.

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## Change checklist

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota-indexer/src/indexer_reader.rs [hunk 1]
```diff
@@ -1579,22 +1579,34 @@ impl IndexerReader {
...
 
     pub fn get_latest_move_call_metrics(&self) -> IndexerResult<MoveCallMetrics> {
+        let latest_epoch = run_query!(&self.pool, |conn| {
+            move_call_metrics::table
+                .select(move_call_metrics::dsl::epoch)
+                .order(move_call_metrics::dsl::epoch.desc())
+                .limit(1)
+                .first::<i64>(conn)
+        })
+        .map_err(|_| IndexerError::PostgresRead("record not found".to_string()))?;
```
Comment (sergiupopescu199) [inline crates/iota-indexer/src/indexer_reader.rs]: It's OK to have a generic error message or `latest epoch record not found` could suit better as error message?

**Review by sergiupopescu199 — APPROVED** [review]
lgtm 🐼

File: crates/iota-indexer/src/indexer_reader.rs [hunk 2]
```diff
@@ -1579,22 +1579,34 @@ impl IndexerReader {
...
+
         let latest_3d_move_call_metrics = run_query!(&self.pool, |conn| {
             move_call_metrics::table
+                .filter(move_call_metrics::dsl::epoch.eq(latest_epoch))
```
Comment (kodemartin) [inline crates/iota-indexer/src/indexer_reader.rs]: Using a subquery here would avoid the need for an additional query in L1582 to fetch the latest epoch. Something equivalent to `WHERE epoch = (SELECT MAX(epoch) from move_call_metrics WHERE day = 3)`

Note that we should also select the `MAX(epoch)` for the desired `day` (in this case 3).

File: crates/iota-indexer/src/indexer_reader.rs (hunk 1 above)
Comment (samuel-rufi) [reply crates/iota-indexer/src/indexer_reader.rs]: Yes, better me more clear about it!

File: crates/iota-indexer/src/indexer_reader.rs (hunk 2 above)
Comment (samuel-rufi) [reply crates/iota-indexer/src/indexer_reader.rs]: Thanks for the suggestion! Good point, we should match the day too (also considering there is an index that would make it more efficient). I tried to solve it using diesel alias tables but unfortunately this doesn't seem trivial and I'm not sure at this point if sub query filtering is supported. I therefore propose to use a raw query (also for simplicity and readability) similarly as we do for other queries and auto-deserializing the data using `load()` into `QueriedMoveCallMetrics`.

Comment (samuel-rufi) [reply crates/iota-indexer/src/indexer_reader.rs]: Fixed by: https://github.com/iotaledger/iota/pull/5648/commits/c4b0e2f548d0a23bc33ca913e03cf596694d1154

Tested and everything looks good.

File: crates/iota-indexer/src/indexer_reader.rs [hunk 3]
```diff
@@ -1582,40 +1585,33 @@ impl IndexerReader {
...
+            sql_query(query)
+                .bind::<BigInt, _>(day_value)
+                .load::<QueriedMoveCallMetrics>(conn)?
+                .into_iter()
+                .map(|m| {
+                    m.try_into()
+                        .map_err(|e| diesel::result::Error::DeserializationError(Box::new(e)))
+                })
+                .collect()
+        };
```
Comment (kodemartin) [inline crates/iota-indexer/src/indexer_reader.rs]: Nit: Move to a dedicated function. This will improve readability, testing, reuseability.

**Review by kodemartin — APPROVED** [review]
lgtm :beach_umbrella:

File: crates/iota-indexer/src/indexer_reader.rs (hunk 3 above)
Comment (samuel-rufi) [reply crates/iota-indexer/src/indexer_reader.rs]: Fixed with https://github.com/iotaledger/iota/pull/5648/commits/961202c2fb4be9b8f2547e6488624601536d4cb4
