### PR TITLE
feat(consensus): fix consensus committed messages metric

### LINKED ISSUE #9017: Refactor BPS metric for Starfish
In Starfish the metric `consensus_committed_messages` has changed it's meaning and is not comparable with the same metric for Mysticeti. This is a bit confusing and problematic, because node operators' and our internal monitoring tool use this metric as one of the healthchecks. This should be changed to measure committed block headers and a new metric should be introduced to measure committed blocks with transactions.

### PR DESCRIPTION
**Pull request by VorobyevIlya**
# Description of change

PR fixes consensus_committed_messages that worked incorrectly for starfish and counted only blocks with non-empty vector of transactions.

## Links to any relevant issues

fixes #9017 

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [ ] Patch-specific tests (correctness, functionality coverage)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by filipdulic — APPROVED** [review]

File: crates/iota-core/src/consensus_handler.rs [hunk 1]
```diff
@@ -295,14 +295,19 @@ impl<C: CheckpointServiceNotify + Send + Sync> ConsensusHandler<C> {
             .with_label_values(&[&leader_author.to_string()])
             .inc();
 
+        for (authority_index, number_of_committed_headers) in
+            consensus_output.number_of_headers_in_commit_by_authority()
```
Comment (polinikita) [inline crates/iota-core/src/consensus_handler.rs:299]: The naming can be confusing for Mysticeti, but we can stick with this to not rename later.

**Review by polinikita — APPROVED** [review]

**Review by muXxer — APPROVED** [review]
