### PR TITLE
feat(apps-ui-kit): fix tooltip

### LINKED ISSUE #5851: Fix tooltip overflow
at some point, the tooltip component has changed, and this has caused it to appear cut off in some places

Image

### PR DESCRIPTION
**Pull request by evavirseda**
# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/5851

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: apps/wallet-dashboard/components/migration/migration-object-details-card/MigrationObjectDetailsCard.tsx [hunk 1]
```diff
@@ -171,7 +171,12 @@ function UnlockConditionLabel({ groupKey, isTimelocked: isTimelocked }: UnlockCo
                     text={`~${outputTimestampMsCountdown}`}
                     label={isTimelocked ? 'Unlocks in' : 'Expires in'}
                 />
-                <Tooltip maxWidth={0} position={TooltipPosition.Left} text={tooltipText}>
+                <Tooltip
+                    maxWidth="max-w-none
```
Comment (panteleymonchuk) [inline apps/wallet-dashboard/components/migration/migration-object-details-card/MigrationObjectDetailsCard.tsx:175]: following concept of passing class instead of number, maybe then better to pass className?
it will be more flexible. Wdyt?

**Review by panteleymonchuk — APPROVED** [review]

File: .changeset/sixty-points-itch.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@iota/apps-ui-kit': minor
```
Comment (begonaalvarezd) [inline .changeset/sixty-points-itch.md]: patch

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
nit

**Review by begonaalvarezd — APPROVED** [review]
