### PR TITLE
fix(nightly-tests): make nightly tests use the same nextest config as local and CI tests

### LINKED ISSUE #5192: Nightly checks: use same config as local/CI tests, make all pass
## Bug description

Flaky tests seem to fail during Nightly checks:
https://github.com/iotaledger/iota/actions/runs/13125355811

Seems like the new nextest.toml config for flaky tests is not used for nightly checks. Let's fix that by making nightly checks use the same config as local/PR tests. This should make nightly tests way more likely to pass.

### PR DESCRIPTION
**Pull request by nmrshll**
Flaky tests seem to fail during Nightly checks:
https://github.com/iotaledger/iota/actions/runs/13125355811

Seems like the new nextest.toml config for flaky tests is not used for nightly checks. Let's fix that by making nightly checks use the same config as local/PR tests. This should make nightly tests way more likely to pass.

# Description of change

Change nextest profile `simtestnightly` to include recent changes to CI test profile:
- give more retries to flaky tests, more time to slow tests before

Also added as side changes while testing:
- script functions to run cargo deny steps locally

## Links to any relevant issues

Fixes #5192 

## Type of change

- CI testing fix (a non-breaking change which fixes an issue)

## How the change has been tested

Ran nightly simtests locally:

```shell
PER_TEST_TIMEOUT_MS=180000 SIMTEST_LOGS_DIR="$(git rev-parse --show-toplevel)/.cache/simtest_logs" ./scripts/simtest/simtest-run.sh
```

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by DaughterOfMars — COMMENTED** [review]
I'd prefer that we keep the ci profile and just apply it as needed

File: scripts/ci_tests/rust_tests.sh [hunk 1]
```diff
@@ -178,6 +178,17 @@ function tests_using_postgres() {
...
 
+function deny() {
+    local MANIFEST_PATH=${MANIFEST_PATH:-"./Cargo.toml"}
+    cargo deny --manifest-path "$MANIFEST_PATH" check bans licenses sources
+    # check security advisories (in-house crates)
+    cargo deny --manifest-path "$MANIFEST_PATH" check advisories
+}
+
+function deny_external() {
+    MANIFEST_PATH="./external-crates/move/Cargo.toml" deny
```
Comment (muXxer) [inline scripts/ci_tests/rust_tests.sh]: does this line call the deny function then? Maybe add a comment, that wasn't clear to me at the first view, and I thought you forgot the "cargo" 😅

File: .config/nextest.toml [hunk 2]
```diff
@@ -1,22 +1,18 @@
...
 fail-fast = false
-
-[profile.ci]
-# For CI runs only, print failure output both at the error site and at the end.
-failure-output = "immediate"
-# Show skipped tests in the CI output.
-status-level = "skip"
+# Print failure output both at the error site and at the end (for easy scrollability).
+failure-output = "immediate-final"
+# Default imeout tests after 5 minutes
```
Comment (muXxer) [inline .config/nextest.toml]:
```suggestion
# Default timeout tests after 5 minutes
```

File: .config/nextest.toml [hunk 3]
```diff
@@ -59,14 +55,17 @@ or test(test_stake_all)
...
+[profile.ci.junit]
+path = "junit.xml"
+
+# Custom profiles are layered on top of the default profile.
 [profile.simtestnightly]
-# Print out output for failing tests as soon as they fail, and also at the end
-# of the run (for easy scrollability).
-failure-output = "immediate"
 # Show skipped tests in the CI output.
 status-level = "fail"
```
Comment (muXxer) [inline .config/nextest.toml:77]: is that comment correct?
Same comment for "fail" and "skip" some lines above.

**Review by muXxer — CHANGES_REQUESTED** [review]

**Comment by muXxer** [comment]
> I'd prefer that we keep the ci profile and just apply it as needed

I'm not sure I understand that whole "ci profiles" stuff, but isn't the `ci profile` still there, just some lines below, inherited from default?

File: scripts/ci_tests/rust_tests.sh (hunk 1 above)
Comment (nmrshll) [reply scripts/ci_tests/rust_tests.sh]: I'll rename the function to something a bit more distinctive then 👍

File: .config/nextest.toml (hunk 3 above)
Comment (nmrshll) [reply .config/nextest.toml:77]: it wasn't, I changed the value back and forth for testing and the comment didn't follow
Thanks

**Comment by nmrshll** [comment]
> > I'd prefer that we keep the ci profile and just apply it as needed
> 
> I'm not sure I understand that whole "ci profiles" stuff, but isn't the `ci profile` still there, just some lines below, inherited from default?

@DaughterOfMars yes the profiles are still there below, called `ci` and `simtestnightly`, and now they both inherit the default profile and the overrides for slow and flaky tests.
I've commented a bit more though, to make that clearer.

**Comment by DaughterOfMars** [comment]
> > > I'd prefer that we keep the ci profile and just apply it as needed
> > 
> > 
> > I'm not sure I understand that whole "ci profiles" stuff, but isn't the `ci profile` still there, just some lines below, inherited from default?
> 
> @DaughterOfMars yes the profiles are still there below, called `ci` and `simtestnightly`, and now they both inherit the default profile and the overrides for slow and flaky tests. I've commented a bit more though, to make that clearer.

Ah, I misread the changeset. 😅

**Review by DaughterOfMars — APPROVED** [review]

**Review by muXxer — APPROVED** [review]

**Review by DaughterOfMars — APPROVED** [review]

**Review by muXxer — APPROVED** [review]
