### PR TITLE
fix(node): gracefully clean up iota-node validator components

### LINKED ISSUE #6277: Validator node crashes when it was a validator node before, and becomes a validator/committee member again

### PR DESCRIPTION
**Pull request by semenov-vladyslav**
# Description of change

After a validator node leaves the committee, a few resources in validator components are leaked including metrics and grpc server. If the node will try to re-join the committee it will crash due to resources already being in use.

This PR:
- changes the way validator metrics are registered: a dedicated registry is used instead of default one;
- adds a graceful shutdown of validator grpc server and metrics registry clean up during reconfiguration when a validator leaves the committee;
- adds a reproducer test.

## Notes

There are a few ways to handle metrics issue:
- ignore `AlreadyReg` error while trying to re-register metrics with the default registry; requires special unwrap handling for each metric;
- unregister individual metrics with the default registry; the existing components do not provide such functionality; requires unregistering all individual metrics;
- use a dedicated registry and remove it entirely from the registry service once node is not validator anymore; this seems to be the easiest and cleanest way.

:warning: There may be other undetected resources leaking that do not cause error if validator components are re-created.

## Links to any relevant issues

Fixes #6277.

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

```sh
scripts/simtest/cargo-simtest simtest --package iota-e2e-tests --test "reconfiguration_tests" --profile ci -- test_reconfig_with_same_validator
```

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### Release Notes

- [ ] Protocol:
- [x] Nodes (Validators and Full nodes): Fixed a bug causing iota-node to crash after re-joining the consensus committee as validator.
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [ ] CLI:
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: crates/iota-node/src/lib.rs [hunk 1]
```diff
@@ -1724,20 +1745,28 @@ impl IotaNode {
...
+                    if self.registry_service.remove(validator_registry_id) {
+                        debug!("Removed validator metrics registry");
+                    } else {
+                        warn!("Failed to remove validator metrics registry");
+                    }
+                    if validator_server_cancel_handle.send(()).is_ok() {
+                        debug!("Validator grpc server cancelled");
+                    } else {
+                        warn!("Failed to cancel validator grpc server");
+                    }
```
Comment (jkrvivian) [inline crates/iota-node/src/lib.rs:1771]: Good catch on the grpc server cancellation!! 🤯

**Review by jkrvivian — APPROVED** [review]

File: crates/iota-e2e-tests/tests/reconfiguration_tests.rs [hunk 2]
```diff
@@ -671,6 +671,101 @@ async fn test_reconfig_with_committee_change_basic() {
...
+                MIN_VALIDATOR_JOINING_STAKE_NANOS,
+                DEFAULT_GAS_AMOUNT,
+                MIN_VALIDATOR_JOINING_STAKE_NANOS,
+            ],
+        }));
+
+    // create test cluster with 4 default validators
+    let mut test_cluster = TestClusterBuilder::new()
+        .with_num_validators(4)
+        // .with_validator_candidates(std::iter::once(node_address))
```
Comment (gokhan-simsek-iota) [inline crates/iota-e2e-tests/tests/reconfiguration_tests.rs]: Remove?

File: crates/iota-e2e-tests/tests/reconfiguration_tests.rs [hunk 3]
```diff
@@ -671,6 +671,101 @@ async fn test_reconfig_with_committee_change_basic() {
...
+
+        if node_handle.is_none() {
+            // spawn node if not already
+            node_handle = Some(test_cluster.spawn_new_validator(build_node_config()).await);
+        }
+
+        // sync nodes
+        test_cluster.wait_for_epoch_all_nodes(epoch).await;
+
+        // the running node acknowledges being or not a committee member
```
Comment (gokhan-simsek-iota) [inline crates/iota-e2e-tests/tests/reconfiguration_tests.rs]: ... or not being a committee member ?

**Review by piotrm50 — APPROVED** [review]
lgtm

File: crates/iota-node/src/lib.rs [hunk 4]
```diff
@@ -1446,7 +1461,10 @@ impl IotaNode {
         state: Arc<AuthorityState>,
         consensus_adapter: Arc<ConsensusAdapter>,
         prometheus_registry: &Registry,
-    ) -> Result<tokio::task::JoinHandle<Result<()>>> {
+    ) -> Result<(
+        tokio::task::JoinHandle<Result<()>>,
+        tokio::sync::oneshot::Sender<()>,
+    )> {
```
Comment (nmrshll) [inline crates/iota-node/src/lib.rs:1467]: Would it make sense to make the return type a struct ? so both return values can be named ? (just for clarity & knowing what they are, wouldn't change functionality)

File: crates/iota-node/src/lib.rs [hunk 5]
```diff
@@ -1464,15 +1482,16 @@ impl IotaNode {
 
         server_builder = server_builder.add_service(ValidatorServer::new(validator_service));
 
-        let server = server_builder
+        let mut server = server_builder
             .bind(config.network_address())
             .await
             .map_err(|err| anyhow!(err.to_string()))?;
+        let cancel_handle = server.take_cancel_handle().unwrap();
```
Comment (nmrshll) [inline crates/iota-node/src/lib.rs]: I suppose unwrapping is okay here since this only gets run once at node startup ? Also should we use expect instead of unwrap to add error context ?

Comment (nmrshll) [reply crates/iota-node/src/lib.rs]: Actually, cancel_handle seems to always contain a handle (at least until using take() the first time):
https://vscode.dev/github/iotaledger/iota/blob/node/fix-6277-revalidator-crash/crates/iota-network-stack/src/server.rs#L210

Would it then make sense to implement cancel() on the server itself ? e.g. grpc_server.cancel() or grpc_server.shutdown() ? then the server can handle the logic of take()-ing its own cancel handle ,and just emit a warning if it's already received a cancel order previously ?

Again this wouldn't really change the logic, it's just for clarity, so it's also fine with me if we don't want to spend time on changing this

**Review by muXxer — APPROVED** [review]

**Review by bingyanglin — APPROVED** [review]
LGTM!

**Review by miker83z — APPROVED** [review]
