### PR TITLE
fix(iota-indexer): Refactor the network metrics processor to efficiently handle data migrations

### LINKED ISSUE #5480: iotax_getNetworkMetrics fails to read PostgresDB with Unexpected null for non-null column
## Bug description

Requesting the network metrics fails in the testnet with `{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Indexer failed to read PostgresDB with error: `Unexpected null for non-null column`"}} `

To reproduce run:
```
curl https://indexer.testnet.iota.cafe \
--header 'content-type: application/json' \
--data '{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "iotax_getNetworkMetrics",
  "params": []
}'
```

### PR DESCRIPTION
**Pull request by samuel-rufi**
# Description of change

Refactors the Indexer network metrics processor to efficiently index and handle data migrations. This patch ensures that the processor now takes `MAX_NETWORK_METRICS_PROCESSOR_BATCH_SIZE` checkpoints if available, otherwise defaulting to anything less available. Additionally, to prevent the processor from running on every checkpoint in a highly synchronized state, the `MIN_NETWORK_METRICS_PROCESSOR_BATCH_SIZE` has been introduced.

Both options can be overridden by the corresponding environment variables `MIN_NETWORK_METRICS_PROCESSOR_BATCH_SIZE` and `MAX_NETWORK_METRICS_PROCESSOR_BATCH_SIZE`.

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/5480

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Checked the data produced by the network metrics processor locally in 

`cargo run --features indexer --bin iota start --with-indexer --pg-port 5432 --pg-db-name iota_indexer --with-graphql=0.0.0.0:8000 --force-regenesis`

## Change checklist

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota-indexer/src/processors/network_metrics_processor.rs [hunk 1]
```diff
@@ -25,21 +27,29 @@ where
...
+        let max_network_processor_metrics_batch_size =
+            std::env::var("MAX_NETWORK_METRICS_PROCESSOR_BATCH_SIZE")
+                .map(|s| {
+                    s.parse::<usize>()
+                        .unwrap_or(MAX_NETWORK_METRICS_PROCESSOR_BATCH_SIZE)
+                })
+                .unwrap_or(MAX_NETWORK_METRICS_PROCESSOR_BATCH_SIZE);
         let network_processor_metrics_parallelism =
-            std::env::var("NETWORK_PROCESSOR_METRICS_PARALLELISM")
+            std::env::var("NETWORK_METRICS_PROCESSOR_PARALLELISM")
```
Comment (kodemartin) [inline crates/iota-indexer/src/processors/network_metrics_processor.rs:45]: Nit: You might want to rename also the `network_processor` variable names to `network_metrics_processor`.

File: crates/iota-indexer/src/processors/network_metrics_processor.rs [hunk 2]
```diff
@@ -25,21 +27,29 @@ where
     S: IndexerAnalyticalStore + Clone + Sync + Send + 'static,
 {
     pub fn new(store: S, metrics: IndexerMetrics) -> NetworkMetricsProcessor<S> {
-        let network_processor_metrics_batch_size =
-            std::env::var("NETWORK_PROCESSOR_METRICS_BATCH_SIZE")
```
Comment (kodemartin) [inline crates/iota-indexer/src/processors/network_metrics_processor.rs:29]: Doesn't this break backward compatibility? If someone is configuring the service already using this env variable they will not get the expected results.

Comment (samuel-rufi) [reply crates/iota-indexer/src/processors/network_metrics_processor.rs:29]: Yes, it does. However we didn't advise anyone to make use of the existing `NETWORK_PROCESSOR_METRICS_BATCH_SIZE` env variable as far as I know. Also we don't use it in any prod deployment (also checked the docker-compose). And since the network metrics processor logic changed and behaves differently now, I guess even if it breaks (if really someone used this env var) it is good to run the changes with the default settings.

**Review by kodemartin — APPROVED** [review]
lgtm :bar_chart:

**Review by sergiupopescu199 — APPROVED** [review]
lgtm!
