### PR TITLE
fix(iota-core): skip duplicate EndOfPublish in white-flag mode

### LINKED ISSUE #10925: pcool: excessive duplicate EndOfPublish messages during epoch transition in white-flag mode
## Problem

In certificate mode, the `send_end_of_publish` path in `consensus_adapter.rs` (`submit_and_wait_inner` notification callback, ~line 869) was designed as a rare race condition handler — pending certificates drain while another is being processed.

In white-flag (certificate-less) mode, `pending_consensus_certificates` is always empty, so `is_pending_consensus_certificates_empty()` always returns `true`. This means **every `UserTransactionV1` processed while in `RejectUserCerts` state triggers an `EndOfPublish` submission**.

The existing comment (line 876) says duplicate EndOfPublish messages "don't affect correctness" — but that was written for the rare-race case, not for every-transaction-triggers-it. This creates unnecessary consensus overhead during epoch transition.

## Suggested Fix

Guard with an `AtomicBool` to send `EndOfPublish` only once in white-flag mode, or at minimum add a `debug!` log when duplicates are suppressed.

## Location

`crates/iota-core/src/consensus_adapter.rs` ~line 869

### PR DESCRIPTION
**Pull request by piotrm50**
# Description of change

In white-flag (certificate-less) mode, every `UserTransactionV1` completing in `RejectUserCerts` state triggered an `EndOfPublish` submission from `submit_and_wait_inner`, because `pending_consensus_certificates_count()` is always 0. This produced N duplicate `EndOfPublish` messages where N is the number of in-flight user transactions at epoch transition.

The `submit_and_wait_inner` EndOfPublish logic exists for the certificate drain scenario — detecting when the last pending certificate completes. In white-flag mode there's nothing to drain, so `close_epoch` is the correct and sufficient sender.

This change skips the EndOfPublish check in `submit_and_wait_inner` for white-flag mode entirely. The certificate-mode drain logic is preserved but annotated with a TODO for removal when the certificate flow is cleaned up.

## Links to any relevant issues

Fixes #10925

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [x] Patch-specific tests (correctness, functionality coverage)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by bingyanglin — APPROVED** [review]

File: crates/iota-core/src/consensus_adapter.rs [hunk 1]
```diff
@@ -874,35 +874,40 @@ impl ConsensusAdapter {
...
-
-                    true
-                } else {
-                    // In certificate mode, `EndOfPublish` is sent only once the list
-                    // of pending consensus certificates is drained.
+            if epoch_store.protocol_config().enable_white_flag_flow() {
+                // In certificate-less mode, `EndOfPublish` is sent solely from
+                // `close_epoch`. There is no pending certificate drain to
+                // monitor here, and sending from this per-transaction callback
+                // would produce N duplicate EndOfPublish messages (one per
```
Comment (roman1e2f5p8s) [inline crates/iota-core/src/consensus_adapter.rs:881]: It would be great to explicitly mention here that `submit_and_wait_inner` is spawned as a separate task for each `submit`/`submit_batch` call; otherwise, it is not obvious from the local context.

**Review by roman1e2f5p8s — APPROVED** [review]
Great catch!

For clarity, I would also docstring `submit_and_wait_inner` that it is spawned as a separate task for each `submit`/`submit_batch` call and that the `transactions` vector typically contains a single transaction or multiple transactions in the case of a soft bundle - both are not self-evident from the function signature.

**Review by filipdulic — APPROVED** [review]
