### PR TITLE
fix(iota): use gas coin as payment, if only a single gas coin is available

### LINKED ISSUE #6951: CLI: Make sure that all name commands work with a single gas coin
Some commands didn't work in the past, if one had only a single gas coin, as coin was used to split the payment and then there was no coin available for the gas payment anymore. In such a case, the amount should be split from the gas coin instead, so the transaction still works.
Go though each command that does a transaction and try it while having only a single gas coin.

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Use gas coin as payment, if only a single gas coin is available.
Also improved the error message when fetching the price config fails (usually happens if the package id was not set correct)

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/6951

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Running `cargo run --features=iota-names name register test.iota` with a single gas coin and also with multiple gas coins (another name in this case), both work now.

If the package id was not set correct for the network, previously the error was
`Some(NotExists { object_id: 0xc0671ed8571ed80dae4ca18124c13d5cec36463837e5fdcc11591e2dbb6ba1ff })`, now it's `couldn't fetch pricing config: Some(NotExists { object_id: 0xc0671ed8571ed80dae4ca18124c13d5cec36463837e5fdcc11591e2dbb6ba1ff })`
We could even add something like `make sure to have the env variables set for IOTA-Names` or similar in this case, but not sure about this here

### CODE REVIEW

File: crates/iota/src/name_commands.rs [hunk 1]
```diff
@@ -1992,29 +1994,30 @@ impl PricingConfig {
     }
 }
 
-async fn select_coin_for_payment(
+// Returns "@<coin id>" or "gas" to be used as coin payment argument in a PTB
```
Comment (thibault-martinez) [inline crates/iota/src/name_commands.rs:1997]: Does "gas" assume the variable has been set already?

Comment (Thoralf-M) [reply crates/iota/src/name_commands.rs:1997]: Not sure what you mean, which variable?

Comment (thibault-martinez) [reply crates/iota/src/name_commands.rs:1997]: Why are we returning "gas", what is this?

Comment (Thoralf-M) [reply crates/iota/src/name_commands.rs:1997]: That's how one references the gas coin in a PTB, providing the actual gas coin would result in an error, as coins in arguments are separated from the actual gas coins
```
iota client ptb \
--split-coins gas "[1000000000]" \ # the gas here
--assign coin
```

Comment (thibault-martinez) [reply crates/iota/src/name_commands.rs:1997]: Ah yeah I see, got confused, thanks

**Review by thibault-martinez — APPROVED** [review]

File: crates/iota/src/name_commands.rs [hunk 2]
```diff
@@ -1992,29 +1994,30 @@ impl PricingConfig {
...
+async fn select_coin_arg_for_payment(
     domain_name: &str,
     coin: Option<ObjectID>,
     price: u64,
     context: &mut WalletContext,
-) -> anyhow::Result<ObjectID> {
+) -> anyhow::Result<String> {
     Ok(match coin {
-        Some(coin) => coin,
+        Some(coin) => format!("@{coin}"),
```
Comment (DaughterOfMars) [inline crates/iota/src/name_commands.rs:2005]: Not sure I'm a fan of the double format :c

Comment (Thoralf-M) [reply crates/iota/src/name_commands.rs:2005]: You mean here and then for the PTB string? If we don't do the `@` addition here, we have to match on the result of this function and add it or not depending on the gas coin or an object id

Comment (DaughterOfMars) [reply crates/iota/src/name_commands.rs:2005]: Oh, I see. It's using the `gas` var. Is that always available?

Comment (thibault-martinez) [reply crates/iota/src/name_commands.rs:2005]: I had the exact same brainfart, yes is is

Comment (DaughterOfMars) [reply crates/iota/src/name_commands.rs:2005]: okie dokie then

**Review by DaughterOfMars — APPROVED** [review]

**Comment by thibault-martinez** [comment]
@Thoralf-M Maybe this deserved a release note btw?

**Comment by Thoralf-M** [comment]
@thibault-martinez I didn't add it, because it's not actually in the released binary atm

**Comment by thibault-martinez** [comment]
> @thibault-martinez I didn't add it, because it's not actually in the released binary atm

Fair enough but we've been adding IOTA-Names CLI notes anyway
