### PR TITLE
fix(wallet): Use current chain for wallet dry runs when requesting txs signings

### LINKED ISSUE #8428: Wallet ignores chain parameter for transaction signing
## Bug description

When requesting the web wallet to sign a transaction, there is a chain parameter to specify the network like `iota:mainnet`. This should be used to do the dry run in the correct network, right now it's ignored and always uses the network selected in the wallet itself

https://github.com/iotaledger/iota/blob/abf4d2b61667d1ebf7fc71385bb188aa619b2ddb/sdk/wallet-standard/src/features/iotaSignTransaction.ts#L31

## Steps To reproduce the bug

1. call signTransaction() with the chain parameter set to a different network than what's selected in the browser wallet
2. dry run fails

## Expected behaviour

Wallet should do the dry run with the node for the corresponding chain parameter and then the dry run should not fail

## Actual behaviour

Dry run fails

### PR DESCRIPTION
**Pull request by marc2332**
Closes https://github.com/iotaledger/iota/issues/8428

Dapps only need to add the new `chain` property in `WalletProvider` https://github.com/iotaledger/iota/blob/533e0b08eab50592c01980ff4e0c1a1ecd6547be/apps/wallet-dashboard/providers/AppProviders.tsx#L62 for this to work, that or pass `chain` every time `useSignAndExecuteTransaction` is called.

### CODE REVIEW

File: apps/wallet/src/shared/messaging/messages/payloads/transactions/approvalRequest.ts [hunk 1]
```diff
@@ -13,6 +13,7 @@ export type TransactionDataType = {
     type: 'transaction';
     data: string;
     account: string;
+    chain?: ChainType;
```
Comment (brancoder) [inline apps/wallet/src/shared/messaging/messages/payloads/transactions/approvalRequest.ts:16]: should we use the `IdentifierString` type from wallet standard here? and also possibly remove out ChainType type, because now we have two types for the same thing across projects?
seams we have added the CoinType in this PR https://github.com/iotaledger/iota/pull/219/files#diff-05477b1fd3a3bfb3af4614271e1969cc43f1677991e10d40fe5b6d6bce7deac0

**Review by brancoder — CHANGES_REQUESTED** [review]
in walletStandardInterface.ts `#signTransaction`  we spread the input `...input,` so the chain property gets sent to approval request:
image

but in the `#signAndExecuteTransaction` we dont propagate the chain property. we could add it also so that we don't have the same issue when using `#signAndExecuteTransaction:`
image

to test this out qickly i just changed the `signTransaction` method for `signAndExecuteTransaction` method in `useSignAndExecuteTransaction` hook
image

File: apps/wallet/src/shared/messaging/messages/payloads/transactions/approvalRequest.ts (hunk 1 above)
Comment (marc2332) [reply apps/wallet/src/shared/messaging/messages/payloads/transactions/approvalRequest.ts:16]: ChainType is also used in the sdk so its weird to make it depend on the wallet standard no? its just a type alias anyway

File: apps/wallet/src/ui/app/walletSigner.ts [hunk 2]
```diff
@@ -28,20 +32,34 @@ export abstract class WalletSigner {
         this.client = client;
     }
 
+    protected getClient(chain?: ChainType): IotaClient {
+        const requestedNetwork = Object.values(getAllNetworks() ?? {}).find(
+            (network) => network.chain === chain,
+        ) as NetworkId | undefined;
+        const client = requestedNetwork
+            ? new IotaClient({ url: getFullnodeUrl(requestedNetwork) })
```
Comment (brancoder) [inline apps/wallet/src/ui/app/walletSigner.ts]: we can access the url from the found requestedNetwork directly. no need to call `getFullnodeUrl` because it just calls -> getNetwork() -> getAllNetworks().
ex.
```
 const requestedNetwork = Object.values(getAllNetworks() ?? {}).find(
            (network) => network.chain === chain,
        );
        const client = requestedNetwork
            ? new IotaClient({ url: requestedNetwork.url })
            : this.client;
        return client;
```

**Review by brancoder — CHANGES_REQUESTED** [review]
LG 🚀  just a nit about client url

**Review by brancoder — APPROVED** [review]
LGTM Nice job 🚀

**Review by brancoder — CHANGES_REQUESTED** [review]
its good, just conflicts 🙏

**Review by brancoder — APPROVED** [review]
LGTM

**Review by msarcev — APPROVED** [review]
