### PR TITLE
upstream(iota): fix missing check on conflicting addresses after compiling

### LINKED ISSUE #10217: upstream: Fix missing check on conflicting addresses after compiling
https://github.com/MystenLabs/sui/pull/22390

### PR DESCRIPTION
**Pull request by thibault-martinez**
# Description of change

This PR fixes missing a check on conflicting addresses after compiling when publishing or when calling `build --dump-bytecode-as-base64`.

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/10217

## How the change has been tested

- [ ] Basic tests (linting, compilation, formatting, unit/integration tests)
- [ ] Patch-specific tests (correctness, functionality coverage)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### Release Notes

- [ ] Protocol:
- [ ] Nodes (Validators and Full nodes):
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [x] CLI: Fix missing check on conflicting addresses after compiling
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: crates/iota/tests/cli_tests.rs [hunk 1]
```diff
@@ -2897,11 +2897,10 @@ async fn test_package_management_on_upgrade_command_conflict() -> Result<(), any
 
     let expect = expect![[r#"
         Conflicting published package address: `Move.toml` contains published-at address 0x0000000000000000000000000000000000000000000000000000000000000bad but `Move.lock` file contains published-at address <elided-for-test>. You may want to:
-
-                         - delete the published-at address in the `Move.toml` if the `Move.lock` address is correct; OR
-                         - update the `Move.lock` address using the `iota manage-package` command to be the same as the `Move.toml`; OR
-                         - check that your `iota active-env` (currently localnet) corresponds to the chain on which the package is published (i.e., devnet, testnet, mainnet); OR
-                         - contact the maintainer if this package is a dependency and request resolving the conflict."#]];
+ - delete the published-at address in the `Move.toml` if the `Move.lock` address is correct; OR
+ - update the `Move.lock` address using the `iota manage-package` command to be the same as the `Move.toml`; OR
```
Comment (Thoralf-M) [inline crates/iota/tests/cli_tests.rs:2901]: We don't have the `iota manage-package` command

Comment (thibault-martinez) [reply crates/iota/tests/cli_tests.rs:2901]: Comment was already there. It's either we remove and potentially forget to bring it back or we keep it until we add the command.

Comment (Thoralf-M) [reply crates/iota/tests/cli_tests.rs:2901]: Hm true

**Review by Thoralf-M — APPROVED** [review]

File: crates/iota/src/client_commands.rs [hunk 2]
```diff
@@ -2254,11 +2255,10 @@ pub(crate) async fn upgrade_package(
...
                  You may want to:
-
-                 - delete the published-at address in the `Move.toml` if the `Move.lock` address is correct; OR
-                 - update the `Move.lock` address using the `iota manage-package` command to be the same as the `Move.toml`; OR
-                 - check that your `iota active-env` {env_alias} corresponds to the chain on which the package is published (i.e., devnet, testnet, mainnet); OR
-                 - contact the maintainer if this package is a dependency and request resolving the conflict."
+ - delete the published-at address in the `Move.toml` if the `Move.lock` address is correct; OR
+ - update the `Move.lock` address using the `iota manage-package` command to be the same as the `Move.toml`; OR
+ - check that your `iota active-env` {env_alias} corresponds to the chain on which the package is published (i.e., devnet, testnet, mainnet); OR
+ - contact the maintainer if this package is a dependency and request resolving the conflict."
```
Comment (DaughterOfMars) [inline crates/iota/src/client_commands.rs:2261]: I don't think this is needed

Comment (thibault-martinez) [reply crates/iota/src/client_commands.rs:2261]: What exactly?

Comment (DaughterOfMars) [reply crates/iota/src/client_commands.rs:2261]: the spacing change

Comment (thibault-martinez) [reply crates/iota/src/client_commands.rs:2261]: Pretty sure it is, see my previous commit. I can try if you want though.

Comment (DaughterOfMars) [reply crates/iota/src/client_commands.rs:2261]: eh, okay whatever

**Review by DaughterOfMars — APPROVED** [review]

**Review by miker83z — APPROVED** [review]
