### PR TITLE
fix sidebar highlights

### LINKED ISSUE #4432: Fix Sidebar Active Element Highlighting
When navigating through the documentation in the sidebar, it can be challenging to identify the current active element. The current styling for the active element is too similar to the rest of the tree. It would be helpful to make the active element stand out more clearly.

Suggested Improvements:

- Adjust the styling of the active element to make it more distinct (e.g., a stronger highlight, bold text, or a different background color).

Image

### PR DESCRIPTION
**Pull request by vivekjain23**
# Description of change

This PR brings up the changes to the sidebar highlights. 

## Links to any relevant issues

fixes #4432.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Documentation Fix

## How the change has been tested

Changes were built locally.

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: docs/site/src/components/API/api-ref/refnav.js [hunk 1]
```diff
@@ -41,10 +41,9 @@ const RefNav = (props) => {
                 .map((method) => {
                   return (
                     <Link
-                      className={`menu__link font-medium block hover:no-underline text-base ${page === method.name && 'menu__link--active'}`}
+                      className={`menu__link font-medium block  hover:no-underline text-base ${page === method.name && 'menu__link--active'}`}
```
Comment (lucas-tortora) [inline docs/site/src/components/API/api-ref/refnav.js]: Is there a reason for the extra blank space?

**Review by lucas-tortora — APPROVED** [review]

File: docs/site/src/components/API/api-ref/refnav.js (hunk 1 above)
Comment (vivekjain23) [reply docs/site/src/components/API/api-ref/refnav.js]: It's a typo, my bad.

**Review by Ginowine — APPROVED** [review]
