### PR TITLE
fix(iota-json-rpc-types): fix `Display` impl for `IotaTransactionBlockResponse` with empty balance changes

### LINKED ISSUE #5366: [Bug (iota-json-rpc-types)]: `Display` implementation for `IotaTransactionBlockResponse` panics if balance changes are empty
## Bug description

While using the [get_transaction_with_options](https://github.com/iotaledger/iota/blob/0355a82d9a25cfbe9a6ea9f2f5e70c898c9952ab/crates/iota-sdk/src/apis/read.rs#L460) read API, I have noticed that [formatting (via `{}`)](https://github.com/iotaledger/iota/blob/0355a82d9a25cfbe9a6ea9f2f5e70c898c9952ab/crates/iota-json-rpc-types/src/iota_transaction.rs#L279) the returned [IotaTransactionBlockResponse](https://github.com/iotaledger/iota/blob/0355a82d9a25cfbe9a6ea9f2f5e70c898c9952ab/crates/iota-json-rpc-types/src/iota_transaction.rs#L207) instance panics if the returned instance contains an empty vector of balance changes.

Identified scenarios in which requested balance changes in `IotaTransactionBlockResponse` can be empty:

- `get_transaction_with_options` for a system transaction like `ConsensusCommitPrologueV1` with `show_balance_changes` option being enabled (for example, via `full_content()` or `with_balance_changes()` methods).

If the vector of balance changes is empty, the current implementation of the `Display` trait for `IotaTransactionBlockResponse`
https://github.com/iotaledger/iota/blob/0355a82d9a25cfbe9a6ea9f2f5e70c898c9952ab/crates/iota-json-rpc-types/src/iota_transaction.rs#L333-L345
is still building an **empty** table and then trying to operate on it, which results in a panic on the [tabled](https://docs.rs/tabled/latest/tabled/url) crate side:

```text
thread 'main' panicked at /home/rom/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tabled-0.12.2/src/grid/records/records_mut.rs:25:18:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Rust version

- `rustc 1.84.1 (e71f9a9a9 2025-01-27)`

## Version

`develop` branch

## Steps To reproduce the bug

Two utilities are provided (either can be used) to reproduce the bug:

- [display_tx_with_empty_balance_changes](https://github.com/iotaledger/iota/blob/protocol-research/test/display-full-content-iota-transaction-block-response-for-system-tx/crates/iota-sdk/examples/read_api/display_tx_with_empty_balance_changes.rs) example in `iota-sdk`, or
- [get_transaction_block_with_full_content_and_then_display_it](https://github.com/iotaledger/iota/blob/c8e534e4a5725dd331daa6669a8d5d9ba7473099/crates/iota-json-rpc-tests/tests/read_api.rs#L1675C10-L1675C69) test in `iota-json-rpc-tests`,

both available on a separate branch (`protocol-research/test/display-full-content-iota-transaction-block-response-for-system-tx`).

> [!NOTE]
> Note that this auxiliary branch is not intended for merging, but probably the provided test could be added to `develop` if deemed reasonable. The brach will be deleted when this issue is closed.

### Using `display_tx_with_empty_balance_changes` example:

```console
git checkout protocol-research/test/display-full-content-iota-transaction-block-response-for-system-tx
cd crates/iota-sdk
cargo run --example display_tx_with_empty_balance_changes
cd ../..
```

### Using `get_transaction_block_with_full_content_and_then_display_it` test:

```console
git checkout protocol-research/test/display-full-content-iota-transaction-block-response-for-system-tx
cargo test -p iota-json-rpc-tests get_transaction_block_with_full_content_and_then_display_it -- --exact
```

## Expected behaviour

Empty-formatting, `{}`, of `IotaTransactionBlockResponse` with empty balance changes should print out transaction data without a panic.

## Actual behaviour

```text
Transaction Digest: J5RRT49tB4rCvLvd5Cro4M81QE1FdivREK3B29tuRkZm
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Transaction Data                                                                                                                            │
├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Sender: 0x0000000000000000000000000000000000000000000000000000000000000000                                                                  │
│ Gas Owner: 0x0000000000000000000000000000000000000000000000000000000000000000                                                               │
│ Gas Budget: 0 NANOS                                                                                                                         │
│ Gas Price: 1 NANOS                                                                                                                          │
│ Gas Payment:                                                                                                                                │
│  ┌──                                                                                                                                        │
│  │ ID: 0x0000000000000000000000000000000000000000000000000000000000000000                                                                   │
│  │ Version: 0                                                                                                                               │
│  │ Digest: 11111111111111111111111111111111                                                                                                 │
│  └──                                                                                                                                        │
│                                                                                                                                             │
│ Transaction Kind: Consensus Commit Prologue V1                                                                                              │
│ Epoch: 86, Round: 1071671, SubDagIndex: None, Timestamp: 1739357300271, ConsensusCommitDigest: EBjtAQ4AEDt63zJx1R6k2PEbg4koSdAUJ3xbvxEqxgUh │
│                                                                                                                                             │
│                                                                                                                                             │
│ Signatures:                                                                                                                                 │
│    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==                                                 │
│                                                                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭───────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Transaction Effects                                                                               │
├───────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Digest: J5RRT49tB4rCvLvd5Cro4M81QE1FdivREK3B29tuRkZm                                              │
│ Status: Success                                                                                   │
│ Executed Epoch: 86                                                                                │
│ Mutated Objects:                                                                                  │
│  ┌──                                                                                              │
│  │ ID: 0x0000000000000000000000000000000000000000000000000000000000000006                         │
│  │ Owner: Shared( 1 )                                                                             │
│  │ Version: 129932211                                                                             │
│  │ Digest: DiwP2ehcg7LEGSpaybmejEWyamYUsAryU82xPau918QK                                           │
│  └──                                                                                              │
│ Shared Objects:                                                                                   │
│  ┌──                                                                                              │
│  │ ID: 0x0000000000000000000000000000000000000000000000000000000000000006                         │
│  │ Version: 129932210                                                                             │
│  │ Digest: 7rCCiGt7Yn9hLU9R7s5XMvtowraiXqnVrDmrSfwWfJeE                                           │
│  └──                                                                                              │
│ Gas Object:                                                                                       │
│  ┌──                                                                                              │
│  │ ID: 0x0000000000000000000000000000000000000000000000000000000000000000                         │
│  │ Owner: Account Address ( 0x0000000000000000000000000000000000000000000000000000000000000000 )  │
│  │ Version: 0                                                                                     │
│  │ Digest: 11111111111111111111111111111111                                                       │
│  └──                                                                                              │
│ Gas Cost Summary:                                                                                 │
│    Storage Cost: 0 NANOS                                                                          │
│    Computation Cost: 0 NANOS                                                                      │
│    Storage Rebate: 0 NANOS                                                                        │
│    Non-refundable Storage Fee: 0 NANOS                                                            │
│                                                                                                   │
│ Transaction Dependencies:                                                                         │
│    BNzKtDyzhEb72LYw2iMPL7CW6dGfPLi66c8imiUnC6cY                                                   │
╰───────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────╮
│ No transaction block events │
╰─────────────────────────────╯

╭─────────────────────────────────────────────────────────────────────────────────╮
│ Object Changes                                                                  │
├─────────────────────────────────────────────────────────────────────────────────┤
│ Mutated Objects:                                                                │
│  ┌──                                                                            │
│  │ ObjectID: 0x0000000000000000000000000000000000000000000000000000000000000006 │
│  │ Sender: 0x0000000000000000000000000000000000000000000000000000000000000000   │
│  │ Owner: Shared( 1 )                                                           │
│  │ ObjectType: 0x2::clock::Clock                                                │
│  │ Version: 129932211                                                           │
│  │ Digest: DiwP2ehcg7LEGSpaybmejEWyamYUsAryU82xPau918QK                         │
│  └──                                                                            │
╰─────────────────────────────────────────────────────────────────────────────────╯
thread 'main' panicked at /home/rom/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tabled-0.12.2/src/grid/records/records_mut.rs:25:18:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Errors

```text
thread 'main' panicked at /home/rom/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tabled-0.12.2/src/grid/records/records_mut.rs:25:18:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Proposed Solution

Similarly to how `Display` is implemented for `IotaTransactionBlockEvents`, there should be a check whether a vector of balance changes is non-empty, in which case a table can be constructed and safely operated on:
https://github.com/iotaledger/iota/blob/0355a82d9a25cfbe9a6ea9f2f5e70c898c9952ab/crates/iota-json-rpc-types/src/iota_transaction.rs#L1115-L1133

## Are you planning to do it yourself in a pull request?

Yes.

### PR DESCRIPTION
**Pull request by roman1e2f5p8s**
# Description of change

In the `Display` implementation for `IotaTransactionBlockResponse`, add a check for a vector of balance changes being non-empty - only then a build a table and safely operate on it. A similar check is done in the `Display` implementation for `IotaTransactionBlockEvents`.

## Links to any relevant issues

Fixes #5366.

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Two utilities are provided (either can be used) to test the changes:

- [display_tx_with_empty_balance_changes](https://github.com/iotaledger/iota/blob/protocol-research/test/display-full-content-iota-transaction-block-response-for-system-tx/crates/iota-sdk/examples/read_api/display_tx_with_empty_balance_changes.rs) example in `iota-sdk`, or
- [get_transaction_block_with_full_content_and_then_display_it](https://github.com/iotaledger/iota/blob/c8e534e4a5725dd331daa6669a8d5d9ba7473099/crates/iota-json-rpc-tests/tests/read_api.rs#L1675C10-L1675C69) test in `iota-json-rpc-tests`,

both available on a separate branch (`protocol-research/test/display-full-content-iota-transaction-block-response-for-system-tx`).

> [!NOTE]
> Note that this auxiliary branch is not intended for merging, but probably the provided test could be added to `develop` if deemed reasonable. The brach will be deleted when this PR is closed.

### Using `display_tx_with_empty_balance_changes` example:

```console
git checkout protocol-research/test/display-full-content-iota-transaction-block-response-for-system-tx
git merge protocol-research/fix/display-tx-block-response-with-empty-balance-changes
cd crates/iota-sdk
cargo run --example display_tx_with_empty_balance_changes
cd ../..
git reset --merge HEAD~1
```

### Using `get_transaction_block_with_full_content_and_then_display_it` test:

```console
git checkout protocol-research/test/display-full-content-iota-transaction-block-response-for-system-tx
git merge protocol-research/fix/display-tx-block-response-with-empty-balance-changes
cargo test -p iota-json-rpc-tests get_transaction_block_with_full_content_and_then_display_it -- --exact
git reset --merge HEAD~1
```

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by DaughterOfMars — APPROVED** [review]

**Comment by Thoralf-M** [comment]
I think it would make sense to add your test from the other branch to this PR here

**Comment by roman1e2f5p8s** [comment]
> I think it would make sense to add your test from the other branch to this PR here

Makes sense to me too, as there appears to be no test for `Display` implementation for `IotaTransactionBlockResponse` - let's see what @iotaledger/infrastructure thinks. Then I could move the test to this branch.

**Review by samuel-rufi — APPROVED** [review]

**Comment by roman1e2f5p8s** [comment]
@samuel-rufi, do you think this [test](https://github.com/iotaledger/iota/blob/c8e534e4a5725dd331daa6669a8d5d9ba7473099/crates/iota-json-rpc-tests/tests/read_api.rs#L1675C10-L1675C69) should be added to this PR?

**Comment by roman1e2f5p8s** [comment]
I added the [test](https://github.com/iotaledger/iota/blob/ffd9913b20f287976fe89d8d1b49bb3a4456c9a8/crates/iota-json-rpc-tests/tests/read_api.rs#L1671) to this PR as @Thoralf-M suggested.

File: crates/iota-json-rpc-tests/tests/read_api.rs [hunk 1]
```diff
@@ -1665,3 +1666,64 @@ async fn try_get_object_before_version_not_exists() {
         matches!(rpc_obj_before_ver, IotaPastObjectResponse::ObjectNotExists(ref obj_id) if obj_id == &ObjectID::ZERO)
     );
 }
+
+#[sim_test]
+async fn get_system_transaction_block_with_full_content_and_invoke_display_impl_on_it() {
```
Comment (DaughterOfMars) [inline crates/iota-json-rpc-tests/tests/read_api.rs]: 👀  this is nice and descriptive but maybe...too descriptive?

Comment (roman1e2f5p8s) [reply crates/iota-json-rpc-tests/tests/read_api.rs]: Renamed :)

**Comment by samuel-rufi** [comment]
Yes @roman1e2f5p8s , I think the added test is good to have! 👍
