### PR TITLE
fix(wallet,wallet-dashboard): blinking reward not started

### LINKED ISSUE #6709: Blinking "reward not started" block on open stake details first time
## Bug description

Issue happens on both wallet and dashbord

https://github.com/user-attachments/assets/1881466e-c8fa-459f-9a5a-7c34735811ac

## Version

Wallet v.1.0.0

### PR DESCRIPTION
**Pull request by KeitoTadashi**
## Links to any relevant issues

fixes #6709

### CODE REVIEW

File: apps/core/src/hooks/useGetNextEpochCommitteeMember.ts [hunk 1]
```diff
@@ -1,19 +1,23 @@
-// Copyright (c) 2025 IOTA Stiftung
```
Comment (begonaalvarezd) [inline apps/core/src/hooks/useGetNextEpochCommitteeMember.ts]: we cant remove this

File: apps/core/src/hooks/useGetNextEpochCommitteeMember.ts [hunk 2]
```diff
@@ -1,19 +1,23 @@
...
+    );
+    const { data: maxCommitteeSize, isLoading: isMaxCommitteeSizeLoading } = useMaxCommitteeSize();
+
+    const isValidatorExpectedToBeInTheCommitteeLoading =
+        isSystemStateLoading || isMaxCommitteeSizeLoading;
 
     const isValidatorExpectedToBeInTheCommittee = useMemo(() => {
         if (!systemState || !maxCommitteeSize) return false;
 
+        // Sort and slice only if data is available
```
Comment (begonaalvarezd) [inline apps/core/src/hooks/useGetNextEpochCommitteeMember.ts]: is this comment needed? looks like an AI comment :trollface:

File: apps/core/src/hooks/useGetNextEpochCommitteeMember.ts [hunk 3]
```diff
@@ -1,19 +1,23 @@
-// Copyright (c) 2025 IOTA Stiftung
-// SPDX-License-Identifier: Apache-2.0
-
 import { useIotaClientQuery } from '@iota/dapp-kit';
 import { useMemo } from 'react';
 import { useMaxCommitteeSize } from './useMaxCommitteeSize';
 
 export function useGetNextEpochCommitteeMember(validatorAddress: string): {
     isValidatorExpectedToBeInTheCommittee: boolean;
+    isValidatorExpectedToBeInTheCommitteeLoading: boolean;
```
Comment (begonaalvarezd) [inline apps/core/src/hooks/useGetNextEpochCommitteeMember.ts]: i would problably call this `isLoading` and then rename it wherever is used, there is no need for such a long name

File: apps/wallet-dashboard/components/dialogs/staking/views/DetailsView.tsx [hunk 4]
```diff
@@ -53,7 +53,7 @@ export function DetailsView({
 }: StakeDialogProps): JSX.Element {
     const totalStake = BigInt(stakedDetails?.principal || 0n);
     const validatorAddress = stakedDetails?.validatorAddress;
-    const { isValidatorExpectedToBeInTheCommittee } =
+    const { isValidatorExpectedToBeInTheCommittee, isValidatorExpectedToBeInTheCommitteeLoading } =
```
Comment (begonaalvarezd) [inline apps/wallet-dashboard/components/dialogs/staking/views/DetailsView.tsx]: you assign `isLoading` to `isValidatorExpectedToBeInTheCommitteeLoading` if you do what I suggested about the rename

File: apps/wallet/src/ui/app/staking/delegation-detail/DelegationDetailCard.tsx [hunk 5]
```diff
@@ -75,7 +75,7 @@ export function DelegationDetailCard({ validatorAddress, stakedId }: DelegationD
     const { data: metadata } = useCoinMetadata(IOTA_TYPE_ARG);
     const { isCommitteeMember } = useIsValidatorCommitteeMember();
     const { isActiveValidator } = useIsActiveValidator();
-    const { isValidatorExpectedToBeInTheCommittee } =
+    const { isValidatorExpectedToBeInTheCommittee, isValidatorExpectedToBeInTheCommitteeLoading } =
```
Comment (begonaalvarezd) [inline apps/wallet/src/ui/app/staking/delegation-detail/DelegationDetailCard.tsx]: you assign `isLoading` to `isValidatorExpectedToBeInTheCommitteeLoading` if you do what I suggested about the rename

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — APPROVED** [review]

**Review by evavirseda — APPROVED** [review]
