### PR TITLE
Indexer: Fix wrap-unwrap bug

### LINKED ISSUE #5020: indexer: fix unwrap after wrap bug in a checkpoint batch `{"side-effects": "medium", "type": "fix"}`
Pull in bugfix from upstream: https://github.com/MystenLabs/sui/pull/19468

Should be done after: https://github.com/iotaledger/iota/issues/5049

### PR DESCRIPTION
**Pull request by tomxey**
# Description of change

Pull bugfix https://github.com/MystenLabs/sui/pull/19468 from upstream

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/5020

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

`cargo ci-clippy`
`cargo nextest run -p iota-graphql-e2e-tests --features pg_integration`
`cargo test --package=iota-indexer --profile=simulator --features=shared_test_runtime`

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota-indexer/src/store/pg_indexer_store.rs [hunk 1]
```diff
@@ -1660,10 +1656,7 @@ impl IndexerStore for PgIndexerStore {
         let elapsed = guard.stop_and_record();
         info!(
             elapsed,
-            "Persisted {} objects with {} mutations and {} deletions ",
-            len,
-            mutation_len,
-            deletion_len,
+            "Persisted objects with {} mutations and {} deletions ", mutation_len, deletion_len,
```
Comment (sergiupopescu199) [inline crates/iota-indexer/src/store/pg_indexer_store.rs]:
```suggestion
            "Persisted objects with {mutation_len} mutations and {deletion_len} deletions"
````

File: crates/iota-indexer/src/store/pg_indexer_store.rs [hunk 2]
```diff
@@ -2222,38 +2183,87 @@ fn make_objects_history_to_commit(
     deleted_objects.into_iter().chain(mutated_objects).collect()
 }
 
-fn make_objects_snapshot_to_commit(
+// Partition object changes into deletions and mutations,
+// within partition of mutations or deletions, retain the latest with highest
+// version; For overlappings of mutations and deletions, only keep one with
+// higher version. This is necessary b/c after this step, DB commit will be done
+// in parallel and not in order.
+fn retain_latest_indexed_objects(
```
Comment (sergiupopescu199) [inline crates/iota-indexer/src/store/pg_indexer_store.rs]: I'm wondering if this could be converted into a function doc using `///`, the info seems quite important even tough is a private function.

File: crates/iota-indexer/src/store/pg_indexer_store.rs [hunk 3]
```diff
@@ -2222,38 +2183,87 @@ fn make_objects_history_to_commit(
...
+                    Either::Left(mutation) => {
+                        let id = mutation.object.id();
+                        let mutation_version = mutation.object.version();
+                        if let Some(existing) = deletions.remove(&id) {
+                            assert!(
+                                existing.object_version < mutation_version.value(),
+                                "Mutation version ({:?}) should be greater than existing deletion version ({:?}) for object {:?}",
+                                mutation_version,
+                                existing.object_version,
+                                id
```
Comment (sergiupopescu199) [inline crates/iota-indexer/src/store/pg_indexer_store.rs]:
```suggestion
                                "Mutation version ({mutation_version:?}) should be greater than existing deletion version ({:?}) for object {id:?}", existing.object_version
```

File: crates/iota-indexer/src/store/pg_indexer_store.rs [hunk 4]
```diff
@@ -2222,38 +2183,87 @@ fn make_objects_history_to_commit(
...
+                            );
+                        }
+                        if let Some(existing) = mutations.insert(id, mutation) {
+                            assert!(
+                                existing.object.version() < mutation_version,
+                                "Mutation version ({:?}) should be greater than existing mutation version ({:?}) for object {:?}",
+                                mutation_version,
+                                existing.object.version(),
+                                id
```
Comment (sergiupopescu199) [inline crates/iota-indexer/src/store/pg_indexer_store.rs]:
```suggestion
                                "Mutation version ({mutation_version:?}) should be greater than existing mutation version ({:?}) for object {id:?}", existing.object.version()
```

File: crates/iota-indexer/src/store/pg_indexer_store.rs [hunk 5]
```diff
@@ -2222,38 +2183,87 @@ fn make_objects_history_to_commit(
...
+                    Either::Right(deletion) => {
+                        let id = deletion.object_id;
+                        let deletion_version = deletion.object_version;
+                        if let Some(existing) = mutations.remove(&id) {
+                            assert!(
+                                existing.object.version().value() < deletion_version,
+                                "Deletion version ({:?}) should be greater than existing mutation version ({:?}) for object {:?}",
+                                deletion_version,
+                                existing.object.version(),
+                                id
```
Comment (sergiupopescu199) [inline crates/iota-indexer/src/store/pg_indexer_store.rs]:
```suggestion
                                "Deletion version ({deletion_version:?}) should be greater than existing mutation version ({:?}) for object {id:?}", existing.object.version()
```

File: crates/iota-indexer/src/store/pg_indexer_store.rs [hunk 6]
```diff
@@ -2222,38 +2183,87 @@ fn make_objects_history_to_commit(
...
+                            );
+                        }
+                        if let Some(existing) = deletions.insert(id, deletion) {
+                            assert!(
+                                existing.object_version < deletion_version,
+                                "Deletion version ({:?}) should be greater than existing deletion version ({:?}) for object {:?}",
+                                deletion_version,
+                                existing.object_version,
+                                id
```
Comment (sergiupopescu199) [inline crates/iota-indexer/src/store/pg_indexer_store.rs]:
```suggestion
                                "Deletion version ({deletion_version:?}) should be greater than existing deletion version ({:?}) for object {id:?}", existing.object_version
```

**Review by sergiupopescu199 — APPROVED** [review]
lgtm 🐝 with some tiny nitpicks

File: crates/iota-graphql-e2e-tests/tests/objects/wrap_unwrap.move [hunk 7]
```diff
@@ -0,0 +1,90 @@
+// Copyright (c) Mysten Labs, Inc.
+// SPDX-License-Identifier: Apache-2.0
```
Comment (samuel-rufi) [inline crates/iota-graphql-e2e-tests/tests/objects/wrap_unwrap.move]: Don't we need to add the modifications license header here?

**Review by samuel-rufi — APPROVED** [review]
Looks good! 🌞

File: crates/iota-graphql-e2e-tests/tests/objects/wrap_unwrap.move (hunk 7 above)
Comment (tomxey) [reply crates/iota-graphql-e2e-tests/tests/objects/wrap_unwrap.move]: good catch, added
