### PR TITLE
fix(node): Fix estimated rewards during safe mode

### LINKED ISSUE #5180: [jsonrpc] fix estimated rewards during safe mode (#20182) · MystenLabs/sui@27098db
[[jsonrpc] fix estimated rewards during safe mode (#20182) · MystenLabs/sui@27098db](https://github.com/MystenLabs/sui/commit/27098dbcd89d5ed0f98207230318bbaaead88868)
- Uses the exchange rate from the previous existing epoch instead of the default one value

### PR DESCRIPTION
**Pull request by bingyanglin**
# Description of change

Uses the exchange rate from the previous existing epoch instead of the default one value.

## Links to any relevant issues

fixes #5180 

## Type of change

- Bug fix

## How the change has been tested

Ran the local network with `RUST_LOG=info cargo run --release --bin iota start --force-regenesis --with-faucet`

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota-types/src/iota_system_state/mod.rs [hunk 1]
```diff
@@ -407,6 +407,13 @@ impl PoolTokenExchangeRate {
             self.pool_token_amount as f64 / self.iota_amount as f64
         }
     }
+
```
Comment (miker83z) [inline crates/iota-types/src/iota_system_state/mod.rs:410]:
```suggestion
#[cfg(test)]
```

**Review by kodemartin — CHANGES_REQUESTED** [review]
The respective logic in `iota-indexer` needs to be updated as well accordingly:

https://github.com/iotaledger/iota/blob/e9a5b0cc4e86ac2ac06f9c4925a7f4260e668969/crates/iota-indexer/src/apis/governance_api.rs#L311

If not trivial, please create an issue so that @iotaledger/infrastructure picks it up.

File: crates/iota-types/src/iota_system_state/mod.rs (hunk 1 above)
Comment (bingyanglin) [reply crates/iota-types/src/iota_system_state/mod.rs:410]: Looks like this does not work (see [da22916](https://github.com/iotaledger/iota/pull/5184/commits/da229161615615b870c0a8488d63499062e3234e))?

**Comment by bingyanglin** [comment]
> The respective logic in `iota-indexer` needs to be updated as well accordingly:
> 
> https://github.com/iotaledger/iota/blob/e9a5b0cc4e86ac2ac06f9c4925a7f4260e668969/crates/iota-indexer/src/apis/governance_api.rs#L311
> 
> If not trivial, please create an issue so that @iotaledger/infrastructure picks it up.

Thanks for pointing that out. Also updated `iota-indexer`.

File: crates/iota-types/src/iota_system_state/mod.rs (hunk 1 above)
Comment (miker83z) [reply crates/iota-types/src/iota_system_state/mod.rs:410]: Right, then please consider to rename the function as `new_for_testing` to indicate that this function shouldn't be used for no other purpose than testing.

File: crates/iota-indexer/src/apis/governance_api.rs [hunk 2]
```diff
@@ -561,6 +563,36 @@ impl GovernanceReadApi {
...
+                prev_rate = Some(rate.clone());
+                filled_rates.push((*e, rate.clone()));
+            }
+            None => {
+                if let Some(rate) = prev_rate.clone() {
+                    filled_rates.push((epoch, rate));
+                }
+            }
+        }
+    }
```
Comment (kodemartin) [inline crates/iota-indexer/src/apis/governance_api.rs]: I'd like to propose the following refactoring to make it more concise and efficient
```suggestion
    rates.sort_unstable_by_key(|(epoch_id, _)| *epoch_id);
    let mut filled_rates: Vec<(EpochId, PoolTokenExchangeRate)> = Vec::with_capacity(rates.len());
    let mut missing_rates = Vec::new();
    for (epoch_id, rate) in rates {
        if let Some((prev_epoch_id, prev_rate)) = filled_rates.last() {
            for missing_epoch_id in prev_epoch_id + 1..epoch_id {
                missing_rates.push((missing_epoch_id, prev_rate.clone()));
            }
        };
        filled_rates.append(&mut missing_rates);
        filled_rates.push((epoch_id, rate));
    }
```

File: crates/iota-json-rpc/src/governance_api.rs [hunk 3]
```diff
@@ -758,6 +761,36 @@ pub struct ValidatorExchangeRates {
...
+                prev_rate = Some(rate.clone());
+                filled_rates.push((*e, rate.clone()));
+            }
+            None => {
+                if let Some(rate) = prev_rate.clone() {
+                    filled_rates.push((epoch, rate));
+                }
+            }
+        }
+    }
```
Comment (kodemartin) [inline crates/iota-json-rpc/src/governance_api.rs]: Same here:
```suggestion
    rates.sort_unstable_by_key(|(epoch_id, _)| *epoch_id);
    let mut filled_rates: Vec<(EpochId, PoolTokenExchangeRate)> = Vec::with_capacity(rates.len());
    let mut missing_rates = Vec::new();
    for (epoch_id, rate) in rates {
        if let Some((prev_epoch_id, prev_rate)) = filled_rates.last() {
            for missing_epoch_id in prev_epoch_id + 1..epoch_id {
                missing_rates.push((missing_epoch_id, prev_rate.clone()));
            }
        };
        filled_rates.append(&mut missing_rates);
        filled_rates.push((epoch_id, rate));
    }
```

**Review by kodemartin — COMMENTED** [review]
hey @bingyanglin thanks for adapting `iota-indexer` as well. Looks good, but I left a suggestion that I reckon improves on the upstream implementation.

File: crates/iota-types/src/iota_system_state/mod.rs (hunk 1 above)
Comment (bingyanglin) [reply crates/iota-types/src/iota_system_state/mod.rs:410]: Makes sense. Thanks for the suggestion!

Comment (bingyanglin) [reply crates/iota-types/src/iota_system_state/mod.rs:410]: Modified it at [4abb6d4](https://github.com/iotaledger/iota/pull/5184/commits/4abb6d4e03e0ae943664580f63c4649820655068).

File: crates/iota-json-rpc/src/governance_api.rs (hunk 3 above)
Comment (bingyanglin) [reply crates/iota-json-rpc/src/governance_api.rs]: Thanks for the suggestions! I also make the rates to be `mut` in [4abb6d4](https://github.com/iotaledger/iota/pull/5184/commits/4abb6d4e03e0ae943664580f63c4649820655068).

**Review by kodemartin — APPROVED** [review]
lgtm

File: crates/iota-indexer/src/apis/governance_api.rs [hunk 4]
```diff
@@ -561,6 +563,31 @@ impl GovernanceReadApi {
     }
 }
 
+/// Backfill missing rates for some epochs due to safe mode. If a rate is
+/// missing for epoch e, we will use the rate for epoch e-1 to fill it. Rates
+/// returned are in descending order by epoch.
+fn backfill_rates(
+    mut rates: Vec<(EpochId, PoolTokenExchangeRate)>,
```
Comment (muXxer) [inline crates/iota-indexer/src/apis/governance_api.rs:570]: We will change the sorting of the original vector, is this intended?

**Review by jkrvivian — APPROVED** [review]

File: crates/iota-indexer/src/apis/governance_api.rs [hunk 5]
```diff
@@ -561,6 +563,31 @@ impl GovernanceReadApi {
...
+) -> Vec<(EpochId, PoolTokenExchangeRate)> {
+    if rates.is_empty() {
+        return rates;
+    }
+    rates.sort_unstable_by_key(|(epoch_id, _)| *epoch_id);
+    let mut filled_rates: Vec<(EpochId, PoolTokenExchangeRate)> = Vec::with_capacity(rates.len());
+    let mut missing_rates = Vec::new();
+    for (epoch_id, rate) in rates {
```
Comment (muXxer) [inline crates/iota-indexer/src/apis/governance_api.rs:592]: the original code was way easier to understand.
Can we add comments to this optimized version?

I'm not quite sure it's the same.
Why do we append the `missing_rates` in every loop iteration to the `filled_rates` for example?

File: crates/iota-indexer/src/apis/governance_api.rs [hunk 6]
```diff
@@ -667,3 +694,40 @@ impl IotaRpcModule for GovernanceReadApi {
...
+    use iota_types::iota_system_state::PoolTokenExchangeRate;
+
+    use super::*;
+    #[test]
+    fn test_backfill_rates_empty() {
+        let rates = vec![];
+        assert_eq!(backfill_rates(rates), vec![]);
+    }
+    #[test]
+    fn test_backfill_rates_no_gaps() {
```
Comment (muXxer) [inline crates/iota-indexer/src/apis/governance_api.rs:738]: Please add newlines between all the tests as on upstream.

File: crates/iota-json-rpc/src/governance_api.rs [hunk 7]
```diff
@@ -758,6 +761,31 @@ pub struct ValidatorExchangeRates {
...
+/// missing for epoch e, we will use the rate for epoch e-1 to fill it. Rates
+/// returned are in descending order by epoch.
+fn backfill_rates(
+    mut rates: Vec<(EpochId, PoolTokenExchangeRate)>,
+) -> Vec<(EpochId, PoolTokenExchangeRate)> {
+    if rates.is_empty() {
+        return rates;
+    }
+    rates.sort_unstable_by_key(|(epoch_id, _)| *epoch_id);
+    let mut filled_rates: Vec<(EpochId, PoolTokenExchangeRate)> = Vec::with_capacity(rates.len());
```
Comment (muXxer) [inline crates/iota-json-rpc/src/governance_api.rs]: Depending on what we decide for the code in the other file, we should update that here too.

File: crates/iota-json-rpc/src/governance_api.rs [hunk 8]
```diff
@@ -770,6 +798,8 @@ impl IotaRpcModule for GovernanceReadApi {
 
 #[cfg(test)]
 mod tests {
+    use iota_types::iota_system_state::PoolTokenExchangeRate;
```
Comment (muXxer) [inline crates/iota-json-rpc/src/governance_api.rs:821]: Add it below the "super" line.

**Review by muXxer — CHANGES_REQUESTED** [review]

File: crates/iota-json-rpc/src/governance_api.rs (hunk 8 above)
Comment (bingyanglin) [reply crates/iota-json-rpc/src/governance_api.rs:821]: Yeah I thought it should be below the "super" line but looks like the `cargo +nightly fmt` will force this line to put here.

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 5 above)
Comment (muXxer) [reply crates/iota-indexer/src/apis/governance_api.rs:592]: OK, `missing_rates` gets moved into `filled_rates` and is empty afterwards, that's why it works, understood.
We should add comments to make it easier to read.

File: crates/iota-indexer/src/apis/governance_api.rs [hunk 9]
```diff
@@ -561,6 +563,31 @@ impl GovernanceReadApi {
...
+    let mut filled_rates: Vec<(EpochId, PoolTokenExchangeRate)> = Vec::with_capacity(rates.len());
+    let mut missing_rates = Vec::new();
+    for (epoch_id, rate) in rates {
+        if let Some((prev_epoch_id, prev_rate)) = filled_rates.last() {
+            for missing_epoch_id in prev_epoch_id + 1..epoch_id {
+                missing_rates.push((missing_epoch_id, prev_rate.clone()));
+            }
+        };
+        filled_rates.append(&mut missing_rates);
+        filled_rates.push((epoch_id, rate));
```
Comment (muXxer) [inline crates/iota-indexer/src/apis/governance_api.rs]:
```suggestion
    // ensure epochs are processed in increasing order
    rates.sort_unstable_by_key(|(epoch_id, _)| *epoch_id);
    
    let mut filled_rates: Vec<(EpochId, PoolTokenExchangeRate)> = Vec::with_capacity(rates.len());
    let mut missing_rates = Vec::new();
    for (epoch_id, rate) in rates {
        // fill gaps between the last processed epoch and the current one
        if let Some((prev_epoch_id, prev_rate)) = filled_rates.last() {
            for missing_epoch_id in prev_epoch_id + 1..epoch_id {
                missing_rates.push((missing_epoch_id, prev_rate.clone()));
            }
        };
        
        // append any missing_rates before adding the current epoch.
        // if empty, nothing gets appended.
        // if not empty, it will be empty afterwards because it was moved into filled_rates
        filled_rates.append(&mut missing_rates);
        filled_rates.push((epoch_id, rate));
```

File: crates/iota-json-rpc/src/governance_api.rs [hunk 10]
```diff
@@ -802,4 +832,39 @@ mod tests {
...
+
+    #[test]
+    fn test_backfill_rates_no_gaps() {
+        let rate1 = PoolTokenExchangeRate::new_for_testing(100, 100);
+        let rate2 = PoolTokenExchangeRate::new_for_testing(200, 220);
+        let rate3 = PoolTokenExchangeRate::new_for_testing(300, 330);
+        let rates = vec![(2, rate2.clone()), (3, rate3.clone()), (1, rate1.clone())];
+
+        let expected: Vec<(u64, PoolTokenExchangeRate)> =
+            vec![(3, rate3.clone()), (2, rate2), (1, rate1)];
```
Comment (muXxer) [inline crates/iota-json-rpc/src/governance_api.rs:870]: Please make this multiline, as it is easier to read.

**Comment by muXxer** [comment]
I think we maybe could optimize it further, if we are 100% sure there are no duplicate entries for an epoch.

If we first sort, and then take the first and last element, we know the first epoch and last epoch. If the diff between these two +1 equals the length of the vector, there are no missing entries and we could return the list directly without further looping.

Would that maybe work @kodemartin ?

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 4 above)
Comment (kodemartin) [reply crates/iota-indexer/src/apis/governance_api.rs:570]: I respond since I proposed this refactoring: The original vector is consumed, so this has no side effects for the caller.

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 9 above)
Comment (bingyanglin) [reply crates/iota-indexer/src/apis/governance_api.rs]: Thanks for the detailed comments!

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 5 above)
Comment (kodemartin) [reply crates/iota-indexer/src/apis/governance_api.rs:592]: The original code was iterating over the min to max epoch range and for each epoch id was searching for a match in the original rates sequence, which led to quadratic complexity when filling the gaps. If there was no match found then it was pushing the previous rate in the `filled_rates`

This implementation iterates linearly and identifies any gaps between the  last filled epoch (`fillled_rates.last`) and the current `(epoch_id, rate)`. These gaps are filled intermittently in `missing_rates`, which captures the missing rates on every iteration steps.

By appending the missing rates we fill the gaps.

This is equivalent to the original, is evidently more concise and hence readable, and I argue even more efficient.

**Comment by kodemartin** [comment]
> I think we maybe could optimize it further, if we are 100% sure there are no duplicate entries for an epoch.
> 
> If we first sort, and then take the first and last element, we know the first epoch and last epoch. If the diff between these two +1 equals the length of the vector, there are no missing entries and we could return the list directly without further looping.
> 
> Would that maybe work @kodemartin ?

That should work yes. We still need to reverse though before returning/

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 9 above)
Comment (kodemartin) [reply crates/iota-indexer/src/apis/governance_api.rs]: I have to point out that these comment seem a bit redundant as the respective API docs  for `sort..` and `append` are pretty explicit about the operations and side effects.

If we have to inline a summary of what the methods called do, it probably defeats the purpose of using the most appropriate method to make the code more concise. 

Do we really need those comments then @muXxer, @bingyanglin ?

https://doc.rust-lang.org/std/vec/struct.Vec.html#method.append
https://doc.rust-lang.org/std/vec/struct.Vec.html#method.sort_unstable_by_key

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 6 above)
Comment (bingyanglin) [reply crates/iota-indexer/src/apis/governance_api.rs:738]: Thanks for identifying this! Modified at [fe47c16](https://github.com/iotaledger/iota/pull/5184/commits/fe47c165b1f3851f3f8f2bcefca211059d1f7e94).

File: crates/iota-json-rpc/src/governance_api.rs (hunk 10 above)
Comment (bingyanglin) [reply crates/iota-json-rpc/src/governance_api.rs:870]: I agree it would be nicer to have
```rust
        let rates = vec![(2, rate2.clone()), 
                         (3, rate3.clone()), 
                         (1, rate1.clone())];
        let expected: Vec<(u64, PoolTokenExchangeRate)> =
            vec![(3, rate3.clone()), 
                 (2, rate2), 
                 (1, rate1)];
 ```
 but looks like the `cargo +nightly fmt` will force them to be one line.

**Comment by bingyanglin** [comment]
> > I think we maybe could optimize it further, if we are 100% sure there are no duplicate entries for an epoch.
> > If we first sort, and then take the first and last element, we know the first epoch and last epoch. If the diff between these two +1 equals the length of the vector, there are no missing entries and we could return the list directly without further looping.
> > Would that maybe work @kodemartin ?
> 
> That should work yes. We still need to reverse though before returning/

Thanks for the suggestion @muXxer @kodemartin , the early abortion logic and special test case was added at [d387b5f](https://github.com/iotaledger/iota/pull/5184/commits/d387b5f88dd0c990d8193c469f97b3c067450dbe). More test cases were added at  [5f3f8bf](https://github.com/iotaledger/iota/pull/5184/commits/5f3f8bfa7cb79d58a715fa572e2abf16fd5fa9ff) too.

File: crates/iota-indexer/src/apis/governance_api.rs [hunk 11]
```diff
@@ -561,6 +563,50 @@ impl GovernanceReadApi {
...
+) -> Vec<(EpochId, PoolTokenExchangeRate)> {
+    if rates.is_empty() {
+        return rates;
+    }
+    // ensure epochs are processed in increasing order
+    rates.sort_unstable_by_key(|(epoch_id, _)| *epoch_id);
+
+    // Check if there are any gaps in the epochs
+    let min_epoch = rates.first().unwrap().0;
+    let max_epoch = rates.last().unwrap().0;
```
Comment (kodemartin) [inline crates/iota-indexer/src/apis/governance_api.rs]: Nit: It is typically preferred to use [expect as precondition](https://doc.rust-lang.org/std/error/index.html#common-message-styles) instead of unwrapping, and use pattern matching instead of indexing the tuple.
```suggestion
    let (min_epoch, _) = rates.first().expect("rates should not be empty");
    let (max_epoch, _) = rates.last().expect("rates should not be empty");
```

File: crates/iota-indexer/src/apis/governance_api.rs [hunk 12]
```diff
@@ -561,6 +563,50 @@ impl GovernanceReadApi {
...
+    let expected_len = (max_epoch - min_epoch + 1) as usize;
+
+    // Only perform backfilling if there are gaps
+    if rates.len() == expected_len {
```
Comment (semenov-vladyslav) [inline crates/iota-indexer/src/apis/governance_api.rs]: Is it guaranteed that the epoch ids are all unique? Otherwise this optimization will work incorrectly.

File: crates/iota-indexer/src/apis/governance_api.rs [hunk 13]
```diff
@@ -561,6 +563,50 @@ impl GovernanceReadApi {
...
+        rates.reverse();
+        return rates;
+    }
+
+    let mut filled_rates: Vec<(EpochId, PoolTokenExchangeRate)> = Vec::with_capacity(rates.len());
```
Comment (semenov-vladyslav) [inline crates/iota-indexer/src/apis/governance_api.rs]: Was `expected_len` meant here instead of `rates.len()`?

File: crates/iota-indexer/src/apis/governance_api.rs [hunk 14]
```diff
@@ -561,6 +563,50 @@ impl GovernanceReadApi {
...
+    let mut missing_rates = Vec::new();
```
Comment (semenov-vladyslav) [inline crates/iota-indexer/src/apis/governance_api.rs]: Do we really need additional vec `missing_rates`?

File: crates/iota-indexer/src/apis/governance_api.rs [hunk 15]
```diff
@@ -561,6 +563,50 @@ impl GovernanceReadApi {
...
+    for (epoch_id, rate) in rates {
+        // fill gaps between the last processed epoch and the current one
+        if let Some((prev_epoch_id, prev_rate)) = filled_rates.last() {
+            for missing_epoch_id in prev_epoch_id + 1..epoch_id {
+                missing_rates.push((missing_epoch_id, prev_rate.clone()));
```
Comment (semenov-vladyslav) [inline crates/iota-indexer/src/apis/governance_api.rs:596]: Why not just push directly into `filled_rates`?

**Review by semenov-vladyslav — CHANGES_REQUESTED** [review]

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 11 above)
Comment (bingyanglin) [reply crates/iota-indexer/src/apis/governance_api.rs]: Got it. Thanks.

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 13 above)
Comment (bingyanglin) [reply crates/iota-indexer/src/apis/governance_api.rs]: No the rates might have gaps, so `rates.len()` < `expected_len` here. (If equal then it will be early aborted in previous codes)

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 15 above)
Comment (bingyanglin) [reply crates/iota-indexer/src/apis/governance_api.rs:596]: (Same reason as the previous comment)

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 14 above)
Comment (bingyanglin) [reply crates/iota-indexer/src/apis/governance_api.rs:590]: Because `filled_rates` was also immutable borrowed at filled_rates.last(). Also I think using a new missing_rates vec might be easier to read, and the compiler will optimize them so I guess it is fine.

Comment (bingyanglin) [reply crates/iota-indexer/src/apis/governance_api.rs]: Yeah that's a good point, because `filled_rates` was also immutable borrowed at `filled_rates.last()`. Also I think using a new missing_rates vec might be easier to read, and the compiler will optimize them so I guess it is fine.

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 13 above)
Comment (semenov-vladyslav) [reply crates/iota-indexer/src/apis/governance_api.rs]: Yeah, right. But I mean that the final `filled_rates` vec will contain exactly `expected_len` elements. That's exactly the purpose of `with_capacity` constructor.

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 14 above)
Comment (semenov-vladyslav) [reply crates/iota-indexer/src/apis/governance_api.rs]: Surely you can just clone the last element, no need to keep it borrowed. Just do `filled_rates.last().cloned()` instead.

Comment (bingyanglin) [reply crates/iota-indexer/src/apis/governance_api.rs]: Yeah but I guess might be fine to make it easier to read so I might want o keep to use the additional `missing_rates`

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 13 above)
Comment (bingyanglin) [reply crates/iota-indexer/src/apis/governance_api.rs]: Yes you are right. Modified. Thanks!.

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 14 above)
Comment (kodemartin) [reply crates/iota-indexer/src/apis/governance_api.rs]: I would add that cloning `filled_rates.last()` is suboptimal. `missing_rates` allows cloning `prev_rate` **only** if we need to. That is, inside the `for` loop that follows.

Comment (semenov-vladyslav) [reply crates/iota-indexer/src/apis/governance_api.rs]: IDK, for me it's a bit harder to understand additional `missing_rates` vec. As for cloning, the objects are lightweight and the pattern is easy for compiler to optimize, not sure it's the case with additional vector where you do actually need to allocate memory, etc..

Comment (kodemartin) [reply crates/iota-indexer/src/apis/governance_api.rs]: An alternative to avoid cloning would be to derive `Copy` for the rate type. This could eliminate the need for `missing_rates` from the borrow-checker perspective.

But I do some merit from the readability perspective as well. `missing_rates` are updated on the occasion of a gap, and as such it represents the gaps that we fill on every iteration.

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 12 above)
Comment (bingyanglin) [reply crates/iota-indexer/src/apis/governance_api.rs]: After tracing the code, the The `bcs_name` is deserialized into an `EpochId`, and dynamic fields cannot have duplicate names/keys. Therefore, it's not possible to have duplicate epochs in the rates vector for a single validator. (Please correct me if I'm wrong)

File: crates/iota-json-rpc/src/governance_api.rs [hunk 16]
```diff
@@ -773,7 +773,18 @@ fn backfill_rates(
...
+    let expected_len = (max_epoch - min_epoch + 1) as usize;
+
+    // Only perform backfilling if there are gaps
+    if rates.len() == expected_len {
+        rates.reverse();
+        return rates;
+    }
+
+    let mut filled_rates: Vec<(EpochId, PoolTokenExchangeRate)> = Vec::with_capacity(expected_len);
     let mut missing_rates = Vec::new();
```
Comment (muXxer) [inline crates/iota-json-rpc/src/governance_api.rs]: We already know how many rates are missing at this point. We could initialise with a capacity already.

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 14 above)
Comment (muXxer) [reply crates/iota-indexer/src/apis/governance_api.rs]: With the new check in place, this code should be executed only if there are was a safe mode (hopefully really rare) anyways. So I wouldn't overoptimise and keep readability.

File: crates/iota-indexer/src/apis/governance_api.rs (hunk 5 above)
Comment (muXxer) [reply crates/iota-indexer/src/apis/governance_api.rs:592]: I am not against that change at all. 

For me it was harder to understand in the beginning, so I corrected my initial statement and asked for maybe some comments in the code, which we added now :)

File: crates/iota-indexer/src/apis/governance_api.rs [hunk 17]
```diff
@@ -561,6 +563,50 @@ impl GovernanceReadApi {
...
+    let expected_len = (max_epoch - min_epoch + 1) as usize;
+
+    // Only perform backfilling if there are gaps
+    if rates.len() == expected_len {
+        rates.reverse();
+        return rates;
+    }
+
+    let mut filled_rates: Vec<(EpochId, PoolTokenExchangeRate)> = Vec::with_capacity(expected_len);
+    let mut missing_rates = Vec::new();
```
Comment (muXxer) [inline crates/iota-indexer/src/apis/governance_api.rs]: We already know how many rates are missing at this point. We could initialise with a capacity already.

Comment (bingyanglin) [reply crates/iota-indexer/src/apis/governance_api.rs]: Thanks. Missed this. Added at [86467c0](https://github.com/iotaledger/iota/pull/5184/commits/86467c034510d51e2d2423220ff7e4d2000c9839).

File: crates/iota-json-rpc/src/governance_api.rs (hunk 16 above)
Comment (bingyanglin) [reply crates/iota-json-rpc/src/governance_api.rs]: Thanks. Missed this. Added at [86467c0](https://github.com/iotaledger/iota/pull/5184/commits/86467c034510d51e2d2423220ff7e4d2000c9839).

**Review by muXxer — APPROVED** [review]

**Review by semenov-vladyslav — APPROVED** [review]
