### PR TITLE
fix(iota): canonicalize keystore path

### LINKED ISSUE #4923: fix(iota): canonicalize keystore path
https://github.com/MystenLabs/sui/pull/19312

### PR DESCRIPTION
**Pull request by thibault-martinez**
Fixes https://github.com/iotaledger/iota/issues/4923

# Wallet config was created in the current directory as a relative path

## Before

```
thibault@Host-002 ~/i/iota (develop)> mkdir -p /tmp/b
thibault@Host-002 ~/i/iota (develop)> cd /tmp/b
thibault@Host-002 /t/b> $iota client --client.config client.yaml new-address
Config file ["client.yaml"] doesn't exist, do you want to connect to an IOTA Full node server [y/N]?y
IOTA Full node server URL (Defaults to IOTA Testnet if not specified) : 
Keys saved as Bech32.
╭────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Created new keypair and saved it to keystore.                                                      │
├────────────────┬───────────────────────────────────────────────────────────────────────────────────┤
│ alias          │ keen-euclase                                                                      │
│ address        │ 0xfd6dc2c9dd4db5a51090c9012b5f95f310edde4f79998708e6b15aadf8e949b7                │
│ keyScheme      │ ed25519                                                                           │
│ recoveryPhrase │ decrease world super dumb stool wish mechanic gesture amused medal bachelor royal │
╰────────────────┴───────────────────────────────────────────────────────────────────────────────────╯
thibault@Host-002 /t/b> cd -
thibault@Host-002 ~/i/iota (develop)> $iota client --client.config /tmp/b/client.yaml active-address
None
```

keystore path: `iota.keystore`

## After

```
thibault@Host-002 ~/i/iota (canonicalize-keystore-path)> mkdir -p /tmp/b
thibault@Host-002 ~/i/iota (canonicalize-keystore-path)> cd /tmp/b
thibault@Host-002 /t/b> $iota client --client.config client.yaml new-address
Config file ["client.yaml"] doesn't exist, do you want to connect to an IOTA Full node server [y/N]?y
IOTA Full node server URL (Defaults to IOTA Testnet if not specified) : 
Keys saved as Bech32.
╭───────────────────────────────────────────────────────────────────────────────────────╮
│ Created new keypair and saved it to keystore.                                         │
├────────────────┬──────────────────────────────────────────────────────────────────────┤
│ alias          │ fervent-labradorite                                                  │
│ address        │ 0xfb3b7750b64d36817e63ec974301a44533bfccd54b49413d58b5ce219a228456   │
│ keyScheme      │ ed25519                                                              │
│ recoveryPhrase │ sketch box follow fire blast benefit more wreck loan draw clever joy │
╰────────────────┴──────────────────────────────────────────────────────────────────────╯
thibault@Host-002 /t/b> cd -
thibault@Host-002 ~/i/iota (canonicalize-keystore-path)> $iota client --client.config /tmp/b/client.yaml active-address
0xfb3b7750b64d36817e63ec974301a44533bfccd54b49413d58b5ce219a228456
```

keystore path: `/private/tmp/b/iota.keystore`

# Wallet config was given a path with some parent - relative

## Before

```
thibault@Host-002 ~/i/iota (develop)> mkdir -p /tmp/a
thibault@Host-002 ~/i/iota (develop)> cd /tmp/a
thibault@Host-002 /t/a> $iota client --client.config ./client.yaml new-address
Config file ["./client.yaml"] doesn't exist, do you want to connect to an IOTA Full node server [y/N]?y
IOTA Full node server URL (Defaults to IOTA Testnet if not specified) : 
╭──────────────────────────────────────────────────────────────────────────────────────────────╮
│ Created new keypair and saved it to keystore.                                                │
├────────────────┬─────────────────────────────────────────────────────────────────────────────┤
│ alias          │ sharp-plasma                                                                │
│ address        │ 0x3bf84a08601a6295893ba68a2b73235cabcc22bf1672912ac0d51439a83ce571          │
│ keyScheme      │ ed25519                                                                     │
│ recoveryPhrase │ illness win over school gadget tail bread budget cup ecology program settle │
╰────────────────┴─────────────────────────────────────────────────────────────────────────────╯
thibault@Host-002 /t/a> cd -
thibault@Host-002 ~/i/iota (develop)> $iota client --client.config /tmp/a/client.yaml active-address
None
```

keystore path: `./iota.keystore`

## After

```
thibault@Host-002 ~/i/iota (canonicalize-keystore-path)> mkdir -p /tmp/a
thibault@Host-002 ~/i/iota (canonicalize-keystore-path)> cd /tmp/a
thibault@Host-002 /t/a> $iota client --client.config ./client.yaml new-address
Config file ["./client.yaml"] doesn't exist, do you want to connect to an IOTA Full node server [y/N]?y
IOTA Full node server URL (Defaults to IOTA Testnet if not specified) : 
parent "."
2. Wallet config was given a path with some parent (could be relative or absolute).
keystore_path "/private/tmp/a/iota.keystore"
Keys saved as Bech32.
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│ Created new keypair and saved it to keystore.                                               │
├────────────────┬────────────────────────────────────────────────────────────────────────────┤
│ alias          │ stupefied-heliotrope                                                       │
│ address        │ 0xd1a83285756c455989f6977766d18f1bc44569c310386489716b3285d856515d         │
│ keyScheme      │ ed25519                                                                    │
│ recoveryPhrase │ spoon angry atom patrol route essay black cement effort stock symptom cash │
╰────────────────┴────────────────────────────────────────────────────────────────────────────╯
thibault@Host-002 /t/a> cd -
thibault@Host-002 ~/i/iota (canonicalize-keystore-path)> $iota client --client.config /tmp/a/client.yaml active-address
0xd1a83285756c455989f6977766d18f1bc44569c310386489716b3285d856515d
```

keystore path `/private/tmp/a/iota.keystore`

# Wallet config was given a path with some parent - absolute

## Before

```
thibault@Host-002 ~/i/iota (develop)> mkdir -p /tmp/a
thibault@Host-002 ~/i/iota (develop)> cd /tmp/a
thibault@Host-002 /t/a> $iota client --client.config /private/tmp/a/client.yaml new-address
Config file ["/private/tmp/a/client.yaml"] doesn't exist, do you want to connect to an IOTA Full node server [y/N]?y
IOTA Full node server URL (Defaults to IOTA Testnet if not specified) : 
╭──────────────────────────────────────────────────────────────────────────────────────────────╮
│ Created new keypair and saved it to keystore.                                                │
├────────────────┬─────────────────────────────────────────────────────────────────────────────┤
│ alias          │ hardcore-amethyst                                                           │
│ address        │ 0x748118a27fc44629e4cd84aa184e59dae6a6469f99976e5e199911cb760d0cb7          │
│ keyScheme      │ ed25519                                                                     │
│ recoveryPhrase │ exercise series describe boost fix trade reason turtle off exit depart kite │
╰────────────────┴─────────────────────────────────────────────────────────────────────────────╯
thibault@Host-002 /t/a> cd -
thibault@Host-002 ~/i/iota (develop)> $iota client --client.config /tmp/a/client.yaml active-address
0x748118a27fc44629e4cd84aa184e59dae6a6469f99976e5e199911cb760d0cb7
```

keystore path: `/private/tmp/a/iota.keystore`

## After

```
thibault@Host-002 ~/i/iota (canonicalize-keystore-path)> mkdir -p /tmp/a
thibault@Host-002 ~/i/iota (canonicalize-keystore-path)> cd /tmp/a
thibault@Host-002 /t/a> $iota client --client.config /private/tmp/a/client.yaml new-address
Config file ["/private/tmp/a/client.yaml"] doesn't exist, do you want to connect to an IOTA Full node server [y/N]?y
IOTA Full node server URL (Defaults to IOTA Testnet if not specified) : 
parent "/private/tmp/a"
2. Wallet config was given a path with some parent (could be relative or absolute).
keystore_path "/private/tmp/a/iota.keystore"
Keys saved as Bech32.
╭─────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Created new keypair and saved it to keystore.                                                   │
├────────────────┬────────────────────────────────────────────────────────────────────────────────┤
│ alias          │ determined-garnet                                                              │
│ address        │ 0x4b529f417cb06f8ca1e13aff772d49af3e1007dff7c0f2b7bb5b0111fbfaa049             │
│ keyScheme      │ ed25519                                                                        │
│ recoveryPhrase │ creek false prefer february erupt organ market excess timber cause motion axis │
╰────────────────┴────────────────────────────────────────────────────────────────────────────────╯
thibault@Host-002 /t/a> cd -
thibault@Host-002 ~/i/iota (canonicalize-keystore-path)> $iota client --client.config /tmp/a/client.yaml active-address
0x4b529f417cb06f8ca1e13aff772d49af3e1007dff7c0f2b7bb5b0111fbfaa049
```

keystore path: `/private/tmp/a/iota.keystore`

### CODE REVIEW

File: crates/iota/src/iota_commands.rs [hunk 1]
```diff
@@ -1275,12 +1275,25 @@ async fn prompt_if_no_config(
...
+                Some(parent) if parent.as_os_str().is_empty() => {
+                    std::env::current_dir().context("Could not find current directory")?
+                }
+                // Wallet config was given a path with some parent (could be relative or absolute).
+                Some(parent) => parent
+                    .canonicalize()
+                    .context("Could not find iota config directory")?,
+                // No parent component and the wallet config was the empty string, use the default
+                // config.
+                None if wallet_conf_path.as_os_str().is_empty() => iota_config_dir()?,
```
Comment (thibault-martinez) [inline crates/iota/src/iota_commands.rs:1288]: Is this even possible?

File: crates/iota/src/iota_commands.rs [hunk 2]
```diff
@@ -1241,12 +1241,25 @@ async fn prompt_if_no_config(
...
 
         if let Some(env) = env {
-            let keystore_path = wallet_conf_path
-                .parent()
-                .unwrap_or(&iota_config_dir()?)
-                .join(IOTA_KEYSTORE_FILENAME);
+            let keystore_path = match wallet_conf_path.parent() {
+                // Wallet config was created in the current directory as a relative path.
+                Some(parent) if parent.as_os_str().is_empty() => {
+                    std::env::current_dir().context("Couldn't find current directory")?
```
Comment (Thoralf-M) [inline crates/iota/src/iota_commands.rs]: Can you change it to `iota config directory` in the error message so it's more clear?

File: crates/iota/src/iota_commands.rs (hunk 1 above)
Comment (Thoralf-M) [reply crates/iota/src/iota_commands.rs:1288]: If wallet_conf_path is an empty String, `PathBuf::new()` would end up like this

Comment (thibault-martinez) [reply crates/iota/src/iota_commands.rs:1288]: Sure but can `wallet_conf_path` actually be empty? I tried from the CLI and clap complains so it never reaches this

Comment (Thoralf-M) [reply crates/iota/src/iota_commands.rs:1288]: Also couldn't do it with the CLI

File: crates/iota/src/iota_commands.rs (hunk 2 above)
Comment (thibault-martinez) [reply crates/iota/src/iota_commands.rs]: I think I would still like to have `current directory` somehow, because that's the actual call that failed, any suggestion?

Comment (Thoralf-M) [reply crates/iota/src/iota_commands.rs]: `current iota config directory`

Comment (Thoralf-M) [reply crates/iota/src/iota_commands.rs]: Or don't you want something in between?

Comment (thibault-martinez) [reply crates/iota/src/iota_commands.rs]: Would you be fine with `Couldn't find current directory for iota config`?

Comment (Thoralf-M) [reply crates/iota/src/iota_commands.rs]: Also fine with that :+1:

Comment (thibault-martinez) [reply crates/iota/src/iota_commands.rs]: https://github.com/iotaledger/iota/pull/4936/commits/6f52eb4d053f84e01cd52c3b2b9a5033f6902192

**Review by Thoralf-M — APPROVED** [review]

**Review by Alex6323 — APPROVED** [review]
