### PR TITLE
fix(devx): Fix CTF Challenge 0 

### LINKED ISSUE #5370: Fix Return In CTF 0
The button to view the NFT in the explorer sends `Undefined` instead of the object ID.

Image

### PR DESCRIPTION
**Pull request by lucas-tortora**
# Description of change

Fixed the pop-in response for CTF challenge 0. 

popup.tst:
* renamed to pop-in.tsx
* fix path props
* use false for setShowPopUp on close always

mint-leap-frog-nft.tsx:
* add digest prop and use it for PopUp

ctf-utils.ts
* fix spacing
* rename Error to Response
* add digest to response

ctf-verifier.tsx
* rename Error to Response
* removed unused imports and constants
 
## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/5370

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: docs/site/src/components/CTF/ctf-verifier.tsx [hunk 1]
```diff
@@ -43,7 +42,7 @@ const ChallengeVerifier: React.FC<ChallengeVerifierProps> = ({
   const wallets = useWallets();
   const { mutate } = useConnectWallet();
   const { mutate: signAndExecuteTransaction} = useSignAndExecuteTransaction();
-  const [digest,setDigest] = useState<string>('');
+  const [setDigest] = useState<string>('');
```
Comment (vivekjain23) [inline docs/site/src/components/CTF/ctf-verifier.tsx]: Let's remove this, as it has no usage.

**Review by vivekjain23 — CHANGES_REQUESTED** [review]

File: docs/site/src/components/CTF/ctf-verifier.tsx (hunk 1 above)
Comment (lucas-tortora) [reply docs/site/src/components/CTF/ctf-verifier.tsx]:
```suggestion
```

File: docs/site/src/components/CTF/ctf-verifier.tsx [hunk 2]
```diff
@@ -55,8 +53,8 @@ const ChallengeVerifier: React.FC<ChallengeVerifierProps> = ({
       signAndExecuteTransaction,
       setLoading,
       setCoins,
-      setError,
-      setShowPopup,
+      setResponse,
+      setShowPopIn,
       setDigest
```
Comment (vivekjain23) [inline docs/site/src/components/CTF/ctf-verifier.tsx]:
```suggestion

```

File: docs/site/src/utils/ctf-utils.ts [hunk 3]
```diff
@@ -11,12 +11,12 @@ export const handleChallengeSubmit = async ({
     signAndExecuteTransaction,
     setLoading,
     setCoins,
-    setError,
-    setShowPopup,
+    setResponse,
+    setShowPopIn,
     setDigest
```
Comment (vivekjain23) [inline docs/site/src/utils/ctf-utils.ts]:
```suggestion

```

**Review by vivekjain23 — APPROVED** [review]
Aside from a few minor changes, LGTM.

**Review by Ginowine — APPROVED** [review]
Challenge 0 works great now, I remember the experience I had when I was recording the video on challenge 0, I got confused a little because it was taking too much time to complete. The popin looks great.
