### PR TITLE
fix(iota-indexer, iota-cluster-test, iota-graphql-rpc): Reset indexer database for `iota start` only once + refactor interfaces

### LINKED ISSUE #5365: Is start_test_indexer() reset db logic correct?
The reset_database param is hardcoded set to false here
https://github.com/iotaledger/iota/blob/c00d430f3abb61d9ad9b35554db30837bb08d1ed/crates/iota-indexer/src/test_utils.rs#L55-L56
But in the config later, it's hardcoded to true
https://github.com/iotaledger/iota/blob/c00d430f3abb61d9ad9b35554db30837bb08d1ed/crates/iota-indexer/src/test_utils.rs#L95 which just means that this closure here https://github.com/iotaledger/iota/blob/c00d430f3abb61d9ad9b35554db30837bb08d1ed/crates/iota-indexer/src/test_utils.rs#L119-L123
always gets executed

Shouldn't there be a single bool used in both cases? Now it seems to reset partially or completely depending on the `new_database` https://github.com/iotaledger/iota/blob/c00d430f3abb61d9ad9b35554db30837bb08d1ed/crates/iota-indexer/src/test_utils.rs#L83-L102

### LINKED ISSUE #5490: iota start command `--with-indexer` resets the database two times
## Bug description

By executing `cargo run --features indexer --bin iota start --with-indexer --pg-port 5432 --pg-db-name iota_indexer --force-regenesis` the database is reset twice, once for the `writer` instance and once for the `analytical worker` instance.

```
2025-02-19T12:48:26.660559Z  INFO iota_indexer::db::setup_postgres: Reset database complete.
2025-02-19T12:48:26.660850Z  WARN iota_metrics: init_metrics registry overwritten
2025-02-19T12:48:26.661840Z  INFO iota::iota_commands: Indexer in writer mode started
2025-02-19T12:48:26.661866Z  INFO iota_indexer::test_utils: Setting DB_POOL_SIZE to 10
2025-02-19T12:48:26.661952Z  WARN iota_metrics: init_metrics registry overwritten
2025-02-19T12:48:26.661965Z  INFO iota_indexer::indexer: IOTA Indexer Writer (version "0.10.0-alpha") started...
```

```
2025-02-19T12:48:27.197518Z  INFO iota_indexer::db::setup_postgres: Reset database complete.
2025-02-19T12:48:27.197662Z  WARN iota_metrics: init_metrics registry overwritten
2025-02-19T12:48:27.198465Z  INFO iota_indexer::indexer: IOTA Indexer Analytical Worker (version "0.10.0-alpha") started...
```

---

While the second reset happens, the writer instance might run into errors like:

```
2025-02-19T12:48:26.817174Z ERROR commit_checkpoints{first=0 last=0}: iota_indexer::store::pg_indexer_store: Error with persisting data into DB: ErrorWithContext("Failed to write to events::table DB", Postgres(DatabaseError(Unknown, "relation \"events\" does not exist"))), retrying...
2025-02-19T12:48:26.817353Z ERROR iota_indexer::store::pg_indexer_store: Error with persisting data into DB: ErrorWithContext("Failed to write to tx_senders::table DB", Postgres(DatabaseError(Unknown, "relation \"tx_senders\" does not exist"))), retrying...
2025-02-19T12:48:26.817470Z ERROR iota_indexer::store::pg_indexer_store: Error with persisting data into DB: ErrorWithContext("Failed to write to tx_changed_objects::table DB", Postgres(DatabaseError(Unknown, "relation \"tx_changed_objects\" does not exist"))), retrying...
2025-02-19T12:48:26.817551Z ERROR commit_checkpoints{first=0 last=0}: iota_indexer::store::pg_indexer_store: Error with persisting data into DB: Postgres(DatabaseError(Unknown, "relation \"display\" does not exist")), retrying...
2025-02-19T12:48:26.817661Z  INFO iota_indexer::store::pg_indexer_store: Persisted 0 rows to tx_calls_pkg tables elapsed=0.004073083
```

As suggested in the logs, it is retrying. However, eventually a `.expect()` in the committer (https://github.com/iotaledger/iota/blob/develop/crates/iota-indexer/src/handlers/committer.rs#L192) if triggered would stop the writer instance. To avoid this, we should make sure the database is only reset once.

### PR DESCRIPTION
**Pull request by samuel-rufi**
# Description of change

The hardcoding of `reset_db: true` in https://github.com/iotaledger/iota/blob/c00d430f3abb61d9ad9b35554db30837bb08d1ed/crates/iota-indexer/src/test_utils.rs#L95 resulted in multiple database resets when multiple indexer worker instances (writer mode, analytical writer) were created as in the `iota start` subcommand https://github.com/iotaledger/iota/blob/1b832e0126ad15cf53b58999770ced49b07cc3f1/crates/iota/src/iota_commands.rs#L811-L840

The second reset had side effects for the primary Writer, as tables might not exist and writing to them failed.

Furthermore, the mutable variable `reset_database` defined in 

https://github.com/iotaledger/iota/blob/c00d430f3abb61d9ad9b35554db30837bb08d1ed/crates/iota-indexer/src/test_utils.rs#L71

 and hardcoded by default to `false` in https://github.com/iotaledger/iota/blob/c00d430f3abb61d9ad9b35554db30837bb08d1ed/crates/iota-indexer/src/test_utils.rs#L55-L56

was used to indicate if the database should be dropped and created. This is not to be confused with database resets managed by the `reset_db` variable. It's about creating a new database if the test indexer should not run with the default db and therefore had a misleading naming. Also, `reset_database` was only enabled/mutated if https://github.com/iotaledger/iota/blob/c00d430f3abb61d9ad9b35554db30837bb08d1ed/crates/iota-indexer/src/test_utils.rs#L74 was `Some`. 

For this reason, the PR also refactors and simplifies the interfaces.

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/5490
Fixes https://github.com/iotaledger/iota/issues/5365

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

To check if the database resets happen only once anymore, the output of following commands was checked:
`cargo run --features indexer --bin iota start --with-indexer --pg-port 5432 --pg-db-name iota_indexer --with-graphql=0.0.0.0:8000 --force-regenesis`

## Change checklist

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: crates/iota-indexer/src/test_utils.rs [hunk 1]
```diff
@@ -42,64 +42,51 @@ impl IndexerTypeConfig {
...
 
 /// Starts an indexer reader or writer for testing depending on the
-/// `reader_writer_config`. If `reset_database` is true, the database instance
-/// named in `db_url` will be dropped and reinstantiated.
+/// `reader_writer_config`.
 pub async fn start_test_indexer_impl(
-    db_url: Option<String>,
+    db_url: String,
+    drop_and_create_db: bool,
+    reset_db: bool,
```
Comment (kodemartin) [inline crates/iota-indexer/src/test_utils.rs]: These are not independent I reckon. If I pass 
```rust
drop_and_create_db: true,
reset_db: false
```
A  new database will be created according to the `db_url`, but no migrations will be run, and hence we will still have an issue.

So I would propose to keep only a `reset_db` that abstracts away the two internal requirements for a new db. These are: recreate the database, apply migrations.

If `reset_db` is `false` then the database in `db_url` will remain intact.

File: crates/iota-indexer/src/test_utils.rs [hunk 2]
```diff
@@ -42,64 +42,51 @@ impl IndexerTypeConfig {
...
     .await
 }
 
 /// Starts an indexer reader or writer for testing depending on the
-/// `reader_writer_config`. If `reset_database` is true, the database instance
-/// named in `db_url` will be dropped and reinstantiated.
+/// `reader_writer_config`.
 pub async fn start_test_indexer_impl(
-    db_url: Option<String>,
+    db_url: String,
```
Comment (kodemartin) [inline crates/iota-indexer/src/test_utils.rs:65]: This now requires that the `db_name` is present in the URL, whereas this was not the case previously I think . 

At any case, it makes sense to ensure that the db-name is included.

File: crates/iota-indexer/src/test_utils.rs (hunk 1 above)
Comment (samuel-rufi) [reply crates/iota-indexer/src/test_utils.rs]: Good point, I see. Let me adjust this!

File: crates/iota-indexer/src/test_utils.rs (hunk 2 above)
Comment (samuel-rufi) [reply crates/iota-indexer/src/test_utils.rs:65]: Yes, I share your view! `db_url` should really point to the db.
Previously, if `new_database` was `Some` we added the name to the provided url or replaced the db name in the default URL using:

```
    if let Some(new_database) = new_database {
        db_url = replace_db_name(&db_url, new_database).0;
        ....
    };
```

It seems like in all of these `Some` cases however only name replacements happened (as the URL was interpolated by `get_indexer_db_url`) or the URL came from a default implementation.

So, I guess there is no further action to do here at this point. In future I think it would make sense to have proper type for the database url for more safety.

File: crates/iota-indexer/src/test_utils.rs (hunk 1 above)
Comment (samuel-rufi) [reply crates/iota-indexer/src/test_utils.rs]: Fixed with https://github.com/iotaledger/iota/pull/5590/commits/c57ea7e3dc0e4fe7bd2f6d2ef647e6bc2e180de0

**Review by kodemartin — APPROVED** [review]
lgtm :broom:

**Review by DaughterOfMars — APPROVED** [review]

**Review by tomxey — COMMENTED** [review]
lgtm ⛰

**Review by tomxey — APPROVED** [review]
