### PR TITLE
fix[docs]: Swizzle CodeBlock to allow multiple CodeBlocks to coexist

### LINKED ISSUE #4403: Live editor broken
Currently we have the live code editor broken as Identity is using the saucelabs import plugin to import their code which overrides the live editor plugin

### PR DESCRIPTION
**Pull request by Dr-Electron**
# Description of change

Swizzle ejected the CodeBlock so we can use multiple CodeBlock plugins

## Links to any relevant issues

Fixes #4403.

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Tested locally

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: docs/site/src/theme/CodeBlock/index.tsx [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+ * REASONS:
+ *  - Add check for reference CodeBlock so it can coexist with the original CodeBlock and the live code block
+ */
+import React from 'react';
+import CodeBlock from '@theme-original/CodeBlock';
+import ReferenceCodeBlock from '@saucelabs/theme-github-codeblock/build/theme/ReferenceCodeBlock';
+import type CodeBlockType from '@theme/CodeBlock';
+import type {WrapperProps} from '@docusaurus/types';
+
+type Props = WrapperProps<typeof CodeBlockType>;
```
Comment (Dr-Electron) [inline docs/site/src/theme/CodeBlock/index.tsx:13]: We should use proper props here. Not sure how to solve that in a good way. We probably need to extend the original props with both props from the code block plugins 🤔

Comment (Dr-Electron) [reply docs/site/src/theme/CodeBlock/index.tsx:13]: Done. Not sure if this is the proper react way and if I understood everything correctly, but done 😆

File: docs/site/src/theme/CodeBlock/index.tsx [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+
+function isReferenceCodeBlockType(props: object): props is ReferenceCodeBlockProps {
+  return 'reference' in props 
+    || ('metastring' in props && typeof props.metastring === 'string' && props.metastring.split(' ').includes('reference'));
+}
+
+// Wrap CodeBlock to check if the Code Block is a reference code block
+// IF it isn't, we just return the live theme CodeBlock which will check,
+// if the code block is a live code block or the original code block
```
Comment (Dr-Electron) [inline docs/site/src/theme/CodeBlock/index.tsx]:
```suggestion
// Wrap CodeBlock to check if it is a reference (saucepans) CodeBlock.
// If it isn't, we just return the live plugin CodeBlock which will check,
// if the CodeBlock is a live CodeBlock or the original CodeBlock
```

File: docs/site/src/theme/CodeBlock/index.tsx [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+        <ReferenceCodeBlock {...props} />
+      </>
+    );
+  } else {
+    return (
+      <>
+        <CodeBlock {...props} />
+      </>
+    );
+  }
```
Comment (vivekjain23) [inline docs/site/src/theme/CodeBlock/index.tsx]: this could be done like this also

```suggestion
    return (
      <>
       {isReferenceCodeBlockType(props) ?  <ReferenceCodeBlock {...props} /> :  <CodeBlock {...props} />}
      </>
    );
  }
```

**Review by lucas-tortora — APPROVED** [review]
Besides @vivekjain23's comment, LGTM

File: docs/site/src/theme/CodeBlock/index.tsx (hunk 3 above)
Comment (Dr-Electron) [reply docs/site/src/theme/CodeBlock/index.tsx]: Yes I actually know. But in the end I just started with a copy of the saucepans code and then kept it this way 😆 

But yeah looks nicer this way 👍

**Review by vivekjain23 — APPROVED** [review]
We have a build issue, the rest looks good to me :)

**Review by Ginowine — APPROVED** [review]
