### PR TITLE
fix(iota): display MultiSigCombinePartialSig details

### LINKED ISSUE #7668: iota keytool multi-sig-combine-partial-sig returns same value for multisigParsed and multisigSerialized
## Bug description

iota keytool multi-sig-combine-partial-sig returns same value for multisigParsed and multisigSerialized:
```
iota keytool multi-sig-combine-partial-sig \
--pks \
AIKM0+W7wvP6pitTgJQVB7Yfn2oMO3aZd3votkb6x87l \
AIA4z3cY/7bzUz/Kj1mPe5I9k82gpL3J/WppWjnB53SI \
APBL9QuKI1MjSNn5Jt0w0zOUWdCQxbn84UlKmJtGbuU4 \
--weights 1 1 1 \
--threshold 2 \
--sigs \
AP58oYBpNZRsR8ReDL05R/37o8l5t89e+RdBDId7yA0+Oxt/F/jlfCw8bnFR596zhVi9CN19bb0aWpn8U0cENQqCjNPlu8Lz+qYrU4CUFQe2H59qDDt2mXd76LZG+sfO5Q== \
AIG+CPPEfpfJC/1AMSXrfPGmJ4hK7n2nGRp7ZTrYW3mPgM6zGJ+vepGk+CL0F9ihnzdA++CM2DUUCYOv4rHrQAqAOM93GP+281M/yo9Zj3uSPZPNoKS9yf1qaVo5wed0iA==
```
results in
```
╭────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ multisigAddress    │  0x9c3d1202a483f33cc340183df29ae9ffa55697947be431c963be78917e7fc538                                                                                                                                                                                                                                                                │
│ multisigParsed     │  AwIA/nyhgGk1lGxHxF4MvTlH/fujyXm3z175F0EMh3vIDT47G38X+OV8LDxucVHn3rOFWL0I3X1tvRpamfxTRwQ1CgCBvgjzxH6XyQv9QDEl63zxpieISu59pxkae2U62Ft5j4DOsxifr3qRpPgi9BfYoZ83QPvgjNg1FAmDr+Kx60AKAwADAIKM0+W7wvP6pitTgJQVB7Yfn2oMO3aZd3votkb6x87lAQCAOM93GP+281M/yo9Zj3uSPZPNoKS9yf1qaVo5wed0iAEA8Ev1C4ojUyNI2fkm3TDTM5RZ0JDFufzhSUqYm0Zu5TgBAgA=  │
│ multisigSerialized │  AwIA/nyhgGk1lGxHxF4MvTlH/fujyXm3z175F0EMh3vIDT47G38X+OV8LDxucVHn3rOFWL0I3X1tvRpamfxTRwQ1CgCBvgjzxH6XyQv9QDEl63zxpieISu59pxkae2U62Ft5j4DOsxifr3qRpPgi9BfYoZ83QPvgjNg1FAmDr+Kx60AKAwADAIKM0+W7wvP6pitTgJQVB7Yfn2oMO3aZd3votkb6x87lAQCAOM93GP+281M/yo9Zj3uSPZPNoKS9yf1qaVo5wed0iAEA8Ev1C4ojUyNI2fkm3TDTM5RZ0JDFufzhSUqYm0Zu5TgBAgA=  │
╰────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```
which makes no sense

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Display MultiSigCombinePartialSig::multisigParsed details instead of bas64 (this is still displayed in MultiSigCombinePartialSig::multisigSerialized)

Looks like this now
```
iota keytool multi-sig-combine-partial-sig --pks AIKM0+W7wvP6pitTgJQVB7Yfn2oMO3aZd3votkb6x87l AIA4z3cY/7bzUz/Kj1mPe5I9k82gpL3J/WppWjnB53SI APBL9QuKI1MjSNn5Jt0w0zOUWdCQxbn84UlKmJtGbuU4 --weights 1 1 1 --threshold 2 --sigs AP58oYBpNZRsR8ReDL05R/37o8l5t89e+RdBDId7yA0+Oxt/F/jlfCw8bnFR596zhVi9CN19bb0aWpn8U0cENQqCjNPlu8Lz+qYrU4CUFQe2H59qDDt2mXd76LZG+sfO5Q== AIG+CPPEfpfJC/1AMSXrfPGmJ4hK7n2nGRp7ZTrYW3mPgM6zGJ+vepGk+CL0F9ihnzdA++CM2DUUCYOv4rHrQAqAOM93GP+281M/yo9Zj3uSPZPNoKS9yf1qaVo5wed0iA==`
╭────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ multisigAddress    │ 0x9c3d1202a483f33cc340183df29ae9ffa55697947be431c963be78917e7fc538                                                             │
│ multisigParsed     │ ╭─────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │
│                    │ │ sigs        │ ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │ │
│                    │ │             │ │ ╭─────────┬────────────────────────────────────────────────────────────────────────────────────────────╮ │ │ │
│                    │ │             │ │ │ Ed25519 │  /nyhgGk1lGxHxF4MvTlH/fujyXm3z175F0EMh3vIDT47G38X+OV8LDxucVHn3rOFWL0I3X1tvRpamfxTRwQ1Cg==  │ │ │ │
│                    │ │             │ │ ╰─────────┴────────────────────────────────────────────────────────────────────────────────────────────╯ │ │ │
│                    │ │             │ │ ╭─────────┬────────────────────────────────────────────────────────────────────────────────────────────╮ │ │ │
│                    │ │             │ │ │ Ed25519 │  gb4I88R+l8kL/UAxJet88aYniErufacZGntlOthbeY+AzrMYn696kaT4IvQX2KGfN0D74IzYNRQJg6/isetACg==  │ │ │ │
│                    │ │             │ │ ╰─────────┴────────────────────────────────────────────────────────────────────────────────────────────╯ │ │ │
│                    │ │             │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │ │
│                    │ │ bitmap      │  3                                                                                                           │ │
│                    │ │ multisig_pk │ ╭───────────┬──────────────────────────────────────────────────────────────────────╮                         │ │
│                    │ │             │ │ pk_map    │ ╭──────────────────────────────────────────────────────────────────╮ │                         │ │
│                    │ │             │ │           │ │ ╭──────────────────────────────────────────────────────────────╮ │ │                         │ │
│                    │ │             │ │           │ │ │ ╭─────────┬────────────────────────────────────────────────╮ │ │ │                         │ │
│                    │ │             │ │           │ │ │ │ Ed25519 │  gozT5bvC8/qmK1OAlBUHth+fagw7dpl3e+i2RvrHzuU=  │ │ │ │                         │ │
│                    │ │             │ │           │ │ │ ╰─────────┴────────────────────────────────────────────────╯ │ │ │                         │ │
│                    │ │             │ │           │ │ │  1                                                           │ │ │                         │ │
│                    │ │             │ │           │ │ ╰──────────────────────────────────────────────────────────────╯ │ │                         │ │
│                    │ │             │ │           │ │ ╭──────────────────────────────────────────────────────────────╮ │ │                         │ │
│                    │ │             │ │           │ │ │ ╭─────────┬────────────────────────────────────────────────╮ │ │ │                         │ │
│                    │ │             │ │           │ │ │ │ Ed25519 │  gDjPdxj/tvNTP8qPWY97kj2TzaCkvcn9amlaOcHndIg=  │ │ │ │                         │ │
│                    │ │             │ │           │ │ │ ╰─────────┴────────────────────────────────────────────────╯ │ │ │                         │ │
│                    │ │             │ │           │ │ │  1                                                           │ │ │                         │ │
│                    │ │             │ │           │ │ ╰──────────────────────────────────────────────────────────────╯ │ │                         │ │
│                    │ │             │ │           │ │ ╭──────────────────────────────────────────────────────────────╮ │ │                         │ │
│                    │ │             │ │           │ │ │ ╭─────────┬────────────────────────────────────────────────╮ │ │ │                         │ │
│                    │ │             │ │           │ │ │ │ Ed25519 │  8Ev1C4ojUyNI2fkm3TDTM5RZ0JDFufzhSUqYm0Zu5Tg=  │ │ │ │                         │ │
│                    │ │             │ │           │ │ │ ╰─────────┴────────────────────────────────────────────────╯ │ │ │                         │ │
│                    │ │             │ │           │ │ │  1                                                           │ │ │                         │ │
│                    │ │             │ │           │ │ ╰──────────────────────────────────────────────────────────────╯ │ │                         │ │
│                    │ │             │ │           │ ╰──────────────────────────────────────────────────────────────────╯ │                         │ │
│                    │ │             │ │ threshold │  2                                                                   │                         │ │
│                    │ │             │ ╰───────────┴──────────────────────────────────────────────────────────────────────╯                         │ │
│                    │ ╰─────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│ multisigSerialized │ AwIA/nyhgGk1lGxHxF4MvTlH/fujyXm3z175F0EMh3vIDT47G38X+OV8LDxucVHn3rOFWL0I3X1tvRpamfxTRwQ1CgCBvgjzxH6XyQv9QDEl63zxpieISu59pxkae2 │
│                    │ U62Ft5j4DOsxifr3qRpPgi9BfYoZ83QPvgjNg1FAmDr+Kx60AKAwADAIKM0+W7wvP6pitTgJQVB7Yfn2oMO3aZd3votkb6x87lAQCAOM93GP+281M/yo9Zj3uSPZPN │
│                    │ oKS9yf1qaVo5wed0iAEA8Ev1C4ojUyNI2fkm3TDTM5RZ0JDFufzhSUqYm0Zu5TgBAgA=                                                           │
╰────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/7668

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [x] Patch-specific tests (correctness, functionality coverage)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### Release Notes

- [ ] Protocol:
- [ ] Nodes (Validators and Full nodes):
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [x] CLI: Fixed `iota keytool multi-sig-combine-partial-sig` output to display multisigParsed details instead of a base64 string (still available from multisigSerialized field)
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

**Comment by thibault-martinez** [comment]
conflicts

File: crates/iota/src/unit_tests/keytool_tests.rs [hunk 1]
```diff
@@ -667,3 +668,63 @@ async fn test_show() -> Result<(), anyhow::Error> {
...
+    let output = KeyToolCommand::MultiSigCombinePartialSig {
+        sigs,
+        pks,
+        weights,
+        threshold,
+    }
+    .execute(&mut keystore)
+    .await?;
+
+    match output {
```
Comment (Alex6323) [inline crates/iota/src/unit_tests/keytool_tests.rs]: instead of this `match` you could use `let ... else ...` here.

Comment (Thoralf-M) [reply crates/iota/src/unit_tests/keytool_tests.rs]: Sure, but why is this better?

**Review by Alex6323 — APPROVED** [review]

File: crates/iota/src/unit_tests/keytool_tests.rs (hunk 1 above)
Comment (Alex6323) [reply crates/iota/src/unit_tests/keytool_tests.rs]: it removes a level of nesting, and it's exactly the use-case for what you do with the `match` here (only one match arm, else panic).

Comment (Thoralf-M) [reply crates/iota/src/unit_tests/keytool_tests.rs]: Ah yeah good suggestion, first thought you mean if let and then it wouldn't make such a big of a difference

Comment (Thoralf-M) [reply crates/iota/src/unit_tests/keytool_tests.rs]: https://github.com/iotaledger/iota/pull/7812/commits/d64d25bee6ae9ca7044860307c1bb61fee946cbd

**Review by thibault-martinez — APPROVED** [review]

**Review by DaughterOfMars — APPROVED** [review]
