### PR TITLE
fix(core): Remove `reexecute_local_checkpoints`

### LINKED ISSUE #8290: Remove `reexecute_local_checkpoints` in `crates/iota-core/src/checkpoints/mod.rs`
Re-executes transactions from local uncertified checkpoints was added to support upgrades from non-data-quarantine to data-quarantine. This logic is no longer needed once all nodes are upgraded and can be safely removed.

### PR DESCRIPTION
**Pull request by jkrvivian**
# Description of change

Remove `reexecute_local_checkpoints` from the `CheckpointStore`. This function was responsible for re-executing transactions from local checkpoints for crash recovery, but is no longer needed after the data quarantine upgrade. 

The `reexecute_local_checkpoints` removal is included in upstream commit https://github.com/MystenLabs/sui/commit/ebfbc0c22b6d2a27d1970cfae6ebfb80b327eb46

## Links to any relevant issues

Fixes #8290 

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration tests)
- [ ] Patch-specific tests (correctness, functionality coverage)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by muXxer — APPROVED** [review]

**Comment by alexsporn** [comment]
There are other places where `is_data_quarantine_active_from_beginning_of_epoch` is used where this could be cleaned up now, including the `fn is_data_quarantine_active_from_beginning_of_epoch` itself.

File: crates/iota-core/src/authority/authority_per_epoch_store.rs [hunk 1]
```diff
@@ -4118,20 +4108,14 @@ impl AuthorityPerEpochStore {
...
-            let db_iter = tables
-                .pending_checkpoints
-                .safe_iter_with_bounds(last.map(|height| height + 1), None);
-            db_iter.collect::<Result<Vec<(CheckpointHeight, PendingCheckpoint)>, _>>()?
-        } else {
-            vec![]
-        };
+        // Reading from the db table is only needed when upgrading to data quarantining
+        // for the first time.
+        let tables = self.tables()?;
```
Comment (muXxer) [inline crates/iota-core/src/authority/authority_per_epoch_store.rs]: This is the wrong branch you removed! The function itself can be reduced to just calling the consensus_quarantine equivalent.

**Review by muXxer — CHANGES_REQUESTED** [review]

**Review by muXxer — APPROVED** [review]

**Review by semenov-vladyslav — APPROVED** [review]

**Review by bingyanglin — APPROVED** [review]
