### PR TITLE
fix(wallet-dashboard, tooling-core): review staking numbers for bigints

### LINKED ISSUE #4428: Review staking numbers for bigints
this should be `BigInt` https://github.com/iotaledger/iota/blob/46d52c3a5e4ddb57b9779e9e2830fe779c193185/apps/wallet-dashboard/lib/utils/vesting/vesting.ts#L178-L179
Review more more places to be changed

### PR DESCRIPTION
**Pull request by cpl121**
# Description of change

Review staking numbers for bigints

## Links to any relevant issues

Closes #4428

### CODE REVIEW

File: apps/core/src/components/transaction/info/UnstakeTransactionInfo.tsx [hunk 1]
```diff
@@ -27,21 +27,21 @@ export function UnstakeTransactionInfo({
     renderExplorerLink,
 }: UnstakeTransactionInfoProps) {
     const json = event.parsedJson as {
-        principal_amount?: number;
-        reward_amount?: number;
+        principal_amount?: bigint;
+        reward_amount?: bigint;
```
Comment (marc2332) [inline apps/core/src/components/transaction/info/UnstakeTransactionInfo.tsx]: these two are not `bigint` neither `number`, they are `string`

image

```json
{
    "id": {
        "txDigest": "GEKf5VksPPsFuGi18esM9Hg7uHRjZo3v4H2dvpaWHdwb",
        "eventSeq": "0"
    },
    "packageId": "0x0000000000000000000000000000000000000000000000000000000000000003",
    "transactionModule": "iota_system",
    "sender": "0x5803e16d23f3efa47a3eb98af8eb70a6aef6f2c2d26503b925594d2d775087a6",
    "type": "0x3::validator::UnstakingRequestEvent",
    "parsedJson": {
        "pool_id": "0xc21fe95f73941a9e1209b4d1f52f19ed5530d25484a881c28fe022f3f0af910d",
        "principal_amount": "2000000000",
        "reward_amount": "0",
        "stake_activation_epoch": "26",
        "staker_address": "0x5803e16d23f3efa47a3eb98af8eb70a6aef6f2c2d26503b925594d2d775087a6",
        "unstaking_epoch": "25",
        "validator_address": "0xa276b4c076fff55588255630e9ee35cf0d07e8d80c78991cfd58b43b687b4206"
    },
    "bcs": "LsANhAaAWUiVWa8PpJrhynnojqEiNA4exwjmmZsa41arzFvzLsYwU2Gs1Rp2fjpyShfm9imocBPPSNJQNBqekhwpneNEs3VbDyMBQ63Pga9GxWEcGPkqkd7dVogi1vDFCL9YgwiWx9pejzCBywRxMPqs5BBjfTctLWsHXF9dBcLrrgF"
}
```

File: apps/wallet-dashboard/lib/utils/vesting/vesting.spec.ts [hunk 2]
```diff
@@ -125,12 +125,12 @@ describe('vesting overview', () => {
     it('should get correct vesting overview data with timelocked objects', () => {
         const timelockedObjects = MOCKED_SUPPLY_INCREASE_VESTING_TIMELOCKED_OBJECTS;
         const lastPayout = timelockedObjects[timelockedObjects.length - 1];
-        const totalAmount = bigIntRound(
-            (SUPPLY_INCREASE_STAKER_VESTING_DURATION *
-                SUPPLY_INCREASE_VESTING_PAYOUTS_IN_1_YEAR *
+        const totalAmount =
+            (BigInt(SUPPLY_INCREASE_STAKER_VESTING_DURATION) *
```
Comment (marc2332) [inline apps/wallet-dashboard/lib/utils/vesting/vesting.spec.ts:125]: Instead of creating the bigints here, why don't you do it in the definition of the variable instead?

**Review by marc2332 — CHANGES_REQUESTED** [review]

File: apps/wallet-dashboard/lib/utils/vesting/vesting.spec.ts (hunk 2 above)
Comment (cpl121) [reply apps/wallet-dashboard/lib/utils/vesting/vesting.spec.ts:125]: because we use as a number in `getSupplyIncrreaseVestingPayoutsCount`, and the duration is a number

**Review by brancoder — CHANGES_REQUESTED** [review]
conficts 🙏

**Review by brancoder — CHANGES_REQUESTED** [review]
lint 🙏

**Review by brancoder — APPROVED** [review]
LGTM

File: apps/wallet-dashboard/lib/utils/vesting/vesting.spec.ts [hunk 3]
```diff
@@ -278,16 +268,12 @@ describe('vesting overview', () => {
         const timelockObjects = mixedObjects.filter(isTimelockedObject);
         const availableClaiming = timelockObjects.reduce(
             (acc, current) =>
-                current.expirationTimestampMs <= Date.now()
-                    ? acc + bigIntRound(current.locked.value)
```
Comment (marc2332) [inline apps/wallet-dashboard/lib/utils/vesting/vesting.spec.ts:282]: I see that you are no longer using this here, but it is still being used other places of this file, should you also update those or no?

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by marc2332 — APPROVED** [review]

**Review by begonaalvarezd — APPROVED** [review]
