### PR TITLE
fix(iota): improve coin selection in `iota name` commands

### LINKED ISSUE #7790: [iota-cli] CLI chooses Coin<IOTA> with 0 balance as gas payment
## Bug description

If an address has 2 `Coin<IOTA>` objects, one with `balance: 0`, crafting a transaction that consumes as input the second object results in the CLI picking the `balance: 0` coin object as gas payment, which obviously fails the dry run.

The error (from devnet interactions):
```
Cannot find gas coin for signer address 0x7f5ef659f341e3256d4abd256c66f754fcf78bf574034f5d5ae8d11e55207d20 with amount sufficient for the required gas budget 2980400. If you are using the pay or transfer commands, you can use the pay-iota command instead, which will use the only object as gas payment.
```
,while the two coin objects owned by the account are:
```
╭───────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ objectId      │  0x054e4f7fa570823ee034022348d16243068e656aa7c570827886103a14fc2d5b                                        │
│ version       │  382639204                                                                                                 │
│ digest        │  BmGcbfUrTxo8DrmxuJCqGJsuZnh7ddpsXc17qHjjrz2q                                                              │
│ objType       │  0x2::coin::Coin<0x2::iota::IOTA>                                                                          │
│ owner         │ ╭──────────────┬──────────────────────────────────────────────────────────────────────╮                    │
│               │ │ AddressOwner │  0x7f5ef659f341e3256d4abd256c66f754fcf78bf574034f5d5ae8d11e55207d20  │                    │
│               │ ╰──────────────┴──────────────────────────────────────────────────────────────────────╯                    │
│ prevTx        │  BJiFQU1v2DzW1PQtPKSpssb2fDktgfL15zqawbAvu42H                                                              │
│ storageRebate │  980400                                                                                                    │
│ content       │ ╭──────────┬─────────────────────────────────────────────────────────────────────────────────────────────╮ │
│               │ │ dataType │  moveObject                                                                                 │ │
│               │ │ type     │  0x2::coin::Coin<0x2::iota::IOTA>                                                           │ │
│               │ │ fields   │ ╭─────────┬───────────────────────────────────────────────────────────────────────────────╮ │ │
│               │ │          │ │ balance │  68880435600                                                                  │ │ │
│               │ │          │ │ id      │ ╭────┬──────────────────────────────────────────────────────────────────────╮ │ │ │
│               │ │          │ │         │ │ id │  0x054e4f7fa570823ee034022348d16243068e656aa7c570827886103a14fc2d5b  │ │ │ │
│               │ │          │ │         │ ╰────┴──────────────────────────────────────────────────────────────────────╯ │ │ │
│               │ │          │ ╰─────────┴───────────────────────────────────────────────────────────────────────────────╯ │ │
│               │ ╰──────────┴─────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰───────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


╭───────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ objectId      │  0x907a397cbaf63218db5d30135760a5e2870dca46feabe2dd879bf1495fb53e4f                                        │
│ version       │  382639204                                                                                                 │
│ digest        │  CR3Rei3jfmJpSkjGgBQ7q55kyUnSv54CccF1riuK3szQ                                                              │
│ objType       │  0x2::coin::Coin<0x2::iota::IOTA>                                                                          │
│ owner         │ ╭──────────────┬──────────────────────────────────────────────────────────────────────╮                    │
│               │ │ AddressOwner │  0x7f5ef659f341e3256d4abd256c66f754fcf78bf574034f5d5ae8d11e55207d20  │                    │
│               │ ╰──────────────┴──────────────────────────────────────────────────────────────────────╯                    │
│ prevTx        │  BJiFQU1v2DzW1PQtPKSpssb2fDktgfL15zqawbAvu42H                                                              │
│ storageRebate │  980400                                                                                                    │
│ content       │ ╭──────────┬─────────────────────────────────────────────────────────────────────────────────────────────╮ │
│               │ │ dataType │  moveObject                                                                                 │ │
│               │ │ type     │  0x2::coin::Coin<0x2::iota::IOTA>                                                           │ │
│               │ │ fields   │ ╭─────────┬───────────────────────────────────────────────────────────────────────────────╮ │ │
│               │ │          │ │ balance │  0                                                                            │ │ │
│               │ │          │ │ id      │ ╭────┬──────────────────────────────────────────────────────────────────────╮ │ │ │
│               │ │          │ │         │ │ id │  0x907a397cbaf63218db5d30135760a5e2870dca46feabe2dd879bf1495fb53e4f  │ │ │ │
│               │ │          │ │         │ ╰────┴──────────────────────────────────────────────────────────────────────╯ │ │ │
│               │ │          │ ╰─────────┴───────────────────────────────────────────────────────────────────────────────╯ │ │
│               │ ╰──────────┴─────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰───────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

## Expected behaviour

Either the user is notified that there are no avaiable gas coins, or the gas coin with an actual balance is set as gas payment, while the transaction input requirement

## Actual behaviour

Tx fails dry-running as a gas coin with 0 balance is et.

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Use the gas coin for payment, if no other coin with sufficient balance is available.
I used 0.009 IOTA because there doesn't seem to be a good way before to know how much exactly is needed and this should be sufficient for most registrations without making the requirement so big that it would prevent someone from using a separated coins for the gas payment even if it would be sufficient.
Here are some txs as reference:
https://explorer.iota.org/txblock/Et7LroTKeBmGbpVFzEa8ogjFNFBKPqQsUsv9jHqT2zvj?network=devnet
https://explorer.iota.org/txblock/EXJd7SXTU6YK1dFfDQ4wQHQ19KDYWCAgk1T1NUQgtiFM?network=devnet
https://explorer.iota.org/txblock/3Mt5CwQuWqBHQMbkekLpbTpBQTrREadmjbrCEQT51NKD?network=devnet

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/7790

## How the change has been tested

Registered a name with only one coin that had sufficient balance for payment/gas and multiple coins with less balance:
```
iota client gas
╭────────────────────────────────────────────────────────────────────┬──────────────────────┬────────────────────╮
│ gasCoinId                                                          │ nanosBalance (NANOS) │ iotaBalance (IOTA) │
├────────────────────────────────────────────────────────────────────┼──────────────────────┼────────────────────┤
│ 0x03554b2f73410bf889ca29193996e39b6f0fd83dbcd042d9a7a6e59d6ddaf088 │ 0                    │ 0.00               │
│ 0x43eb2f00aec671ff07ae5d1ce4505c2d53ab5511ee19aadc8d72bf40ebe82ea5 │ 10000                │ 0.00               │
│ 0xf2edfea0df021c05cbaa29903089c5f80984206ad70a7cc87e6956a2781f55d6 │ 9815578400           │ 9.81               │
╰────────────────────────────────────────────────────────────────────┴──────────────────────┴────────────────────╯

iota name register tiny-coins.iota
Registered record:
╭────────────────┬────────────────────────────────────────────────────────────────────╮
│ field          │ value                                                              │
├────────────────┼────────────────────────────────────────────────────────────────────┤
│ NFT ID         │ 0x549967e52b67d299d1dfed6409f2fc69a1fc13e55aed7fdf00e7d792f7f74dc1 │
│ Target Address │ none                                                               │
│ Expiration     │ 1784107678787 (2026-07-15 09:27:58.787000000 UTC)                  │
╰────────────────┴────────────────────────────────────────────────────────────────────╯
Created NFT:
╭────────────┬────────────────────────────────────────────────────────────────────╮
│ field      │ value                                                              │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ ID         │ 0x549967e52b67d299d1dfed6409f2fc69a1fc13e55aed7fdf00e7d792f7f74dc1 │
│ Name       │ tiny-coins.iota                                                    │
│ Expiration │ 1784107678787 (2026-07-15 09:27:58.787000000 UTC)                  │
╰────────────┴────────────────────────────────────────────────────────────────────╯
Transaction digest: 3Mt5CwQuWqBHQMbkekLpbTpBQTrREadmjbrCEQT51NKD
```

### Release Notes

- [ ] Protocol:
- [ ] Nodes (Validators and Full nodes):
- [ ] Indexer:
- [ ] JSON-RPC:
- [ ] GraphQL:
- [x] CLI: don't select coins with less than 0.009 IOTA for gas payments in `iota name` commands
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: crates/iota/src/name_commands.rs [hunk 1]
```diff
@@ -2132,7 +2132,10 @@ async fn select_coin_arg_for_payment(
                 .await?;
             let mut balance = 0;
             if let IotaClientCommandResult::Gas(coins) = gas_result {
-                if coins.len() == 1 {
+                // Ignore coins > 0.009 IOTA (9_000_000 NANOs), because they are probably not
```
Comment (alexsporn) [inline crates/iota/src/name_commands.rs]: You mean `<` here in the comment

Comment (Thoralf-M) [inline crates/iota/src/name_commands.rs]:
```suggestion
                // Ignore coins < 0.009 IOTA (9_000_000 NANOs), because they are probably not
```

Comment (Thoralf-M) [reply crates/iota/src/name_commands.rs]: Yes thanks, I rewrote it and messed up

Comment (Thoralf-M) [reply crates/iota/src/name_commands.rs]: Fixed here https://github.com/iotaledger/iota/pull/7813/commits/62bed2f09214d0d78cd853bcd2ed298e07485a21

File: crates/iota/src/name_commands.rs [hunk 2]
```diff
@@ -2132,7 +2132,10 @@ async fn select_coin_arg_for_payment(
                 .await?;
             let mut balance = 0;
             if let IotaClientCommandResult::Gas(coins) = gas_result {
-                if coins.len() == 1 {
+                // Ignore coins < 0.009 IOTA (9_000_000 NANOs), because they are probably not
+                // sufficient for the gas payment
+                let eligible_coins = coins.iter().filter(|c| c.value() >= 9_000_000);
```
Comment (Alex6323) [inline crates/iota/src/name_commands.rs]: Can we create a constant for that and move the documentation there? I suggest: `MIN_COIN_AMOUNT_FOR_GAS_PAYMENT` or smth?

File: crates/iota/src/name_commands.rs [hunk 3]
```diff
@@ -2132,7 +2132,10 @@ async fn select_coin_arg_for_payment(
...
+                if eligible_coins.clone().count() == 1 {
```
Comment (Alex6323) [inline crates/iota/src/name_commands.rs]: do you really need to clone here?

Comment (Thoralf-M) [reply crates/iota/src/name_commands.rs]: No, removed

File: crates/iota/src/name_commands.rs (hunk 2 above)
Comment (Thoralf-M) [reply crates/iota/src/name_commands.rs]: Sure, https://github.com/iotaledger/iota/pull/7813/commits/fcde0cc49f503e3160980b0472bf009dcf38df05

File: crates/iota/src/name_commands.rs [hunk 4]
```diff
@@ -58,6 +58,11 @@ use crate::{
 /// The overbid must be at least of 1 IOTA, which is 10^9 NANOs
 const MIN_OVERBID: u64 = 1_000_000_000;
 
+/// Minimum coin amount (in NANOs) required for gas payment eligibility.
+/// Coins below this value (9_000_000 NANOs = 0.009 IOTA) are ignored for gas
+/// payment.
+const MIN_COIN_AMOUNT_FOR_GAS_PAYMENT: u64 = 9_000_000;
```
Comment (thibault-martinez) [inline crates/iota/src/name_commands.rs:64]: Is this something we may have to change in the future because gas config changes?

**Review by thibault-martinez — APPROVED** [review]

File: crates/iota/src/name_commands.rs (hunk 4 above)
Comment (Thoralf-M) [reply crates/iota/src/name_commands.rs:64]: Yes maybe, if we have gas smashing support we could maybe also just merge all coins together and always use the gas coin then, unless there are any things that speaks against that

**Review by Alex6323 — APPROVED** [review]
